---
title: "Polypeptide sequencing"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
  code_folding: "hide"
toc: true
toc_depth: 4
toc_float: 
  collapsed: false
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = F, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r}
source("./script/02.PolypeptideSequencing/AdditionalFunctions.R")
library(openxlsx)
library(data.table)
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("LFGV", amino_acid)]
meta <- meta[!grepl("blank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(1:5, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解/", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```

```{r}
mclapply(6:7, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解/", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 53, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```

```{r}
mclapply(8, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解/", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```


















```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("LSGV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(1:5, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```













```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("^FEV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(1:3, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  # phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```

























```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("^SLFEV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(3:5, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```









```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("LSGV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(2, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 6
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor(DenSm)
  } else {
    L0 <- L0Coor(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor(DenSm)
    } else {
      L0 <- L0Coor(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```





























```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("LFGV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
L0Coor2 <- function(den, d = NULL) {
  Bx <- den$x[start(IRanges(diff(den$y) > 0))]
  By <- den$y[start(IRanges(diff(den$y) > 0))]
  
  Px <- den$x[start(IRanges(diff(den$y) < 0))]
  Py <- den$y[start(IRanges(diff(den$y) < 0))]
  
  Py <- Py[Px > 90 & Px < 110]
  Px <- Px[Px > 90 & Px < 110]
  
  if(is.null(d)) {
    Peakx <- which(sort(c(Bx, Px)) == Px[which.max(Py)])
    c(sort(c(Bx, Px))[Peakx - 1], sort(c(Bx, Px))[Peakx + 1])
  } else {
    Peakx <- which(sort(c(Bx, Px)) == Px[which.min(abs(Px - d))])
    c(sort(c(Bx, Px))[Peakx - 1], sort(c(Bx, Px))[Peakx + 1])
  }
}

mclapply(5, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor2(DenSm)
  } else {
    L0 <- L0Coor2(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor2(DenSm)
    } else {
      L0 <- L0Coor2(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```












```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("LFGV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(8, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor2(DenSm)
  } else {
    L0 <- L0Coor2(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor2(DenSm)
    } else {
      L0 <- L0Coor2(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```
















```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[grepl("^FEV", amino_acid)]
meta <- meta[!grepl("lank", amino_acid)]
meta[, .(file_name, date, amino_acid, `start_time.(min)`, `end_time.(min)`, baseline_mean)]
```

```{r}
mclapply(1, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  # phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor2(DenSm)
  } else {
    L0 <- L0Coor2(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor2(DenSm)
    } else {
      L0 <- L0Coor2(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```

```{r}
L0Coor3 <- function(den, d = NULL) {
  Bx <- den$x[start(IRanges(diff(den$y) > 0))]
  By <- den$y[start(IRanges(diff(den$y) > 0))]
  
  Px <- den$x[start(IRanges(diff(den$y) < 0))]
  Py <- den$y[start(IRanges(diff(den$y) < 0))]
  
  Py <- Py[Px > 110 & Px < 130]
  Px <- Px[Px > 110 & Px < 130]
  
  if(is.null(d)) {
    Peakx <- which(sort(c(Bx, Px)) == Px[which.max(Py)])
    c(sort(c(Bx, Px))[Peakx - 1], sort(c(Bx, Px))[Peakx + 1])
  } else {
    Peakx <- which(sort(c(Bx, Px)) == Px[which.min(abs(Px - d))])
    c(sort(c(Bx, Px))[Peakx - 1], sort(c(Bx, Px))[Peakx + 1])
  }
}
```

```{r}
mclapply(2, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  # phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor3(DenSm)
  } else {
    L0 <- L0Coor3(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor3(DenSm)
    } else {
      L0 <- L0Coor3(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, "_2.pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, "_2.Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, "_2.xlsx"))
}, mc.cores = 1)
```




```{r}
mclapply(3, function(f) {
  print(paste0(f, " of ", nrow(meta)))
  filename <- meta[f, file_name]
  File <- list.files("./data/ZhangMing_20220406/20220406肿瘤新抗原水解", filename, full.names = T)
  StartTime <- as.numeric(meta[f, `start_time.(min)`])
  EndTime <- as.numeric(meta[f, `end_time.(min)`])
  base_mean <- as.numeric(meta[f, baseline_mean])
  
  phe <- readABF::readABF(File)
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  # phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 30, ]
  phe <- phe[pA < 140, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  # L0 for BUB
  adj <- 4
  DenSm <- density(phe[, Sm], adjust = adj)
  
  if(is.na(base_mean)) {
    L0 <- L0Coor3(DenSm)
  } else {
    L0 <- L0Coor3(DenSm, d = base_mean)
  }
  
  while (anyNA(L0)) {
    adj <- adj - 0.25
    DenSm <- density(phe[, Sm], adjust = adj)
    
    if(is.na(base_mean)) {
      L0 <- L0Coor3(DenSm)
    } else {
      L0 <- L0Coor3(DenSm, d = base_mean)
    }
  }
  
  L0Min <- min(max(L0) * 0.89, 100)
  
  pdf(paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/L0_Coord_", filename, ".pdf"))
  plot(DenSm, main = paste0("adjust = ", adj))
  abline(v = c(L0))
  abline(v = L0Min, col = 2)
  abline(v = base_mean, col = 3)
  dev.off()
  
  # BUB
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  
  # Baseline value filtering
  L0F <- data.table(pA = mapply(function(x) x[L == "B", mean2(pA)], BUB))
  rg <- quantile(L0F$pA, c(0.05, 0.95))
  BUB <- BUB[L0F[, pA > min(rg) & pA < max(rg)]]
  
  # Baseline length filtering
  BL_Sum <- mapply(BUB, FUN = function(x) sum(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BL_Min <- mapply(BUB, FUN = function(x) min(runLength(Rle(x[, L == "B"]))[runValue(Rle(x[, L == "B"])) == TRUE]))
  BUB <- BUB[BL_Sum >= 500 & BL_Min >= 50]
  
  # Time filtering
  Wid <- mapply(BUB, FUN = function(x) x[L == "U", diff(range(Time))])
  BUB <- BUB[Wid > 0.00075]
  
  saveRDS(BUB, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/BUB", filename, ".Rds"))
  # AA Signal
  Sigs <- lapply(BUB, FUN = function(x) tryCatch(DensityPeaksSignal(Sig = x, adjust = 0.1, plot = FALSE), error = function(e) NULL))
  Sigs <- do.call(rbind, Sigs)
  
  openxlsx::write.xlsx(Sigs, paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/AA_Signals_", filename, ".xlsx"))
}, mc.cores = 1)
```


