---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(parallel)
library(caret)
library(openxlsx)
library(cowplot)
library(ggseqlogo)
```

```{r}
mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x >= min(q) & x <= max(q)])
}
```

```{r}
set.seed(19)
AA_Cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(AA_Cols) <- Biostrings::AA_STANDARD
```

```{r}
xlsxfiles <- list.files("./analysis/02.PolypeptideSequencing/20220406/Version1", ".xlsx", full.names = TRUE)
Signalsfiles <- list.files("./analysis/02.PolypeptideSequencing/20220406/Version1", ".Rds", full.names = TRUE)
```

# Signal transformation

```{r}
lapply(seq_along(xlsxfiles), function(i) {
  Signal <- as.data.table(read.xlsx(xlsxfiles[i]))
  Signal$ID <- paste0(gsub(".xlsx", "", basename(xlsxfiles[i])), "_", sprintf("%04d", seq_len(Signal[, .N])))
  
  BUBs <- readRDS(Signalsfiles[i])
  names(BUBs) <- Signal$ID
  BUBs <- mclapply(BUBs, function(x) {
    basemean <- x[L == "B", mean2(pA)]
    x[, pA := pA / basemean]
    x[, Sm := NULL]
    x[L == "U"]
  }, mc.cores = 10)
  
  Signal$AllTime <- mapply(BUBs, FUN = function(x) x[, diff(range(Time))] * 1000)
  Signal$Blockade2 <- mcmapply(Signal$ID, FUN = function(x) {
    den <- BUBs[[x]][, density(pA)]
    1 - with(den, x[which.max(y)])
  }, mc.cores = 10)
  
  BinExp <- mclapply(BUBs, function(x) round(density(x[, pA], from = 0, to = 1, n = 200, adjust = 1)$y, 3), mc.cores = 10)
  BinExp <- do.call(rbind, BinExp)
  colnames(BinExp) <- paste0("D", sprintf("%03d", seq_len(ncol(BinExp))))
  
  SampPoint <- mclapply(BUBs, FUN = function(x) {
    x[, pA][sort(x[, sample(.N, 200, replace = TRUE)])]
  }, mc.cores = 10)
  SampPoint <- do.call(rbind, SampPoint)
  colnames(SampPoint) <- paste0("P", sprintf("%03d", seq_len(ncol(SampPoint))))
  
  Mat <- cbind(BinExp, SampPoint, Signal[, .(ID, AllTime, DwellTime, SignalSD, Blockade, Blockade2)])
  Mat <- na.omit(Mat)
  
  save(Mat, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/01.SignalTransform/", gsub(".xlsx", ".RData", basename(xlsxfiles[i]))))
})
```

# AA Prediction

```{r}
files <- list.files("./analysis/02.PolypeptideSequencing/20220406/Version1/01.SignalTransform", ".RData", full.names = TRUE)
```

```{r}
lapply(seq_along(files), function(j) {
  print(j)
  load(files[j])
  # RF predict
  Models <- list.files("./analysis/03.MachineLearning/Version8/02.Modeling/01.RF/01.Models", "RF_Fit", full.names = T)
  Polypeptide1 <- mclapply(1:6, function(i) {
    Fit <- readRDS(Models[i])
    if(nrow(Mat[AllTime > i & SignalSD < 4, ]) == 0) return(NULL)
    ROC_Test <- predict(Fit, Mat[AllTime > i & SignalSD < 4, ], type = "prob")
    row.names(ROC_Test) <- Mat[AllTime > i & SignalSD < 4, ID]
    ppm <- melt(as.data.table(ROC_Test, keep.rownames = "ID"), value.name = "Prob", variable.name = "pred")[, .SD[which.max(Prob), ], ID]
    ppm[, Model := paste0("RF", i)]
    ppm <- merge(ppm, as.data.table(Mat, keep.rownames = "ID")[, .(ID, AllTime, DwellTime, SignalSD, Blockade, Blockade2)], by = "ID")
    return(ppm)
  }, mc.cores = 6)
  Polypeptide1 <- do.call(rbind, Polypeptide1)
  Polypeptide1[, pred := as.character(pred)]
  setnames(Polypeptide1, "pred", "AA")
  Polypeptide1_RF <- copy(Polypeptide1)
  
  # KNN predict
  Models <- list.files("./analysis/03.MachineLearning/Version8/02.Modeling/04.KNN/01.Models", "KNN_Fit", full.names = T)
  Polypeptide1 <- mclapply(1:6, function(i) {
    Fit <- readRDS(Models[i])
    if(nrow(Mat[AllTime > i & SignalSD < 4, ]) == 0) return(NULL)
    ROC_Test <- predict(Fit, Mat[AllTime > i & SignalSD < 4, ], type = "prob")
    row.names(ROC_Test) <- Mat[AllTime > i & SignalSD < 4, ID]
    ppm <- melt(as.data.table(ROC_Test, keep.rownames = "ID"), value.name = "Prob", variable.name = "pred")[, .SD[which.max(Prob), ], ID]
    ppm[, Model := paste0("KNN", i)]
    ppm <- merge(ppm, as.data.table(Mat, keep.rownames = "ID")[, .(ID, AllTime, DwellTime, SignalSD, Blockade, Blockade2)], by = "ID")
    return(ppm)
  }, mc.cores = 6)
  Polypeptide1 <- do.call(rbind, Polypeptide1)
  Polypeptide1[, pred := as.character(pred)]
  setnames(Polypeptide1, "pred", "AA")
  Polypeptide1_KNN <- copy(Polypeptide1)
  
  # CART predict
  Models <- list.files("./analysis/03.MachineLearning/Version8/02.Modeling/05.CART/01.Models", "CART_Fit", full.names = T)
  Polypeptide1 <- mclapply(1:6, function(i) {
    Fit <- readRDS(Models[i])
    if(nrow(Mat[AllTime > i & SignalSD < 4, ]) == 0) return(NULL)
    ROC_Test <- predict(Fit, Mat[AllTime > i & SignalSD < 4, ], type = "prob")
    row.names(ROC_Test) <- Mat[AllTime > i & SignalSD < 4, ID]
    ppm <- melt(as.data.table(ROC_Test, keep.rownames = "ID"), value.name = "Prob", variable.name = "pred")[, .SD[which.max(Prob), ], ID]
    ppm[, Model := paste0("CART", i)]
    ppm <- merge(ppm, as.data.table(Mat, keep.rownames = "ID")[, .(ID, AllTime, DwellTime, SignalSD, Blockade, Blockade2)], by = "ID")
    return(ppm)
  }, mc.cores = 6)
  
  Polypeptide1 <- do.call(rbind, Polypeptide1)
  Polypeptide1[, pred := as.character(pred)]
  setnames(Polypeptide1, "pred", "AA")
  Polypeptide1_CART <- copy(Polypeptide1)
  
  # Merge
  Polypeptide1_iden <- lapply(1:6, function(i) {
    RF_i <- Polypeptide1_RF[Model == paste0("RF", i), .(ID, Prob, AA)]
    KNN_i <- Polypeptide1_KNN[Model == paste0("KNN", i), .(ID, Prob, AA)]
    CART_i <- Polypeptide1_CART[Model == paste0("CART", i), .(ID, Prob, AA)]
    
    RF_i <- RF_i[Prob >= 0, .(ID, AA)]
    KNN_i <- KNN_i[Prob >= 0, .(ID, AA)]
    CART_i <- CART_i[Prob >= 0, .(ID, AA)]
    setnames(RF_i, "AA", "RF")
    setnames(KNN_i, "AA", "KNN")
    setnames(CART_i, "AA", "CART")
    
    Pred_i <- Reduce(function(x, y) merge(x, y, all = T), list(RF_i, KNN_i, CART_i))
    Pred_i <- Pred_i[rowSums(is.na(Pred_i)) <= 1]
    Pred_i <- na.omit(melt.data.table(Pred_i, id.vars = "ID", value.name = "AA"))[, .N, list(ID, AA)][N == 3]
    
    RF_i <- merge(Polypeptide1_RF[Model == paste0("RF", i), .(ID, DwellTime, Blockade, Blockade2, Prob)], Pred_i[, .(ID, AA)], by = "ID")
    KNN_i <- merge(Polypeptide1_KNN[Model == paste0("KNN", i), .(ID, DwellTime, Blockade, Blockade2, Prob)], Pred_i[, .(ID, AA)], by = "ID")
    CART_i <- merge(Polypeptide1_CART[Model == paste0("CART", i), .(ID, DwellTime, Blockade, Blockade2, Prob)], Pred_i[, .(ID, AA)], by = "ID")
    
    setnames(RF_i, "Prob", "RF")
    setnames(KNN_i, "Prob", "KNN")
    setnames(CART_i, "Prob", "CART")
    merge(merge(RF_i, KNN_i, by = c("ID", "DwellTime", "Blockade", "Blockade2", "AA")), CART_i)
    
    res <- Reduce(function(x, y) merge(x, y, by = c("ID", "DwellTime", "Blockade", "Blockade2", "AA")), list(RF_i, KNN_i, CART_i))
    data.table(Cutoff = paste0("C", i), res)
  })
  Polypeptide1_iden <- do.call(rbind, Polypeptide1_iden)
  
  save(Polypeptide1_iden, Polypeptide1_RF, Polypeptide1_KNN, Polypeptide1_CART, file = paste0("./analysis/02.PolypeptideSequencing/20220406/Version1/02.SignalPrediction/", basename(files[j])))
})
```



```{r}
set.seed(19)
AA_Cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(AA_Cols) <- Biostrings::AA_STANDARD
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[2:3]

meta$AA <- mapply(strsplit(meta[, amino_acid], "\\+"), FUN = function(x) {
  paste0(plyr::mapvalues(x, tolower(AMINO_ACID_CODE), names(AMINO_ACID_CODE)), collapse = "")
})

setkey(meta, file_name)
files <- list.files("./analysis/02.PolypeptideSequencing/20220406/Version1/02.SignalPrediction", full.names = TRUE)
```

```{r}
load(files[1])
Polypeptide1_iden$MaxPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, max)
Polypeptide1_iden$MinPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, min)
Polypeptide1_iden$MeanPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, mean)
Polypeptide1_iden1 <- copy(Polypeptide1_iden)
```

```{r}
load(files[2])
Polypeptide1_iden$MaxPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, max)
Polypeptide1_iden$MinPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, min)
Polypeptide1_iden$MeanPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, mean)
Polypeptide1_iden2 <- copy(Polypeptide1_iden)
```

```{r}
Polypeptide1_iden <- rbind(Polypeptide1_iden1, Polypeptide1_iden2)
```

```{r fig.width=10, fig.height=6}
ggplot(Polypeptide1_iden[MaxPP > 0.9], aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) + 
  facet_wrap( ~ Cutoff) + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none")
```











