---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(Biostrings)
library(IRanges)
library(ggplot2)
library(parallel)
library(ggpubr)
library(patchwork)
library(changepoint)
library(ggExtra)
library(tidyr)

# SignalFiltering <- function(x) {
#   x <- x[DeltaMean < 1 & Valid == TRUE]
#   # x <- x[DwellTime >= with(density(x[, DwellTime], n = 10000, adjust = 1), x[which.max(y)])]
#   x <- x[DwellTime > 0.001]
#   x <- x[StageSD < 3]
#   x <- x[LeftLength >= 50 & RightLength >= 50]
#   x <- x[BaseMean > min(WhiskerRange(x[, BaseMean])) & BaseMean < max(WhiskerRange(x[, BaseMean]))]
#   rk <- rank(x[, DwellTime]) + rank(x[, -1 * StageSD])
#   x[rk > quantile(rk, 0.1)]
# }

# SignalFiltering <- function(x) {
#   x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50 & SignalCurrentPercent == 100]
#   x[!(DwellTime < mean(DwellTime) & StageSD > mean(StageSD))]
# }

SignalFiltering <- function(x) {
  x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
  x[!(DwellTime < 0.003 & StageSD > 2)]
}

SignalCurrent <- function(x, abf, cores = 10) {
  Sigs_Multiple_Current <- mclapply(seq_len(nrow(x)), FUN = function(i) {
    data.table(ID = x[i, ID], Current = abf[Time > x[i, StartTime] & Time < x[i, EndTime], pA] / x[i, BaseMean])
  }, mc.cores = cores)
  do.call(rbind, Sigs_Multiple_Current)
}

densityPeak <- function(x, bw = 1, n = 1024, plot = T, ...) {
  Peaks <- function(x, y) {
    stopifnot(length(x) == length(y))
    uR <- IRanges(diff(y) >= 0)
    dR <- IRanges(diff(y) <= 0)
    res <- do.call(c, lapply(seq_along(uR), function(i) {
      reduce(c(uR[i], dR[i]))
    }))
    pk <- res[queryHits(findOverlaps(res, IRanges(which.max(y), which.max(y))))]
    c(x[start(pk)], x[end(pk)])
  }
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  if(plot) {
    plot(den)
    abline(v = ps, lty = 2, col = 2)
    return(ps)
  } else {
    return(ps)
  }
}
```

```{r}
setwd("/mnt/raid61/Personal_data/tangchao/AANanopore")
library(data.table)
library(ggplot2)
library(Biostrings)
```

```{r}
meta <- rbind(data.table(openxlsx::read.xlsx("./data/meta_info_and_base_line_20210525.xlsx")), data.table(openxlsx::read.xlsx("./data/meta_info_and_base_line_20210525additional.xlsx")))
meta[amino_acid == "cys", amino_acid := "Cys"]

meta <- meta[file_name != 21703001]
```

# Asn

```{r}
meta[, unique(amino_acid)]
a <- "Asn"
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Asp

```{r}
meta[, unique(amino_acid)]
a <- "Asp"
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .55)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Gln

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Gln")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .55)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Glu

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Glu")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0, aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .5)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Ile

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Ile")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .03)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .5)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Leu

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Leu")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .03)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Met

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Met")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Phe

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Phe")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Thr

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Thr")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Trp

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Trp")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > max(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Val

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Val")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .01)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Ser

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Ser")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .00056)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean > min(ps) & BaseMean < max(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Arg

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Arg")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p1
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .005)
```

```{r}
Sig0[, BlockadeValid := (Blockade > min(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean < min(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```


# Tyr

```{r}
meta[, unique(amino_acid)]
```

```{r}
(a <- "Tyr")
```

```{r}
Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- do.call(rbind, Sig0)
Sig0[, Blockade := 1 - SignalCurrent / BaseMean]
# Sig1 <- SignalFiltering(Sig0)
```

```{r fig.height=5, fig.width=12}
ggplot(Sig0[Segments == 1], aes(y = DwellTime, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 0.0015) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", Sig0[, .N])) -> p1
ggplot(Sig0[Segments == 1], aes(y = StageSD, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  geom_hline(yintercept = 2) +
  # scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Current SD", x = "Blockade", title = paste0(a, ": ", Sig0[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r}
Sig0[, TimeAndSDValid := !(DwellTime < 0.0015 & StageSD > 2)]
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100, Blockade], bw = 1, n = 1024, plot = T, adjust = .005)
```

```{r}
Sig0[, BlockadeValid := (Blockade > max(ps))]
```

```{r fig.width=12, fig.height=5}
ggplot(Sig0[SignalCurrentPercent == 100], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100, .N])) -> p0

ggplot(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T], aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, .N])) -> p1
cowplot::plot_grid(ggMarginal(p0), ggMarginal(p1))
```

```{r}
ps <- densityPeak(Sig0[SignalCurrentPercent == 100 & TimeAndSDValid == T, BaseMean], bw = 1, n = 1024, plot = T, adjust = .6)
p1 + geom_hline(yintercept = ps)
```

```{r}
Sig0[, BaseMeanValid := (BaseMean < max(ps) & BaseMean > min(ps))]
```

```{r fig.width=10, fig.height=5}
ggplot(Sig0, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0)), subtitle = "All")

ggplot(Sig0[SignalCurrentPercent == 100], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100])), subtitle = "SignalCurrentPercent == 100")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T")

ggplot(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(a, ": ", nrow(Sig0[SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T])), 
       subtitle = "SignalCurrentPercent == 100 & BaseMeanValid == T & TimeAndSDValid == T & BlockadeValid == T")
```

```{r}
fwrite(Sig0, paste0("./analysis/12.SignalFiltering/Dec28/Filter1/", a, "_Filter1.txt"), sep = "\t", quote = F, row.names = F)
```

