---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(cowplot)
library(parallel)
library(caret)
```

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10)

library(doParallel)
cl <- makePSOCKcluster(10)
registerDoParallel(cl)
```

# RF

```{r}
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version8/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  RFC <- train(Class ~ ., data = Train, 
                preProc = c("center", "scale", "YeoJohnson", "nzv"),
                method = "rf", 
                trControl = fitControl,
                verbose = FALSE,
                ## to evaluate:
                tuneGrid = expand.grid(mtry = 60),
                # tuneLength = 50,
                metric = "Accuracy", 
                allowParallel = TRUE)
  saveRDS(RFC, file = paste0("./analysis/03.MachineLearning/Version8/02.Modeling/01.RF/01.Models/RF_Fit", i, ".Rds"))
})
stopCluster(cl)
```

