---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(caret)
library(shiny)
library(patchwork)
library(plotly)
library(Biostrings)
library(ggpubr)
```

```{r}
aa_cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)])

names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC")
```

```{r}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

KnnSelecting <- function(signals, dists, dist_method = "euclidean", k = 20, noise = 0) {
  stopifnot(noise < k)
  if(is(dists, "dist")) {
    knn1 <- dbscan::kNN(dists, k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists, "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  } else {
    knn1 <- dbscan::kNN(dists[[dist_method]], k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists[[dist_method]], "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  }
  
  tu <- row.names(knn1$id)[which(rowSums(knn2) <= noise)]
  # tu <- union(tu, knn2[which(rowSums(knn2) <= noise), 1])
  tu <- grep("^Noise", tu, invert = TRUE, value = TRUE)
  ggplot(signals, aes(x = Blockade, y = DwellTime, colour = !ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = c("#E41A1C", "#377EB8")) + 
    theme_classic() + 
    theme(legend.position = "none") -> p1
  ggplot(signals[ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#E41A1C") + 
    theme_classic() + 
    theme(legend.position = "none") + 
    labs(title = length(tu)) -> p2
  ggplot(signals[!ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#377EB8") + 
    theme_classic() + 
    theme(legend.position = "none") -> p3
  print(p1 + p2 + p3)
  return(tu)
}

RemoveOutlier1 <- function(tree, n = 10, o = NULL) {
  k <- ceiling(length(res.hc$labels)/100)
  res_ct <- stats::cutree(res.hc, k = k)
  while (sum(table(res_ct) >= n) == 1) {
    k <- k + 1
    res_ct <- stats::cutree(res.hc, k = k)
  }
  if(is.null(o)) o <- n
  names(res_ct[res_ct %in% names(which(table(res_ct) >= o))])
}
RemoveOutlier <- function(tree, n = 10, Keep = 0.95) {
  h <- length(tree$height)
  g <- cutree(tree, h = tree$height[h])
  g <- data.table(tip = names(g), cluster = g)
  
  while (g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] > Keep) {
    h <- h - 1
    g <- cutree(tree, h = tree$height[h])
    g <- data.table(tip = names(g), cluster = g)
  }
  cat(paste0("Keep: ", round(g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] * 100, 2), "%"))
  g[cluster %in% g[, .N, cluster][N >= n, cluster], tip]
}

get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

# Peaks <- function(x, y) {
#   stopifnot(length(x) == length(y))
#   uR <- IRanges(diff(y) >= 0)
#   dR <- IRanges(diff(y) <= 0)
#   res <- do.call(c, lapply(seq_along(uR), function(i) {
#     reduce(c(uR[i], dR[i]))
#   }))
#   
#   Ps <- mapply(seq_along(res), FUN = function(i) {
#     x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
#   })
#   res <- IRanges(start = x[start(res)], end = x[end(res)])
#   end(res[length(res)]) <- max(x)
#   attr(res, "peaks") <- Ps
#   return(res)
# }
Peaks <- function(x, y) {
  stopifnot(length(x) == length(y))
  uR <- IRanges(diff(y) >= 0)
  dR <- IRanges(diff(y) <= 0)
  res <- do.call(c, lapply(seq_along(uR), function(i) {
    reduce(c(uR[i], dR[i]))
  }))
  
  Ps <- mapply(seq_along(res), FUN = function(i) {
    x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
  })
  Py <- mapply(seq_along(res), FUN = function(i) {
    max(y[start(res[i]):end(res[i])])
  })
  res <- data.table(x = Ps, xmin = x[start(res)], xmax = x[end(res)], y = Py)
  attr(res, "peaks") <- Ps
  return(res)
}

densityPeak <- function(x, bw = 0.01, peaks = 2, n = 1024, from = 0, to = 1, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  dx <- attr(ps, "peaks")
  dy <- den$y[den$x %in% attr(ps, "peaks")]
  dy <- dy/max(dy)
  
  dx2 <- dx[dx <= dx[which.max(dy)]]
  dy2 <- dy[dx <= dx[which.max(dy)]]
  
  dx2 <- dx2[dy2 %in% head(sort(dy2, decreasing = T), peaks)]
  dy2 <- dy2[dy2 %in% head(sort(dy2, decreasing = T), peaks)]
  res <- sort(dx2, decreasing = T)
  df <- mean(abs(diff(den$y)))
  CI <- mapply(res, FUN = function(i) {
    from <- with(den, x[x < i])[max(start(IRanges(diff(with(den, y[x < i])) > mean(abs(diff(with(den, y[x < i])))))))]
    to <- with(den, x[x > i])[min(end(IRanges(diff(with(den, y[x > i])) < mean(abs(diff(with(den, y[x > i])))))))]
    min(c(i - from, to - i))
  })
  attr(res, "CI") <- CI
  if(plot) {
    plot(den)
    abline(v = res, lty = 2, col = 2)
    abline(v = res - attr(res,"CI"), lty = 2, col = 3)
    abline(v = res + attr(res,"CI"), lty = 2, col = 3)
  } else {
    return(res)
  }
}

BaseMeanFiltering <- function(SigFile, starttime = NULL, endtime = NULL, outdir = NULL, target = NULL, product = NULL) {
  if(is.null(starttime)) stop()
  if(is.null(endtime)) stop()
  if(is.null(outdir)) stop()
  if(is.null(target)) stop()
  outdir <- gsub("//", "/", paste0(outdir, "/", target))
  if(!dir.exists(outdir)) dir.create(outdir)
  dataset <- fread(SigFile)
  dataset <- dataset[StartTime > starttime*60 & EndTime < endtime*60]
  dataset[, A := target]
  dataset[, DwellTime := DwellTime * 1000]
  shinyApp(
    ui = fluidPage(
      fluidRow(style = "padding-bottom: 20px;",
               column(2, numericInput('size', 'Point size', value = .3, min = .1, max = 1, step = .1)),
               column(3, sliderInput('nbins', 'Number of bins', value = 500, min = 100, max = 1000, step = 50)),
               column(3, sliderInput('BaseMean', 'BaseMean region', value = c(90, 130), min = 80, max = max(dataset[, round(BaseMean)]))),
               column(3, radioButtons(inputId = "LogScale", label = "log scale:", choices = c("TRUE", "FALSE"), inline = T))
      ),
      fluidRow(column(6, plotlyOutput('BaseMeanBlockade')), column(6, plotlyOutput('BlockadeDwellTime'))),
      plotlyOutput('BaseMeanHistogram'),
      actionButton("goButton", 'Save', class = "btn-success"),
      verbatimTextOutput("sp")
    ), 
    server = function(input, output, session) {
      selectedData <- reactive({
        dataset[BaseMean > input$BaseMean[1] & BaseMean < input$BaseMean[2]]
      })
      
      output$BaseMeanBlockade = renderPlotly({
        ggplot(selectedData(), aes(x = BaseMean, y = Blockade)) + 
          geom_point(size = input$size) + 
          # geom_hline(yintercept = AABlockade[amino_acid %in% selectedData()[, unique(A)], Blockade], color = "red") + 
          theme_minimal() -> p
        ggplotly(p)
      })
      
      output$BaseMeanHistogram = renderPlotly({
        ggplot(selectedData(), aes(x = BaseMean)) + 
          geom_histogram(bins = input$nbins) + 
          theme_minimal() -> p2
        ggplotly(p2) %>% layout(dragmode = "select")
      })
      
      output$BlockadeDwellTime = renderPlotly({
        d <- (event_data("plotly_selected"))
        if(is.null(d)) {
          selectedData2 <- reactive({
            dataset
          })
        } else {
          selectedData2 <- reactive({
            dataset[BaseMean > min(d$x) & BaseMean < max(d$x)]
          })
        }
        ggplot(selectedData2(), aes(x = Blockade, y = DwellTime)) + 
          geom_point(size = input$size) + 
          # geom_vline(xintercept = product, color = "red") +
          theme_minimal() + 
          labs(title = selectedData2()[, unique(A)]) -> p3
        if(!is.null(product)) {
          p3 <- p3 + geom_vline(xintercept = product, color = "red")
        }
        
        if(input$LogScale == "TRUE") {
          p3 <- p3 + scale_y_log10()
        }
        ggplotly(p3)
      })
      
      output$sp <- renderPrint({
        d <- (event_data("plotly_selected"))
        if(is.null(d)) {
          cat("Number of selected points:", nrow(d))
        } else {
          selectedData2 <- reactive({
            dataset[BaseMean > min(d$x) & BaseMean < max(d$x)]
          })
          if(input$goButton != 0) {
            if(!is.null(d)) {
              fwrite(selectedData2(), paste0(outdir, "/", gsub(".txt", ".MainL0.txt", basename(SigFile))), sep = "\t", quote = F)
              cat("Saved", nrow(selectedData2()), "points.")
            } else {
              cat("Number of selected points:", nrow(selectedData2()))
            }
          } else {
            cat("Number of selected points:", nrow(selectedData2()))
          }
        }
      })
    }
  )
}

MainRidge <- function(x, bw = 0.001, bwstep = NULL, n = 1024, peaks = 2, mingap = 0.01, CI = 0.99, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  res <- ps[order(y, decreasing = T)][seq_len(peaks)]
  res <- na.omit(res)
  if(peaks > 1) {
    if(is.null(bwstep)) bwstep <- mingap/10
    while (nrow(res) > 1 & min(res[, diff(sort(x))]) < mingap) {
      bw <- bw + bwstep
      den <- density(x, bw = bw, n = n, ...)
      ps <- Peaks(den$x, den$y)
      res <- ps[order(y, decreasing = T)][seq_len(peaks)]
      res <- na.omit(res)
    }
  }
  if(CI < 1) {
    new_x <- lapply(seq_len(nrow(res)), function(i) {
      resy <- with(den, y[x > res[i, xmin] & x < res[i, xmax]])
      resy <- resy > max(resy) * (1 - CI) + min(resy)
      resx <- range(with(den, x[x > res[i, xmin] & x < res[i, xmax]])[resy])
      resx
    })
    new_x <- do.call(rbind, new_x)
    res$xmin <- new_x[, 1]
    res$xmax <- new_x[, 2]
  }
  res$ratio <- mapply(function(i) mean(x >= res$xmin[i] & x <= res$xmax[i]), seq_len(nrow(res)))
  
  if(plot) {
    plot(den)
    abline(v = res[, x], lty = 2, col = 2)
    abline(v = res[, xmin], lty = 2, col = 3)
    abline(v = res[, xmax], lty = 2, col = 3)
  } else {
    return(res)
  }
}
```

```{r}
files <- list.files("./analysis/61.SignalSelecting/01.StandardAA/02.SelectedSignals", "_V2.Rds", full.names = T)

Sigs1 <- lapply(files, function(x) {
  readRDS(x)[[1]]
})
Sigs1 <- do.call(rbind, Sigs1)[State == "Sington"]

SigSumm <- Sigs1[, .(BlockadeSD = sd(Blockade), 
                     BlockadeMean = mean(Blockade), 
                     BlockadeMedian = median(Blockade), 
                     BlockadeQ1 = quantile(Blockade, 1/4), 
                     BlockadeQ3 = quantile(Blockade, 3/4), 
                     DwellTimeSD = sd(DwellTime), 
                     DwellTimeMAD = mad(DwellTime), 
                     DwellTimeQ1 = quantile(DwellTime, 1/4), 
                     DwellTimeQ3 = quantile(DwellTime, 3/4), 
                     DwellTimeMean = mean(DwellTime), 
                     DwellTimeMedian = median(DwellTime)), A]
```

```{r}
meta <- data.table(openxlsx::read.xlsx("./data/ChenShanchuan/20230715/数据记录20230715.xlsx", sheet = 2))
colnames(meta) <- c("file_name", "start_time", "end_time", "amino_acid", "purpose", "priority", "sample", "base_line", "note", "temperature")
meta <- meta[grepl("温度实验", purpose)]
meta[, amino_acid := "EKFS"]
meta[, temperature := c(21, 21, 25, 25, 25, 25, 21)]
meta <- meta[, .(file_name, start_time, end_time, amino_acid = sample, temperature)]
meta$abf_file <- mapply(function(x) list.files("./data", x, full.names = T, recursive = T), meta[, file_name])
setkey(meta, amino_acid)
```

# L0 select

```{r}
meta1 <- meta[temperature == 21]
meta1$sig_file <- paste0("./analysis/21.ABFProcessing/06.Temperature/RawSignal/RawSignal_", meta1$file_name, ".txt")
stopifnot(all(file.exists(meta1$sig_file)))
```

```{r eval=FALSE}
BaseMeanFiltering(SigFile = meta1[2, sig_file], starttime = meta1[2, start_time], endtime = meta1[2, end_time], 
                  outdir = "./analysis/61.SignalSelecting/03.Temperature", target = meta1[2, file_name], 
                  product = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), BlockadeMean])

BaseMeanFiltering(SigFile = meta1[3, sig_file], starttime = meta1[3, start_time], endtime = meta1[3, end_time], 
                  outdir = "./analysis/61.SignalSelecting/03.Temperature", target = meta1[3, file_name], 
                  product = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), BlockadeMean])
```


```{r}
meta2 <- meta[temperature == 25]
meta2$sig_file <- paste0("./analysis/21.ABFProcessing/06.Temperature/RawSignal/RawSignal_", meta2$file_name, ".txt")
stopifnot(all(file.exists(meta2$sig_file)))
```

```{r eval=FALSE}
BaseMeanFiltering(SigFile = meta2[1, sig_file], starttime = meta2[1, start_time], endtime = meta2[1, end_time], 
                  outdir = "./analysis/61.SignalSelecting/03.Temperature", target = meta2[1, file_name], 
                  product = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), BlockadeMean])

BaseMeanFiltering(SigFile = meta2[2, sig_file], starttime = meta2[2, start_time], endtime = meta2[2, end_time], 
                  outdir = "./analysis/61.SignalSelecting/03.Temperature", target = meta2[2, file_name], 
                  product = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), BlockadeMean])

BaseMeanFiltering(SigFile = meta2[4, sig_file], starttime = meta2[4, start_time], endtime = meta2[4, end_time], 
                  outdir = "./analysis/61.SignalSelecting/03.Temperature", target = meta2[4, file_name], 
                  product = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), BlockadeMean])
```




```{r}
sigs <- do.call(rbind, lapply(list.files("./analysis/61.SignalSelecting/03.Temperature", ".MainL0.txt", full.names = TRUE, recursive = TRUE), fread))
```

```{r fig.width=10, fig.height=12}
ggplot(sigs, aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point() + 
  scale_y_log10() + 
  facet_wrap(~ A, ncol = 1, scales = "free_y")
```

# Distance of signal

```{r}
StandardAA_bg_FeatureMatrixs <- readRDS("./analysis/61.SignalSelecting/01.StandardAA/01.SignalDistance/StandardAA_Big_FeatureMatrixs.Rds")
StandardAA_bg_FeatureMatrixs[, AA := NULL]
```

## 21 度

### Background data

```{r}
meta1 <- meta1[file_name %in% gsub("RawSignal_", "", gsub(".MainL0.txt", "", basename(list.files("./analysis/61.SignalSelecting/03.Temperature", ".MainL0.txt", full.names = F, recursive = TRUE))))]
bgsignals <- sigs[A == meta1[amino_acid == "blank", file_name], ]
bgsignals[, ID := paste0("Noise_", ID)]

B_file <- bgsignals[, unique(A)]
Big_FeatureMatrix <- list.files(path = "./analysis/21.ABFProcessing/06.Temperature/FeatureMatrix", B_file, full.names = TRUE)
Big_FeatureMatrix <- fread(Big_FeatureMatrix)
Big_FeatureMatrix[, ID := paste0("Noise_", ID)]
Big_FeatureMatrix <- Big_FeatureMatrix[ID %in% bgsignals$ID]
```

### Signal data

```{r}
sgsignals <- sigs[A %in% meta1[amino_acid != "blank", file_name], ]
B_file <- sgsignals[, unique(A)]
Sig_FeatureMatrix <- lapply(B_file, function(x) {
  fread(list.files(path = "./analysis/21.ABFProcessing/06.Temperature/FeatureMatrix", x, full.names = TRUE))[ID %in% sgsignals$ID]
})
Sig_FeatureMatrix <- do.call(rbind, Sig_FeatureMatrix)
```

```{r eval=FALSE}
lapply(sgsignals[, unique(A)], function(x) {
  SFMi <- Sig_FeatureMatrix[ID %in% sgsignals[A == x, ID]]
  if(nrow(SFMi) > nrow(Big_FeatureMatrix)) {
    FeatureMatrix <- rbind(Big_FeatureMatrix, 
                           StandardAA_bg_FeatureMatrixs[sample(.N, nrow(SFMi) - nrow(Big_FeatureMatrix))], 
                           SFMi)
  } else {
    FeatureMatrix <- rbind(Big_FeatureMatrix, SFMi)
  }
  setkey(FeatureMatrix, ID)
  FeatureMatrix <- data.frame(FeatureMatrix[, grepl("^X", colnames(FeatureMatrix)) | grepl("DwellTime", colnames(FeatureMatrix)), with = F], row.names = FeatureMatrix[[1]])
  euclidean = stats::dist(FeatureMatrix, method = "euclidean")
  saveRDS(euclidean, file = paste0("./analysis/61.SignalSelecting/03.Temperature/", x, "/Signals_euclidean_distance.Rds"))
})
```

### Distance filtering


```{r fig.width=24, fig.height=6}
Run1_dist <- readRDS(paste0("./analysis/61.SignalSelecting/03.Temperature/", sgsignals[, unique(A)], "/Signals_euclidean_distance.Rds"))
select_sigs_Run1 <- KnnSelecting(signals = sgsignals, dists = Run1_dist, k = 4, noise = 0)
```

```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run1]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run1 <- RemoveOutlier(tree = res.hc, n = 100, Keep = 0.9)
ggplot(sgsignals[ID %in% select_sigs_RemoveOutlier_Run1], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  scale_y_log10() + 
  labs(title = length(select_sigs_RemoveOutlier_Run1)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```


## 25 度

### Background data

```{r}
meta2 <- meta2[file_name %in% gsub("RawSignal_", "", gsub(".MainL0.txt", "", basename(list.files("./analysis/61.SignalSelecting/03.Temperature", ".MainL0.txt", full.names = F, recursive = TRUE))))]
bgsignals <- sigs[A == meta2[amino_acid == "blank", file_name], ]
bgsignals[, ID := paste0("Noise_", ID)]

B_file <- bgsignals[, unique(A)]
Big_FeatureMatrix <- list.files(path = "./analysis/21.ABFProcessing/06.Temperature/FeatureMatrix", B_file, full.names = TRUE)
Big_FeatureMatrix <- fread(Big_FeatureMatrix)
Big_FeatureMatrix[, ID := paste0("Noise_", ID)]
Big_FeatureMatrix <- Big_FeatureMatrix[ID %in% bgsignals$ID]
```

### Signal data

```{r}
sgsignals <- sigs[A %in% meta2[amino_acid != "blank", file_name], ]
B_file <- sgsignals[, unique(A)]
Sig_FeatureMatrix <- lapply(B_file, function(x) {
  fread(list.files(path = "./analysis/21.ABFProcessing/06.Temperature/FeatureMatrix", x, full.names = TRUE))[ID %in% sgsignals$ID]
})
Sig_FeatureMatrix <- do.call(rbind, Sig_FeatureMatrix)
```

```{r eval=FALSE}
lapply(sgsignals[, unique(A)], function(x) {
  SFMi <- Sig_FeatureMatrix[ID %in% sgsignals[A == x, ID]]
  if(nrow(SFMi) > nrow(Big_FeatureMatrix)) {
    FeatureMatrix <- rbind(Big_FeatureMatrix, 
                           StandardAA_bg_FeatureMatrixs[sample(.N, nrow(SFMi) - nrow(Big_FeatureMatrix))], 
                           SFMi)
  } else {
    FeatureMatrix <- rbind(Big_FeatureMatrix, SFMi)
  }
  setkey(FeatureMatrix, ID)
  FeatureMatrix <- data.frame(FeatureMatrix[, grepl("^X", colnames(FeatureMatrix)) | grepl("DwellTime", colnames(FeatureMatrix)), with = F], row.names = FeatureMatrix[[1]])
  euclidean = stats::dist(FeatureMatrix, method = "euclidean")
  saveRDS(euclidean, file = paste0("./analysis/61.SignalSelecting/03.Temperature/", x, "/Signals_euclidean_distance.Rds"))
})
```

### Distance filtering


```{r fig.width=24, fig.height=6}
Run2_dist <- readRDS(paste0("./analysis/61.SignalSelecting/03.Temperature/", sgsignals[, unique(A)][2], "/Signals_euclidean_distance.Rds"))
select_sigs_Run2 <- KnnSelecting(signals = sgsignals[A == sgsignals[, unique(A)][2]], dists = Run2_dist, k = 4, noise = 0)
```

```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run2]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run2 <- RemoveOutlier(tree = res.hc, n = 10, Keep = 0.97)
ggplot(sgsignals[ID %in% select_sigs_RemoveOutlier_Run2], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  scale_y_log10() + 
  labs(title = length(select_sigs_RemoveOutlier_Run2)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```

# Compare

```{r}
select_sigs <- union(select_sigs_RemoveOutlier_Run1, select_sigs_RemoveOutlier_Run2)
select_sigs <- sigs[ID %in% select_sigs]
select_sigs <- merge(meta[, .(file_name, amino_acid, temperature)], select_sigs, by.x = "file_name", by.y = "A")
select_sigs[, Temperature := paste0(temperature, "℃")]
fwrite(select_sigs, "./analysis/61.SignalSelecting/03.Temperature/Selected_signals.txt", sep = "\t", quote = FALSE)
```

```{r}
ggplot() + 
  geom_point(data = select_sigs, aes(x = Blockade, y = DwellTime, colour = Temperature), size = .5) + 
  geom_rect(data = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), ], aes(xmin = BlockadeMean - BlockadeSD, xmax = BlockadeMean + BlockadeSD, ymin = 0, ymax = 30, fill = A), alpha = 0.3) +
  scale_y_log10() + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = guide_legend(title = element_blank())) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        panel.grid = element_blank())
```

```{r}
ggplot() + 
  geom_histogram(data = select_sigs, aes(x = Blockade, fill = Temperature), size = .5, binwidth = 0.005) + 
  # geom_rect(data = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), ], aes(xmin = BlockadeMean - BlockadeSD, xmax = BlockadeMean + BlockadeSD, ymin = 0, ymax = 230, fill = A), alpha = 0.3) +
  # scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = guide_legend(title = element_blank())) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        panel.grid = element_blank())

ggplot() + 
  geom_line(data = select_sigs[Blockade < 0.25], aes(x = Blockade, colour = Temperature), stat = "density", bw = 0.001) + 
  geom_rect(data = SigSumm[A %in% c("Glu", "Lys", "Phe", "Ser"), ], aes(xmin = BlockadeMean - BlockadeSD, xmax = BlockadeMean + BlockadeSD, ymin = 0, ymax = 23, fill = A), alpha = 0.3) +
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = guide_legend(title = element_blank())) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        panel.grid = element_blank())
```

