---
title: "Signal selecting"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r}
library(factoextra)
library(data.table)
library(Biostrings)
library(patchwork)
library(ggplot2)
library(ggrepel)
library(IRanges)
library(dplyr)
library(lsa)
```

```{r}
KnnSelecting <- function(signals, dists, dist_method = "euclidean", k = 20, noise = 0, index = NULL) {
  stopifnot(noise < k)
  if(is(dists, "dist")) {
    knn1 <- dbscan::kNN(dists, k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists, "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  } else {
    if(is(dists, "kNN")) {
      if(k > dists$k) stop("K too big")
      knn1 <- dists
      knn2 <- apply(knn1$id[, 1:k], 2, function(x) x %in% which(grepl("^Noise", rownames(knn1$id))))
    } else {
      knn1 <- dbscan::kNN(dists[[dist_method]], k = k)
      knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists[[dist_method]], "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
    }
  }
  
  tu <- row.names(knn1$id)[which(rowSums(knn2) <= noise)]
  # tu <- union(tu, knn2[which(rowSums(knn2) <= noise), 1])
  tu <- grep("^Noise", tu, invert = TRUE, value = TRUE)
  ggplot(signals, aes(x = Blockade, y = DwellTime, colour = !ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = c("#E41A1C", "#377EB8")) + 
    theme_classic() + 
    theme(legend.position = "none") -> p1
  ggplot(signals[ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#E41A1C") + 
    theme_classic() + 
    theme(legend.position = "none") + 
    labs(title = length(tu)) -> p2
  ggplot(signals[!ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#377EB8") + 
    theme_classic() + 
    theme(legend.position = "none") -> p3
  if(!is.null(index)) {
    p1 <- p1 + geom_vline(xintercept = index, colour = "red")
    p2 <- p2 + geom_vline(xintercept = index, colour = "red")
    p3 <- p3 + geom_vline(xintercept = index, colour = "red")
  }
  print(p1 + p2 + p3)
  return(tu)
}

RemoveOutlier <- function(tree, n = 10, Keep = 0.95) {
  h <- length(tree$height)
  g <- cutree(tree, h = tree$height[h])
  g <- data.table(tip = names(g), cluster = g)
  
  while (g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] > Keep) {
    h <- h - 1
    g <- cutree(tree, h = tree$height[h])
    g <- data.table(tip = names(g), cluster = g)
  }
  cat(paste0("Keep: ", round(g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] * 100, 2), "%"))
  g[cluster %in% g[, .N, cluster][N >= n, cluster], tip]
}
```

```{r}
AABlockade <- lapply(list.files("./analysis/61.SignalSelecting/01.StandardAA/02.SelectedSignals", "_V2.Rds", full.names = T), function(x) readRDS(x)$Summary)
AABlockade <- do.call(rbind, AABlockade)
AABlockade <- AABlockade[State == "State1"]
```

# LSGV

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./analysis/89.Neoantigen/02.SignalDistance/meta.xlsx", sheet = 1))
meta <- meta[amino_acid == "LSGV"]
meta[, sig_file := paste0("./analysis/89.Neoantigen/01.SelectedL0/", file_id, ".MainL0.txt")]
meta
```

```{r fig.width=24, fig.height=6}
dataset <- do.call(rbind, lapply(meta[amino_acid == "LSGV", sig_file], fread))[Blockade < 0.35 & DwellTime > 0.3]
B_file <- paste0("./analysis/81.ABFProcessing/FeatureMatrix/FeatureMatrix_", unique(meta[amino_acid == "LSGV", file_name]), ".txt")
FeatureMatrix <- do.call(rbind, lapply(B_file, fread))
FM0 <- FeatureMatrix[ID %in% dataset$ID]
FeatureMatrix <- data.frame(FeatureMatrix[, grepl("^X", colnames(FeatureMatrix)) | colnames(FeatureMatrix) %in% c("DwellTime", "DeltaMean", "StageSD", "CurrentSD", "SignalCurrentPercent", "SignalCurrentWidth", "Blockade"), with = F], row.names = FeatureMatrix[[1]])
```

```{r}
model1 <- readRDS("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/SubAAs/ModelFGLSV/RFmodel.Rds")
model2 <- readRDS("./analysis/91.RealTimeHydrolysis/00.Models/01.EFHLSY/Model_EFHLSY_Noise.Rds")
```

```{r}
pred1 <- data.table(ID = FM0$ID, 
                    Pred1 = as.character(predict(model1, FM0)), 
                    Prob1 = apply(predict(model1, FM0, type = "prob"), 1, max), 
                    Delta1 = apply(predict(model1, FM0, type = "prob"), 1, function(x) - diff(head(sort(x, decreasing = T), 2))))
pred2 <- data.table(ID = FM0$ID, 
                    Pred2 = as.character(predict(model2, FM0)), 
                    Prob2 = apply(predict(model2, FM0, type = "prob"), 1, max), 
                    Delta2 = apply(predict(model2, FM0, type = "prob"), 1, function(x) - diff(head(sort(x, decreasing = T), 2))))
```

```{r}
dataset <- merge(dataset, merge(pred1, pred2), by = "ID")
dataset[A == "Username_2022-03-11_003.1", experiment := "Rep1"]
dataset[A %in% c("22402004.1", "22402007.1"), experiment := "Rep2"]
dataset[A %in% c("22402005.1", "22402006.1"), experiment := "Rep3"]
```

```{r}
dataset1 <- fread("./analysis/89.Neoantigen/03.SelectedSignals/LSGV_Username_2022-03-11_003.1_euclidean_distance_knn_selected.signals.txt")
```

```{r fig.width=10, fig.height=4}
ggplot(dataset1, aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[AA %in% AMINO_ACID_CODE[unlist(strsplit("LSGV", ""))], Blockade]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  theme_classic()
```

```{r}
ggplot(dataset[ID %in% dataset1$ID], aes(x = Blockade, y = DwellTime, colour = Pred1)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[AA %in% AMINO_ACID_CODE[unlist(strsplit("LSGV", ""))], Blockade]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  theme_classic()
```

```{r}
dataset_rep1 <- dataset[ID %in% dataset1$ID]
```

```{r}
ggplot(dataset[experiment == "Rep2" & Delta1 > 0.9 & Pred1 != "Phe"], aes(x = Blockade, y = DwellTime, colour = Pred1)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[AA %in% AMINO_ACID_CODE[unlist(strsplit("LSGV", ""))], Blockade]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  theme_classic()
```

```{r}
ggplot(dataset[experiment == "Rep3" & Delta1 > 0.9 & Pred1 != "Phe"], aes(x = Blockade, y = DwellTime, colour = Pred1)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[AA %in% AMINO_ACID_CODE[unlist(strsplit("LSGV", ""))], Blockade]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  theme_classic()
```

```{r}
dataset_rep1 <- dataset[ID %in% dataset1$ID]
dataset_rep2 <- dataset[experiment == "Rep2" & Delta1 > 0.9 & Pred1 != "Phe"]
dataset_rep3 <- dataset[experiment == "Rep3" & Delta1 > 0.9 & Pred1 != "Phe"]
```

```{r}
dataset3 <- rbind(dataset_rep1, dataset_rep2, dataset_rep3)
```

```{r}
fwrite(dataset3, "./analysis/89.Neoantigen/04.SignalsPrediction/LSGV_prediction_V2.txt", sep = "\t")
```


