---
title: "Figure 3"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(Biostrings)
library(patchwork)
library(ggthemes)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
library(caret)
library(multiROC)
library(pROC)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
```

# B 

```{r}
roc_mat <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3B.xlsx", 1))
AUCs <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3B.xlsx", 2))
```

```{r }
ggplot(roc_mat, aes(x = 1 - Specificity, y = Sensitivity, colour = Dataset)) + 
  geom_path(size = 1) + 
  geom_text(data = AUCs, mapping = aes(x = 0.75, y = 3:1/10, label = paste("AUC:", round(AUC, 3))), size = 6) +
  scale_color_brewer(palette = "Set1", guide = guide_legend(nrow = 1)) +
  lims(x = c(0, 1), y = c(0, 1)) + 
  labs(tag = "b") + 
  theme_bw(base_size = 22) + 
  theme(legend.position = c(.5, 1.1), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        legend.box.background = element_blank(), 
        panel.grid = element_blank(), 
        axis.text = element_text(colour = "black"), 
        axis.title = element_text(colour = "black"), 
        plot.tag = element_text(size = 30, face = "bold")) -> p1
p1
```


# C


```{r}
cM <- openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3C.xlsx", rowNames = T)
```

```{r}
m1 <- reshape2::melt(as.matrix(cM))
colnames(m1)[3] <- "Percentage"
ggplot(data = m1, aes(x = Var1, y = Var2, fill = Percentage)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") + 
  labs(x = "Prediction", y = "Reference", tag = "c") +
  theme_bw(base_size = 22) + 
  theme(plot.margin = unit(c(0.25, 0, 0, 0), "lines"), 
        axis.text = element_text(colour = "black"), 
        axis.title = element_text(colour = "black"), 
        plot.tag = element_text(size = 30, face = "bold"), 
        legend.position = "top")  -> p3
```


# D 


```{r}
vImp <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3D.xlsx"))
vImp <- vImp[, x := as.numeric(gsub("X", "", Variable))]
```

```{r}
ggplot(vImp[!is.na(x)], aes(x = x, y = Importance)) + 
  geom_line() + 
  scale_x_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("X0001", "X0250", "X0500", "X0750", "X1000"), 
                     sec.axis = dup_axis(name = "Blockade", breaks = c(0, 250, 500, 750, 1000), labels = c(1, 0.75, 0.5, 0.25, 0))) + 
  labs(x = "Predictors", tag = "d") + 
  theme_bw(base_size = 22) + 
  theme(plot.background = element_blank(), 
        axis.text = element_text(colour = "black"), 
        axis.title = element_text(colour = "black"), 
        plot.tag = element_text(size = 30, face = "bold"), 
        panel.grid = element_blank()) -> p4
p4
```


# E-G


```{r}
Gly_All_Sig_Freq <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3E-G.xlsx", 1))
Arg_All_Sig_Freq <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3E-G.xlsx", 2))
Asp_All_Sig_Freq <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3E-G.xlsx", 3))
```

```{r}
ggplot() + 
  # geom_point(data = Gly_All_Sig_Freq, aes(x = Concentration, y = Frequency), colour = "grey") + 
  stat_summary(data = Gly_All_Sig_Freq, aes(x = Concentration, y = Frequency), fun.data = "mean_sd", colour = aa_cols["Gly"]) + 
  geom_smooth(data = Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), method = "lm", se = F, colour = "grey") + 
  scale_y_continuous(limits = c(0, 40)) + 
  labs(x = "Concentration (μM)", y = expression(Signal~frequency~"("*"min"^-1*")"), tag = "g") +
  stat_cor(data = Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), size = 6) + 
  stat_regline_equation(data = Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], 
                        aes(x = Concentration, y = Frequency, label = paste(..eq.label.., ..adj.rr.label.., sep = "~`,`~~")), 
                        label.y.npc = 0.8, size = 6) + 
  facet_wrap(~ "Gly (G)") + 
  theme_bw(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        axis.text = element_text(colour = "black"), 
        axis.title = element_text(colour = "black"), 
        plot.tag = element_text(size = 30, face = "bold"), 
        plot.background = element_blank()) -> pg
```

```{r}
ggplot() + 
  # geom_point(data = Arg_All_Sig_Freq, aes(x = Concentration, y = Frequency), colour = "grey") + 
  stat_summary(data = Arg_All_Sig_Freq, aes(x = Concentration, y = Frequency), fun.data = "mean_sd", colour = aa_cols["Arg"]) + 
  
  geom_smooth(data = Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), method = "lm", se = F, colour = "grey") + 
  scale_x_continuous(limits = c(0, 16)) + 
  labs(x = "Concentration (μM)", y = expression(Signal~frequency~"("*"min"^-1*")"), tag = "e") +
  stat_cor(data = Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), size = 6) + 
  stat_regline_equation(data = Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], 
                        aes(x = Concentration, y = Frequency, label = paste(..eq.label.., ..adj.rr.label.., sep = "~`,`~~")), 
                        label.y.npc = 0.8, size = 6) + 
  facet_wrap(~ "Arg (R)") + 
  theme_bw(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        axis.text = element_text(colour = "black"), 
        axis.title = element_text(colour = "black"), 
        plot.tag = element_text(size = 30, face = "bold"), 
        plot.background = element_blank()) -> pe
```

```{r}
ggplot() + 
  # geom_point(data = Asp_All_Sig_Freq, aes(x = Concentration, y = Frequency), colour = "grey") + 
  stat_summary(data = Asp_All_Sig_Freq, aes(x = Concentration, y = Frequency), fun.data = "mean_sd", colour = aa_cols["Asp"]) + 
  geom_smooth(data = Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), method = "lm", se = F, colour = "grey") + 
  scale_y_continuous(limits = c(0, 80)) + 
  scale_x_continuous(limits = c(0, 4)) + 
  labs(x = "Concentration (μM)", y = expression(Signal~frequency~"("*"min"^-1*")"), tag = "f") +
  stat_cor(data = Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), size = 6) + 
  stat_regline_equation(data = Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], 
                        aes(x = Concentration, y = Frequency, label = paste(..eq.label.., ..adj.rr.label.., sep = "~`,`~~")), 
                        label.y.npc = 0.8, size = 6) + 
  facet_wrap(~ "Asp (D)") + 
  theme_bw(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        axis.text = element_text(colour = "black"), 
        axis.title = element_text(colour = "black"), 
        plot.tag = element_text(size = 30, face = "bold"), 
        plot.background = element_blank()) -> pf
```


```{r fig.width=15, fig.height=5}
pe + pf + pg + plot_layout(nrow = 1)
```


```{r fig.height=13, fig.width=18, echo=FALSE}
design <- "
  111133334444
  111133334444
  111133334444
  111133334444
  555566667777
  555566667777
  555566667777
"
p1 + p3 + p4 + pe + pf + pg + 
  plot_layout(design = design)
```


```{r fig.height=18, fig.width=24, echo=FALSE}
grDevices::cairo_pdf("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/Fig3B-G.pdf", width = 18, height = 13)
p1 + p3 + p4 + pe + pf + pg + 
  plot_layout(design = design)
dev.off()
```

```{r fig.height=18, fig.width=24, echo=FALSE}
grDevices::cairo_pdf("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/Fig3E-G.pdf", width = 18, height = 5.57)
pe + pf + pg + plot_layout(nrow = 1)
dev.off()
```
