---
title: "Supplementary Figure 11"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(Biostrings)
library(patchwork)
library(ggthemes)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpmisc)
library(ggpubr)
library(caret)
library(gridExtra)
```

# a

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig11A.xlsx", 1))
```

```{r fig.width=6, fig.height=4}
ggplot(data, aes(x = 1 - Specificity, y = Sensitivity, colour = Method)) + 
  geom_path(size = 1) + 
  geom_text(data = data[, .(AUC = unique(AUC)), Method], mapping = aes(x = 0.75, y = 6:1/10, label = paste("AUC:", round(AUC, 3)))) +
  theme_bw(base_size = 15) + 
  # scale_color_manual(values = MoldeCols[od]) + 
  lims(x = c(0, 1), y = c(0, 1)) + 
  labs(tag = "a") + 
  theme(panel.grid = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold")) -> p1
```

# b

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig11B.xlsx", 1))
```

```{r fig.width=7, fig.height=4}
ggplot(data, aes(x = Recovery, y = Accuracy, colour = State, linetype = Dataset)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)", tag = "b") + 
  scale_color_brewer(palette = "Dark2", guide = guide_legend(reverse = F, ncol = 1)) + 
  scale_linetype(guide = guide_legend(reverse = T, ncol = 1)) + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank()) -> p2
```

# c 

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig11C.xlsx", 1))
```

```{r}
ggplot(data[!is.na(x)], aes(x = x, y = Importance, colour = State)) + 
  geom_line() + 
  scale_x_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("X0001", "X0250", "X0500", "X0750", "X1000"), 
                     sec.axis = dup_axis(name = "Blockade", breaks = c(0, 250, 500, 750, 1000), labels = c(1, 0.75, 0.5, 0.25, 0))) + 
  scale_color_brewer(palette = "Dark2", guide = guide_legend(reverse = F, ncol = 1)) + 
  labs(x = "Predictors", tag = "c") + 
  theme_bw(base_size = 15) + 
  theme(plot.background = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank()) -> p3
```

# Fig

```{r fig.width=16, fig.height=4}
p1 + p2 + p3
ggsave("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/SupFig11.pdf", width = 16, height = 4)
```

