---
title: "Supplementary Figure 17"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig17.xlsx"))
```

```{r}
tab1 <- data.table(x = 1 - c(0.2443979, 0.2004430, 0.2201597, 0.1319094, 0.2130025), label = c("Glu", "Leu", "Phe", "Ser", "Tyr"))
tab1[, L := plyr::mapvalues(label, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
```

```{r fig.width=12, fig.height=5}
ggplot(data, aes(x = x, y = y, colour = paste0(Experiment, Peptide), lty = Peptide)) + 
  geom_line() + 
  guides(colour = "none") + 
  scale_colour_brewer(palette = "Dark2") + 
  scale_x_continuous(sec.axis = dup_axis(breaks = tab1$x, labels = tab1$L)) + 
  theme_bw(base_size = 22) + 
  theme(panel.grid = element_blank()) + 
  labs(y = "Density", x = "Blockade")
ggsave("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/SupFig17.pdf", width = 12, height = 5)
```

