---
title: "Supplementary Figure 18"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig18.xlsx"))
data <- as.matrix(data[, -1])
```

```{r fig.width=9, fig.height=8}
pheatmap::pheatmap(t(data), color = colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name = "Reds")))(100), show_rownames = T, show_colnames = F)
```

```{r fig.width=9, fig.height=8}
pdf("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/SupFig18.pdf", width = 9, height = 8)
pheatmap::pheatmap(t(data), color = colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name = "Reds")))(100), show_rownames = T, show_colnames = F)
dev.off()
```

