---
title: "Supplementary Figure 10"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(Biostrings)
library(patchwork)
library(ggthemes)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpmisc)
library(ggpubr)
library(caret)
library(gridExtra)
```

# a

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig10A.xlsx", 1))
data[, Class := factor(Class, levels = c("Upsampling signals", "Unique signals"))]
data[, AminoAcid := factor(AminoAcid, levels = data[Class != "Unique signals"][order(Number, AminoAcid), AminoAcid])]
```

```{r}
ggplot(data, aes(x = AminoAcid, y = Number, fill = Class)) + 
  geom_col() + 
  geom_text(aes(label = Label), position = position_stack(vjust = .5)) + 
  scale_fill_manual(values = c("#FEE0D2", "#CB181D")) + 
  labs(y = "Number of signals", tag = "a") + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "top", 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) -> p1
```

# b

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig10B.xlsx", 1))
```

```{r }
ggplot(data, aes(x = AminoAcid, y = Number, fill = Dataset)) + 
  geom_col(position = position_dodge()) + 
  geom_text(aes(label = Number, y = Number + 800), position = position_dodge(width = 0.9), angle = 90) + 
  scale_y_continuous(limits = c(0, 10000)) + 
  labs(y = "Number of signals", tag = "b") + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "top", 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) -> p2
```

# c

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig10C.xlsx", 1))
```

```{r fig.width=4, fig.height=4}
ggplot(data, aes(x = Recovery, y = Accuracy, colour = Dataset)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)", tag = "c") + 
  scale_color_brewer(palette = "Set1", guide = guide_legend(reverse = T)) + 
  theme_bw(base_size = 15) + 
  theme(#legend.position = "top", 
        legend.position = c(.75, .25), 
        panel.grid = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold")) -> p3
```

# d

```{r}
data <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig10D.xlsx", 1))
```

```{r}
ggplot(data, aes(x = Probability, fill = Type)) + 
  geom_histogram(binwidth = 0.05) + 
  facet_wrap( ~ Dataset, scales = "free") +
  scale_fill_brewer(palette = "Dark2", guide = guide_legend(reverse = T)) + 
  labs(x = "Prediction probability", y = "Count", tag = "d") + 
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), strip.background = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold")) -> p4
```

# Fig

```{r fig.width=16, fig.height=8}
design <- "
  11111222222
  33344444444
"
p1 + p2 + p3 + p4 + 
  plot_layout(design = design)
ggsave("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/SupFig10.pdf", width = 16, height = 8)
```

