---
title: "Supplementary Figure 16"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")

a_cols <- aa_cols
names(a_cols) <- plyr::mapvalues(names(aa_cols), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
polyp <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig16.xlsx"))
polyp[, AminoAcid := factor(AminoAcid, levels = c("F", "L", "V", "K", "A", "G", "S", "His2", "His1", "Y", "E"))]
```

```{r fig.width=12, fig.height=6}
a_cols <- a_cols[polyp[, levels(AminoAcid)]]
ggplot(polyp, aes(x = Blockade, y = DwellTime, alpha = Density, colour = AminoAcid)) + 
  geom_point() + 
  scale_colour_manual(breaks = names(a_cols), values = a_cols) + 
  scale_y_log10() + 
  facet_wrap(~ Polypeptide) + 
  guides(alpha = "none") + 
  theme_bw(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        legend.title = element_blank()) + 
  labs(y = "Dwell time (ms)")
ggsave("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Figure/SupFig16.pdf", width = 12, height = 6)
```

