---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(cowplot)
library(ggseqlogo)
```

```{r}
set.seed(19)
AA_Cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(AA_Cols) <- Biostrings::AA_STANDARD
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/混合氨基酸实验信息表20210517.xlsx"))
meta[, file_name := gsub("2020_", "2020-", file_name)]

meta$AA <- mapply(strsplit(meta[, amino_acid], "\\+"), FUN = function(x) {
  paste0(plyr::mapvalues(x, tolower(AMINO_ACID_CODE), names(AMINO_ACID_CODE)), collapse = "")
})

setkey(meta, file_name)
files <- list.files("./analysis/05.MixedAA/Version1_Signal_Prediction", pattern = "_V2.RData", full.names = TRUE)
```

```{r}
load(files[2])
Polypeptide1_iden$MaxPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, max)
Polypeptide1_iden$MinPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, min)
Polypeptide1_iden$MeanPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, mean)
```

```{r fig.width=10, fig.height=6}
ggplot(Polypeptide1_iden[MaxPP > 0.9], aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) + 
  facet_wrap( ~ Cutoff) + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none")
```


```{r}
Pred_AA_C4 <- lapply(files, function(x) {
  load(x)
  Polypeptide1_iden$MaxPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, max)
  Polypeptide1_iden$MinPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, min)
  Polypeptide1_iden$MeanPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, mean)

  Polypeptide1_iden[MaxPP > 0.7 & Cutoff == "C4", AA]
})
meta[file_name == "Username_2020-07-13_008", AA := "DQ"]
names(Pred_AA_C4) <- meta[gsub("AA_Signals_", "", gsub("_V2.RData", "", basename(files))), AA]

TargetPercent <- mapply(seq_along(Pred_AA_C4), FUN = function(i) {
  mean(Pred_AA_C4[[i]] %in% unlist(strsplit(names(Pred_AA_C4)[i], "")))
})
TargetPercent <- data.table(Target = names(Pred_AA_C4), Percent = TargetPercent * 100, Number = mapply(length, Pred_AA_C4))
TargetPercent[order(Percent, decreasing = T)]
```


```{r fig.width=30, fig.height=4}
Ps <- lapply(seq_along(Pred_AA_C4), function(i) {
  if(i == 1) {
    ggseqlogo(Pred_AA_C4[[i]]) + 
      labs(title = names(Pred_AA_C4)[i]) + 
      theme_minimal_grid(font_size = 15) +
      theme(legend.position = "none", 
            panel.grid = element_blank(), 
            axis.title.x = element_blank(), 
            axis.text.x = element_blank(), 
            axis.ticks.x = element_blank(), 
            plot.title = element_text(hjust = 0.5))
  } else {
    ggseqlogo(Pred_AA_C4[[i]]) + 
      labs(title = names(Pred_AA_C4)[i]) + 
      theme_minimal_grid(font_size = 15) +
      theme(legend.position = "none", 
            panel.grid = element_blank(), 
            axis.title = element_blank(), 
            axis.ticks = element_blank(), 
            axis.text = element_blank(), 
            plot.title = element_text(hjust = 0.5))
  }
})
names(Ps) <- names(Pred_AA_C4)
patchwork::wrap_plots(plotlist = Ps, nrow = 1)
# ggsave("./analysis/05.MixedAA/Version2/03.Plot/Cutoff4_All_Seqlogo.pdf", width = 14, height = 2)
```

```{r fig.width=30, fig.height=4}
patchwork::wrap_plots(plotlist = Ps, nrow = 1)
ggsave("./analysis/05.MixedAA/Version1_Plot/Cutoff4_All_Seqlogo_V2.pdf", width = 14, height = 2)
```

```{r}
Sig_Res <- lapply(seq_along(files), function(i) {
  load(files[i])
  Polypeptide1_iden$MaxPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, max)
  Polypeptide1_iden$MinPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, min)
  Polypeptide1_iden$MeanPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, mean)

  res <- Polypeptide1_iden[MaxPP > 0.7 & Cutoff == "C4"]
  res[, ID := gsub("AA_Signals_", "", ID)]
  res$Target <- meta[paste0(head(unlist(strsplit(res[1, ID], "_")), 3), collapse = "_"), AA]
  res
})
Sig_Res <- do.call(rbind, Sig_Res)
```


```{r fig.width=10, fig.height=10}
ggplot(Sig_Res, aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) + 
  facet_wrap( ~ Target, nrow = 5, scales = "free_y") + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none")
ggsave("./analysis/05.MixedAA/Version1_Plot/Cutoff4_Scatters_V2.pdf", width = 10, height = 10)
```
