---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(Biostrings)
library(IRanges)
library(ggplot2)
library(parallel)
library(ggpubr)
library(patchwork)
library(changepoint)
library(ggExtra)
library(tidyr)
library(data.table)
library(ggplot2)
library(Biostrings)
```

```{r}
set.seed(10)
aa_cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(aa_cols) <- Biostrings::AA_STANDARD
aa_cols[aa_cols == "#FFFF99"] <- "#000000"
names(aa_cols) <- plyr::mapvalues(names(aa_cols), names(AMINO_ACID_CODE), AMINO_ACID_CODE)
```

```{r}
mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x > min(q) & x < max(q)])
}
BaselineSelect <- function(si, AABlockade, a, G = 4, minG = NULL, minlambda = 0.05) {
  if(is.null(minG)) minG <- round(G / 2)
  
  si[, Blockade := 1 - SignalCurrent / BaseMean]
  fit_list <- list()
  rs <- vector()
  den <- density(si[, BaseMean], n = 1024, bw = 1)
  
  k <- G
  fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
  out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
  
  rp <- 1
  while (rp <= 10 & any(out[, sigma] < 0.01)) {
    if(any(out[, sigma] < 0.01)) {
      fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
      out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    }
    rp <- rp + 1
  }
  
  xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
  ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
    plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
  })), 2, which.max)
  
  while (any(duplicated(ys[xs])) & k > minG) {
    k <- k - 1
    fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
    out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    rp <- 1
    while (rp <= 10 & any(out[, sigma] < 0.01)) {
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      rp <- rp + 1
    }
    xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
    ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, which.max)
  }
  k <- G
  
  fit_list[[1]] <- fit
  pred_y <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
    plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
  })), 2, max)
  r <- summary(lm(pred_y ~ den$y))$r.squared
  rs[1] <- r
  
  irt <- 2
  while (r < 0.95 & irt < 50) {
    fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
    out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    rp <- 1
    while (rp <= 10 & any(out[, sigma] < 0.01)) {
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      rp <- rp + 1
    }
    xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
    ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, which.max)
    
    while (any(duplicated(ys[xs])) & k > minG) {
      k <- k - 1
      fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
      out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
      ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
        plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
      })), 2, which.max)
    }
    k <- G
    
    fit_list[[irt]] <- fit
    pred_y <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, max)
    r <- summary(lm(pred_y ~ den$y))$r.squared
    rs[irt] <- r
    irt <- irt + 1
  }
  
  fit <- fit_list[[which.max(rs)]]
  out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
  
  out$BaselineGroup <- paste0("G", seq_len(nrow(out)))
  out <- out[sigma > 2 | lambda < minlambda, BaselineGroup := NA]
  
  si$BaselineGroup <- paste0("G", apply(fit$posterior, 1, which.max))
  # majorG <- si[BaselineGroup %in% out[!is.na(BaselineGroup), BaselineGroup], .(mean2(Blockade)), BaselineGroup][which.min(abs(V1 - AABlockade[amino_acid == a, Blockade])), BaselineGroup]
  majorG <- out[which.max(lambda), BaselineGroup]
  
  si[BaselineGroup == majorG, BaselineGroup := "G0"]
  
  attr(si, "out") <- out
  attr(si, "majorG") <- majorG
  return(si)
}

BaselinePlot <- function(si) {
  out <- attr(si, "out")
  majorG <- attr(si, "majorG")
  
  out1 <- out[BaselineGroup == majorG]
  out2 <- out[BaselineGroup != majorG | is.na(BaselineGroup)]
  ggplot(si, aes(x = BaseMean)) + 
    geom_histogram(data = si, aes(x = BaseMean, y = after_stat(density)), fill = "grey", binwidth = .2) +
    # geom_density() + 
    theme_bw(base_size = 15) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out1[1, mu], out1[1, sigma], lam = out1[1, lambda]), colour = 2, lwd = 1, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[1, mu], out2[1, sigma], lam = out2[1, lambda]), colour = 1, lwd = .5, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[2, mu], out2[2, sigma], lam = out2[2, lambda]), colour = 1, lwd = .5, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[3, mu], out2[3, sigma], lam = out2[3, lambda]), colour = 1, lwd = .5, n = 2000) + 
    labs(title = si[, unique(file_name)])
}

plot_mix_comps <- function(x, mu, sigma, lam) {
  lam * dnorm(x, mu, sigma)
}
```

```{r}
meta1 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 1, cols = 1:7))
meta2 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 2, cols = 1:7))
meta3 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 3, cols = 1:7))
meta4 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 4, cols = 1:7))
meta <- rbind(meta1, meta2, meta3, meta4, use.names = FALSE)
colnames(meta) <- c("file_name", "date", "amino_acid", "concentration", "start_time", "end_time", "type")
meta[amino_acid == "cys", amino_acid := "Cys"]
meta <- meta[amino_acid %in% Biostrings::AMINO_ACID_CODE]
meta <- meta[concentration == 0]
meta$file_path <- mapply(meta$file_name, FUN = function(x) list.files("./data", recursive = TRUE, full.names = TRUE, pattern = as.character(x))[1])
meta <- meta[!is.na(file_path)]
meta[, start_time := as.numeric(start_time)]
meta[, end_time := as.numeric(end_time)]
meta <- meta[!grepl("abf$", file_name)]
```


```{r}
meta[, unique(amino_acid)]
A <- "Glu"
```

```{r}
Sig0 <- lapply(meta[, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec27/RawSignal_", x, ".txt")))
  x[, Blockade := 1 - SignalCurrent / BaseMean]
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig0 <- Sig0[mapply(nrow, Sig0) > 0]
```

```{r}
ggplot(do.call(rbind, Sig0), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  facet_wrap(~ file_name) +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", do.call(rbind, Sig0)[, .N], " (Right L0)"))

ggplot(do.call(rbind, Sig0), aes(y = BaseMean, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  facet_wrap(~ file_name) +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", do.call(rbind, Sig0)[, .N], " (Right L0)"))
```

```{r message=F}
Sig1 <- mclapply(Sig0, function(x) BaselineSelect(si = x, AABlockade = AABlockade, a = A, G = 4, minG = 3), mc.cores = 10)
rr <- mapply(is.null, mapply(nrow, Sig1))
Sig1[which(rr)] <- mclapply(Sig0[which(rr)], function(x) BaselineSelect(si = x, AABlockade = AABlockade, a = A, G = 2, minG = 2), mc.cores = 10)
```

```{r fig.width=12, fig.height=6}
Ps <- lapply(Sig1[1:12], BaselinePlot)
cowplot::plot_grid(plotlist = Ps)
```

```{r}
Sig2 <- do.call(rbind, Sig1)
```

```{r fig.height=5, fig.width=15}
ggplot(Sig2, aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig2[, .N], " (Raw)")) -> p1

ggplot(Sig2[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig2[BaselineGroup == "G0", .N], " (Right L0)")) -> p2

ggplot(Sig2[BaselineGroup == "G0" & SignalCurrentPercent > 90], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig2[BaselineGroup == "G0" & SignalCurrentPercent > 90, .N], " (Right L0 & State1)")) -> p3

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2), ggMarginal(p3), nrow = 1)
```

```{r}
Sig2 <- merge(Sig2, meta[, .(file_name, amino_acid, type)], by = "file_name")
```

```{r fig.width=25, fig.height=16}
ggplot(Sig2[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  facet_wrap(~ amino_acid)
ggsave("./analysis/12.SignalFiltering/Dec28/Filter2/Plot/Blank_signal_Blockade_of_each_AA.pdf", width = 20, height = 12)
```


```{r}
Sig3 <- Sig2[amino_acid %in% c("Arg", "Asn", "Asp", "Glu", "His", "Ile", "Leu", "Lys", "Phe", "Pro", "Ser", "Thr", "Trp", "Tyr", "Val")]
```

```{r fig.width=25, fig.height=16}
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  facet_wrap(~ amino_acid)
```

```{r}
ggplot(Sig2[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = amino_acid)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")
```

```{r}
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = amino_acid)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")
```

```{r}
fwrite(Sig2, "./analysis/12.SignalFiltering/Dec28/Filter2/Blank_Signal.txt", sep = "\t", row.names = FALSE)
```

```{r}
Sig2_samp <- Sig2[, .SD[sample(.N, 20)], amino_acid]
Sig2_samp <- split(Sig2_samp, Sig2_samp$amino_acid)
```

```{r}
Plot_data <- lapply(1:20, function(i) {
  Ai <- Sig2_samp[[i]]
  Si <- mclapply(seq_len(nrow(Ai)), function (j) {
    Si <- Ai[j, ]
    abf <- readRDS(paste0("./analysis/11.SignalIdentification/Dec27/ABF_", as.character(Si[, file_name]), ".Rds"))
    current <- abf[Time >= Si[, StartTime] - 0.001 & Time <= Si[, EndTime] + 0.001]
    current[, Scaled_pA := pA / Si$BaseMean]
    return(current)
  }, mc.cores = 10)
  Si <- data.table(ID = rep(Ai[, ID], mapply(nrow, Si)), do.call(rbind, Si))
  data.table(amino_acid = names(Sig2_samp)[i], Si)
})
```

```{r fig.width=20, fig.height=1.5}
ggplot(Plot_data[[1]], aes(x = Time, y = Scaled_pA)) + 
  geom_line() + 
  geom_hline(yintercept = AABlockade[amino_acid == Plot_data[[1]][, unique(amino_acid)], 1- Blockade], colour = 2) + 
  scale_y_continuous(n.breaks = 5) +
  facet_wrap(~ ID, nrow = 1, scales = "free_x") + 
  theme_bw(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(), 
        strip.text = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank()) + 
  labs(y = Plot_data[[1]][, unique(amino_acid)])
```

```{r fig.width=20, fig.height=20}
Ps <- lapply(1:20, function(i) {
  ggplot(Plot_data[[i]], aes(x = Time, y = Scaled_pA)) + 
    geom_line() + 
    geom_hline(yintercept = AABlockade[amino_acid == Plot_data[[i]][, unique(amino_acid)], 1- Blockade], colour = 2) + 
    scale_y_continuous(n.breaks = 5) +
    facet_wrap(~ ID, nrow = 1, scales = "free_x") + 
    theme_bw(base_size = 15) + 
    theme(axis.title.x = element_blank(), 
          axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(), 
          strip.text = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.grid.major.x = element_blank()) + 
    labs(y = Plot_data[[i]][, unique(amino_acid)])
})
```

```{r fig.width=20, fig.height=20}
cowplot::plot_grid(plotlist = Ps, ncol = 1, align = "hv")
ggsave("./analysis/12.SignalFiltering/Dec28/Filter2/Plot/Blank_signal.pdf", width = 15, height = 20)
```

```{r fig.height=3, fig.width=6}
ggplot(Sig2, aes(x = Blockade, colour = amino_acid)) + 
  geom_line(stat = "density") + 
  theme_bw(base_size = 15) + 
  scale_colour_manual(values = aa_cols, breaks = names(aa_cols)) + 
  guides(colour = guide_legend(ncol = 2, title = element_blank())) + 
  labs(y = "Density")
ggsave("./analysis/12.SignalFiltering/Dec28/Filter2/Plot/Blank_signal_Blockade_density.pdf", width = 6, height = 3)
```

```{r fig.height=3.5, fig.width=6}
ggplot(Sig2, aes(x = Blockade, y = DwellTime * 1000, colour = amino_acid)) + 
  geom_point(size = 0.1) + 
  scale_y_log10() + 
  scale_colour_manual(values = aa_cols, breaks = names(aa_cols)) + 
  guides(colour = guide_legend(ncol = 2, title = element_blank(), override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)") +
  theme_bw(base_size = 15) + 
  theme(legend.key.size = unit(1, "line")) -> p1
ggMarginal(p1, margins = "x", groupColour = TRUE)
ggsave("./analysis/12.SignalFiltering/Dec28/Filter2/Plot/Blank_signal_Blockade_DwellTime.pdf", width = 6, height = 3.5)
```


