---
title: "Phe"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = F, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
```

```{r}
library(readABF)
library(data.table)
library(S4Vectors)
library(IRanges)
library(changepoint)
library(ggplot2)

KBins <- function(sig, minseglen1 = 100, minseglen2 = 10, pen.value = 1e-3) {
  ansmean1 <- suppressWarnings(changepoint::cpt.meanvar(sig, penalty = "None", method = "PELT", minseglen = minseglen1))
  Tab1 <- data.table(P = sig, B1 = rep(seq_len(nseg(ansmean1)), seg.len(ansmean1)))
  Tab2 <- Tab1[, .(P = median(P)), by = "B1"]
  
  ansmean2 <- suppressWarnings(changepoint::cpt.meanvar(Tab2[, P], penalty = "Asymptotic", pen.value = pen.value, method = "PELT", minseglen = minseglen2))
  Tab2[, B := rep(seq_len(nseg(ansmean2)), seg.len(ansmean2))]
  res <- merge(Tab1, Tab2[, .(B1, B)], by = "B1")
  res[, B1 := NULL]
  res[, .(P = median(P), N = .N), "B"][, rep(P, N)]
}

KBins2 <- function(sig, minseglen1 = 100, minseglen2 = 10, pen.value = 1e-3) {
  ansmean1 <- suppressWarnings(changepoint::cpt.mean(sig, penalty = "MBIC", method = "PELT", minseglen = minseglen1))
  Tab1 <- data.table(P = sig, B1 = rep(seq_len(nseg(ansmean1)), seg.len(ansmean1)))
  Tab2 <- Tab1[, .(P = median(P)), by = "B1"]
  
  ansmean2 <- suppressWarnings(changepoint::cpt.meanvar(Tab2[, P], penalty = "Asymptotic", pen.value = pen.value, method = "PELT", minseglen = minseglen2))
  Tab2[, B := rep(seq_len(nseg(ansmean2)), seg.len(ansmean2))]
  res <- merge(Tab1, Tab2[, .(B1, B)], by = "B1")
  res[, B1 := NULL]
  res[, .(P = median(P), N = .N), "B"][, rep(P, N)]
}
```

# Step1. read ABF file

```{r}
phe <- readABF::readABF("/mnt/raid62/Personal_data/zhangdan/AA_zhangming/0304-phe#2-3/21304011.abf")
phe <- as.data.table(as.data.frame(phe))
colnames(phe) <- c("Time", "pA", "mV")
phe <- phe[Time > 2.7 * 60 & Time < 8.6 * 60, ]
```

Only keep data with a voltage of 50 mV
```{r}
paste0("Only ", round(mean(phe[, round(mV) == 50]) * 100, 2), "% of the data is retained.")
phe <- phe[round(mV) == 50, ]
```

Raw current density plot
```{r fig.width=12, fig.height=6}
plot(density(phe[pA < 130 & pA >= 0, pA], adjust = 3), xlab = "Current (pA)", main = "density of raw current")
```

# Step2. Noise reduction

```{r}
# phe$Sm <- KBins(sig = phe$pA, pen.value = 1e-3, minseglen1 = 4, minseglen2 = 10)
phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
```

```{r fig.width=12, fig.height=6}
phe[Time > 162.2 & Time < 162.3, plot(Time, pA, type = "s")]
phe[Time > 162.2 & Time < 162.3, lines(Time, Sm, type = "s", col = "red")]
```

```{r fig.width=12, fig.height=6}
phe[Time > 0.91 & Time < 0.94, plot(Time, pA, type = "s")]
phe[Time > 0.91 & Time < 0.94, lines(Time, Sm, type = "s", col = "red")]
```

## Density plot of smoothed signal

```{r fig.width=12, fig.height=6}
DenSm <- density(phe[Sm < 130 & Sm >= 0, Sm], adjust = 1)

Bx <- DenSm$x[start(IRanges(diff(DenSm$y) > 0))]
By <- DenSm$y[start(IRanges(diff(DenSm$y) > 0))]

Px <- DenSm$x[start(IRanges(diff(DenSm$y) < 0))]
Py <- DenSm$y[start(IRanges(diff(DenSm$y) < 0))]

ic <- Py > 0.1 * max(Py)

plot(DenSm, xlab = "Current (pA)", main = "density of smooth current")
text(x = Px[ic], y = Py[ic] + max(Py) * 0.02, labels = round(Px[ic], 1))

ib <- c(mapply(Px[ic], FUN = function(x) max(which(Bx < x))), mapply(Px[ic], FUN = function(x) min(which(Bx > x))))
ib <- ib[!is.infinite(ib)]

text(x = Bx[ib], y = By[ib] - max(Py) * 0.02, labels = round(Bx[ib], 1))
```

# Step3. Division of signal interval

```{r}
pAFreq <- phe[, .N, by = round(Sm)]
setnames(pAFreq, "round", "pA")
pAFreq[, P := N/sum(N) * 100]

HFpA <- pAFreq[order(P, decreasing = TRUE), pA]

for(i in seq_along(HFpA)) {
  if(diff(range(HFpA[1:i])) + 1 == i) {
    next()
  } else {
    break()
  }
}
L0 <- HFpA[1:(i - 1)]

if(length(L0) > 3) L0 <- L0[1:3]

L0Min <- min(L0) * 0.9
```

```{r}
DenSmTab <- data.table(x = DenSm$x, y = DenSm$y)

for(i in seq_along(DenSmTab$y)) {
  gr <- IRanges(DenSmTab$y >= sort(DenSmTab$y, decreasing = TRUE)[i])
  
  if(length(gr) == 1) {
    next()
  } else {
    break()
  }
}
gr <- IRanges(DenSmTab$y >= sort(DenSmTab$y, decreasing = TRUE)[i - 1])

L0 <- range(floor(range(DenSmTab[start(gr):end(gr), x])), ceiling(range(DenSmTab[start(gr):end(gr), x])))
L0Min <- min(L0) * 0.9
```

```{r}
phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
phe[Sm < L0Min, L := "U"] # U shape
phe[is.na(L), L := "O"] # Other
```

```{r}
LRle <- Rle(phe[, L])
LRg <- IRanges(start(LRle), end(LRle))
mcols(LRg)$L <- runValue(LRle)

LRleVa <- paste0(runValue(LRle), collapse = "")

allcombn <- c("BUB", "BOUB", "BUOB")

BUB <- lapply(allcombn, function(x) gregexpr(x, LRleVa)[[1]])
BUB <- BUB[!mapply(function(x) all(x == -1), BUB)]

BUB <- lapply(BUB, function(x) {
  start <- as.numeric(x)
  steps <- unique(attr(x, "match.length"))
  lapply(start, function(x) phe[start(range(LRg[x:(x + steps - 1)])):end(range(LRg[x:(x + steps - 1)])), ])
})
BUB <- do.call(c, BUB)
```


```{r fig.width=12, fig.height=6}
DenSm <- density(do.call(rbind, BUB)[Sm < 130 & Sm >= 0, Sm], adjust = 3)

Bx <- DenSm$x[start(IRanges(diff(DenSm$y) > 0))]
By <- DenSm$y[start(IRanges(diff(DenSm$y) > 0))]

Px <- DenSm$x[start(IRanges(diff(DenSm$y) < 0))]
Py <- DenSm$y[start(IRanges(diff(DenSm$y) < 0))]

ic <- Py > 0.003 * max(Py)

plot(DenSm, xlab = "Current (pA)", main = "density of smooth current")
text(x = Px[ic], y = Py[ic] + max(Py) * 0.02, labels = round(Px[ic], 1))

ib <- c(mapply(Px[ic], FUN = function(x) max(which(Bx < x))), mapply(Px[ic], FUN = function(x) min(which(Bx > x))))
ib <- ib[!is.infinite(ib)]

text(x = Bx[ib], y = By[ib] - max(Py) * 0.02, labels = round(Bx[ib], 1))
```

```{r}
DenSm <- density(do.call(rbind, BUB)[Sm < L0Min & Sm >= 0, Sm], adjust = 1)

Bx <- DenSm$x[start(IRanges(diff(DenSm$y) > 0))]
By <- DenSm$y[start(IRanges(diff(DenSm$y) > 0))]

Px <- DenSm$x[start(IRanges(diff(DenSm$y) < 0))]
Py <- DenSm$y[start(IRanges(diff(DenSm$y) < 0))]

ic <- Py > 0.1 * max(Py)

plot(DenSm, xlab = "Current (pA)", main = "density of smooth current")
text(x = Px[ic], y = Py[ic] + max(Py) * 0.02, labels = round(Px[ic], 1))

ib <- c(mapply(Px[ic], FUN = function(x) max(which(Bx < x))), mapply(Px[ic], FUN = function(x) min(which(Bx > x))))
ib <- ib[!is.infinite(ib)]

text(x = Bx[ib], y = By[ib] - max(Py) * 0.02, labels = round(Bx[ib], 1))
```

```{r}
pAFreq <- do.call(rbind, BUB)[Sm < L0Min & Sm >= 0, .N, by = round(Sm)]
setnames(pAFreq, "round", "pA")
pAFreq[, P := N/sum(N) * 100]
pAFreq <- pAFreq[order(P, decreasing = TRUE), ]
HFpA <- pAFreq[order(P, decreasing = TRUE), pA]

for(i in seq_along(HFpA)) {
  if(diff(range(HFpA[1:i])) + 1 == i) {
    next()
  } else {
    break()
  }
}
L1 <- HFpA[1:(i - 1)]
L1Min <- min(L1) * 0.9
```

```{r}
DenSmTab <- data.table(x = DenSm$x, y = DenSm$y)

for(i in seq_along(DenSmTab$y)) {
  gr <- IRanges(DenSmTab$y >= sort(DenSmTab$y, decreasing = TRUE)[i])
  
  if(length(gr) == 1) {
    next()
  } else {
    break()
  }
}
gr <- IRanges(DenSmTab$y >= sort(DenSmTab$y, decreasing = TRUE)[i - 1])

L1 <- range(floor(range(DenSmTab[start(gr):end(gr), x])), ceiling(range(DenSmTab[start(gr):end(gr), x])))
L1Min <- min(L1) * 0.9
```

```{r}
DenSm <- density(do.call(rbind, BUB)[Sm < L1Min & Sm >= 0, Sm], adjust = 1)

Bx <- DenSm$x[start(IRanges(diff(DenSm$y) > 0))]
By <- DenSm$y[start(IRanges(diff(DenSm$y) > 0))]

Px <- DenSm$x[start(IRanges(diff(DenSm$y) < 0))]
Py <- DenSm$y[start(IRanges(diff(DenSm$y) < 0))]

ic <- Py > 0.1 * max(Py)

plot(DenSm, xlab = "Current (pA)", main = "density of smooth current")
text(x = Px[ic], y = Py[ic] + max(Py) * 0.02, labels = round(Px[ic], 1))

ib <- c(mapply(Px[ic], FUN = function(x) max(which(Bx < x))), mapply(Px[ic], FUN = function(x) min(which(Bx > x))))
ib <- ib[!is.infinite(ib)]

text(x = Bx[ib], y = By[ib] - max(Py) * 0.02, labels = round(Bx[ib], 1))
```

```{r}
pAFreq <- do.call(rbind, BUB)[Sm < L1Min & Sm >= 0, .N, by = round(Sm)]
setnames(pAFreq, "round", "pA")
pAFreq[, P := N/sum(N) * 100]
pAFreq <- pAFreq[order(P, decreasing = TRUE), ]
HFpA <- pAFreq[order(P, decreasing = TRUE), pA]

for(i in seq_along(HFpA)) {
  if(diff(range(HFpA[1:i])) + 1 == i) {
    next()
  } else {
    break()
  }
}
L2 <- HFpA[1:(i - 1)]
```

```{r}
DenSmTab <- data.table(x = DenSm$x, y = DenSm$y)

for(i in seq_along(DenSmTab$y)) {
  gr <- IRanges(DenSmTab$y >= sort(DenSmTab$y, decreasing = TRUE)[i])
  
  if(length(gr) == 1) {
    next()
  } else {
    break()
  }
}
gr <- IRanges(DenSmTab$y >= sort(DenSmTab$y, decreasing = TRUE)[i - 1])

L2 <- range(floor(range(DenSmTab[start(gr):end(gr), x])), ceiling(range(DenSmTab[start(gr):end(gr), x])))
L2Min <- min(L2) * 0.9
```

# Step4. Primary baseline current processing

## Repolish

## Signal classification

```{r}
BUB2 <- BUB[mapply(function(x) any(x[, Sm] <= max(L1)), BUB)]
BUB2 <- BUB2[!mapply(function(x) any(x[, Sm] < min(L2)), BUB2)]
```

```{r}
BUB2 <- lapply(BUB2, function(x) {
  y <- copy(x)
  y[Sm <= max(L0) & Sm >= min(L0), S := "0"] # baseline
  y[Sm <= max(L1) & Sm >= min(L1), S := "1"] # first
  y[Sm <= max(L2) & Sm >= min(L2), S := "2"] # second
  return(y)
})
```

## Filtering

```{r}
BUB2 <- BUB2[!mapply(function(x) all(unique(x[!is.na(S), L]) == "B"), BUB2)]
```

```{r}
Lsd <- mapply(function(x) x[!is.na(S) & S != 0, sd(pA), by = "S"][, mean(V1)], BUB2)
hist(Lsd, breaks = 100)
```

```{r}
BUB2 <- BUB2[Lsd < 4]
```

```{r}
Lna <- mapply(function(x) x[, sum(is.na(S))]/x[S != 0 | is.na(S), .N], BUB2)
hist(Lna, breaks = 200)
```

```{r}
BUB2 <- BUB2[Lna < .3]
```

```{r}
mapply(BUB2, FUN = function(x) {
  paste0(runValue(Rle(x[!is.na(S), S])), collapse = "")
}) -> sigclass
names(BUB2) <- sigclass
```

```{r}
sigclass <- as.data.table(as.data.frame(table(sigclass), stringsAsFactors = FALSE))
sigclass[, sigclass := as.character(sigclass)]
# sigclass[, sigclass := gsub("^B", "", sigclass)]
# sigclass[, sigclass := gsub("B$", "", sigclass)]

setkey(sigclass, Freq, sigclass)
sigclass$sigclass <- factor(sigclass$sigclass, levels = rev(sigclass$sigclass))
```

```{r fig.width=10, fig.height=4}
ggplot(sigclass, aes(x = sigclass, y = Freq)) + 
  geom_col() + 
  geom_text(aes(x = sigclass, y = Freq + 10, label = Freq)) +
  theme_classic(base_size = 15) + 
  theme(axis.title.x = element_blank()) + 
  theme(axis.text.x = element_text(angle = 10, hjust = 1))
```

## Example of primary baseline

```{r fig.width=12, fig.height=6}
Tab <- BUB2[[which(names(BUB2) == "010")[431]]]

ggplot() + 
  geom_step(data = Tab, aes(Time, pA)) + 
  geom_step(data = Tab, aes(Time, Sm, colour = "red")) + 
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = min(L0), ymax = max(L0)), alpha = 0.2) + 
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = min(L1), ymax = max(L1)), alpha = 0.2) + 
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = min(L2), ymax = max(L2)), alpha = 0.2) + 
  theme_classic(base_size = 16) + 
  theme(legend.position = "none")
```

```{r}
saveRDS(object = BUB2, file = "/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/01.AASignalRecognition/ZhangMing20210402/phe/21304011_BUB.Rds")
```

```{r}
BUB2 <- readRDS("/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/01.AASignalRecognition/ZhangMing20210402/phe/21304011_BUB.Rds")
```

## Density 

```{r fig.width=12, fig.height=6}
DenSm <- density(do.call(rbind, BUB2)[, pA], adjust = 5)

Bx <- DenSm$x[start(IRanges(diff(DenSm$y) > 0))]
By <- DenSm$y[start(IRanges(diff(DenSm$y) > 0))]

Px <- DenSm$x[start(IRanges(diff(DenSm$y) < 0))]
Py <- DenSm$y[start(IRanges(diff(DenSm$y) < 0))]

ic <- Py > 0.1 * max(Py)

plot(DenSm, xlab = "Current (pA)", main = "density of smooth current")
text(x = Px[ic], y = Py[ic] + max(Py) * 0.02, labels = round(Px[ic], 1))

ib <- c(mapply(Px[ic], FUN = function(x) max(which(Bx < x))), mapply(Px[ic], FUN = function(x) min(which(Bx > x))))
ib <- ib[!is.infinite(ib)]

text(x = Bx[ib], y = By[ib] - max(Py) * 0.02, labels = round(Bx[ib], 1))
```

# Step5. Features of levels

## Level 1 from 010

```{r}
B1B <- BUB2[names(BUB2) == "010"]

L1_B1B <- lapply(B1B, function(x) {
  BaseMedian <- x[S == 0, median(pA)]
  Lev1Median <- x[S == 1, median(pA)]
  TimeDiff <- diff(x[S == 1, range(Time)])
  data.table(BaseMedian = BaseMedian, Lev1Median = Lev1Median, TimeDiff = TimeDiff)
})
L1_B1B <- do.call(rbind, L1_B1B)
```

```{r}
hist(L1_B1B[, TimeDiff], breaks = 20, main = "Histogram of time", xlab = "Time (s)")
```

```{r}
plot(density(L1_B1B[, TimeDiff]), main = "Density of time", xlab = "Time (s)")
```

```{r}
hist(L1_B1B[, Lev1Median/(BaseMedian - Lev1Median)], breaks = 100)
mean(L1_B1B[, Lev1Median/(BaseMedian - Lev1Median)])
# [1] 3.577859
sd(L1_B1B[, Lev1Median/(BaseMedian - Lev1Median)])
# [1] 0.09681285
```

```{r}
plot(density(L1_B1B[, Lev1Median/(BaseMedian - Lev1Median)]), main = "Density of time", xlab = "Time (s)")
```