---
title: "Figure 3"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
library(caret)
library(multiROC)
library(pROC)
```

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels/ModelARNDCQEGHILKMFPSTWYV.RData")
model1 <- readRDS("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels/ModelARNDCQEGHILKMFPSTWYV.Rds")
train_res <- data.table(ID = Sigs_Train_Upsample$ID, Obse = Sigs_Train_Upsample$AA, Pred = model1$finalModel$predicted, Prob = apply(model1$finalModel$votes, 1, max))
train_res[, Obse := factor(Obse, levels = train_res[, levels(Pred)])]
train_res[, mean(Obse == Pred)]
test_res <- data.table(ID = Sigs_Test$ID, Obse = Sigs_Test$AA, Pred = predict(model1, Sigs_Test_FM), Prob = apply(predict(model1, Sigs_Test_FM, type = "prob"), 1, max))
test_res[, Obse := factor(Obse, levels = test_res[, levels(Pred)])]
test_res[, mean(Obse == Pred)]
model1_res <- rbind(data.table(train_res, Dataset = "Training"), data.table(test_res, Dataset = "Testing"))
```

```{r}
cutoffList <- lapply(1:50/50, function(b) {
  merge(model1_res[, .(Recovery = mean(Prob >= b) * 100), by = Dataset], 
        model1_res[Prob >= b, .(Accuracy = mean(Obse == Pred) * 100), by = Dataset])
})
cutoffList <- data.table(Cutoff = rep(1:50/50, mapply(nrow, cutoffList)), do.call(rbind, cutoffList))
cutoffList[, L := paste0("(", round(Recovery, 1), ", ", round(Accuracy, 1), ")")]
```

```{r fig.width=4, fig.height=4}
ggplot(cutoffList, aes(x = Recovery, y = Accuracy, colour = Dataset)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)") + 
  geom_point(data = cutoffList[Cutoff %in% c(c(5)/10)]) +
  geom_text_repel(data = cutoffList[Cutoff %in% c(c(5)/10)], aes(x = Recovery, y = Accuracy, label = L)) +
  scale_color_brewer(palette = "Dark2", guide = guide_legend(reverse = T)) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "top", panel.grid = element_blank())
```

```{r}
cM <- test_res[, confusionMatrix(Pred, Obse)]
cM <- as.matrix(cM$table)
cM <- reshape2::dcast(as.data.frame(cM), Prediction ~ Reference)
cM <- data.frame(cM[, -1], row.names = cM[, 1])
cM <- apply(cM, 2, prop.table)*100
row.names(cM) <- plyr::mapvalues(row.names(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
colnames(cM) <- plyr::mapvalues(colnames(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
m1 <- reshape2::melt(as.matrix(cM))
colnames(m1)[3] <- "Percentage"
ggplot(data = m1, aes(x = Var1, y = Var2, fill = Percentage)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") + 
  labs(x = "Prediction", y = "Reference") +
  theme_bw(base_size = 15) + 
  theme(plot.margin = unit(c(0.25, 0, 0, 0), "lines"))  -> p1

ggplot(data.table(A = factor(rownames(cM), levels = rownames(cM)), Percentage = rowSums(cM)), aes(x = A, y = Percentage)) +
  geom_col(fill = "#A50F15") +
  theme_bw(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "lines")) -> p2
```

```{r fig.width=5, fig.height=4}
p2 / p1 + plot_layout(heights = c(2, 8))
```


```{r}
vImp <- varImp(model1, scale = T)
vImp <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))
```

```{r}
ggplot(vImp, aes(x = x, y = Importance)) + 
  geom_line() + 
  scale_x_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("X0001", "X0250", "X0500", "X0750", "X1000")) + 
  labs(x = "Predictors") + 
  ggthemes::theme_clean(base_size = 20)
```





```{r eval=FALSE}
models0 <- lapply(c("AdaBoost", "CART", "knn", "NB", "NNet", "RF"), function(m) {
  if(m == "RF") {
    readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels/ModelARNDCQEGHILKMFPSTWYV.Rds")
  } else {
    readRDS(list.files("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels", paste0(m, ".Rds"), full.names = T))
  }
})


predicts0 <- lapply(c("AdaBoost", "CART", "knn", "NB", "NNet", "RF"), function(m) {
  if(m == "RF") {
    model <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels/ModelARNDCQEGHILKMFPSTWYV.Rds")
  } else {
    model <- readRDS(list.files("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels", paste0(m, ".Rds"), full.names = T))
  }
  data.table(Method = m, ID = Sigs_Test$ID, Obse = Sigs_Test$AA, Pred = predict(model, Sigs_Test_FM), Prob = apply(predict(model, Sigs_Test_FM, type = "prob"), 1, max))
})
predicts0 <- do.call(rbind, predicts0)
predicts0[, Obse := factor(Obse, levels = AMINO_ACID_CODE[1:20])]
```

```{r eval=FALSE}
cutoffList2 <- lapply(1:50/50, function(b) {
  merge(predicts0[, .(Recovery = mean(Prob >= b) * 100), by = Method], 
        predicts0[Prob >= b, .(Accuracy = mean(Obse == Pred) * 100), by = Method])
})
cutoffList2 <- data.table(Cutoff = rep(1:50/50, mapply(nrow, cutoffList2)), do.call(rbind, cutoffList2))
cutoffList2[, L := paste0("(", round(Recovery, 1), ", ", round(Accuracy, 1), ")")]
```

```{r eval=FALSE, fig.width=12, fig.height=8}
ggplot(cutoffList2, aes(x = Recovery, y = Accuracy, colour = Method)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)") + 
  geom_point(data = cutoffList2[Cutoff %in% c(c(5)/10)]) +
  geom_text_repel(data = cutoffList2[Cutoff %in% c(c(5)/10)], aes(x = Recovery, y = Accuracy, label = L)) +
  scale_color_brewer(palette = "Dark2", guide = guide_legend(reverse = T)) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none", panel.grid = element_blank()) + 
  facet_wrap(~ Method, scales = "free")
```


```{r eval=FALSE}
predicts1 <- lapply(c("AdaBoost", "CART", "knn", "NB", "NNet", "RF"), function(m) {
  if(m == "RF") {
    model <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels/ModelARNDCQEGHILKMFPSTWYV.Rds")
  } else {
    model <- readRDS(list.files("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.TrainModels", paste0(m, ".Rds"), full.names = T))
  }
  predi <- predict(model, Sigs_Test_FM, type = "prob")
  colnames(predi) <- paste0(colnames(predi), paste0("_pred_", m))
  predi
})
predicts1 <- do.call(cbind, predicts1)

true_label1 <- dummies::dummy(test_res$Obse, sep = " ")
true_label1 <- data.frame(true_label1)
colnames(true_label1) <- gsub("Obse.", "", colnames(true_label1))
colnames(true_label1) <- paste0(colnames(true_label1), "_true")

roc_RF1 <- multiROC::multi_roc(cbind(true_label1, predicts1))
pr_RF1 <- multiROC::multi_pr(cbind(true_label1, predicts1))
```

```{r eval=FALSE}
mapply(function(x) x$macro, roc_RF1$AUC)
```
