---
title: "Figure 3"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
library(caret)
library(multiROC)
library(pROC)
```

# Algorithm

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/Modeling_Data.RData")
Sigs_Test_FM <- Sigs_Test_FM[Sigs_Test[, !is.infinite(SignalCurrentWidth)], ]
Sigs_Test <- Sigs_Test[!is.infinite(SignalCurrentWidth)]
```

```{r eval=FALSE}
predicts1 <- mclapply(c("AdaBoost", "CART", "KNN", "NB", "NNet", "RF"), function(m) {
  model <- readRDS(paste0("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/", m, "_model.Rds"))
  predi <- predict(model, Sigs_Test_FM, type = "prob")
  colnames(predi) <- paste0(colnames(predi), paste0("_pred_", m))
  predi
}, mc.cores = 6)
saveRDS(predicts1, file = "analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/predicts1.Rds")
```

```{r}
if(!is.element("predicts1", ls())) predicts1 <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/predicts1.Rds")
```

```{r}
predicts2 <- do.call(cbind, predicts1)

true_label1 <- dummies::dummy(Sigs_Test$AA, sep = " ")
true_label1 <- data.frame(true_label1)
colnames(true_label1) <- gsub("AA.", "", colnames(true_label1))
colnames(true_label1) <- paste0(colnames(true_label1), "_true")

roc_RF1 <- multiROC::multi_roc(cbind(true_label1, predicts2))
pr_RF1 <- multiROC::multi_pr(cbind(true_label1, predicts2))
```

```{r}
mapply(function(x) x$macro, roc_RF1$AUC)
mapply(function(x) x$macro, pr_RF1$AUC)
```

```{r}
plot_roc <- lapply(predicts1, function(x) {
  as.data.table(multiROC::plot_roc_data(multiROC::multi_roc(cbind(true_label1, x))))
})

plot_pr <- lapply(predicts1, function(x) {
  as.data.table(multiROC::plot_pr_data(multiROC::multi_pr(cbind(true_label1, x))))
})
```

```{r}
roc_mat <- lapply(plot_roc, function(x) {
  set.seed(123)
  x[Group == "Macro"][sort(sample(.N, 1000))]
})
roc_mat <- do.call(rbind, roc_mat)
```

```{r}
AUCs <- data.table(Method = names(mapply(function(x) x$macro, roc_RF1$AUC)), AUC = mapply(function(x) x$macro, roc_RF1$AUC))
```

```{r fig.width=6, fig.height=4}
ggplot(roc_mat, aes(x = 1 - Specificity, y = Sensitivity, colour = Method)) + 
  geom_path(size = 1) + 
  geom_text(data = AUCs, mapping = aes(x = 0.75, y = 6:1/10, label = paste("AUC:", round(AUC, 3)))) +
  theme_bw(base_size = 15) + 
  # scale_color_manual(values = MoldeCols[od]) + 
  lims(x = c(0, 1), y = c(0, 1)) + 
  labs(tag = "a") + 
  theme(panel.grid = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold")) -> p1
p1
```


# Cutoff-list

L1 

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/Modeling_Data.RData")
model1 <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/RF_model.Rds")
train_res <- data.table(ID = Sigs_Train_Upsample$ID, Obse = Sigs_Train_Upsample$AA, Pred = model1$finalModel$predicted, Prob = apply(model1$finalModel$votes, 1, max))
train_res[, Obse := factor(Obse, levels = train_res[, levels(Pred)])]
train_res[, mean(Obse == Pred)]

Sigs_Test_FM <- Sigs_Test_FM[Sigs_Test[, !is.infinite(SignalCurrentWidth)], ]
Sigs_Test <- Sigs_Test[!is.infinite(SignalCurrentWidth)]
test_res <- data.table(ID = Sigs_Test$ID, Obse = Sigs_Test$AA, Pred = predict(model1, Sigs_Test_FM), Prob = apply(predict(model1, Sigs_Test_FM, type = "prob"), 1, max))
test_res[, Obse := factor(Obse, levels = test_res[, levels(Pred)])]
test_res[, mean(Obse == Pred)]
model1_res <- rbind(data.table(train_res, Dataset = "Training"), data.table(test_res, Dataset = "Testing"))

cutoffList <- lapply(1:50/50, function(b) {
  merge(model1_res[, .(Recovery = mean(Prob >= b) * 100), by = Dataset], 
        model1_res[Prob >= b, .(Accuracy = mean(Obse == Pred) * 100), by = Dataset])
})
cutoffList <- data.table(Cutoff = rep(1:50/50, mapply(nrow, cutoffList)), do.call(rbind, cutoffList))
cutoffList[, L := paste0("(", round(Recovery, 1), ", ", round(Accuracy, 1), ")")]

gdata::mv("cutoffList", "cutoffList_L1")
```

L2

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L2/Modeling_Data.RData")
model1 <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L2/RF_model.Rds")
train_res <- data.table(ID = Sigs_Train_Upsample$ID, Obse = Sigs_Train_Upsample$AA, Pred = model1$finalModel$predicted, Prob = apply(model1$finalModel$votes, 1, max))
train_res[, Obse := factor(Obse, levels = train_res[, levels(Pred)])]
train_res[, mean(Obse == Pred)]

Sigs_Test_FM <- Sigs_Test_FM[Sigs_Test[, !is.infinite(SignalCurrentWidth)], ]
Sigs_Test <- Sigs_Test[!is.infinite(SignalCurrentWidth)]
test_res <- data.table(ID = Sigs_Test$ID, Obse = Sigs_Test$AA, Pred = predict(model1, Sigs_Test_FM), Prob = apply(predict(model1, Sigs_Test_FM, type = "prob"), 1, max))
test_res[, Obse := factor(Obse, levels = test_res[, levels(Pred)])]
test_res[, mean(Obse == Pred)]
model1_res <- rbind(data.table(train_res, Dataset = "Training"), data.table(test_res, Dataset = "Testing"))

cutoffList <- lapply(1:50/50, function(b) {
  merge(model1_res[, .(Recovery = mean(Prob >= b) * 100), by = Dataset], 
        model1_res[Prob >= b, .(Accuracy = mean(Obse == Pred) * 100), by = Dataset])
})
cutoffList <- data.table(Cutoff = rep(1:50/50, mapply(nrow, cutoffList)), do.call(rbind, cutoffList))
cutoffList[, L := paste0("(", round(Recovery, 1), ", ", round(Accuracy, 1), ")")]

gdata::mv("cutoffList", "cutoffList_L2")
```

Ls

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/Ls/Modeling_Data.RData")
model1 <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/Ls/RF_model.Rds")
train_res <- data.table(ID = Sigs_Train_Upsample$ID, Obse = Sigs_Train_Upsample$AA, Pred = model1$finalModel$predicted, Prob = apply(model1$finalModel$votes, 1, max))
train_res[, Obse := factor(Obse, levels = train_res[, levels(Pred)])]
train_res[, mean(Obse == Pred)]

Sigs_Test_FM <- Sigs_Test_FM[Sigs_Test[, !is.infinite(SignalCurrentWidth)], ]
Sigs_Test <- Sigs_Test[!is.infinite(SignalCurrentWidth)]
test_res <- data.table(ID = Sigs_Test$ID, Obse = Sigs_Test$AA, Pred = predict(model1, Sigs_Test_FM), Prob = apply(predict(model1, Sigs_Test_FM, type = "prob"), 1, max))
test_res[, Obse := factor(Obse, levels = test_res[, levels(Pred)])]
test_res[, mean(Obse == Pred)]
model1_res <- rbind(data.table(train_res, Dataset = "Training"), data.table(test_res, Dataset = "Testing"))

cutoffList <- lapply(1:50/50, function(b) {
  merge(model1_res[, .(Recovery = mean(Prob >= b) * 100), by = Dataset], 
        model1_res[Prob >= b, .(Accuracy = mean(Obse == Pred) * 100), by = Dataset])
})
cutoffList <- data.table(Cutoff = rep(1:50/50, mapply(nrow, cutoffList)), do.call(rbind, cutoffList))
cutoffList[, L := paste0("(", round(Recovery, 1), ", ", round(Accuracy, 1), ")")]

gdata::mv("cutoffList", "cutoffList_Ls")
```

```{r}
cutoffList <- rbind(data.table(State = "State1", cutoffList_L1), data.table(State = "State2", cutoffList_L2), data.table(State = "State1 + State2", cutoffList_Ls))
cutoffList[, State := factor(State, levels = c("State1", "State2", "State1 + State2"))]
```

```{r fig.width=7, fig.height=4}
ggplot(cutoffList, aes(x = Recovery, y = Accuracy, colour = State, linetype = Dataset)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)", tag = "b") + 
  scale_color_brewer(palette = "Dark2", guide = guide_legend(reverse = F, ncol = 1)) + 
  scale_linetype(guide = guide_legend(reverse = T, ncol = 1)) + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank()) -> p2
p2
```

# Importance

```{r}
vImp1 <- lapply(c("L1", "L2", "Ls"), function(x) {
  model1 <- readRDS(paste0("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/", x, "/RF_model.Rds"))
  vImp <- varImp(model1, scale = T)
  vImp <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))
  vImp1 <- vImp[grepl("^X", Variable)]
  vImp1[, x := as.numeric(gsub("X", "", Variable))]
  data.table(State = x, vImp1)
})
vImp1 <- do.call(rbind, vImp1)
vImp1[, State := plyr::mapvalues(State, c("L1", "L2", "Ls"), c("State1", "State2", "State1 + State2"))]
vImp1[, State := factor(State, levels = c("State1", "State2", "State1 + State2"))]
```

```{r}
ggplot(vImp1[!is.na(x)], aes(x = x, y = Importance, colour = State)) + 
  geom_line() + 
  scale_x_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("X0001", "X0250", "X0500", "X0750", "X1000"), 
                     sec.axis = dup_axis(name = "Blockade", breaks = c(0, 250, 500, 750, 1000), labels = c(1, 0.75, 0.5, 0.25, 0))) + 
  scale_color_brewer(palette = "Dark2", guide = guide_legend(reverse = F, ncol = 1)) + 
  labs(x = "Predictors", tag = "c") + 
  theme_bw(base_size = 15) + 
  theme(plot.background = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank()) -> p3
p3
```

```{r fig.width=16, fig.height=4}
p1 + p2 + p3 + plot_layout(nrow = 1)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig3/Fig3_S1.pdf", width = 16, height = 4)
```


# number of signal

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version3/L1/Modeling_Data.RData")

Nsigs_1 <- Sigs_Train_Upsample[, .(N = .N, n = length(unique(ID))), AA]
Nsigs_1[, u := N - n]
Nsigs_1 <- melt.data.table(Nsigs_1, id.vars = "AA")[variable != "N"]

Nsigs_1[, Type := plyr::mapvalues(variable, c("n", "u"), c("Unique signals", "Upsampling signals"))]
Nsigs_1[, AA := factor(AA, levels = Nsigs_1[variable == "u"][order(value, AA), AA])]
Nsigs_1[, Type := factor(Type, levels = c("Upsampling signals", "Unique signals"))]
Nsigs_1[, L := as.character(value)]
Nsigs_1[value == 1000, L := ""]
Nsigs_1[value == 0, L := ""]
Nsigs_1[variable == "n", L := ""]
```

```{r}
ggplot(Nsigs_1, aes(x = AA, y = value, fill = Type)) + 
  geom_col() + 
  geom_text(aes(label = L), position = position_stack(vjust = .5)) + 
  scale_fill_manual(values = c("#FEE0D2", "#CB181D")) + 
  labs(y = "Number of signals", tag = "a") + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "top", 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) -> p4
p4
```

```{r}
Nsigs_2 <- Sigs_Test[, .N, .(AA)]
Nsigs_2[, AA := factor(AA, levels = levels(Nsigs_1$AA))]
ggplot(Nsigs_2, aes(x = AA, y = N)) + 
  geom_col() + 
  geom_text(aes(label = N), position = position_nudge(y = 300)) + 
  labs(y = "Number of signals", tag = "a") + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "top", 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) 
```

```{r}
Nsigs_3 <- Sigs_Valid[, .N, .(AA)]
Nsigs_3[, AA := factor(AA, levels = levels(Nsigs_1$AA))]
ggplot(Nsigs_3, aes(x = AA, y = N)) + 
  geom_col() + 
  geom_text(aes(label = N), position = position_nudge(y = 30)) + 
  labs(y = "Number of signals", tag = "a") + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "top", 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) 
```

```{r }
ggplot(rbind(data.table(Dataset = "Testing", Nsigs_2), data.table(Dataset = "Validation", Nsigs_3)), aes(x = AA, y = N, fill = Dataset)) + 
  geom_col(position = position_dodge()) + 
  geom_text(aes(label = N, y = N + 800), position = position_dodge(width = 0.9), angle = 90) + 
  scale_y_continuous(limits = c(0, 10000)) + 
  labs(y = "Number of signals", tag = "b") + 
  theme_bw(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "top", 
        axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) -> p5
p5
```

# cutoff-list

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version3/L1/Modeling_Data.RData")
model1 <- readRDS("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version3/L1/RF_model.Rds")
Sigs_Train_Upsample <- Sigs_Train_Upsample[AA %in% model1$levels]
train_res <- data.table(ID = Sigs_Train_Upsample$ID, Obse = Sigs_Train_Upsample$AA, Pred = model1$finalModel$predicted, Prob = apply(model1$finalModel$votes, 1, max))
train_res[, Obse := factor(Obse, levels = train_res[, levels(Pred)])]
train_res[, mean(Obse == Pred)]

test_res <- data.table(ID = Sigs_Test$ID, Obse = Sigs_Test$AA, Pred = predict(model1, Sigs_Test_FM), Prob = apply(predict(model1, Sigs_Test_FM, type = "prob"), 1, max))
test_res <- test_res[Obse != "CMC"]
test_res[, Obse := factor(Obse, levels = test_res[, levels(Pred)])]
test_res[, mean(Obse == Pred)]

valid_res <- data.table(ID = Sigs_Valid$ID, Obse = Sigs_Valid$AA, Pred = predict(model1, Sigs_Valid_FM), Prob = apply(predict(model1, Sigs_Valid_FM, type = "prob"), 1, max))
valid_res <- valid_res[Obse != "CMC"]
valid_res[, Obse := factor(Obse, levels = valid_res[, levels(Pred)])]
valid_res[, mean(Obse == Pred)]

model1_res <- rbind(data.table(train_res, Dataset = "Training"), data.table(test_res, Dataset = "Testing"), data.table(valid_res, Dataset = "Validation"))
model1_res[, Dataset := factor(Dataset, levels = c("Training", "Testing", "Validation"))]
```

```{r}
cutoffList <- lapply(1:50/50, function(b) {
  merge(model1_res[, .(Recovery = mean(Prob >= b) * 100), by = Dataset], 
        model1_res[Prob >= b, .(Accuracy = mean(Obse == Pred) * 100), by = Dataset])
})
cutoffList <- data.table(Cutoff = rep(1:50/50, mapply(nrow, cutoffList)), do.call(rbind, cutoffList))
cutoffList[, L := paste0("(", round(Recovery, 1), ", ", round(Accuracy, 1), ")")]
cutoffList[, Dataset := factor(Dataset, levels = c("Training", "Testing", "Validation"))]
```

```{r fig.width=4, fig.height=4}
ggplot(cutoffList, aes(x = Recovery, y = Accuracy, colour = Dataset)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)", tag = "c") + 
  # geom_point(data = cutoffList[Cutoff %in% c(c(6)/10)]) +
  # geom_text_repel(data = cutoffList[Cutoff %in% c(c(6)/10)], aes(x = Recovery, y = Accuracy, label = L)) +
  scale_color_brewer(palette = "Set1", guide = guide_legend(reverse = T)) + 
  theme_bw(base_size = 15) + 
  theme(#legend.position = "top", 
        legend.position = c(.75, .25), 
        panel.grid = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold")) -> p6
p6
```

```{r}
pred_res <- rbind(data.table(train_res, Dataset = "Training"), data.table(test_res, Dataset = "Testing"), data.table(valid_res, Dataset = "Validation"))
pred_res[, Type := ifelse(Obse == Pred, "Correct", "Wrong")]
pred_res[, Dataset := factor(Dataset, levels = c("Training", "Testing", "Validation"))]
```

```{r}
ggplot(pred_res, aes(x = Prob, fill = Type)) + 
  geom_histogram(binwidth = 0.05) + 
  facet_wrap( ~ Dataset, scales = "free") +
  scale_fill_brewer(palette = "Dark2", guide = guide_legend(reverse = T)) + 
  labs(x = "Prediction probability", y = "Count", tag = "d") + 
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), strip.background = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold")) -> p7
p7
```


```{r fig.width=16, fig.height=8}
design <- "
  11111222222
  33344444444
"
p4 + p5 + p6 + p7 + 
  plot_layout(design = design)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig3/Fig3_S2.pdf", width = 16, height = 8)
```

