---
title: "LNFAE"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(Biostrings)
library(patchwork)
library(ggplot2)
```

```{r}
KnnSelecting <- function(signals, dists, dist_method = "euclidean", k = 20, noise = 0, index = NULL) {
  stopifnot(noise < k)
  if(is(dists, "dist")) {
    knn1 <- dbscan::kNN(dists, k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists, "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  } else {
    if(is(dists, "kNN")) {
      if(k > dists$k) stop("K too big")
      knn1 <- dists
      knn2 <- apply(knn1$id[, 1:k], 2, function(x) x %in% which(grepl("^Noise", rownames(knn1$id))))
    } else {
      knn1 <- dbscan::kNN(dists[[dist_method]], k = k)
      knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists[[dist_method]], "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
    }
  }
  
  tu <- row.names(knn1$id)[which(rowSums(knn2) <= noise)]
  # tu <- union(tu, knn2[which(rowSums(knn2) <= noise), 1])
  tu <- grep("^Noise", tu, invert = TRUE, value = TRUE)
  ggplot(signals, aes(x = Blockade, y = DwellTime, colour = !ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = c("#E41A1C", "#377EB8")) + 
    theme_classic() + 
    theme(legend.position = "none") -> p1
  ggplot(signals[ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#E41A1C") + 
    theme_classic() + 
    theme(legend.position = "none") + 
    labs(title = length(tu)) -> p2
  ggplot(signals[!ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#377EB8") + 
    theme_classic() + 
    theme(legend.position = "none") -> p3
  if(!is.null(index)) {
    p1 <- p1 + geom_vline(xintercept = index, colour = "red")
    p2 <- p2 + geom_vline(xintercept = index, colour = "red")
    p3 <- p3 + geom_vline(xintercept = index, colour = "red")
  }
  print(p1 + p2 + p3)
  return(tu)
}

RemoveOutlier <- function(tree, n = 10, Keep = 0.95) {
  h <- length(tree$height)
  g <- cutree(tree, h = tree$height[h])
  g <- data.table(tip = names(g), cluster = g)
  
  while (g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] > Keep) {
    h <- h - 1
    g <- cutree(tree, h = tree$height[h])
    g <- data.table(tip = names(g), cluster = g)
  }
  cat(paste0("Keep: ", round(g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] * 100, 2), "%"))
  g[cluster %in% g[, .N, cluster][N >= n, cluster], tip]
}
```

```{r}
meta <- fread("./data/ChenShanchuan/20231226/meta_20231226.txt")[amino_acid == "EAFNL"]
meta[, sig_file := paste0("./analysis/81.ABFProcessing/RawSignal/RawSignal_", file_name, ".txt")]
```

# base line distribution

```{r}
RawSig <- lapply(meta[, sig_file], fread)
RawSig <- data.table(file_id = rep(meta[, file_name], mapply(nrow, RawSig)), do.call(rbind, RawSig))
```

```{r fig.width=18, fig.height=8}
ggplot(RawSig[BaseMean > 110 & BaseMean < 130], aes(x = BaseMean)) + 
  geom_histogram(binwidth = .5) + 
  facet_wrap(~ file_id, scales = "free", nrow = 2)
```

```{r}
ggplot(RawSig[BaseMean > 119 & BaseMean < 123], aes(x = Blockade, y = DwellTime * 1000)) + 
  geom_point(size = 0.1) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  facet_wrap(~ file_id)
```

# Amino acid prediction

```{r}
B_file <- unique(meta[!is.na(amino_acid), file_name])
B_file <- paste0("./analysis/81.ABFProcessing/FeatureMatrix/FeatureMatrix_", B_file, ".txt")
B_file <- B_file[file.exists(B_file)]
Sig_FeatureMatrixs <- do.call(rbind, lapply(B_file, fread))
```

```{r}
model1 <- readRDS("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/SubAAs/ModelAEFLN/RFmodel.Rds")
```

```{r}
pred1 <- data.table(ID = Sig_FeatureMatrixs$ID, 
                    Pred1 = as.character(predict(model1, Sig_FeatureMatrixs)), 
                    Prob1 = apply(predict(model1, Sig_FeatureMatrixs, type = "prob"), 1, max), 
                    Delta1 = apply(predict(model1, Sig_FeatureMatrixs, type = "prob"), 1, function(x) - diff(head(sort(x, decreasing = T), 2))))
```

```{r}
EAFNL <- merge(RawSig, pred1, by = "ID")
EAFNL[, AA := plyr::mapvalues(Pred1, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
EAFNL[, AA := factor(AA, levels = c("E", "A", "F", "N", "L"))]
```


```{r fig.width=12, fig.height=4}
ggplot(EAFNL[Delta1 > 0.99], aes(x = Blockade, y = DwellTime * 1000, colour = Pred1)) + 
  geom_point(size = .2) + 
  scale_y_log10() + 
  scale_x_continuous(breaks = AABlockade[AA %in% AMINO_ACID_CODE[unlist(strsplit("LNFAE", ""))], Blockade], limits = c(0.1, 0.4), 
                     labels = AABlockade[AA %in% AMINO_ACID_CODE[unlist(strsplit("LNFAE", ""))], AA]) + 
  facet_wrap( ~ file_id, nrow = 1)
```


```{r fig.width=8, fig.height=4}
ggplot(EAFNL, aes(x = BaseMean)) + 
  geom_histogram(binwidth = .5) + 
  facet_wrap( ~ file_id, scales = "free", nrow = 1)
```

```{r fig.width=8, fig.height=4}
ggplot(EAFNL[Delta1 > 0.99], aes(x = BaseMean)) + 
  geom_histogram(binwidth = .5) + 
  facet_wrap( ~ file_id, scales = "free", nrow = 1)
```


```{r}
Pred_N <- EAFNL[Delta1 > 0.99, .N, .(Pred1, file_id)]
Pred_N[, A := plyr::mapvalues(Pred1, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
Pred_N[, A := factor(A, levels = c("E", "A", "F", "N", "L"))]
```

```{r}
ggplot(Pred_N, aes(x = A, y = N)) + 
  geom_col() + 
  facet_wrap(~ file_id)

ggplot(Pred_N, aes(x = A, y = N, fill = file_id)) + 
  geom_col()
```

```{r}
ggplot(EAFNL[file_id == "2023_12_26_0008" & Delta1 > 0.99], aes(StartTime, colour = AA)) + 
  stat_ecdf() + 
  # scale_y_log10() + 
  scale_colour_brewer(palette = "Dark2")
```

```{r}
ggplot(EAFNL[file_id == "2023_12_26_0009" & Delta1 > 0.99], aes(StartTime, colour = AA)) + 
  stat_ecdf() + 
  # scale_y_log10() + 
  scale_colour_brewer(palette = "Dark2")
```

