---
title: "Figure 3 c"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
library(caret)
library(multiROC)
library(pROC)
```

```{r}
cM <- openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig3C.xlsx", rowNames = T)
```

```{r}
m1 <- reshape2::melt(as.matrix(cM))
colnames(m1)[3] <- "Percentage"
ggplot(data = m1, aes(x = Var1, y = Var2, fill = Percentage)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") + 
  labs(x = "Prediction", y = "Reference") +
  theme_bw(base_size = 22) + 
  theme(plot.margin = unit(c(0.25, 0, 0, 0), "lines"), 
        legend.position = "bottom")  -> p2

ggplot(data.table(A = factor(rownames(cM), levels = rownames(cM)), Percentage = rowSums(cM)), aes(x = A, y = Percentage)) + 
  geom_col(fill = "#A50F15") + 
  labs(tag = "c") + 
  theme_bw(base_size = 22) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        axis.title.y = element_text(hjust = 0), 
        plot.tag = element_text(size = 30, face = "bold"),
        plot.margin = unit(c(0, 0, 0, 0), "lines")) -> p1
```

```{r fig.width=6, fig.height=8}
p1 / p2 + plot_layout(heights = c(2, 8))
ggsave("./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Figure/Fig3C.pdf", width = 6, height = 8)
```


```{r fig.width=6, fig.height=7}
p2 + labs(tag = "c") + 
  scale_fill_continuous(low = "#FFF5F0", high = "#67000D", breaks = c(0, 50, 100)) + 
  theme(legend.box.spacing = unit(0, "line"), 
        legend.position = "top", 
        plot.tag = element_text(face = "bold"))
ggsave("./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Figure/Fig3C.pdf", width = 6, height = 7)
```
