---
title: "Figure 6 E"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
a_cols <- aa_cols
names(a_cols) <- plyr::mapvalues(names(a_cols), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
polyp <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig6GH.xlsx"))
```

```{r}
AADensityPlot2 <- function(x, target, legend = F, adjust = 2) {
  x <- x[Pred %in% x[, .N, Pred][N > 20, Pred]]
  ggplot() +
    geom_density(data = x, aes(x = Blockade, y = after_stat(count / max(count)), fill = Pred, colour = Pred), adjust = adjust, alpha = 0.5) + 
    scale_fill_manual(breaks = names(aa_cols), values = aa_cols) + 
    scale_colour_manual(breaks = names(aa_cols), values = aa_cols) + 
    theme_bw(base_size = 22) + 
    theme(legend.title = element_blank(), legend.position = ifelse(legend, "right", "none")) + 
    labs(y = "Relative abundance", x = "blockade") -> p
  pd <- ggplot_build(p)
  tab <- as.data.table(pd$data[[1]])[, .SD[which.max(count), ], colour][order(count, decreasing = T), ][colour %in% aa_cols[target]]
  tab <- merge(tab, data.table(AA = names(aa_cols), colour = aa_cols), by = "colour")
  p + geom_text_repel(data = tab, aes(x = x, y = y * 1.2, label = plyr::mapvalues(AA, AMINO_ACID_CODE, names(AMINO_ACID_CODE)), colour = AA), size = 5, direction = "y", nudge_y = .05, min.segment.length = unit(100, "cm")) + 
    theme(plot.tag = element_text(size = 20, face = "bold"), panel.grid = element_blank())
}
p2 <- AADensityPlot2(x = polyp[PPT == "FHL" & Prob > 0.7], target = c("Phe", "His1", "His2", "Leu")) + 
  labs(y = "FHL", tag = "g") + 
  scale_x_continuous(limits = c(0.12, 0.27)) + 
  theme_classic(base_size = 22) + 
  theme(plot.tag = element_text(face = "bold"), 
        axis.line.x = element_blank(),
        axis.text = element_blank(), 
        axis.title.x = element_blank(),
        axis.ticks = element_blank(), 
        legend.position = "none")
p2
```


```{r}
p3 <- AADensityPlot2(x = polyp[PPT == "FYSL" & Prob > 0.7], target = AMINO_ACID_CODE[unlist(strsplit("FYSL", ""))]) + 
  labs(y = "FYSL") + 
  scale_x_continuous(limits = c(0.12, 0.27)) + 
  theme_classic(base_size = 22) + 
  theme(plot.tag = element_text(face = "bold", size = 20), 
        axis.line.x = element_blank(),
        axis.text = element_blank(), 
        axis.title.x = element_blank(),
        axis.ticks = element_blank(), 
        legend.position = "none")
p3
```

```{r}
p4 <- AADensityPlot2(x = polyp[PPT == "LEF" & Prob > 0.7], target = AMINO_ACID_CODE[unlist(strsplit("LEF", ""))]) + 
  labs(y = "LEF") + 
  scale_x_continuous(limits = c(0.12, 0.27)) + 
  theme_classic(base_size = 22) + 
  theme(plot.tag = element_text(face = "bold", size = 20), 
        # axis.line.y = element_blank(), 
        axis.text.y = element_blank(), 
        # axis.title.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        legend.position = "none")
p4
```


```{r}
p5 <- AADensityPlot2(x = polyp[PPT == "LVFFA" & Prob > 0.7], target = AMINO_ACID_CODE[unlist(strsplit("LVFFA", ""))]) + 
  labs(y = "LVFFA", tag = "h") + 
  scale_x_continuous(limits = c(0.1, 0.25)) + 
  theme_classic(base_size = 22) + 
  theme(plot.tag = element_text(face = "bold"), 
        axis.line.x = element_blank(),
        axis.text = element_blank(), 
        axis.title.x = element_blank(),
        axis.ticks = element_blank(), 
        legend.position = "none")
p5
```


```{r}
p6 <- AADensityPlot2(x = polyp[PPT == "LVFFAG" & Prob > 0.7], target = AMINO_ACID_CODE[unlist(strsplit("LVFFAG", ""))]) + 
  labs(y = "LVFFAG") + 
  scale_x_continuous(limits = c(0.1, 0.25)) + 
  theme_classic(base_size = 22) + 
  theme(plot.tag = element_text(face = "bold", size = 20), 
        axis.line.x = element_blank(),
        axis.text = element_blank(), 
        axis.title.x = element_blank(),
        axis.ticks = element_blank(), 
        legend.position = "none")
p6
```


```{r}
p7 <- AADensityPlot2(x = polyp[PPT == "LVFFAK" & Prob > 0.7], target = AMINO_ACID_CODE[unlist(strsplit("LVFFAK", ""))]) + 
  labs(y = "LVFFAK") + 
  scale_x_continuous(limits = c(0.1, 0.25)) + 
  theme_classic(base_size = 22) + 
  theme(plot.tag = element_text(face = "bold", size = 20), 
        # axis.line.y = element_blank(), 
        axis.text.y = element_blank(), 
        # axis.title.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        legend.position = "none")
p7
```


```{r fig.height=6, fig.width=9, echo=FALSE}
design <- "
  14
  25
  36
"
p2 + p3 + p4 + p5 + p6 + p7 + 
  plot_layout(design = design)
```



