---
title: "Figure 6 i"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
a_cols <- aa_cols
names(a_cols) <- plyr::mapvalues(names(a_cols), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
cmd_raw_result <- openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig6I.xlsx")
```

```{r fig.width=7, fig.height=6}
ggplot(cmd_raw_result, aes(x = Dim.1, Dim.2, colour = PPT)) + 
  ggforce::geom_mark_ellipse(expand = unit(0, "mm"), con.cap = 0, con.border = "none", con.type = "straight") + 
  ggforce::geom_mark_ellipse(aes(label = PPT, filter = !PPT %in% c("LVFFA", "LVFFAG", "LVFFAK")), expand = unit(0, "line"), 
                             label.colour = "grey", con.colour = "grey", con.cap = 0, con.border = "none", con.type = "straight") + 
  geom_point(size = 2) + 
  scale_colour_brewer(palette = "Paired", guide = guide_legend(nrow = 3)) + 
  labs(tag = "i") + 
  theme_base(base_size = 22) + 
  theme(plot.background = element_blank(), 
        legend.position = "top",
        plot.tag = element_text(face = "bold"), 
        legend.title = element_blank())
```