---
title: "Thr"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
  code_folding: "hide"
toc: true
toc_depth: 4
toc_float: 
  collapsed: false
number_sections: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = F, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
```

```{r}
source("/mnt/raid61/Personal_data/tangchao/AANanopore/script/01.AASignalRecognition/Version6/SignalProcessing/AdditionalFunctions.R")
```

```{r eval=FALSE}
sort(unique(openxlsx::read.xlsx("/mnt/raid61/Personal_data/tangchao/AANanopore/data/meta_info_and_base_line_20210525additional.xlsx")[[3]]))
```

```{r}
AA <- "Thr"
```

```{r}
meta <- data.table(openxlsx::read.xlsx("/mnt/raid61/Personal_data/tangchao/AANanopore/data/meta_info_and_base_line_20210525additional.xlsx"))[, 1:9]

Ptabf <- file.path("/mnt/raid61/Personal_data/tangchao/AANanopore/data/ZhangMing_20210402")
OutDir <- file.path("/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/01.AASignalRecognition/Version8", AA)

if(!dir.exists(OutDir)) dir.create(OutDir)
# file.remove(list.files(OutDir, full.names = T))

meta <- meta[amino_acid == AA, ]
meta <- na.omit(meta)
DT::datatable(meta)
```

```{r}
meta[, file_name := as.character(file_name)]
L1Min <- unique(meta[, L1min])
L1Max <- unique(meta[, L1max])
```

# BUB signal finding

```{r}
BUBs <- mclapply(seq_len(nrow(meta)), function(i) {
  File <- meta[,file_name][i]
  StartTime <- meta[,start_time][i]
  EndTime <- meta[,end_time][i]
  
  phe <- readABF::readABF(list.files(path = Ptabf, pattern = as.character(File), full.names = T))
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 0, ]
  phe <- phe[pA < 130, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  DenSm <- density(phe[, Sm], adjust = 1)
  
  L0 <- L0Coor(DenSm)
  L0Min <- min(L0) * 0.9
  
  pdf(paste0(file.path(OutDir, File), "_L0_Coordinate.pdf"))
  plot(DenSm, xlab = "Current (pA)", main = "density of smooth current", xlim = c(90, 130))
  abline(v = L0, lty = 2, col = 2)
  dev.off()
  
  # if(ConfusedL0(DenSm) < 0.2) {
  #   return(NULL)
  # }
  
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  return(BUB)
}, mc.cores = nrow(meta))
```

```{r}
names(BUBs) <- meta[, file_name]
saveRDS(BUBs, file = file.path(OutDir, "BUB.Rds"))
```
