---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(changepoint)
library(data.table)
library(Biostrings)
library(parallel)
library(IRanges)
library(ggplot2)
library(plotly)
library(ggpubr)
library(caret)
library(shiny)
```

```{r}
MainRidge <- function(x, bw = 0.005, n = 1024, plot = F, ...) {
  bw <- bw * max(abs(x))
  den <- density(x, bw = bw, n = n, ...)
  MainPeak <- with(den, x[which.max(y)])
  uR <- IRanges(diff(den$y) >= 0)
  dR <- IRanges(diff(den$y) <= 0)
  while (length(uR) != length(dR)) {
    bw <- bw * 1.05
    den <- density(x, bw = bw, n = n, ...)
    MainPeak <- with(den, x[which.max(y)])
    uR <- IRanges(diff(den$y) >= 0)
    dR <- IRanges(diff(den$y) <= 0)
  }
  res <- do.call(c, lapply(seq_along(uR), function(i) {
    reduce(c(uR[i], dR[i]))
  }))
  res <- res[subjectHits(findOverlaps(IRanges(which.max(den$y), which.max(den$y)), res))]
  MainRidgeRatio <- mean(x > den$x[start(res)] & x < den$x[end(res)])
  while (MainRidgeRatio < 0.1) {
    bw <- bw * 1.05
    den <- density(x, bw = bw, n = n, ...)
    MainPeak <- with(den, x[which.max(y)])
    uR <- IRanges(diff(den$y) >= 0)
    dR <- IRanges(diff(den$y) <= 0)
    while (length(uR) != length(dR)) {
      bw <- bw * 1.05
      den <- density(x, bw = bw, n = n, ...)
      MainPeak <- with(den, x[which.max(y)])
      uR <- IRanges(diff(den$y) >= 0)
      dR <- IRanges(diff(den$y) <= 0)
    }
    res <- do.call(c, lapply(seq_along(uR), function(i) {
      reduce(c(uR[i], dR[i]))
    }))
    res <- res[subjectHits(findOverlaps(IRanges(which.max(den$y), which.max(den$y)), res))]
    MainRidgeRatio <- mean(x > den$x[start(res)] & x < den$x[end(res)])
  }
  MainRidgeWidth <- den$x[end(res)] - den$x[start(res)]
  if(plot) {
    plot(den)
    abline(v = with(den, x[c(start(res), end(res))]))
    abline(v = MainPeak, col = 2)
  }
  data.table(MainPeak, MainRidgeWidth, MainRidgeRatio)
}

KBins2 <- function(sig, minseglen1 = 100, minseglen2 = 10, pen.value = 1e-3) {
  ansmean1 <- suppressWarnings(changepoint::cpt.mean(sig, penalty = "MBIC", method = "PELT", minseglen = minseglen1))
  Tab1 <- data.table::data.table(P = sig, B1 = rep(seq_len(changepoint::nseg(ansmean1)), changepoint::seg.len(ansmean1)))
  Tab2 <- Tab1[, .(P = median(P)), by = "B1"]
  
  ansmean2 <- suppressWarnings(changepoint::cpt.meanvar(Tab2[, P], penalty = "Asymptotic", pen.value = pen.value, method = "PELT", minseglen = minseglen2))
  Tab2[, B := rep(seq_len(changepoint::nseg(ansmean2)), changepoint::seg.len(ansmean2))]
  res <- merge(Tab1, Tab2[, .(B1, B)], by = "B1")
  res[, B1 := NULL]
  res[, .(P = median(P), N = .N), "B"][, rep(P, N)]
}

mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x > min(q) & x < max(q)])
}

WhiskerRange <- function(x) {
  iqr <- 1.5 * IQR(x, na.rm = TRUE)
  c(min(x[x >= quantile(x, 1/4, na.rm = T) - iqr], na.rm = TRUE), max(x[x <= quantile(x, 3/4, na.rm = T) + iqr], na.rm = TRUE))
}

GetSignal <- function(x, minblockade = 0.1) {
  abf2 <- x[rep(runLength(Rle(x$Sm)) >= 20, runLength(Rle(x$Sm)))]
  gr <- IRanges(end = cumsum(runLength(Rle(abf2[, Sm]))), width = runLength(Rle(abf2[, Sm])))
  Sm <- runValue(Rle(abf2[, Sm]))
  S0 <- list()
  i <- 1
  while (i < length(Sm)) {
    if(Sm[i + 1] < Sm[i] * (1 - minblockade)) {
      l0 <- which(Sm > Sm[i] * (1 - minblockade))
      l0 <- l0[l0 > i]
      if(length(l0) != 0) {
        Ei <- min(l0)
        S0 <- append(S0, list(c(end(gr[i]), start(gr[Ei]))))
        i <- Ei
      } else {
        i <- i + 1
      }
    } else {
      i <- i + 1
    }
  }
  
  Sigs <- lapply(S0, function(x) {
    L <- gr[end(gr) == x[1]]
    R <- gr[start(gr) == x[2]]
    gri <- gr[queryHits(findOverlaps(gr, IRanges(x[1], x[2]), type = "within"))]
    Main_ridge <- MainRidge(x = abf2[(x[1] + 1):(x[2] - 1), pA], bw = 0.005)
    SignalCurrent <- Main_ridge$MainPeak
    StageSD = abf2[(x[1] + 1):(x[2] - 1), sd(pA), Sm][, mean(V1)]
    SignalCurrentPercent <- Main_ridge$MainRidgeRatio * 100
    SignalCurrentWidth <- Main_ridge$MainRidgeWidth
    data.table(StartTime = abf2[x[1], Time], EndTime = abf2[x[2], Time], 
               LeftLength = width(L), RightLength = width(R), 
               BaseMean = mean2(c(abf2[start(L):end(L), pA], abf2[start(R):end(R), pA])),
               DeltaMean = abs(mean2(abf2[start(L):end(L), pA]) - mean2(abf2[start(R):end(R), pA])),
               StageSD = StageSD, 
               CurrentSD = abf2[(x[1] + 1):(x[2] - 1), sd(pA)], 
               Segments = sum(prop.table(width(gri)) > 0.1), 
               Valid = all(abf2[start(L):end(R), Valid]), 
               SignalCurrent = SignalCurrent, 
               SignalCurrentPercent = SignalCurrentPercent, 
               SignalCurrentWidth = SignalCurrentWidth)
  })
  Sigs <- do.call(rbind, Sigs)
  return(Sigs)
}

SignalCurrent <- function(x, abf) {
  target <- abf[, inrange(Time, x$StartTime, x$EndTime, incbounds = FALSE)]
  target <- IRanges(target)
  target <- as.data.table(target)
  target$ID <- seq_len(nrow(target))
  target <- target[, .(Loci = list(start:end)), ID]
  target <- target[, Loci]
  names(target) <- x$ID
  abf2 <- abf[do.call(c, target)]
  abf2$ID <- rep(names(target), mapply(length, target))
  abf2$BaseMean <- rep(x[, BaseMean], mapply(length, target))
  abf2[, Current := pA / BaseMean]
  abf2[, .(ID, Current)]
}
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/Voltage/不同电压.xlsx"))
colnames(meta) <- c("file_name", "amino_acid", "voltage", "concentration", "start_time", "end_time")
meta <- meta[, .SD[, .(.SD, SubFile = seq_len(.N))], file_name]
colnames(meta) <- gsub(".SD.", "", colnames(meta))
meta[, SubFile := paste0(file_name, "_", SubFile)]
meta[is.na(concentration), concentration := 0]
meta[, amino_acid := gsub("Arg\\(R\\)", "Arg", amino_acid)]
meta[, amino_acid := gsub("Lys\\(K\\)", "Lys", amino_acid)]
setkey(meta, file_name)
meta[SubFile == "21201011_1", amino_acid := "Asp"]
meta[SubFile == "21205019_1", amino_acid := "Arg"]
meta[SubFile == "21203011_1", amino_acid := "Glu"]
meta[SubFile == "21207008_1", amino_acid := "Lys"]
meta[SubFile == "21307001_1", amino_acid := "Trp"]
meta[SubFile == "21319005_1", amino_acid := "Thr"]
# meta[amino_acid == "Lys" & voltage == 50 & concentration != 0, file_name := "21207004"]
# meta[amino_acid == "Lys" & voltage == 50 & concentration != 0, SubFile := "21207004_1"]
# meta[amino_acid == "Lys" & voltage == 50 & concentration != 0, concentration := "100"]
# meta[amino_acid == "Lys" & voltage == 50 & concentration != 0, start_time := "7"]
# meta[amino_acid == "Lys" & voltage == 50 & concentration != 0, end_time := "16"]
meta <- rbind(meta, data.table(file_name = "21207004", amino_acid = "Lys", voltage = 50, concentration = 100, start_time = 7, end_time = 16, SubFile = "21207004_1"))
meta <- rbind(meta, data.table(file_name = "21320003", amino_acid = "Thr", voltage = 50, concentration = 100, start_time = 11, end_time = 18, SubFile = "21320003_1"))
meta <- rbind(meta, data.table(file_name = "21321013", amino_acid = "Leu", voltage = c(50, 75, 100, 100, 100), concentration = 100, 
                               start_time = c(0, 11.2, 14.3, 15.4, 18.4), end_time = c(6.5, 14.2, 14.9, 16.8, 19.2), 
                               SubFile = paste0("21320003_", 1:5)))

meta$abf_file <- mapply(function(x) list.files("./data", x, full.names = T, recursive = T)[1], meta$file_name)
```

```{r}
lapply(seq_len(nrow(meta)), function(i) {
  print(i)
  File <- file.path(meta[i, abf_file])
  StartTime <- as.numeric(meta[i, start_time])
  EndTime <- as.numeric(meta[i, end_time])
  V <- as.numeric(meta[i, voltage])

  abf <- tryCatch(readABF::readABF(File), error = function(e) NULL)
  abf <- as.data.table(as.data.frame(abf))
  colnames(abf) <- c("Time", "pA", "mV")[seq_len(ncol(abf))]
  abf <- abf[Time > StartTime * 60 & Time < EndTime * 60, ]
  abf[, Valid := round(mV) == V]
  abf$Sm <- KBins2(sig = abf$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  saveRDS(abf, paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", meta[i, SubFile], ".Rds"))
  
  # Raw Signal
  Sigs <- GetSignal(x = abf, minblockade = 0.1)
  Sigs[, DwellTime := EndTime - StartTime]
  Sigs <- Sigs[Valid == TRUE]
  if(nrow(Sigs) == 0) return(NULL)
  Sigs[, Blockade := 1 - SignalCurrent / BaseMean]
  
  Sigs <- data.table(ID = paste(meta[i, SubFile], Sigs[, seq_len(.N)], sep = "_"), Sigs)
  fwrite(Sigs, file = paste0("./analysis/21.ABFProcessing/04.Voltage/RawSignal/RawSignal_", meta[i, SubFile], ".txt"), sep = "\t", row.names = F, quote = F)

  # Signal Current
  Current <- SignalCurrent(Sigs, abf = abf)
  saveRDS(Current, file = paste0("./analysis/21.ABFProcessing/04.Voltage/SignalCurrent/SignalCurrent_", meta[i, SubFile], ".Rds"))
  
  # Feature matrix
  Mat <- lapply(Sigs[, ID], function(j) {
    D <- density(Current[ID == j, Current], from = 0, to = 1, n = 1000, bw = 0.005)$y
    pA <- sort(Current[ID == j, Current])
    pA <- pA[round(seq(1, length(pA), length.out = 100))]
    c(D, pA)
  })
  Mat <- as.data.table(do.call(rbind, Mat))
  colnames(Mat) <- c(paste0("X", sprintf("%04d", seq_len(1000))), paste0("P", sprintf("%03d", 1:100)))
  Mat <- data.table(ID = Sigs[, ID], Mat)
  Mat <- merge(Mat, Sigs, by = "ID")
  setkey(Mat, ID)
  Mat <- Mat[Sigs$ID, ]
  fwrite(Mat, paste0("./analysis/21.ABFProcessing/04.Voltage/FeatureMatrix/FeatureMatrix_", meta[i, SubFile], ".txt"), sep = "\t", quote = F)
})
```


