---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(Biostrings)
library(IRanges)
library(ggplot2)
library(parallel)
library(ggpubr)
library(patchwork)
library(changepoint)
library(ggExtra)
library(tidyr)

# SignalFiltering <- function(x) {
#   x <- x[DeltaMean < 1 & Valid == TRUE]
#   # x <- x[DwellTime >= with(density(x[, DwellTime], n = 10000, adjust = 1), x[which.max(y)])]
#   x <- x[DwellTime > 0.001]
#   x <- x[StageSD < 3]
#   x <- x[LeftLength >= 50 & RightLength >= 50]
#   x <- x[BaseMean > min(WhiskerRange(x[, BaseMean])) & BaseMean < max(WhiskerRange(x[, BaseMean]))]
#   rk <- rank(x[, DwellTime]) + rank(x[, -1 * StageSD])
#   x[rk > quantile(rk, 0.1)]
# }

# SignalFiltering <- function(x) {
#   x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50 & SignalCurrentPercent == 100]
#   x[!(DwellTime < mean(DwellTime) & StageSD > mean(StageSD))]
# }

SignalFiltering <- function(x) {
  x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
  x[!(DwellTime < 0.003 & StageSD > 2)]
}

SignalCurrent <- function(x, abf, cores = 10) {
  Sigs_Multiple_Current <- mclapply(seq_len(nrow(x)), FUN = function(i) {
    data.table(ID = x[i, ID], Current = abf[Time > x[i, StartTime] & Time < x[i, EndTime], pA] / x[i, BaseMean])
  }, mc.cores = cores)
  do.call(rbind, Sigs_Multiple_Current)
}
```

```{r}
setwd("/mnt/raid61/Personal_data/tangchao/AANanopore")
library(data.table)
library(ggplot2)
library(Biostrings)

meta1 <- data.table(openxlsx::read.xlsx("./data/meta_info_and_base_line_20210525.xlsx"))
meta2 <- data.table(openxlsx::read.xlsx("./data/meta_info_and_base_line_20210525additional.xlsx"))
meta <- rbind(meta1, meta2)
meta[amino_acid == "cys", amino_acid := "Cys"]

meta <- meta[file_name != 21703001]
```

# Asn

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Asn"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Asp

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Asp"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Gln

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Gln"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Glu

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Glu"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Ile

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Ile"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Leu

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Leu"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Lys

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Lys"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Met

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Met"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Phe

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Phe"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Thr

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Thr"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Trp

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Trp"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Tyr

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Tyr"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Val

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Val"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Ser

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Ser"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Ala

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Ala"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Gly

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Gly"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Arg

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Arg"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# His

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "His"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Pro

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Pro"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


# Cys

```{r}
meta[, unique(amino_acid)]
```

```{r}
a <- "Cys"

Sig0 <- lapply(meta[amino_acid == a, file_name], function(x) {
  x <- data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Dec26/RawSignal_", x, "_V2.txt")))
  x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
})
Sig1 <- lapply(Sig0, SignalFiltering)
Sig1 <- do.call(rbind, Sig1)
Sig0 <- do.call(rbind, Sig0)
```

```{r fig.width=12, fig.height=6}
ggplot(Sig0, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw") + 

ggplot(Sig0[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Raw State1")
```

```{r fig.width=12, fig.height=6}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered") + 

ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  scale_y_log10() + 
  facet_wrap(~file_name, ncol = 1, strip.position = "right", scales = "free_y") + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none")  + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = "Filtered State1")
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N])) -> p2

cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```

```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[, .N])) -> p1
ggplot(Sig1[SignalCurrentPercent == 100], aes(x = 1 - SignalCurrent / BaseMean, y = StageSD, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Current sd", subtitle = paste0(a, ": ", Sig1[SignalCurrentPercent == 100, .N]))  -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


```{r fig.height=4, fig.width=12}
ggplot(Sig1, aes(x = 1 - SignalCurrent / BaseMean, y = DwellTime * 1000, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(x = "Blockade", y = "Dwell time (ms)", title = paste0(a, ": ", Sig1[, .N])) -> p1

ggplot(Sig1, aes(y = BaseMean, x = 1 - SignalCurrent / BaseMean, colour = file_name)) + 
  geom_point(size = .1) + 
  lims(x = c(.1, .3)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  theme(legend.position = "none") + 
  labs(y = "Baseline current (pA)", x = "Blockade", title = paste0(a, ": ", Sig1[, .N])) -> p2
cowplot::plot_grid(ggMarginal(p1), ggMarginal(p2))
```


