---
title: "Figure 2a"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(patchwork)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r fig.width=3.5, fig.height=3.5}
cutoffList <- readRDS(file = "analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Cutoff_Recovery_Accuracy_Test.Rds")
```

```{r fig.width=3.5, fig.height=4}
ggplot(cutoffList[Dataset %in% c("Validation")], aes(x = Recovery * 100, y = Accuracy * 100, colour = Model)) + 
  geom_line() + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)", title = "Validation set") + 
  geom_point(data = cutoffList[Dataset %in% c("Validation") & Cutoff %in% c(c(7)/10)]) +
  geom_text(data = cutoffList[Dataset %in% c("Validation") & Cutoff %in% c(c(7)/10)], aes(x = 25, y = seq(73, 88, 3), label = L)) + 
  scale_color_brewer(palette = "Dark2") + 
  lims(y = c(70, 100)) + 
  guides(colour = "none") + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "top", panel.grid = element_blank())
ggsave("/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/00.FigureTables/Sep24/Figure3/Fig3b.eps", width = 3.5, height = 4)
```


```{r}
Preds <- readRDS(file = "analysis/03.MachineLearning/Version8/02.Modeling/01.RF/02.CompareModels/Preds.Rds")
```

```{r}
cM <- Preds[[4]][Dataset == "ValidationUp" & Prob > 0, confusionMatrix(pred, true)]
cM <- as.matrix(cM$table)
cM <- reshape2::dcast(as.data.frame(cM), Prediction ~ Reference)
cM <- data.frame(cM[, -1], row.names = cM[, 1])
cM <- apply(cM, 2, prop.table)*100
row.names(cM) <- plyr::mapvalues(row.names(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
colnames(cM) <- plyr::mapvalues(colnames(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
m1 <- reshape2::melt(as.matrix(cM))
colnames(m1)[3] <- "Percentage"
ggplot(data = m1, aes(x = Var1, y = Var2, fill = Percentage)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") + 
  labs(x = "Prediction", y = "Reference") +
  theme_bw(base_size = 15) + 
  theme(plot.margin = unit(c(0.25, 0, 0, 0), "lines"))  -> p1

ggplot(data.table(A = factor(rownames(cM), levels = rownames(cM)), Percentage = rowSums(cM)), aes(x = A, y = Percentage)) +
  geom_col(fill = "#A50F15") +
  theme_bw(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "lines")) -> p2
```

```{r fig.width=5, fig.height=4}
p2 / p1 + plot_layout(heights = c(2, 8))
ggsave("/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/00.FigureTables/Sep24/Figure3/Fig3d.eps", width = 5, height = 4)
```

```{r}
Preds <- readRDS(file = "analysis/03.MachineLearning/Version9/02.Modeling/01.RF/02.CompareModels/Preds.Rds")
```

```{r}
cM <- Preds[[4]][Dataset == "ValidationUp" & Prob > 0, confusionMatrix(pred, true)]
cM <- as.matrix(cM$table)
cM <- reshape2::dcast(as.data.frame(cM), Prediction ~ Reference)
cM <- data.frame(cM[, -1], row.names = cM[, 1])
cM <- apply(cM, 2, prop.table)*100
row.names(cM) <- plyr::mapvalues(row.names(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
colnames(cM) <- plyr::mapvalues(colnames(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
m1 <- reshape2::melt(as.matrix(cM))
colnames(m1)[3] <- "Percentage"
ggplot(data = m1, aes(x = Var1, y = Var2, fill = Percentage)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") + 
  labs(x = "Prediction", y = "Reference") +
  theme_bw(base_size = 15) + 
  theme(plot.margin = unit(c(0.25, 0, 0, 0), "lines"))  -> p1

ggplot(data.table(A = factor(rownames(cM), levels = rownames(cM)), Percentage = rowSums(cM)), aes(x = A, y = Percentage)) +
  geom_col(fill = "#A50F15") +
  theme_bw(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "lines")) -> p2
```

```{r fig.width=5, fig.height=4}
p2 / p1 + plot_layout(heights = c(2, 8))
ggsave("/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/00.FigureTables/Sep24/Figure3/Fig3d_20.eps", width = 5, height = 4)
```






