---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(parallel)
library(caret)
library(openxlsx)
library(cowplot)
library(ggseqlogo)
library(pheatmap)
```

# 20211025

```{r}
source("./script/02.PolypeptideSequencing/AdditionalFunctions.R")
```

```{r}
Signalsfiles <- list.files("./analysis/02.PolypeptideSequencing/20211025/Version2_2", ".Rds", full.names = TRUE)
```

```{r}
Ds <- lapply(Signalsfiles, function(i) {
  BUBs <- readRDS(i)
  BUBs <- mclapply(BUBs, function(x) {
    basemean <- x[L == "B", mean2(pA)]
    x[, pA := pA / basemean]
    x[, Sm := NULL]
    x[L == "U"]
  }, mc.cores = 10)
  BUBs <- do.call(rbind, BUBs)
  density(BUBs[, 1- pA], n = 128, adjust = 0.2, from = 0.1, to = 0.3)
})
names(Ds) <- gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))
```

```{r}
Tab <- lapply(Ds, function(i) {
  data.table(x = i$x, y = i$y)
})
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20211025/实验信息表1025.xlsx"))
meta <- meta[!grepl("lank", amino_acid)]
gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))[!gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))) %in% meta$file_name]

meta <- unique(meta[, .(file_name, amino_acid)])
meta <- meta[file_name %in% gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))]
meta$amino_acid <- mapply(function(x) tail(x, 1), strsplit(mapply(function(x) tail(x, 1), strsplit(meta$amino_acid, ", ")), ") "))
```

```{r}
Mat <- data.table(file_name = rep(gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))), mapply(nrow, Tab)), do.call(rbind, Tab))
Mat <- merge(Mat, meta, by = "file_name")
```

```{r fig.width=12, fig.height=3}
ggplot(Mat, aes(x = x, y = y, lty = file_name, colour = amino_acid)) + 
  geom_line() + 
  scale_linetype_manual(values = rep(1, 21), guide = "none") + 
  facet_wrap( ~ amino_acid, scales = "free") +
  theme_classic2()
```


```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "APRLRFYSL"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```
```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "DRVYIHPFHL"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "RPVKVYPNGAEDESAEAFPLEF"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r}
garbage <- c("21o22010", "21o23001", "21o22008", "21o22007")
```

```{r}
saveRDS(Mat, "analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_L1_20211025.Rds")
```


# 20220314

```{r}
Signalsfiles <- list.files("./analysis/02.PolypeptideSequencing/20220314/Version1", ".Rds", full.names = TRUE)
```

```{r}
Ds <- lapply(Signalsfiles, function(i) {
  BUBs <- readRDS(i)
  BUBs <- mclapply(BUBs, function(x) {
    basemean <- x[L == "B", mean2(pA)]
    x[, pA := pA / basemean]
    x[, Sm := NULL]
    x[L == "U"]
  }, mc.cores = 10)
  BUBs <- do.call(rbind, BUBs)
  density(BUBs[, 1- pA], n = 128, adjust = 0.2, from = 0.1, to = 0.3)
})
names(Ds) <- gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))
```

```{r}
plot(Ds[[5]])
```

```{r}
Tab <- lapply(Ds, function(i) {
  data.table(x = i$x, y = i$y)
})
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220314/neoantigen水解20220314.xlsx"))
meta <- meta[!grepl("lank", amino_acid)]
gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))[!gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))) %in% meta$file_name]

meta <- unique(meta[, .(file_name, amino_acid)])
meta <- meta[file_name %in% gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))]
meta$amino_acid <- mapply(function(x) x[2], strsplit(meta$amino_acid, ','))
```

```{r}
Mat <- data.table(file_name = rep(gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))), mapply(nrow, Tab)), do.call(rbind, Tab))
Mat <- merge(Mat, meta, by = "file_name")
```

```{r fig.width=10, fig.height=4}
ggplot(Mat, aes(x = x, y = y, lty = file_name, colour = amino_acid)) + 
  geom_line() + 
  scale_linetype_manual(values = rep(1, 17), guide = "none") + 
  facet_wrap( ~ amino_acid, scales = "free") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LFGV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LSGV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "VGAL"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "VGALD"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r}
saveRDS(Mat, "analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_L1_20220314.Rds")
```


# 20220406

```{r}
Signalsfiles <- list.files("./analysis/02.PolypeptideSequencing/20220406/Version1", ".Rds", full.names = TRUE)
```

```{r}
Ds <- lapply(Signalsfiles, function(i) {
  BUBs <- readRDS(i)
  BUBs <- mclapply(BUBs, function(x) {
    basemean <- x[L == "B", mean2(pA)]
    x[, pA := pA / basemean]
    x[, Sm := NULL]
    x[L == "U"]
  }, mc.cores = 10)
  BUBs <- do.call(rbind, BUBs)
  density(BUBs[, 1- pA], n = 128, adjust = 0.2, from = 0.1, to = 0.3)
})
names(Ds) <- gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))
```

```{r}
plot(Ds[[5]])
```

```{r}
Tab <- lapply(Ds, function(i) {
  data.table(x = i$x, y = i$y)
})
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20220406/neoantigen水解20220406.xlsx"))
meta <- meta[!grepl("lank", amino_acid)]
gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))[!gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))) %in% meta$file_name]
meta[15, file_name := "Username_2022-03-16_009_2"]
gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))[!gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))) %in% meta$file_name]

meta <- unique(meta[, .(file_name, amino_acid)])
meta <- meta[file_name %in% gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles)))]
meta <- meta[amino_acid != "LFGV-EF-53 mV"]
```

```{r}
Mat <- data.table(file_name = rep(gsub("BUB", "", gsub(".Rds", "", basename(Signalsfiles))), mapply(nrow, Tab)), do.call(rbind, Tab))
Mat <- merge(Mat, meta, by = "file_name")
```

```{r fig.width=10, fig.height=4}
ggplot(Mat, aes(x = x, y = y, lty = file_name, colour = amino_acid)) + 
  geom_line() + 
  scale_linetype_manual(values = rep(1, 17), guide = "none") + 
  facet_wrap( ~ amino_acid, scales = "free") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "FEV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LFGV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LFGV-53 mV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LFGV-EF"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LFGV-EF-50 mV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "LSGV "], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r fig.width=5, fig.height=3}
ggplot(Mat[amino_acid == "SLFEV"], aes(x = x, y = y, colour = file_name)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Set1") +
  theme_classic2()
```

```{r}
saveRDS(Mat, "analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_L1_20220406.Rds")
```





```{r}
D1025 <- readRDS("analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_L1_20211025.Rds")
D0314 <- readRDS("analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_L1_20220314.Rds")
D0406 <- readRDS("analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_L1_20220406.Rds")
```


```{r}
DL <- rbind(D1025, D0314, D0406)
# DL <- DL[!file_name %in% c("21o22010", "21o23001", "21o22008", "21o22007", "Username_2022-03-14_005", "Username_2022-03-14_006", "Username_2022-03-14_007","Username_2022-03-11_003", "22401011")]
# DL <- DL[!amino_acid %in% c("SLFEV", "FEV")]
```


```{r fig.width=10, fig.height=10}
ggplot(DL, aes(x = x, y = y, lty = file_name, colour = amino_acid)) + 
  geom_line() + 
  scale_linetype_manual(values = rep(1, 47), guide = "none") + 
  facet_wrap( ~ amino_acid, scales = "free_y", ncol = 2) + 
  theme_pubclean(base_size = 15) + 
  guides(colour = "none") + 
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        axis.title = element_blank())
```



```{r}
DL[, yi := as.numeric(as.factor(file_name))]
Tab <- dcast(DL, x ~ yi, value.var = "y")
Tab <- data.frame(Tab[, -1], row.names = Tab[[1]])
```

```{r}
library(factoextra)
library(FactoMineR)
library(ggthemes)

res.pca <- PCA(t(Tab), ncp = 10, graph = F)
pca_raw_result <- as.data.table(res.pca$ind$coord, keep.rownames = "yi")
pca_raw_result <- merge(pca_raw_result, unique(DL[, .(yi = paste0("X", yi), amino_acid, file_name)]))
```

```{r fig.width=15, fig.height=12}
library(ggrepel)
ggplot(pca_raw_result, aes(x = Dim.1, y = Dim.2, colour = amino_acid)) + 
  geom_point() + 
  geom_text_repel(aes(label = amino_acid)) + 
  xlab(paste("PC1 (",round(res.pca$eig[,2][1],2),"%)",sep = "")) +
  ylab(paste("PC2 (",round(res.pca$eig[,2][2],2),"%)",sep = "")) + 
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank())
```


```{r fig.width=10, fig.height=10}
CT <- cor(Tab, method = "pearson")
colnames(CT) <- plyr::mapvalues(colnames(CT), pca_raw_result$yi, paste0(pca_raw_result$amino_acid, "|", pca_raw_result$file_name))
rownames(CT) <- plyr::mapvalues(rownames(CT), pca_raw_result$yi, pca_raw_result$amino_acid)
pheatmap(CT)
```

```{r fig.width=10, fig.height=10}
CT <- cor(Tab, method = "spearman")
colnames(CT) <- plyr::mapvalues(colnames(CT), pca_raw_result$yi, paste0(pca_raw_result$amino_acid, "|", pca_raw_result$file_name))
rownames(CT) <- plyr::mapvalues(rownames(CT), pca_raw_result$yi, pca_raw_result$amino_acid)
pheatmap(CT)
```

















```{r}
D1025 <- readRDS("analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_20211025.Rds")
D0314 <- readRDS("analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_20220314.Rds")
D0406 <- readRDS("analysis/02.PolypeptideSequencing/Version1/01.Similarity/Signal_density_20220406.Rds")
```


```{r}
DL <- rbind(D1025, D0314, D0406)
# DL <- DL[!file_name %in% c("21o22010", "21o23001", "21o22008", "21o22007", "Username_2022-03-14_005", "Username_2022-03-14_006", "Username_2022-03-14_007","Username_2022-03-11_003", "22401011")]
# DL <- DL[!amino_acid %in% c("SLFEV", "FEV")]
```


```{r fig.width=10, fig.height=10}
ggplot(DL, aes(x = x, y = y, lty = file_name, colour = amino_acid)) + 
  geom_line() + 
  scale_linetype_manual(values = rep(1, 47), guide = "none") + 
  facet_wrap( ~ amino_acid, scales = "free_y", ncol = 2) + 
  theme_pubclean(base_size = 15) + 
  guides(colour = "none") + 
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        axis.title = element_blank())
```



```{r}
DL[, yi := as.numeric(as.factor(file_name))]
Tab <- dcast(DL, x ~ yi, value.var = "y")
Tab <- data.frame(Tab[, -1], row.names = Tab[[1]])
```

```{r}
res.pca <- PCA(t(Tab), ncp = 10, graph = F)
pca_raw_result <- as.data.table(res.pca$ind$coord, keep.rownames = "yi")
pca_raw_result <- merge(pca_raw_result, unique(DL[, .(yi = paste0("X", yi), amino_acid, file_name)]))
```

```{r fig.width=12, fig.height=10}
ggplot(pca_raw_result, aes(x = Dim.1, y = Dim.2, colour = amino_acid)) + 
  geom_point() + 
  geom_text_repel(aes(label = amino_acid)) + 
  xlab(paste("PC1 (",round(res.pca$eig[,2][1],2),"%)",sep = "")) +
  ylab(paste("PC2 (",round(res.pca$eig[,2][2],2),"%)",sep = "")) + 
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank())
```


```{r fig.width=10, fig.height=10}
CT <- cor(Tab, method = "pearson")
colnames(CT) <- plyr::mapvalues(colnames(CT), pca_raw_result$yi, paste0(pca_raw_result$amino_acid, "|", pca_raw_result$file_name))
rownames(CT) <- plyr::mapvalues(rownames(CT), pca_raw_result$yi, pca_raw_result$amino_acid)
pheatmap(CT)
```

```{r fig.width=10, fig.height=10}
CT <- cor(Tab, method = "spearman")
colnames(CT) <- plyr::mapvalues(colnames(CT), pca_raw_result$yi, paste0(pca_raw_result$amino_acid, "|", pca_raw_result$file_name))
rownames(CT) <- plyr::mapvalues(rownames(CT), pca_raw_result$yi, pca_raw_result$amino_acid)
pheatmap(CT)
```






