---
title: "Figure 6 f"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(parallel)
library(caret)
library(IRanges)
library(shiny)
library(plotly)
library(ggpubr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(Biostrings)
```

```{r}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}
```

```{r}
EAFNL <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/EAFNL.txt", sep = "\t")
FHL <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/FHL.txt", sep = "\t")
FYSL <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/FYSL.txt", sep = "\t")
LEF <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LEF.txt", sep = "\t")
LNFAE <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LNFAE.txt", sep = "\t")
LVFAG <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LVFAG.txt", sep = "\t")
LVFA <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LVFA.txt", sep = "\t")
LVFAK <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LVFAK.txt", sep = "\t")
```

```{r}
polyp <- rbind(data.table(PPT = "EAFNL", EAFNL), 
               data.table(PPT = "LNFAE", LNFAE), 
               data.table(PPT = "LVFFAG", LVFAG), 
               data.table(PPT = "LVFFAK", LVFAK), 
               data.table(PPT = "LVFFA", LVFA), 
               data.table(PPT = "FHL", FHL), 
               data.table(PPT = "FYSL", FYSL), 
               data.table(PPT = "LEF", LEF))
```

```{r}
polyp <- polyp[, .(Polypeptide = PPT, Blockade, AminoAcid = Pred2)]
polyp[, AminoAcid := plyr::mapvalues(AminoAcid, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
```

```{r}
openxlsx::write.xlsx(polyp[Polypeptide %in% c("LVFFA", "LVFFAG", "LVFFAK")], "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig6G.xlsx")
openxlsx::write.xlsx(polyp[Polypeptide %in% c("FHL", "FYSL", "LEF")], "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig6H.xlsx")
```
