---
title: "Figure 6 f"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(parallel)
library(caret)
library(IRanges)
library(shiny)
library(plotly)
library(ggpubr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(Biostrings)
```

```{r}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}
```

```{r}
LFGV <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LFGV.txt", sep = "\t")
LSGV <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LSGV.txt", sep = "\t")
```

```{r}
LFGV <- data.table(LFGV, D1 = LFGV[, get_density(Blockade, log10(DwellTime))])
LFGV <- LFGV[, .(DwellTime, Blockade, AminoAcid = Pred2, Density = D1)]
```

```{r}
LSGV <- data.table(LSGV, D1 = LSGV[, get_density(Blockade, log10(DwellTime))])
LSGV <- LSGV[, .(DwellTime, Blockade, AminoAcid = Pred2, Density = D1)]
```

```{r}
data <- rbind(data.table(Peptide = "LFGV", LFGV), data.table(Peptide = "LSGV", LSGV))
```

```{r}
openxlsx::write.xlsx(data, "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig6E.xlsx")
```

