---
title: "Supplementary Figure 5 b, c"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r echo=FALSE}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}
```

```{r echo=FALSE, fig.width=24, fig.height=6}
aat <- "His"
dataset <- fread(paste0("./analysis/81.ABFProcessing/SelectedSignals/", aat, "_signal.txt"))
dataset[, file_id := as.character(file_id)]
dataset[, File := gsub("\\.[0-9]", "", file_id)]
dataset[, ID := paste0(aat, "_", ID)]
dataset$D <- dataset[, get_density(x = Blockade, y = log10(DwellTime))]
data <- dataset[, .(File, ID, StartTime, EndTime, DwellTime, Blockade, Density = D)]
```

```{r}
sig1 <- lapply(list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat, full.names = T), fread)
sig1 <- data.table(A = rep(gsub(".signal.txt", "", list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat)), mapply(nrow, sig1)), do.call(rbind, sig1))
```

```{r}
data[, Class := ifelse(ID %in% sig1$ID, "signal", "noise")]
```

```{r}
openxlsx::write.xlsx(data, "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig5BC.xlsx")
```

```{r}
ggplot(data = data[order(Density)], mapping = aes(x = Blockade, y = DwellTime)) + 
  geom_density_2d_filled(aes(fill = ..level..), contour_var = "ndensity", breaks = seq(0, 1, length.out = 100)) + 
  geom_point(aes(alpha = pmin(Density + .02, 1), colour = File), size = .1) + 
  scale_y_log10(limits = c(0.12, 1345.23)) + 
  scale_x_continuous(limits = c(0.03, 1)) + 
  scale_colour_brewer(palette = "Set2") + 
  scale_fill_manual(values = c(scales::alpha("grey20", 0:99/99), RColorBrewer::brewer.pal(n = 6, name = "Dark2")), aesthetics = c("fill")) + 
    labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        # plot.margin = unit(c(0, 1, 0, 1), "line"), 
        legend.position = "none")
```

```{r}
ggplot(data = data[order(Density)], mapping = aes(x = Blockade, y = DwellTime)) + 
  geom_point(aes(alpha = pmin(Density + .02, 1), colour = Class), size = .5) + 
  scale_y_log10(limits = c(0.12, 1345.23)) + 
  scale_x_continuous(limits = c(0.03, 1)) + 
  scale_colour_brewer(palette = "Set1", direction = -1) + 
  scale_fill_manual(values = c(scales::alpha("#67000D", 0:99/99), RColorBrewer::brewer.pal(n = 4, name = "Dark2")), aesthetics = c("fill")) + 
  guides(alpha = "none", colour = guide_legend(reverse = T)) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = c(0.8, 0.9), 
        legend.background = element_blank(), 
        # plot.margin = unit(c(0, 1, 0, 1), "line"),  
        panel.grid = element_blank())
```

```{r}
ggplot(sig1, aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(aes(shape = as.character(File)), alpha = 0.5) + 
  scale_y_log10() + 
  scale_colour_brewer(palette = "Set2") + 
  guides(shape = "none") + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        legend.box.background = element_blank(), 
        plot.margin = unit(c(0, 1, 1, 1), "line"),
        legend.position = c(0.5, 0.9))
```




