---
title: "Supplementary Figure 11 a"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/Modeling_Data.RData")
Sigs_Test_FM <- Sigs_Test_FM[Sigs_Test[, !is.infinite(SignalCurrentWidth)], ]
Sigs_Test <- Sigs_Test[!is.infinite(SignalCurrentWidth)]
```

```{r eval=FALSE}
predicts1 <- mclapply(c("AdaBoost", "CART", "KNN", "NB", "NNet", "RF"), function(m) {
  model <- readRDS(paste0("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/", m, "_model.Rds"))
  predi <- predict(model, Sigs_Test_FM, type = "prob")
  colnames(predi) <- paste0(colnames(predi), paste0("_pred_", m))
  predi
}, mc.cores = 6)
# saveRDS(predicts1, file = "analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/predicts1.Rds")
```

```{r}
if(!is.element("predicts1", ls())) predicts1 <- readRDS("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version1/L1/predicts1.Rds")
```

```{r}
predicts2 <- do.call(cbind, predicts1)

true_label1 <- dummies::dummy(Sigs_Test$AA, sep = " ")
true_label1 <- data.frame(true_label1)
colnames(true_label1) <- gsub("AA.", "", colnames(true_label1))
colnames(true_label1) <- paste0(colnames(true_label1), "_true")

roc_RF1 <- multiROC::multi_roc(cbind(true_label1, predicts2))
pr_RF1 <- multiROC::multi_pr(cbind(true_label1, predicts2))
```

```{r}
mapply(function(x) x$macro, roc_RF1$AUC)
mapply(function(x) x$macro, pr_RF1$AUC)
```

```{r}
plot_roc <- lapply(predicts1, function(x) {
  as.data.table(multiROC::plot_roc_data(multiROC::multi_roc(cbind(true_label1, x))))
})

plot_pr <- lapply(predicts1, function(x) {
  as.data.table(multiROC::plot_pr_data(multiROC::multi_pr(cbind(true_label1, x))))
})
```

```{r}
roc_mat <- lapply(plot_roc, function(x) {
  set.seed(123)
  x[Group == "Macro"][sort(sample(.N, 1000))]
})
roc_mat <- do.call(rbind, roc_mat)
```

```{r}
AUCs <- data.table(Method = names(mapply(function(x) x$macro, roc_RF1$AUC)), AUC = mapply(function(x) x$macro, roc_RF1$AUC))
```

```{r}
data <- roc_mat[, .(Method, Specificity, Sensitivity, AUC)]
```

```{r}
openxlsx::write.xlsx(data, "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig11A.xlsx")
```

```{r fig.width=6, fig.height=4}
ggplot(data, aes(x = 1 - Specificity, y = Sensitivity, colour = Method)) + 
  geom_path(size = 1) + 
  geom_text(data = data[, .(AUC = unique(AUC)), Method], mapping = aes(x = 0.75, y = 6:1/10, label = paste("AUC:", round(AUC, 3)))) +
  theme_bw(base_size = 15) + 
  # scale_color_manual(values = MoldeCols[od]) + 
  lims(x = c(0, 1), y = c(0, 1)) + 
  labs(tag = "a") + 
  theme(panel.grid = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold"))
```




