---
title: "Supplementary Figure 5 f"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r echo=FALSE, fig.width=24, fig.height=6}
aat <- "His"
bgsignal <- fread(paste0("./analysis/81.ABFProcessing/SelectedSignals/", aat, "_background.txt"))
bgsignal[, file_id := as.character(file_id)]
bgsignal[, File := gsub("\\.[0-9]", "", file_id)]
bgsignal[, ID := paste0("Noise_", ID)]

dataset <- fread(paste0("./analysis/81.ABFProcessing/SelectedSignals/", aat, "_signal.txt"))
dataset[, file_id := as.character(file_id)]
dataset[, File := gsub("\\.[0-9]", "", file_id)]
dataset[, ID := paste0(aat, "_", ID)]

FeatureMatrix <- paste0("./analysis/81.ABFProcessing/FeatureMatrix/FeatureMatrix_", unique(dataset$File), ".txt")
FeatureMatrix <- do.call(rbind, lapply(FeatureMatrix, fread))
FeatureMatrix[, ID := paste0(aat, "_", ID)]
FeatureMatrix <- FeatureMatrix[ID %in% dataset[, ID]]
FeatureMatrix[, AA := aat]
setkey(FeatureMatrix, ID)
FeatureMatrix <- FeatureMatrix[dataset$ID, ]
FeatureMatrix <- data.frame(FeatureMatrix[, grepl("^X", colnames(FeatureMatrix)) | grepl("DwellTime", colnames(FeatureMatrix)), with = F], row.names = FeatureMatrix[[1]])

LineMat <- melt.data.table(as.data.table(FeatureMatrix, keep.rownames = "ID"), id.vars = "ID")[variable != "DwellTime"]
LineMat[, x := as.numeric(gsub("^X", "", variable))]
LineMat[, Blockade := 1 - x/1000]
LineMat <- LineMat[, .SD[, .(alpha = value/sum(value), Blockade)], ID]
```

```{r}
sig1 <- lapply(list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat, full.names = T), fread)
sig1 <- data.table(A = rep(gsub(".signal.txt", "", list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat)), mapply(nrow, sig1)), do.call(rbind, sig1))
```

```{r echo=FALSE}
tab1 <- merge(LineMat, sig1[, .(A, AA, ID, State)])
tab2 <- sig1[, .(.N, ID = list(ID)), .(A, State)]
tab2[, State := plyr::mapvalues(State, c("Sington", "Mixtrue"), c("State 1", "State 2"))]
tab2[, L := paste0(State, "\n", N)]
tab2 <- data.table(tab2[rep(seq_len(nrow(tab2)), mapply(length, tab2$ID))], ID0 = unlist(tab2$ID))
tab1 <- merge(tab1, tab2[, .(ID0, L)], by.x = "ID", by.y = "ID0")
tab1[, L := factor(L, levels = c("State 1\n193", "State 2\n653", "State 1\n306", "State 2\n1032"))]
```

```{r}
data <- tab1[, .(ID, Blockade, alpha, Class = A, AminoAcid = AA, State, Label = L)]
```

```{r}
openxlsx::write.xlsx(data, "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig5F.xlsx")
```

```{r echo=FALSE}
ggplot(data, aes(x = Blockade, y = ID, alpha = alpha, colour = Label)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Dark2") + 
  facet_grid(Label + Class ~ ., scales = "free_y", space = "free") + 
  theme_classic(base_size = 15) + 
  theme(axis.text.y = element_blank(), 
        # axis.title.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.line.y = element_blank(),
        strip.placement = "inside", 
        strip.text.y = element_text(angle = 0), 
        strip.background = element_blank(), 
        panel.background = element_blank(), 
        plot.background = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "none") + 
  labs(x = "Blockade", y = "Signal")
```
