---
title: "Supplementary Figure 17"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(parallel)
library(caret)
library(IRanges)
library(shiny)
library(plotly)
library(ggpubr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(Biostrings)
```

```{r}
FYSL <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/FYSL.txt", sep = "\t")
LEF <- fread("./analysis/93.Revision/04.PolypeptideSimilarity/01.AminoAcidPrediction/LEF.txt", sep = "\t")
```

```{r}
polyp <- rbind(data.table(PPT = "FYSL", FYSL[, .(A, ID)]), 
               data.table(PPT = "LEF", LEF[, .(A, ID)]))
```

```{r}
id2rep <- unique(polyp[, .(PPT, file_id = A)])
id2rep <- id2rep[, .(file_id, Experiment = paste(PPT, seq_len(.N), sep = "_")), PPT]
```

```{r}
CurrList <- mclapply(polyp[, unique(A)], function(fi) {
  # print(fi)
  Curr <- readRDS(paste0("./analysis/81.ABFProcessing/SignalCurrent/SignalCurrent_", gsub("\\.[0-9]$", "", fi), ".Rds"))
  stopifnot(all(polyp[A == fi, ID] %in% Curr[, ID]))
  Curr[ID %in% polyp[A == fi, ID]]
}, mc.cores = 20)
```

```{r}
CurrList_Den <- lapply(CurrList, function(x) {
  density(x[, Current], from = 0, to = 1, n = 1024, bw = 0.001)$y
})
CurrList_Den <- do.call(rbind, CurrList_Den)
row.names(CurrList_Den) <- polyp[, unique(A)]
row.names(CurrList_Den) <- plyr::mapvalues(row.names(CurrList_Den), id2rep$file_id, id2rep$Experiment)
```

```{r}
CurrList_Den_Tab <- melt.data.table(as.data.table(CurrList_Den, keep.rownames = "ID"), id.vars = "ID")
CurrList_Den_Tab[, Peptide := gsub("_[0-9]$", "", ID)]
CurrList_Den_Tab$Experiment <- mapply(function(x) x[2], strsplit(CurrList_Den_Tab$ID, "_"))
# CurrList_Den_Tab <- CurrList_Den_Tab[, .(value = mean(value)), .(Peptide, variable)]
CurrList_Den_Tab[, variable := as.numeric(gsub("V", "", variable))]

CurrList_Den_Tab[, variable := variable / 1024]
CurrList_Den_Tab <- CurrList_Den_Tab[variable > .5]
data <- CurrList_Den_Tab[, .(Peptide, Experiment, x = variable, y = value)]
```

```{r}
openxlsx::write.xlsx(data, "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig17.xlsx")
```

```{r}
ggplot(data, aes(x = x, y = y, colour = Experiment, lty = Peptide)) + 
  geom_line()
```

