---
title: "Supplementary Figure 5 d, e"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
sig1 <- lapply(list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat, full.names = T), fread)
sig1 <- data.table(A = rep(gsub(".signal.txt", "", list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat)), mapply(nrow, sig1)), do.call(rbind, sig1))
data <- sig1[, .(File, ID, StartTime, EndTime, DwellTime, Blockade, Class = A, State)]
```

```{r}
openxlsx::write.xlsx(data, "./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/SupFig5DE.xlsx")
```

```{r}
ggplot(data, aes(x = Blockade, y = DwellTime, colour = Class)) + 
  geom_point(aes(shape = as.character(File)), alpha = 0.5) + 
  scale_y_log10() + 
  scale_colour_brewer(palette = "Set2") + 
  guides(shape = "none") + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        legend.box.background = element_blank(), 
        plot.margin = unit(c(0, 1, 1, 1), "line"),
        legend.position = c(0.5, 0.9))
```

```{r}
ggplot(data, aes(x = Blockade, y = DwellTime, colour = ifelse(State == "Sington", "State 1", "State 2"))) + 
  geom_point(aes(shape = as.character(File)), alpha = 0.5) + 
  scale_y_log10() + 
  guides(colour = guide_legend(nrow = 1, reverse = T), shape = "none") + 
  labs(y = "Dwell time (ms)") + 
  facet_wrap(~ Class) + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_blank(), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        legend.box.background = element_blank(), 
        plot.margin = unit(c(0, 1, 1, 1), "line"),
        legend.position = "none")
```

```{r}
ggplot(data, aes(x = Blockade, fill = ifelse(State == "Sington", "State 1", "State 2"))) + 
  geom_histogram(position = position_dodge(), binwidth = 0.001) + 
  guides(fill = guide_legend(nrow = 1, reverse = F)) + 
  facet_wrap(~ Class) + 
  theme_minimal(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.title = element_blank(), 
        plot.margin = unit(c(1, 1, 0, 1), "line"),
        axis.text = element_blank(), 
        axis.ticks = element_blank(), 
        strip.background = element_rect(size = 0), 
        strip.text = element_blank(),
        legend.position = c(0.7, 0.5), 
        legend.key.width = unit(0.4, "line"), 
        legend.box.spacing = unit(0, "line"), 
        plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank())
```

