---
title: "Figure 2 C"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
```

```{r}
meta <- fread("./data/MetaInfomation/StandardAA_Meta.txt")
```

```{r}
files <- list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals", ".signal.txt", full.names = T)
Sigs <- do.call(rbind, lapply(files, fread))
Sigs <- Sigs[AA != "CbC"]
Sigs[, ID0 := ID]
for (a in Sigs[, unique(AA)]) {
  Sigs[, ID0 := gsub(paste0(a, "_"), "", ID0)]
}
```

```{r}
Mixtrue <- Sigs[, .(N = sum(State == "Mixtrue"), P = mean(State == "Mixtrue") * 100), .(file_name = File, file_id, AA)]
Mixtrue <- merge(Mixtrue, meta, by = c("file_name", "file_id"))
Mixtrue[, concentration := factor(concentration, levels = c("1", "2", "4", "5", "10", "20", "100", "200"))]
Mixtrue <- merge(Mixtrue, Mixtrue[, .N, .(AA, concentration)][N > 2, .(AA, concentration)], by = c("AA", "concentration"))
Mixtrue <- Mixtrue[AA %in% Mixtrue[, length(unique(concentration)), .(AA)][V1 > 1, AA]]
```

```{r fig.width=20, fig.height=5}
ggplot(Mixtrue, aes(x = AA, y = P, colour = concentration)) + 
  geom_boxplot() + 
  scale_colour_brewer(palette = "Reds", guide = guide_legend(nrow = 1, title = "Concentration (uM)")) + 
  labs(y = "Percentage of multi-level signals (%)") + 
  stat_compare_means(label = "..p.signif..", method = "t.test") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank()) + 
  facet_wrap( ~ AA, nrow = 1, scales = "free_x")
```

```{r fig.width=20, fig.height=5}
ggplot(Mixtrue, aes(x = AA, y = P, colour = concentration)) + 
  geom_boxplot() + 
  scale_colour_brewer(palette = "Dark2", guide = guide_legend(nrow = 1, title = "Concentration (uM)")) + 
  labs(y = "Percentage of multi-level signals (%)") + 
  stat_compare_means(label = "..p.signif..", method = "t.test") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank()) + 
  facet_wrap( ~ AA, nrow = 1, scales = "free")
```


```{r fig.width=12, fig.height=4}
ggplot(Mixtrue, aes(x = AA, y = P, colour = concentration)) + 
  geom_violin() + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.9)) + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 5, name = "Dark2"), guide = guide_legend(nrow = 1, title = "Concentration (uM)")) + 
  scale_y_continuous(limits = c(0, 100)) + 
  labs(y = "Percentage of multi-level signals (%)") + 
  stat_compare_means(label = "..p.signif..", method = "t.test", label.y.npc = 0.9) + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank())
ggsave("./analysis/00.FigureTables/Rebuttal/Jan06/Response/Multi-level-signals.pdf", width = 12, height = 4)
```




