---
title: "Figure 3"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(Biostrings)
library(patchwork)
library(ggthemes)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
library(caret)
library(multiROC)
library(pROC)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/MetaInfomation/File_id_to_replicates_rep.xlsx"))
```

# E-G

```{r}
Gly_All_Sig_Freq <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3E-G.xlsx", 1))
Arg_All_Sig_Freq <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3E-G.xlsx", 2))
Asp_All_Sig_Freq <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Jan06/Figures/Data/Fig3E-G.xlsx", 3))
```

```{r}
Gly_All_Sig_Freq <- merge(Gly_All_Sig_Freq, meta, by.x = "File", by.y = "File_id")
Gly_All_Sig_Freq <- Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), .(Concentration, rep)]
```

```{r fig.width=5, fig.height=5}
ggplot() + 
  stat_summary(data = Gly_All_Sig_Freq, aes(x = Concentration, y = Frequency), fun.data = "mean_sd", colour = aa_cols["Gly"]) + 
  geom_smooth(data = Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), method = "lm", se = F, colour = "grey") + 
  geom_hline(yintercept = 5, lty = 2, colour = "grey") + 
  labs(x = "Concentration (μM)", y = expression(Signal~frequency~"("*"min"^-1*")"), tag = "g") +
  stat_cor(data = Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), size = 6) + 
  stat_regline_equation(data = Gly_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], 
                        aes(x = Concentration, y = Frequency, label = paste(..eq.label.., ..adj.rr.label.., sep = "~`,`~~")), 
                        label.y.npc = 0.8, size = 6) + 
  facet_wrap(~ "G") + 
  theme_calc(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        plot.tag = element_text(size = 30, face = "bold"), 
        plot.background = element_blank()) -> pg
```

```{r}
Arg_All_Sig_Freq <- merge(Arg_All_Sig_Freq, meta, by.x = "File", by.y = "File_id")
Arg_All_Sig_Freq <- Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), .(Concentration, rep)]
```

```{r}
ggplot() + 
  stat_summary(data = Arg_All_Sig_Freq, aes(x = Concentration, y = Frequency), fun.data = "mean_sd", colour = aa_cols["Arg"]) + 
  geom_smooth(data = Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), method = "lm", se = F, colour = "grey") + 
  geom_hline(yintercept = 5, lty = 2, colour = "grey") + 
  labs(x = "Concentration (μM)", y = expression(Signal~frequency~"("*"min"^-1*")"), tag = "e") +
  stat_cor(data = Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), size = 6) + 
  stat_regline_equation(data = Arg_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], 
                        aes(x = Concentration, y = Frequency, label = paste(..eq.label.., ..adj.rr.label.., sep = "~`,`~~")), 
                        label.y.npc = 0.8, size = 6) + 
  facet_wrap(~ "R") + 
  theme_calc(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        plot.tag = element_text(size = 30, face = "bold"), 
        plot.background = element_blank()) -> pe
```

```{r}
Asp_All_Sig_Freq <- merge(Asp_All_Sig_Freq, meta, by.x = "File", by.y = "File_id")
Asp_All_Sig_Freq <- Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), .(Concentration, rep)]
```

```{r}
ggplot() + 
  stat_summary(data = Asp_All_Sig_Freq, aes(x = Concentration, y = Frequency), fun.data = "mean_sd", colour = aa_cols["Asp"]) + 
  geom_smooth(data = Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), method = "lm", se = F, colour = "grey") + 
  geom_hline(yintercept = 5, lty = 2, colour = "grey") + 
  labs(x = "Concentration (μM)", y = expression(Signal~frequency~"("*"min"^-1*")"), tag = "f") +
  stat_cor(data = Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], aes(x = Concentration, y = Frequency), size = 6) + 
  stat_regline_equation(data = Asp_All_Sig_Freq[, .(Frequency = mean(Frequency)), Concentration], 
                        aes(x = Concentration, y = Frequency, label = paste(..eq.label.., ..adj.rr.label.., sep = "~`,`~~")), 
                        label.y.npc = 0.8, size = 6) + 
  facet_wrap(~ "D") + 
  theme_calc(base_size = 22) + 
  theme(panel.grid = element_blank(), 
        plot.tag = element_text(size = 30, face = "bold"), 
        plot.background = element_blank()) -> pf
```

```{r fig.width=15, fig.height=5}
pe + pf + pg + plot_layout(nrow = 1)
```



