---
title: "Figure 2a"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(parallel)
library(cowplot)
library(S4Vectors)
library(caret)
```

```{r}
Preds <- readRDS(file = "analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Preds.Rds")
```

```{r}
cM <- Preds[[4]][Dataset == "ValidationUp" & Prob > 0.5, confusionMatrix(pred, true)]
cM <- as.matrix(cM$table)
cM <- reshape2::dcast(as.data.frame(cM), Prediction ~ Reference)
cM <- data.frame(cM[, -1], row.names = cM[, 1])
cM <- apply(cM, 2, prop.table)*100
row.names(cM) <- plyr::mapvalues(row.names(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
colnames(cM) <- plyr::mapvalues(colnames(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))

ggplot(data = reshape2::melt(as.matrix(cM)), aes(x = Var1, y = Var2, fill = value)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") +
  theme_bw(base_size = 15) + 
  theme(legend.title = element_blank(), plot.margin = unit(c(0.25, 0, 0, 0), "lines")) + 
  labs(x = "Prediction", y = "Reference") -> p1

ggplot(data.table(A = factor(rownames(cM), levels = rownames(cM)), Percent = rowSums(cM)), aes(x = A, y = Percent)) +
  geom_col(fill = "#A50F15") +
  theme_bw(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "lines")) -> p2
```

```{r fig.width=5.5, fig.height=5.5}
p2 / p1 + plot_layout(heights = c(2, 8))
# ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix.pdf", width = 7, height = 7)
```


```{r}
cMList <- lapply(Preds, function(x) {
  do.call(rbind, lapply(c("Test", "TestUp", "Validation", "ValidationUp"), function(d) {
    data.table(Model = x[, unique(Model)], DataSet = d, as.data.table(x[Dataset == d, confusionMatrix(pred, true)]$byClass))
  }))
})
cMList <- do.call(rbind, cMList)
cMList[, Model := gsub("Fit", "RF", Model)]
```

```{r fig.width=5, fig.height=3}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Sensitivity, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank(), 
        legend.position = "none") -> p1
p1
```


```{r fig.width=5, fig.height=3}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Specificity, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank(), 
        legend.position = "none") -> p2
p2
```


```{r fig.width=5, fig.height=3}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = F1, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank(), 
        legend.position = "none") -> p3
p3
```


```{r fig.width=5, fig.height=3}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Precision, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank(), 
        legend.position = "top", legend.title = element_blank()) -> p4
p4
```


```{r fig.width=5, fig.height=3}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Recall, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank(), 
        legend.position = "none") -> p5
p5
```

```{r fig.width=16, fig.height=3}
p_a <- plot_grid(p1, p2, p4, p5, p3, nrow = 1, rel_widths = c(1, 1, 1, 1, 1), align = "v")
p_a

p_a <- p1 + p2 + p4 + p5 + p3 + plot_layout(nrow = 1)
```


```{r}
SignalsNumber <- openxlsx::read.xlsx("analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/SignalsNumber.xlsx")
SignalsNumber <- as.data.table(SignalsNumber)

cutoffList <- openxlsx::read.xlsx("analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/cutoffList.xlsx")
cutoffList <- as.data.table(cutoffList)
```

```{r}
SignalsNumber[, Cutoff := Model]
ggplot(SignalsNumber[, mean(Train), Model], aes(x = Model, y = V1, fill = Model)) + 
  geom_col() + 
  geom_text(aes(label = V1, y = V1 + 20)) + 
  scale_fill_brewer(palette = "Dark2") + 
  labs(y = "No. signals of training set") + 
  theme_bw(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        legend.position = "none") -> p1
p1
```


```{r}
ggplot(SignalsNumber, aes(x = Model, y = Test)) + 
  geom_boxplot(aes(colour = Model)) + 
  scale_colour_brewer(palette = "Dark2") + 
  labs(y = "No. signals of test set") + 
  theme_bw(base_size = 15) + 
  geom_text(data = SignalsNumber[, median(Test), Model], 
            mapping = aes(y = V1 + 200, label = V1)) + 
  theme(panel.grid = element_blank(), 
        legend.position = "none") -> p2
p2
```


```{r}
ggplot(SignalsNumber, aes(x = Cutoff, y = Validation)) + 
  geom_boxplot(aes(colour = Cutoff)) + 
  scale_colour_brewer(palette = "Dark2") + 
  labs(y = "No. signals of validation set") + 
  guides(colour = "none") +
  theme_bw(base_size = 15) + 
  geom_text(data = SignalsNumber[, median(Validation), Cutoff], 
            mapping = aes(y = V1 + 30, label = V1)) + 
  theme(panel.grid = element_blank(), 
        legend.position = "none") -> p3
p3
```



```{r fig.width=6, fig.height=4}
roc_mat <- readRDS(file = "./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Test_ROCs.Rds")
ggplot(roc_mat, aes(x = 1 - Specificity, y = Sensitivity, colour = Model)) + 
  geom_path(size = 1) + 
  geom_text(data = AUCs[Curve == "ROC", ], mapping = aes(x = 0.75, y = 6:1/10, label = paste0(Model, ", AUC = ", round(Macro, 4)))) +
  theme_bw(base_size = 15) + 
  scale_color_manual(values = MoldeCols) + 
  lims(x = c(0, 1), y = c(0, 1)) + 
  theme(panel.grid = element_blank(), 
        legend.position = "none") + 
  labs(title = "Test set") -> p4
p4
```

```{r}
roc_mat2 <- readRDS(file = "./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Valid_ROCs.Rds")
ggplot(roc_mat2, aes(x = 1 - Specificity, y = Sensitivity, colour = Model)) + 
  geom_path(size = 1) + 
  geom_text(data = AUCs[Curve == "ROC", ], mapping = aes(x = 0.75, y = 6:1/10, label = paste0(Model, ", AUC = ", round(Macro, 4)))) +
  theme_bw(base_size = 15) + 
  scale_color_manual(values = MoldeCols) + 
  lims(x = c(0, 1), y = c(0, 1)) + 
  theme(panel.grid = element_blank(), 
        legend.position = "none") + 
  labs(title = "Validation set") -> p5
p5
```

```{r}
cutoffList <- readRDS(file = "analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Cutoff_Recovery_Accuracy_Test.Rds")
ggplot(cutoffList[Dataset %in% c("Test")], aes(x = Recovery * 100, y = Accuracy * 100, colour = Model)) + 
  geom_line() + 
  theme_bw(base_size = 15) + 
  scale_x_reverse() + 
  labs(x = "Recovery (%)", y = "Accuracy (%)", title = "Test set") + 
  theme(legend.position = "top") + 
  geom_point(data = cutoffList[Dataset %in% c("Test") & Cutoff %in% c(c(7)/10)]) +
  geom_text(data = cutoffList[Dataset %in% c("Test") & Cutoff %in% c(c(7)/10)], aes(x = 25, y = seq(73, 88, 3), label = L)) + 
  scale_color_brewer(palette = "Dark2") + 
  lims(y = c(70, 100)) + 
  guides(colour = "none") + 
  theme(panel.grid = element_blank()) -> p6
p6
```

```{r fig.width=12, fig.height=8}
p_b <- plot_grid(p1, p2, p3, p4 + theme(legend.position = "none"), p5 + theme(legend.position = "none"), p6, 
                 nrow = 2, rel_heights = c(1, 1.2), labels = letters[1:6], label_size = 24, label_y = 1.03)
p_b
ggsave(plot = p_b, "./analysis/00.FigureTables/Sep24/SupFigure8/SupFigure8.pdf", width = 12, height = 8)
```


```{r}
Preds <- readRDS(file = "analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Preds.Rds")
Preds <- do.call(rbind, Preds)
Preds[pred == true, Result := "Correct"]
Preds[pred != true, Result := "Wrong"]
Preds[, Model := gsub("Fit", "RF", Model)]

```

```{r fig.width=16, fig.height=5}
ggplot(Preds[Dataset %in% c("Test", "Validation")], aes(Prob, fill = Result)) +
  geom_histogram() +
  theme_bw(base_size = 16) +
  facet_grid(Dataset ~ Model, scales = "free_y") +
  theme(legend.position = "right", panel.grid = element_blank()) + 
  labs(x = "Probability", y = "Count         Count") + 
  scale_fill_brewer(palette = "Paired", direction = -1) -> p_c
p_c
```

```{r fig.width=14, fig.height=8}
p_a / p_c + plot_layout(heights = c(3, 5)) + 
  plot_annotation(tag_levels = "a") & 
  theme(plot.tag = element_text(size = 24, face = 'bold'))

plot_grid(p_a, p_c, ncol = 1)
```


```{r fig.width=12, fig.height=5}
Tabs <- rbind(cMList[DataSet %in% c("Test", "Validation"), .(Model, DataSet, value = Sensitivity, Type = "Sensitivity")],
              cMList[DataSet %in% c("Test", "Validation"), .(Model, DataSet, value = Specificity, Type = "Specificity")],
              cMList[DataSet %in% c("Test", "Validation"), .(Model, DataSet, value = Precision, Type = "Precision")],
              cMList[DataSet %in% c("Test", "Validation"), .(Model, DataSet, value = Recall, Type = "Recall")],
              cMList[DataSet %in% c("Test", "Validation"), .(Model, DataSet, value = F1, Type = "F1")])
ggplot(Tabs, aes(x = Model, y = value, colour = DataSet)) +
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) +
  facet_wrap(~ Type, nrow = 1, scales = "free_y") + 
  theme(legend.position = "top", 
        panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank()) + 
  labs(y = "Value") -> p_a
p_a
```

```{r fig.width=12, fig.height=5}
ggplot(Tabs, aes(x = Model, y = value, colour = DataSet)) +
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) +
  facet_wrap(~ Type, nrow = 1, scales = "free_y") + 
  theme(legend.position = "right", 
        panel.grid = element_blank(), 
        axis.text.x = element_text(angle = 30), 
        strip.background = element_blank()) + 
  labs(y = "Value") + 
  stat_compare_means(comparisons = list(c("RF1", "RF4")), label.y.npc = -10) -> p_a
p_a
```


```{r fig.width=13, fig.height=9}
p_a / p_c + plot_layout(heights = c(4, 4)) + 
  plot_annotation(tag_levels = "a") & 
  theme(plot.tag = element_text(size = 24, face = 'bold'))
ggsave("./analysis/00.FigureTables/Sep24/SupFigure8/SupFigure9.pdf", width = 13, height = 9)
```






