---
title: "Polypeptide sequencing"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
  code_folding: "hide"
toc: true
toc_depth: 4
toc_float: 
  collapsed: false
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = T, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r}
library(openxlsx)
library(ggplot2)
library(data.table)
library(ggbeeswarm)
library(ggridges)
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/实验信息表1101.xlsx"))
meta <- meta[amino_acid != "blank", ]
pps <- unique(meta[amino_acid != "blank", amino_acid])
```


# Polypeptide1


```{r}
ppi <- pps[1]
files <- paste0("./analysis/02.PolypeptideSequencing/20211025/Version2/AA_Signals_", 
                meta[amino_acid == ppi & amino_acid != "blank", file_name], ".xlsx")
file.exists(files)
Signals <- lapply(files, read.xlsx)
names(Signals) <- gsub(".xlsx", "", gsub("AA_Signals_", "", basename(basename(files))))
Signal <- data.table(Sample = rep(names(Signals), mapply(nrow, Signals)), do.call(rbind, Signals))

write.xlsx(c(list(Merge = Signal), Signals), "./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide1_APRLRFYSL.xlsx")
```

```{r}
Signal <- as.data.table(read.xlsx("./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide1_APRLRFYSL.xlsx"))
Signal <- na.omit(Signal)
ggplot(Signal, aes(x = Blockade, y = DwellTime)) + 
  geom_point()
```

```{r}
hist(Signal$TimeRatio, breaks = 200, main = "TimeRatio", xlab = "TimeRatio")
```

```{r}
hist(Signal$DwellTime, breaks = 200, main = "DwellTime", xlab = "DwellTime")
abline(v = 0.75, col = 2)
```

```{r}
hist(Signal$SignalSD, breaks = 200, main = "SignalSD", xlab = "SignalSD")
abline(v = 2, col = 2)
```


```{r}
ggplot(Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2], aes(x = Blockade, y = DwellTime)) + 
  geom_point() + 
  labs(title = paste0("N = ", Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2, .N])) + 
  theme_bw(base_size = 16)
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptide1_Blockade_DwellTime.pdf", 
       width = 6, height = 4)
```

```{r}
ggplot(Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2], aes(x = Blockade)) + 
  geom_histogram(binwidth = 0.002) + 
  theme_bw(base_size = 16)
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptide1_Blockade_Histogram.pdf", 
       width = 6, height = 4)
```

```{r}
Signal_P1 <- Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2]
```


# Polypeptide2


```{r}
ppi <- pps[2]
files <- paste0("./analysis/02.PolypeptideSequencing/20211025/Version2/AA_Signals_", 
                meta[amino_acid == ppi & amino_acid != "blank", file_name], ".xlsx")
file.exists(files)
files <- files[file.exists(files)]
Signals <- lapply(files, read.xlsx)
names(Signals) <- gsub(".xlsx", "", gsub("AA_Signals_", "", basename(basename(files))))
Signal <- data.table(Sample = rep(names(Signals), mapply(nrow, Signals)), do.call(rbind, Signals))

write.xlsx(c(list(Merge = Signal), Signals), "./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide2_RPVKVYPNGAEDESAEAFPLEF.xlsx")
```

```{r}
Signal <- as.data.table(read.xlsx("./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide2_RPVKVYPNGAEDESAEAFPLEF.xlsx"))
Signal <- na.omit(Signal)
ggplot(Signal, aes(x = Blockade, y = DwellTime)) + 
  geom_point()
```

```{r}
hist(Signal$TimeRatio, breaks = 200, main = "TimeRatio", xlab = "TimeRatio")
```

```{r}
hist(Signal$DwellTime, breaks = 200, main = "DwellTime", xlab = "DwellTime")
abline(v = 0.75, col = 2)
```

```{r}
hist(Signal$SignalSD, breaks = 200, main = "SignalSD", xlab = "SignalSD")
abline(v = 2, col = 2)
```

```{r}
ggplot(Signal[TimeRatio > 0.8 & SignalSD < 2 & DwellTime > 0.75], aes(x = Blockade, y = DwellTime)) + 
  geom_point() + 
  labs(title = paste0("N = ", Signal[TimeRatio > 0.8 & SignalSD < 2 & DwellTime > 0.75, .N])) + 
  theme_bw(base_size = 16)
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptide2_Blockade_DwellTime.pdf", 
       width = 6, height = 4)
```

```{r}
ggplot(Signal[TimeRatio > 0.8 & SignalSD < 2 & DwellTime > 0.75], aes(x = Blockade)) + 
  geom_histogram(binwidth = 0.002) + 
  theme_bw(base_size = 16)
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptide2_Blockade_Histogram.pdf", 
       width = 6, height = 4)
```

```{r}
Signal_P2 <- Signal[TimeRatio > 0.8 & SignalSD < 2 & DwellTime > 0.75]
```

# Polypeptide3


```{r}
ppi <- pps[3]
files <- paste0("./analysis/02.PolypeptideSequencing/20211025/Version2/AA_Signals_", 
                meta[amino_acid == ppi & amino_acid != "blank", file_name], ".xlsx")
file.exists(files)
files <- files[file.exists(files)]
Signals <- lapply(files, read.xlsx)
names(Signals) <- gsub(".xlsx", "", gsub("AA_Signals_", "", basename(basename(files))))
Signal <- data.table(Sample = rep(names(Signals), mapply(nrow, Signals)), do.call(rbind, Signals))

write.xlsx(c(list(Merge = Signal), Signals), "./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide3_DRVYIHPFHL.xlsx")
```

```{r}
Signal <- as.data.table(read.xlsx("./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide3_DRVYIHPFHL.xlsx"))
Signal <- na.omit(Signal)
ggplot(Signal, aes(x = Blockade, y = DwellTime)) + 
  geom_point()
```

```{r}
hist(Signal$TimeRatio, breaks = 200, main = "TimeRatio", xlab = "TimeRatio")
```

```{r}
hist(Signal$DwellTime, breaks = 200, main = "DwellTime", xlab = "DwellTime")
abline(v = 0.75, col = 2)
```

```{r}
hist(Signal$SignalSD, breaks = 200, main = "SignalSD", xlab = "SignalSD")
abline(v = 2, col = 2)
```

```{r}
ggplot(Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2], aes(x = Blockade, y = DwellTime)) + 
  geom_point() + 
  labs(title = paste0("N = ", Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2, .N])) + 
  theme_bw(base_size = 16) + 
  scale_y_log10()
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptide3_Blockade_DwellTime.pdf", 
       width = 6, height = 4)
```

```{r}
ggplot(Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2], aes(x = Blockade)) + 
  geom_histogram(binwidth = 0.002) + 
  theme_bw(base_size = 16)
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptide3_Blockade_Histogram.pdf", 
       width = 6, height = 4)
```

```{r}
ggplot(Signal[DwellTime > 0.75 & SignalSD < 2], aes(x = Blockade, y = DwellTime)) + 
  geom_point() + 
  labs(title = paste0("N = ", Signal[DwellTime > 0.75 & SignalSD < 2, .N])) + 
  theme_bw(base_size = 16) + 
  scale_y_log10()
```

```{r}
ggplot(Signal[DwellTime > 0.75 & SignalSD < 2], aes(x = Blockade)) + 
  geom_histogram(binwidth = 0.002) + 
  labs(title = paste0("N = ", Signal[DwellTime > 0.75 & SignalSD < 2, .N])) + 
  theme_bw(base_size = 16)
```

```{r}
Signal_P3 <- Signal[TimeRatio > 0.8 & DwellTime > 0.75 & SignalSD < 2]
```


# Similarity

```{r}
Signal_Ps <- rbind(data.table(Peptide = "Peptide1", Signal_P1), 
                   data.table(Peptide = "Peptide2", Signal_P2),
                   data.table(Peptide = "Peptide3", Signal_P3))
```

```{r fig.width=7, fig.height=4}
ggplot(Signal_Ps, aes(x = Blockade, fill = Peptide)) + 
  geom_histogram(binwidth = 0.001, alpha = 0.5) + 
  theme_bw(base_size = 16) -> p

mat <- as.data.table(ggplot_build(p)$data[[1]])
mat[, Peptide := plyr::mapvalues(fill, c("#F8766D", "#00BA38", "#619CFF"), c("Peptide1", "Peptide2", "Peptide3"))]

ggplot(Signal_Ps, aes(x = Blockade, fill = Peptide)) + 
  geom_histogram(binwidth = 0.001, alpha = 0.5) + 
  theme_bw(base_size = 16) + 
  geom_line(data = mat, aes(x = x, y = y, colour = Peptide))
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptides_Blockade_Histogram2.pdf", width = 7, height = 4)
```

```{r fig.width=7, fig.height=4}
ggplot(Signal_Ps, aes(x = Blockade, fill = Peptide)) + 
  geom_histogram(bins = 200, alpha = 1) +
  geom_freqpoly(aes(colour = Peptide), bins = 200) + 
  theme_bw(base_size = 16)
```

```{r fig.width=7, fig.height=4}
ggplot(Signal_Ps, aes(x = Blockade, fill = Peptide)) + 
  geom_histogram(binwidth = 0.002, alpha = 0.5) + 
  theme_bw(base_size = 16)

ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptides_Blockade_Histogram.pdf", width = 7, height = 4)
```

```{r fig.width=7, fig.height=4}
ggplot(Signal_Ps, aes(x = Blockade, colour = Peptide)) + 
  geom_line(stat = "Density", adjust = 0.16) + 
  theme_bw(base_size = 16) -> p1
p1
ggsave("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Polypeptides_Blockade_Density.pdf", p1, width = 7, height = 4)
```

```{r fig.width=7, fig.height=4}
p1b <- ggplot_build(p1)

mat <- as.data.table(p1b$data[[1]])
mat[, Peptide := plyr::mapvalues(colour, c("#F8766D", "#00BA38", "#619CFF"), c("Peptide1", "Peptide2", "Peptide3"))]

ggplot(mat, aes(x = x, y = y, colour = Peptide)) + 
  geom_line() + 
  theme_bw(base_size = 16)
```

```{r}
mat2 <- dcast.data.table(mat, formula = x ~ Peptide, value.var = "y")
r1 <- cor(mat2[, 2:4], method = "pearson")
r2 <- cor(mat2[, 2:4], method = "spearman")
```

```{r}
corrplot::corrplot(r1, 
                   method = "circle", 
                   # type = "upper", 
                   addCoef.col = 'white', 
                   cl.pos = 'n', col.lim = c(0,1))

```

```{r}
corrplot::corrplot(r1, 
                   method = "circle", 
                   # type = "upper", 
                   addCoef.col = 'white', 
                   cl.pos = 'n')

```

```{r}
pdf("analysis/02.PolypeptideSequencing/20211025/Version2/Figures/Similarity.pdf", width = 4, height = 4)
corrplot::corrplot(r1, 
                   method = "circle", 
                   # type = "upper", 
                   addCoef.col = 'white', 
                   cl.pos = 'n')
dev.off()
```

```{r}
corrplot::corrplot(r2, 
                   method = "circle", 
                   # type = "upper", 
                   addCoef.col = 'white', 
                   cl.pos = 'n')
```
