---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(parallel)
library(caret)
library(openxlsx)
library(cowplot)
```

```{r}
set.seed(19)
AA_Cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(AA_Cols) <- Biostrings::AA_STANDARD
```

# Polypeptide3

```{r}
Signal1 <- as.data.table(read.xlsx("./analysis/02.PolypeptideSequencing/20211025/Version2/Polypeptide3_DRVYIHPFHL.xlsx"))
Signal1$ID <- paste0(Signal1[, Sample], "_", sprintf("%04d", do.call(c, lapply(Signal1[, .N, Sample][, N], function(x) seq_len(x)))))

Mat <- readRDS("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/01.PolypeptideSignalTransformation/Polypeptide3_DRVYIHPFHL.signal.Rds")
Mat <- Mat[row.names(Mat) %in% Signal1$ID, ]
```

## RF

```{r}
Models <- list.files("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models", "RF_Density_Line_Ony_Fit", full.names = T)
```

```{r}
Polypeptide3 <- mclapply(1:6, function(i) {
  Fit <- readRDS(Models[i])
  if(nrow(subset.data.frame(Mat, AllTime > i & SignalSD < 4)) == 0) return(NULL)
  ROC_Test <- predict(Fit, subset.data.frame(Mat, AllTime > i & SignalSD < 4), type = "prob")
  ppm <- melt(as.data.table(ROC_Test, keep.rownames = "ID"), value.name = "Prob", variable.name = "pred")[, .SD[which.max(Prob), ], ID]
  ppm[, Model := paste0("RF", i)]
  ppm <- merge(ppm, as.data.table(Mat, keep.rownames = "ID")[, .(ID, AllTime, DwellTime, SignalSD, Blockade)], by = "ID")
  return(ppm)
}, mc.cores = 6)

Polypeptide3 <- do.call(rbind, Polypeptide3)
Polypeptide3[, pred := as.character(pred)]
Polypeptide3[, AA := plyr::mapvalues(pred, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
Polypeptide3 <- merge(Polypeptide3, Signal1[, .(ID, TimeRatio)], by = "ID")
Polypeptide3_RF <- copy(Polypeptide3)
```

```{r fig.width=9, fig.height=4}
ggplot(Polypeptide3_RF, aes(x = Prob, colour = Model)) + 
  geom_line(stat = "Density") + 
  theme_bw(base_size = 15) + 
  scale_color_brewer(palette = "Dark2") + 
  facet_wrap( ~ Model, nrow = 2)
```

```{r fig.width=15, fig.height=8}
ggplot(Polypeptide3_RF[Prob > 0.7], aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) +
  facet_wrap( ~ Model) + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none")
```

## KNN

```{r}
Models <- list.files("./analysis/03.MachineLearning/Version7/02.Modeling/05.knn/01.Models", "knn_Density_Line_Ony_Fit", full.names = T)
```

```{r}
Polypeptide3 <- mclapply(1:6, function(i) {
  Fit <- readRDS(Models[i])
  if(nrow(subset.data.frame(Mat, AllTime > i & SignalSD < 4)) == 0) return(NULL)
  ROC_Test <- predict(Fit, subset.data.frame(Mat, AllTime > i & SignalSD < 4), type = "prob")
  row.names(ROC_Test) <- row.names(subset.data.frame(Mat, AllTime > i & SignalSD < 4))
  ppm <- melt(as.data.table(ROC_Test, keep.rownames = "ID"), value.name = "Prob", variable.name = "pred")[, .SD[which.max(Prob), ], ID]
  ppm[, Model := paste0("KNN", i)]
  ppm <- merge(ppm, as.data.table(Mat, keep.rownames = "ID")[, .(ID, AllTime, DwellTime, SignalSD, Blockade)], by = "ID")
  return(ppm)
}, mc.cores = 6)

Polypeptide3 <- do.call(rbind, Polypeptide3)
Polypeptide3[, pred := as.character(pred)]
Polypeptide3[, AA := plyr::mapvalues(pred, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
Polypeptide3 <- merge(Polypeptide3, Signal1[, .(ID, TimeRatio)], by = "ID")
Polypeptide3_KNN <- copy(Polypeptide3)
```

```{r fig.width=9, fig.height=4}
ggplot(Polypeptide3_KNN, aes(x = Prob, colour = Model)) + 
  geom_line(stat = "Density") + 
  theme_bw(base_size = 15) + 
  scale_color_brewer(palette = "Dark2") + 
  facet_wrap( ~ Model, nrow = 2)
```

```{r fig.width=15, fig.height=8}
ggplot(Polypeptide3_KNN[Prob > 0.9], aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) +
  facet_wrap( ~ Model) + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none")
```

## CART

```{r}
Models <- list.files("./analysis/03.MachineLearning/Version7/02.Modeling/06.CART/01.Models", "CART_Density_Line_Ony_Fit", full.names = T)
```

```{r}
Polypeptide3 <- mclapply(1:6, function(i) {
  Fit <- readRDS(Models[i])
  if(nrow(subset.data.frame(Mat, AllTime > i & SignalSD < 4)) == 0) return(NULL)
  ROC_Test <- predict(Fit, subset.data.frame(Mat, AllTime > i & SignalSD < 4), type = "prob")
  row.names(ROC_Test) <- row.names(subset.data.frame(Mat, AllTime > i & SignalSD < 4))
  ppm <- melt(as.data.table(ROC_Test, keep.rownames = "ID"), value.name = "Prob", variable.name = "pred")[, .SD[which.max(Prob), ], ID]
  ppm[, Model := paste0("CART", i)]
  ppm <- merge(ppm, as.data.table(Mat, keep.rownames = "ID")[, .(ID, AllTime, DwellTime, SignalSD, Blockade)], by = "ID")
  return(ppm)
}, mc.cores = 6)

Polypeptide3 <- do.call(rbind, Polypeptide3)
Polypeptide3[, pred := as.character(pred)]
Polypeptide3[, AA := plyr::mapvalues(pred, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
Polypeptide3 <- merge(Polypeptide3, Signal1[, .(ID, TimeRatio)], by = "ID")
Polypeptide3_CART <- copy(Polypeptide3)
```

```{r fig.width=9, fig.height=4}
ggplot(Polypeptide3_CART, aes(x = Prob, colour = Model)) + 
  geom_line(stat = "Density") + 
  theme_bw(base_size = 15) + 
  scale_color_brewer(palette = "Dark2") + 
  facet_wrap( ~ Model, nrow = 2)
```

```{r fig.width=15, fig.height=8}
ggplot(Polypeptide3_CART[Prob > 0.7], aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) +
  facet_wrap( ~ Model) + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none")
```

## Shared

```{r}
Polypeptide3_iden <- lapply(1:6, function(i) {
  RF_i <- Polypeptide3_RF[Model == paste0("RF", i), .(ID, Prob, AA)]
  KNN_i <- Polypeptide3_KNN[Model == paste0("KNN", i), .(ID, Prob, AA)]
  CART_i <- Polypeptide3_CART[Model == paste0("CART", i), .(ID, Prob, AA)]
  
  RF_i <- RF_i[Prob >= quantile(Prob, 0.4), .(ID, AA)]
  KNN_i <- KNN_i[Prob >= quantile(Prob, 0.4), .(ID, AA)]
  CART_i <- CART_i[Prob >= quantile(Prob, 0.4), .(ID, AA)]
  setnames(RF_i, "AA", "RF")
  setnames(KNN_i, "AA", "KNN")
  setnames(CART_i, "AA", "CART")
  
  Pred_i <- Reduce(function(x, y) merge(x, y, all = T), list(RF_i, KNN_i, CART_i))
  Pred_i <- Pred_i[rowSums(is.na(Pred_i)) <= 1]
  Pred_i <- na.omit(melt.data.table(Pred_i, id.vars = "ID", value.name = "AA"))[, .N, list(ID, AA)][N > 1]
  merge(Polypeptide3_RF[Model == paste0("RF", i), .(ID, Model, DwellTime, Blockade)], Pred_i, by = "ID")
})
Polypeptide3_iden <- do.call(rbind, Polypeptide3_iden)
Polypeptide3_iden[, Model := gsub("RF", "C", Model)]
setnames(Polypeptide3_iden, "Model", "Cutoff")
```

```{r fig.width=4, fig.height=3}
TargetSignal <- do.call(rbind, lapply(c("H", "F", "L"), function(a) {
  Polypeptide3_iden[, .(AA = a, Percent = mean(AA %in% a) * 100), Cutoff]
}))

ggplot(TargetSignal, aes(x = Cutoff, y = Percent)) + 
  geom_col(aes(fill = AA)) +
  scale_fill_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  geom_text(data = TargetSignal[, sum(Percent), Cutoff], 
            aes(x = Cutoff, y = V1 + 5, label = round(V1, 2))) + 
  theme(legend.position = "none")
ggsave("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide3_Prediction_Accuracy.pdf", width = 4, height = 3)
```

```{r fig.width=15, fig.height=8}
ggplot(Polypeptide3_iden, aes(x = Blockade, y = DwellTime, colour = AA)) + 
  geom_text(aes(label = AA)) + 
  facet_wrap( ~ Cutoff) + 
  scale_color_manual(values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none") + 
  scale_y_sqrt()

ggsave("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide3_Prediction_all_Cutoff.pdf", width = 15, height = 8)
```

```{r}
for(i in 1:6) {
  ggplot(Polypeptide3_iden[Cutoff == paste0("C", i)], aes(x = Blockade, y = DwellTime, colour = AA)) + 
    geom_text(aes(label = AA)) +
    scale_color_manual(values = AA_Cols) + 
    theme_bw(base_size = 15) + 
    theme(legend.position = "none") + 
    scale_y_sqrt() -> p
  ggsave(filename = paste0("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide3_Prediction_", i, "_Cutoff.pdf"), p, width = 5, height = 4)
}
```

```{r}
write.csv(Polypeptide3_iden, "./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide3_Prediction_all_Cutoff.csv")
```



```{r}
Polypeptide1_iden <- fread("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide1_Prediction_all_Cutoff.csv")
Polypeptide2_iden <- fread("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide2_Prediction_all_Cutoff.csv")
Polypeptide3_iden <- fread("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide3_Prediction_all_Cutoff.csv")
```

```{r}
Polypeptide1_iden[, V1 := NULL]
Polypeptide2_iden[, V1 := NULL]
Polypeptide3_iden[, V1 := NULL]
```

```{r}
ZM <- na.omit(as.data.table(read.xlsx("./data/blockade_vs_volume_gauss.xlsx")))
colnames(ZM) <- c("aa", "blockade", "SD", "N", "n", "V")
ZM[, V := as.numeric(V)]
ZM <- ZM[!aa %in% c("P", "C")]
```

```{r}
Polypeptide1_iden[, AA := factor(AA, levels = ZM[order(blockade), aa])]
Polypeptide2_iden[, AA := factor(AA, levels = ZM[order(blockade), aa])]
Polypeptide3_iden[, AA := factor(AA, levels = ZM[order(blockade), aa])]
```

```{r fig.width=6, fig.height=3}
for(i in Polypeptide1_iden[, unique(Cutoff)]) {
  mat <- Polypeptide1_iden[Cutoff == i & N == 3, .N, AA]
  setkey(mat, AA)
  mat <- mat[ZM[order(blockade), aa]]
  mat[is.na(N), N := 0]
  mat[, AA := factor(AA, levels = ZM[order(blockade), aa])]
  ggplot(mat, aes(x = AA, y = N, fill = AA)) + 
    geom_col() + 
    theme_bw(base_size = 15) + 
    scale_fill_manual(values = AA_Cols, guide = "none") + 
    theme(panel.grid = element_blank()) + 
    scale_y_continuous(sec.axis = sec_axis(~ . / sum(mat$N) * 100, name = "predicted percentage")) + 
    labs(x = "name of amino acids", y = "predicted counts") -> p
  ggsave(filename = paste0("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide1_", i, "_frequency.pdf"), 
         plot = p, width = 6, height = 3)
}
```


```{r fig.width=6, fig.height=3}
for(i in Polypeptide2_iden[, unique(Cutoff)]) {
  mat <- Polypeptide2_iden[Cutoff == i & N == 3, .N, AA]
  setkey(mat, AA)
  mat <- mat[ZM[order(blockade), aa]]
  mat[is.na(N), N := 0]
  mat[, AA := factor(AA, levels = ZM[order(blockade), aa])]
  ggplot(mat, aes(x = AA, y = N, fill = AA)) + 
    geom_col() + 
    theme_bw(base_size = 15) + 
    scale_fill_manual(values = AA_Cols, guide = "none") + 
    theme(panel.grid = element_blank()) + 
    scale_y_continuous(sec.axis = sec_axis(~ . / sum(mat$N) * 100, name = "predicted percentage")) + 
    labs(x = "name of amino acids", y = "predicted counts") -> p
  ggsave(filename = paste0("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide2_", i, "_frequency.pdf"), 
         plot = p, width = 6, height = 3)
}
```


```{r fig.width=6, fig.height=3}
for(i in Polypeptide3_iden[, unique(Cutoff)]) {
  mat <- Polypeptide3_iden[Cutoff == i & N == 3, .N, AA]
  setkey(mat, AA)
  mat <- mat[ZM[order(blockade), aa]]
  mat[is.na(N), N := 0]
  mat[, AA := factor(AA, levels = ZM[order(blockade), aa])]
  ggplot(mat, aes(x = AA, y = N, fill = AA)) + 
    geom_col() + 
    theme_bw(base_size = 15) + 
    scale_fill_manual(values = AA_Cols, guide = "none") + 
    theme(panel.grid = element_blank()) + 
    scale_y_continuous(sec.axis = sec_axis(~ . / sum(mat$N) * 100, name = "predicted percentage")) + 
    labs(x = "name of amino acids", y = "predicted counts") -> p
  ggsave(filename = paste0("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide3_", i, "_frequency.pdf"), 
         plot = p, width = 6, height = 3)
}
```

```{r}
Polypeptide1_iden[, polypeptide := "peptide1"]
Polypeptide2_iden[, polypeptide := "peptide2"]
Polypeptide3_iden[, polypeptide := "peptide3"]
Polypeptide_iden <- rbind(Polypeptide1_iden, Polypeptide2_iden, Polypeptide3_iden)
```

```{r}
i <- "C3"

mat1 <- Polypeptide1_iden[Cutoff == i & N == 3, .N, AA]
setkey(mat1, AA)
mat1 <- mat1[ZM[order(blockade), aa]]
mat1[is.na(N), N := 0]
mat1[, AA := factor(AA, levels = ZM[order(blockade), aa])]
ggplot(mat1, aes(x = AA, y = N, fill = AA)) + 
  geom_col() + 
  theme_bw(base_size = 15) + 
  scale_fill_manual(values = AA_Cols, guide = "none") + 
  theme(panel.grid = element_blank()) + 
  scale_y_continuous(sec.axis = sec_axis(~ . / sum(mat1$N) * 100, name = "predicted percentage")) + 
  labs(x = "name of amino acids", y = "predicted counts") -> p1

mat2 <- Polypeptide2_iden[Cutoff == i & N == 3, .N, AA]
setkey(mat2, AA)
mat2 <- mat2[ZM[order(blockade), aa]]
mat2[is.na(N), N := 0]
mat2[, AA := factor(AA, levels = ZM[order(blockade), aa])]
ggplot(mat2, aes(x = AA, y = N, fill = AA)) + 
  geom_col() + 
  theme_bw(base_size = 15) + 
  scale_fill_manual(values = AA_Cols, guide = "none") + 
  theme(panel.grid = element_blank()) + 
  scale_y_continuous(sec.axis = sec_axis(~ . / sum(mat2$N) * 100, name = "predicted percentage")) + 
  labs(x = "name of amino acids", y = "predicted counts") -> p2

mat3 <- Polypeptide3_iden[Cutoff == i & N == 3, .N, AA]
setkey(mat3, AA)
mat3 <- mat3[ZM[order(blockade), aa]]
mat3[is.na(N), N := 0]
mat3[, AA := factor(AA, levels = ZM[order(blockade), aa])]
ggplot(mat3, aes(x = AA, y = N, fill = AA)) + 
  geom_col() + 
  theme_bw(base_size = 15) + 
  scale_fill_manual(values = AA_Cols, guide = "none") + 
  theme(panel.grid = element_blank()) + 
  scale_y_continuous(sec.axis = sec_axis(~ . / sum(mat3$N) * 100, name = "predicted percentage")) + 
  labs(x = "name of amino acids", y = "predicted counts") -> p3

p1 <- p1 + theme(axis.title = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.margin = unit(c(0, 1, 0, 1), "line"))
p2 <- p2 + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.margin = unit(c(0, 1, 0, 1), "line"))
p3 <- p3 + theme(axis.title.y = element_blank(), plot.margin = unit(c(0, 1, 0, 1), "line"))
```

```{r fig.width=6, fig.height=5.8}
plot_grid(p1, p2, p3, ncol = 1, align = "v")
ggsave("./analysis/03.MachineLearning/Version7/03.PredictPolypeptide/03.DensityLineModelPrediction/Polypeptide123_C3_frequency.pdf", width = 6, height = 6)
```










