---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(Biostrings)
library(IRanges)
library(ggplot2)
library(parallel)
library(ggpubr)
library(mclust)
library(patchwork)
library(changepoint)
library(ggExtra)
library(tidyr)

# SignalFiltering <- function(x) {
#   x <- x[DeltaMean < 1 & Valid == TRUE]
#   # x <- x[DwellTime >= with(density(x[, DwellTime], n = 10000, adjust = 1), x[which.max(y)])]
#   x <- x[DwellTime > 0.001]
#   x <- x[StageSD < 3]
#   x <- x[LeftLength >= 50 & RightLength >= 50]
#   x <- x[BaseMean > min(WhiskerRange(x[, BaseMean])) & BaseMean < max(WhiskerRange(x[, BaseMean]))]
#   rk <- rank(x[, DwellTime]) + rank(x[, -1 * StageSD])
#   x[rk > quantile(rk, 0.1)]
# }

# SignalFiltering <- function(x) {
#   x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50 & SignalCurrentPercent == 100]
#   x[!(DwellTime < mean(DwellTime) & StageSD > mean(StageSD))]
# }

SignalFiltering <- function(x) {
  x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
  x[!(DwellTime < 0.003 & StageSD > 2)]
}

SignalCurrent <- function(x, abf, cores = 10) {
  Sigs_Multiple_Current <- mclapply(seq_len(nrow(x)), FUN = function(i) {
    data.table(ID = x[i, ID], Current = abf[Time > x[i, StartTime] & Time < x[i, EndTime], pA] / x[i, BaseMean])
  }, mc.cores = cores)
  do.call(rbind, Sigs_Multiple_Current)
}

densityPeak <- function(x, bw = 1, n = 1024, plot = T, ...) {
  Peaks <- function(x, y) {
    stopifnot(length(x) == length(y))
    uR <- IRanges(diff(y) >= 0)
    dR <- IRanges(diff(y) <= 0)
    res <- do.call(c, lapply(seq_along(uR), function(i) {
      reduce(c(uR[i], dR[i]))
    }))
    pk <- res[queryHits(findOverlaps(res, IRanges(which.max(y), which.max(y))))]
    c(x[start(pk)], x[end(pk)])
  }
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  if(plot) {
    plot(den)
    abline(v = ps, lty = 2, col = 2)
    return(ps)
  } else {
    return(ps)
  }
}
mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x > min(q) & x < max(q)])
}
BaselineSelect <- function(si, AABlockade, a, G = 4, minG = NULL, minlambda = 0.05) {
  if(is.null(minG)) minG <- round(G / 2)
  
  si[, Blockade := 1 - SignalCurrent / BaseMean]
  fit_list <- list()
  rs <- vector()
  den <- density(si[, BaseMean], n = 1024, bw = 1)
  
  k <- G
  fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
  out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
  
  rp <- 1
  while (rp <= 10 & any(out[, sigma] < 0.01)) {
    if(any(out[, sigma] < 0.01)) {
      fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
      out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    }
    rp <- rp + 1
  }
  
  xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
  ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
    plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
  })), 2, which.max)
  
  while (any(duplicated(ys[xs])) & k > minG) {
    k <- k - 1
    fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
    out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    rp <- 1
    while (rp <= 10 & any(out[, sigma] < 0.01)) {
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      rp <- rp + 1
    }
    xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
    ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, which.max)
  }
  k <- G
  
  fit_list[[1]] <- fit
  pred_y <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
    plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
  })), 2, max)
  r <- summary(lm(pred_y ~ den$y))$r.squared
  rs[1] <- r
  
  irt <- 2
  while (r < 0.95 & irt < 50) {
    fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
    out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    rp <- 1
    while (rp <= 10 & any(out[, sigma] < 0.01)) {
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      rp <- rp + 1
    }
    xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
    ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, which.max)
    
    while (any(duplicated(ys[xs])) & k > minG) {
      k <- k - 1
      fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
      out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
      ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
        plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
      })), 2, which.max)
    }
    k <- G
    
    fit_list[[irt]] <- fit
    pred_y <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, max)
    r <- summary(lm(pred_y ~ den$y))$r.squared
    rs[irt] <- r
    irt <- irt + 1
  }
  
  fit <- fit_list[[which.max(rs)]]
  out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
  
  out$BaselineGroup <- paste0("G", seq_len(nrow(out)))
  out <- out[sigma > 2 | lambda < minlambda, BaselineGroup := NA]
  
  si$BaselineGroup <- paste0("G", apply(fit$posterior, 1, which.max))
  majorG <- si[BaselineGroup %in% out[!is.na(BaselineGroup), BaselineGroup], .(mean2(Blockade)), BaselineGroup][which.min(abs(V1 - AABlockade[amino_acid == a, Blockade])), BaselineGroup]
  si[BaselineGroup == majorG, BaselineGroup := "G0"]
  
  attr(si, "out") <- out
  attr(si, "majorG") <- majorG
  return(si)
}

BaselinePlot <- function(si) {
  out <- attr(si, "out")
  majorG <- attr(si, "majorG")
  
  out1 <- out[BaselineGroup == majorG]
  out2 <- out[BaselineGroup != majorG | is.na(BaselineGroup)]
  ggplot(si, aes(x = BaseMean)) + 
    geom_histogram(data = si, aes(x = BaseMean, y = after_stat(density)), fill = "grey", binwidth = .2) +
    # geom_density() + 
    theme_bw(base_size = 15) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out1[1, mu], out1[1, sigma], lam = out1[1, lambda]), colour = 2, lwd = 1, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[1, mu], out2[1, sigma], lam = out2[1, lambda]), colour = 1, lwd = .5, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[2, mu], out2[2, sigma], lam = out2[2, lambda]), colour = 1, lwd = .5, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[3, mu], out2[3, sigma], lam = out2[3, lambda]), colour = 1, lwd = .5, n = 2000) + 
    labs(title = si[, unique(file_name)])
}

plot_mix_comps <- function(x, mu, sigma, lam) {
  lam * dnorm(x, mu, sigma)
}
```

```{r}
setwd("/mnt/raid61/Personal_data/tangchao/AANanopore")
library(data.table)
library(ggplot2)
library(Biostrings)
```

```{r}
AABlockade <- data.table(AA = c("A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"), 
                         Blockade = c(0.14718, 0.17148, 0.16516, 0.21409, 0.18622, 0.24528, 0.1882, 0.12072, 0.24652, 0.20722, 0.1995, 0.16875, 0.19772, 0.22018, 0.2183, 0.13131, 0.16101, 0.22744, 0.21276, 0.19044))
AABlockade$amino_acid <- plyr::mapvalues(AABlockade$AA, names(Biostrings::AMINO_ACID_CODE), Biostrings::AMINO_ACID_CODE)
```

```{r}
meta0 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 1, cols = 8:14))
meta1 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 1, cols = 15:21))
meta2 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 2, cols = 1:7))
meta3 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 3, cols = 1:7))
meta4 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 4, cols = 1:7))
meta <- rbind(meta0, meta1, meta2, meta3, meta4, use.names = FALSE)
colnames(meta) <- c("file_name", "date", "amino_acid", "concentration", "start_time", "end_time", "type")
meta <- meta[!is.na(file_name)]
meta[amino_acid == "cys", amino_acid := "Cys"]
meta <- meta[amino_acid %in% Biostrings::AMINO_ACID_CODE]
meta <- meta[concentration != 0]
meta$file_path <- mapply(meta$file_name, FUN = function(x) list.files("./data", recursive = TRUE, full.names = TRUE, pattern = as.character(x))[1])
meta <- meta[!is.na(file_path)]
meta[, start_time := as.numeric(start_time)]
meta[, end_time := as.numeric(end_time)]
meta <- meta[file_name %in% gsub("RawSignal_", "", gsub(".txt", "", list.files("./analysis/11.SignalIdentification/Dec27", "RawSignal_")))]
meta <- meta[!grepl(".abf$", file_name)]
```

```{r}
meta_Val <- rbind(data.table(openxlsx::read.xlsx("./data/meta_info_and_base_line_20210525.xlsx")), data.table(openxlsx::read.xlsx("./data/meta_info_and_base_line_20210525additional.xlsx")))[amino_acid == "Val"]
meta_Val$file_path <- mapply(meta_Val$file_name, FUN = function(x) list.files("./data", recursive = TRUE, full.names = TRUE, pattern = as.character(x))[1])
meta_Val[, L1min := NULL]
meta_Val[, L1max := NULL]
meta <- rbind(meta, meta_Val)
```

# Glu

```{r}
meta[, unique(amino_acid)]
A <- "Glu"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Asp

```{r}
meta[, unique(amino_acid)]
A <- "Asp"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Arg

```{r}
meta[, unique(amino_acid)]
A <- "Arg"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Lys

```{r}
meta[, unique(amino_acid)]
A <- "Lys"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 8, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 6]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 8]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup %in% 2:3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 7, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 7]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# His

```{r}
meta[, unique(amino_acid)]
A <- "His"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 30, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r eval=FALSE}
ggplot(Sig3[BaselineGroup == "G0" & MajorBlockadeGroup %in% c(24, 30)], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) 
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 24]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 30]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup %in% 1:4]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 30, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r eval=FALSE}
ggplot(Sig3[BaselineGroup == "G0" & MajorBlockadeGroup %in% c(24, 30)], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) 
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 24]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 30]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup %in% ]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Phe

```{r}
meta[, unique(amino_acid)]
A <- "Phe"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Trp

```{r}
meta[, unique(amino_acid)]
A <- "Trp"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Tyr

```{r}
meta[, unique(amino_acid)]
A <- "Tyr"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Ile

```{r}
meta[, unique(amino_acid)]
A <- "Ile"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Met

```{r}
meta[, unique(amino_acid)]
A <- "Met"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Thr

```{r}
meta[, unique(amino_acid)]
A <- "Thr"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 2, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Ser

```{r}
meta[, unique(amino_acid)]
A <- "Ser"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 3, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 2]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 3, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 2]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Leu

```{r}
meta[, unique(amino_acid)]
A <- "Leu"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 7, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup %in% 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 7, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup %in% 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Ala

```{r}
meta[, unique(amino_acid)]
A <- "Ala"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 6, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup %in% 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 5]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 8, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup %in% 4]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Gly

```{r}
meta[, unique(amino_acid)]
A <- "Gly"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 3, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 1]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 2]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup %in% 3]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 3, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 1]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 2]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup %in% 4]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Pro

```{r}
meta[, unique(amino_acid)]
A <- "Pro"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 30, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r eval=FALSE}
ggplot(Sig3[BaselineGroup == "G0" & MajorBlockadeGroup %in% c(25:29)], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) 
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 27]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup %in% 28:30]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup %in% 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 30, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r eval=FALSE}
ggplot(Sig4[BaselineGroup == "G0" & MajorBlockadeGroup %in% c(25:29)], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) 
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 27]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup %in% 28:30]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 4, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup %in% 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1[DwellTime > 0.002], Sig_L2[DwellTime > 0.002]), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1[DwellTime > 0.002]), ", L2: ", nrow(Sig_L2[DwellTime > 0.002])))
```

```{r}
fwrite(Sig_L1[DwellTime > 0.002], paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2[DwellTime > 0.002], paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Gln

```{r}
meta[, unique(amino_acid)]
A <- "Gln"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Asn

```{r}
meta[, unique(amino_acid)]
A <- "Asn"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Cys

```{r}
meta[, unique(amino_acid)]
A <- "Cys"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
Sig2 <- Sig2[DwellTime > 0.00035]
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
ggMarginal(p1, adjust = .1, margins = "x")
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 4, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 5, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 5, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 3]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```


# Val

```{r}
meta[, unique(amino_acid)]
A <- "Val"
```

```{r}
Sig0 <- lapply(meta[amino_acid == A, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread(paste0("./analysis/12.SignalFiltering/Dec28/Filter2/", A, "_Signal1.txt"))
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
```

```{r}
Sig2[, Blockade := 1 - SignalCurrent / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig3 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig3[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L1 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig3_L2 <- Sig3[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig3_L2[, MajorBlockadeGroup := NULL]
Sig3_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig3_L2[, .(Blockade)], 3, verbose = F)
Sig3_L2 <- merge(Sig3_L2, with(mb3, data.table(ID = Sig3_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig3_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig3_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig3_L2 <- Sig3_L2[MajorBlockadeGroup == 2]
Sig3_L2[, BaselineGroup := "L2"]
```


```{r}
Sig2[, Blockade := 1 - SignalCurrent.5 / BaseMean]
mb3 <- Mclust(Sig2[BaselineGroup == "G0", .(Blockade)], 4, verbose = F)
Sig4 <- merge(Sig2, with(mb3, data.table(ID = Sig2[BaselineGroup == "G0", ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)
ggplot(Sig4[BaselineGroup == "G0"], aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = .1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4[BaselineGroup == "G0", .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L1 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 3]
Sig4_L2 <- Sig4[BaselineGroup == "G0" & MajorBlockadeGroup == 4]
Sig4_L2[, MajorBlockadeGroup := NULL]
Sig4_L1[, BaselineGroup := "L1"]
```

```{r}
mb3 <- Mclust(Sig4_L2[, .(Blockade)], 3, verbose = F)
Sig4_L2 <- merge(Sig4_L2, with(mb3, data.table(ID = Sig4_L2[, ID], MajorBlockadeGroup = as.character(classification))), by = "ID", all.x = T)

ggplot(Sig4_L2, aes(y = DwellTime * 1000, x = Blockade, colour = MajorBlockadeGroup)) + 
  geom_point(size = 1) + 
  # lims(x = c(.1, .3)) +
  geom_hline(yintercept = 1.5) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  guides(colour = guide_legend(override.aes = list(size = 1))) + 
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": ", Sig4_L2[, .N], " (Right L0)")) -> p1
p1
```

```{r}
Sig4_L2 <- Sig4_L2[MajorBlockadeGroup == 2]
Sig4_L2[, BaselineGroup := "L2"]
```

```{r}
Sig_L1 <- Sig2[ID %in% union(Sig3_L1[, ID], Sig4_L1[, ID])]
Sig_L2 <- Sig2[ID %in% union(Sig3_L2[, ID], Sig4_L2[, ID])]
```

```{r}
ggplot(rbind(Sig_L1, Sig_L2), aes(y = DwellTime * 1000, x = Blockade, colour = file_name)) + 
  geom_jitter(size = .1, height = 0, width = 0) + 
  lims(x = c(.1, .6)) +
  scale_y_log10() + 
  theme_bw(base_size = 15) +
  # facet_wrap(~ Group, scales = "free_y") +
  theme(legend.position = "none") +
  labs(y = "Dwell time (ms)", x = "Blockade", title = paste0(A, ": L1: ", nrow(Sig_L1), ", L2: ", nrow(Sig_L2)))
```

```{r}
fwrite(Sig_L1, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L1.txt"), sep = "\t", quote = F, row.names = F)
fwrite(Sig_L2, paste0("./analysis/12.SignalFiltering/Jan07/Filter2/", A, "_Signal1_Mainly_L2.txt"), sep = "\t", quote = F, row.names = F)
```

