---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(Biostrings)
library(IRanges)
library(ggplot2)
library(parallel)
library(ggpubr)
library(mclust)
library(patchwork)
library(changepoint)
library(ggExtra)
library(tidyr)

# SignalFiltering <- function(x) {
#   x <- x[DeltaMean < 1 & Valid == TRUE]
#   # x <- x[DwellTime >= with(density(x[, DwellTime], n = 10000, adjust = 1), x[which.max(y)])]
#   x <- x[DwellTime > 0.001]
#   x <- x[StageSD < 3]
#   x <- x[LeftLength >= 50 & RightLength >= 50]
#   x <- x[BaseMean > min(WhiskerRange(x[, BaseMean])) & BaseMean < max(WhiskerRange(x[, BaseMean]))]
#   rk <- rank(x[, DwellTime]) + rank(x[, -1 * StageSD])
#   x[rk > quantile(rk, 0.1)]
# }

# SignalFiltering <- function(x) {
#   x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50 & SignalCurrentPercent == 100]
#   x[!(DwellTime < mean(DwellTime) & StageSD > mean(StageSD))]
# }

SignalFiltering <- function(x) {
  x <- x[Valid == TRUE & DeltaMean < 0.5 & BaseMean > 100 & SignalCurrent > 50]
  x[!(DwellTime < 0.003 & StageSD > 2)]
}

SignalCurrent <- function(x, abf, cores = 10) {
  Sigs_Multiple_Current <- mclapply(seq_len(nrow(x)), FUN = function(i) {
    data.table(ID = x[i, ID], Current = abf[Time > x[i, StartTime] & Time < x[i, EndTime], pA] / x[i, BaseMean])
  }, mc.cores = cores)
  do.call(rbind, Sigs_Multiple_Current)
}

densityPeak <- function(x, bw = 1, n = 1024, plot = T, ...) {
  Peaks <- function(x, y) {
    stopifnot(length(x) == length(y))
    uR <- IRanges(diff(y) >= 0)
    dR <- IRanges(diff(y) <= 0)
    res <- do.call(c, lapply(seq_along(uR), function(i) {
      reduce(c(uR[i], dR[i]))
    }))
    pk <- res[queryHits(findOverlaps(res, IRanges(which.max(y), which.max(y))))]
    c(x[start(pk)], x[end(pk)])
  }
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  if(plot) {
    plot(den)
    abline(v = ps, lty = 2, col = 2)
    return(ps)
  } else {
    return(ps)
  }
}
mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x > min(q) & x < max(q)])
}
BaselineSelect <- function(si, AABlockade, a, G = 4, minG = NULL, minlambda = 0.05) {
  if(is.null(minG)) minG <- round(G / 2)
  
  si[, Blockade := 1 - SignalCurrent / BaseMean]
  fit_list <- list()
  rs <- vector()
  den <- density(si[, BaseMean], n = 1024, bw = 1)
  
  k <- G
  fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
  out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
  
  rp <- 1
  while (rp <= 10 & any(out[, sigma] < 0.01)) {
    if(any(out[, sigma] < 0.01)) {
      fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
      out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    }
    rp <- rp + 1
  }
  
  xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
  ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
    plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
  })), 2, which.max)
  
  while (any(duplicated(ys[xs])) & k > minG) {
    k <- k - 1
    fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
    out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    rp <- 1
    while (rp <= 10 & any(out[, sigma] < 0.01)) {
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      rp <- rp + 1
    }
    xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
    ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, which.max)
  }
  k <- G
  
  fit_list[[1]] <- fit
  pred_y <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
    plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
  })), 2, max)
  r <- summary(lm(pred_y ~ den$y))$r.squared
  rs[1] <- r
  
  irt <- 2
  while (r < 0.95 & irt < 50) {
    fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
    out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
    rp <- 1
    while (rp <= 10 & any(out[, sigma] < 0.01)) {
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      rp <- rp + 1
    }
    xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
    ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, which.max)
    
    while (any(duplicated(ys[xs])) & k > minG) {
      k <- k - 1
      fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
      out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      if(any(out[, sigma] < 0.01)) {
        fit <- mixtools::normalmixEM(x = si[, BaseMean], fast = TRUE, k = k, arbmean = TRUE, arbvar = TRUE)
        out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
      }
      xs <- mapply(seq_len(nrow(out)), FUN = function(i) which.max(plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])))
      ys <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
        plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
      })), 2, which.max)
    }
    k <- G
    
    fit_list[[irt]] <- fit
    pred_y <- apply(do.call(rbind, lapply(seq_len(nrow(out)), function(i) {
      plot_mix_comps(den$x, mu = out[i, mu], sigma = out[i, sigma], lam = out[i, lambda])
    })), 2, max)
    r <- summary(lm(pred_y ~ den$y))$r.squared
    rs[irt] <- r
    irt <- irt + 1
  }
  
  fit <- fit_list[[which.max(rs)]]
  out <- with(fit, data.table(mu = mu, lambda = lambda, sigma = sigma))
  
  out$BaselineGroup <- paste0("G", seq_len(nrow(out)))
  out <- out[sigma > 2 | lambda < minlambda, BaselineGroup := NA]
  
  si$BaselineGroup <- paste0("G", apply(fit$posterior, 1, which.max))
  majorG <- si[BaselineGroup %in% out[!is.na(BaselineGroup), BaselineGroup], .(mean2(Blockade)), BaselineGroup][which.min(abs(V1 - AABlockade[amino_acid == a, Blockade])), BaselineGroup]
  si[BaselineGroup == majorG, BaselineGroup := "G0"]
  
  attr(si, "out") <- out
  attr(si, "majorG") <- majorG
  return(si)
}

BaselinePlot <- function(si) {
  out <- attr(si, "out")
  majorG <- attr(si, "majorG")
  
  out1 <- out[BaselineGroup == majorG]
  out2 <- out[BaselineGroup != majorG | is.na(BaselineGroup)]
  ggplot(si, aes(x = BaseMean)) + 
    geom_histogram(data = si, aes(x = BaseMean, y = after_stat(density)), fill = "grey", binwidth = .2) +
    # geom_density() + 
    theme_bw(base_size = 15) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out1[1, mu], out1[1, sigma], lam = out1[1, lambda]), colour = 2, lwd = 1, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[1, mu], out2[1, sigma], lam = out2[1, lambda]), colour = 1, lwd = .5, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[2, mu], out2[2, sigma], lam = out2[2, lambda]), colour = 1, lwd = .5, n = 2000) + 
    stat_function(geom = "line", fun = plot_mix_comps, args = list(out2[3, mu], out2[3, sigma], lam = out2[3, lambda]), colour = 1, lwd = .5, n = 2000) + 
    labs(title = si[, unique(file_name)])
}

plot_mix_comps <- function(x, mu, sigma, lam) {
  lam * dnorm(x, mu, sigma)
}
```

```{r}
setwd("/mnt/raid61/Personal_data/tangchao/AANanopore")
library(data.table)
library(ggplot2)
library(Biostrings)
```

```{r}
AABlockade <- data.table(AA = c("A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"), 
                         Blockade = c(0.14718, 0.17148, 0.16516, 0.21409, 0.18622, 0.24528, 0.1882, 0.12072, 0.24652, 0.20722, 0.1995, 0.16875, 0.19772, 0.22018, 0.2183, 0.13131, 0.16101, 0.22744, 0.21276, 0.19044))
AABlockade$amino_acid <- plyr::mapvalues(AABlockade$AA, names(Biostrings::AMINO_ACID_CODE), Biostrings::AMINO_ACID_CODE)
```

```{r}
meta1 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 1, cols = 1:7))
meta2 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 2, cols = 1:7))
meta3 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 3, cols = 1:7))
meta4 <- data.table(openxlsx::read.xlsx("./data/单氨基酸实验信息表20210517.xlsx", sheet = 4, cols = 1:7))
meta <- rbind(meta1, meta2, meta3, meta4, use.names = FALSE)
colnames(meta) <- c("file_name", "date", "amino_acid", "concentration", "start_time", "end_time", "type")
meta[amino_acid == "cys", amino_acid := "Cys"]
meta <- meta[amino_acid %in% Biostrings::AMINO_ACID_CODE]
meta <- meta[concentration == 0]
meta$file_path <- mapply(meta$file_name, FUN = function(x) list.files("./data", recursive = TRUE, full.names = TRUE, pattern = as.character(x))[1])
meta <- meta[!is.na(file_path)]
meta[, start_time := as.numeric(start_time)]
meta[, end_time := as.numeric(end_time)]
meta <- meta[!grepl("abf$", file_name)]
```

```{r}
Sig0 <- lapply(meta[, file_name], function(x) {
  data.table(file_name = as.character(x), fread(paste0("./analysis/11.SignalIdentification/Jan07/RawSignal_", x, ".txt")))
})
Sig0 <- Sig0[mapply(nrow, Sig0) > 0]
Sig0 <- do.call(rbind, Sig0)
```

```{r}
Sig2 <- fread("./analysis/12.SignalFiltering/Dec28/Filter2/Blank_Signal.txt")
Sig2 <- merge(Sig0, Sig2[, .(ID, BaselineGroup)], by = c("ID"))
Sig2[, file_name := as.character(file_name)]
Sig2 <- merge(Sig2, meta[, .(file_name, amino_acid)], by = "file_name")
```

```{r}
fwrite(Sig2, "./analysis/12.SignalFiltering/Jan07/Filter2/Blank_Signal.txt", sep = "\t", row.names = FALSE)
```

