---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(cowplot)
library(parallel)
library(caret)
```

# Model Training

```{r}
load(file = "./analysis/03.MachineLearning/01.data/Version6/AAInfo_RawSig.RData")
AAInfo[, aa := plyr::mapvalues(amino_acid, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
AAInfo$AllTime <- mcmapply(AAInfo$ID, FUN = function(x) {
  RawSig[ID == x, diff(range(Time))] * 1000
}, mc.cores = 10)

AAInfo$Blockade2 <- mcmapply(AAInfo$ID, FUN = function(x) {
  den <- RawSig[ID == x, density(pA)]
  1 - with(den, x[which.max(y)])
}, mc.cores = 10)
```


```{r}
Mat <- readRDS("./analysis/03.MachineLearning/Version8/01.DataPreparation/All_Transformed_data.Rds")
```

```{r}
# Mat <- Mat[!aa %in% c("C", "P")]
Mat[, aa := as.character(aa)]
Mat[, aa := as.factor(aa)]
```

```{r}
lapply(1:6, function(i) {
  Mat <- Mat[AllTime > i & SignalSD < 4]
  Mat[, DwellTime := NULL]
  Mat[, SignalSD := NULL]
  AAInfoi <- AAInfo[ID %in% Mat[, ID]]
  
  Vali_Set <- AAInfoi[, .N, by = c("amino_acid", "file_name")][N > 20, .SD[which.min(N)], amino_acid]
  Vali_Set <- merge(Vali_Set[, .(amino_acid, file_name)], AAInfoi, by = c("amino_acid", "file_name"))
  
  Valid <- Mat[ID %in% Vali_Set$ID]
  Mat <- Mat[!ID %in% Vali_Set$ID]
  Valid[, ID := NULL]
  
  set.seed(3456)
  up_Mat <- upSample(x = Mat, y = Mat$aa)
  up_Mat <- as.data.table(up_Mat)
  
  Train <- up_Mat[, .SD[sample(.N, round(up_Mat[, .N, aa][, min(N)]*0.8)), ], aa]
  Test <- up_Mat[!ID %in% Train$ID]
  
  Train[, ID := NULL]
  Train[, Class := NULL]
  Train <- data.frame(Train[, -c(1)], Class = Train[[1]])
  
  set.seed(9560)
  up_Test <- upSample(x = Test[, !colnames(Test) %in% c("ID", "aa", "Class"), with = F],
                      y = Test$aa)                         
  
  set.seed(9560)
  up_Valid <- upSample(x = Valid[, !colnames(Valid) %in% c("ID", "aa"), with = F],
                       y = Valid$aa)
  
  save(Train, Test, up_Test, Valid, up_Valid, file = paste0("./analysis/03.MachineLearning/Version10/01.DataPreparation/Modeling_Data_", i, ".RData"))
  save(Train, file = paste0("./analysis/03.MachineLearning/Version10/01.DataPreparation/Train_Data_", i, ".RData"))
})
```

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10)

library(doParallel)
cl <- makePSOCKcluster(5)
registerDoParallel(cl)
```

# RF

```{r}
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version10/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  RFC <- train(Class ~ ., data = Train, 
                preProc = c("center", "scale", "YeoJohnson", "nzv"),
                method = "rf", 
                trControl = fitControl,
                verbose = FALSE,
                ## to evaluate:
                tuneGrid = expand.grid(mtry = 60),
                # tuneLength = 50,
                metric = "Accuracy", 
                allowParallel = TRUE)
  saveRDS(RFC, file = paste0("./analysis/03.MachineLearning/Version10/02.Modeling/01.RF/01.Models/RF_Fit", i, ".Rds"))
})
stopCluster(cl)
```


# Performance

```{r}
RF8 <- readRDS("./analysis/03.MachineLearning/Version8/02.Modeling/01.RF/01.Models/RF_Fit1.Rds")
```

```{r}
Mds <- list.files("./analysis/03.MachineLearning/Version9/02.Modeling/01.RF/01.Models", full.names = T)
```














