---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
# knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(parallel)
library(cowplot)
library(S4Vectors)
library(caret)
```

```{r}
mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x >= min(q) & x <= max(q)])
}

plotSig <- function(x, title = NULL) {
  ggplot() +
    geom_line(data = x, mapping = aes(x = Time, y = pA), size = 1) +
    theme_bw(base_size = 15) +
    labs(title = title) + 
    lims(y = c(0, 1)) + 
    scale_x_continuous(n.breaks = 2, labels = NULL) + 
    theme(axis.ticks.x = element_blank()) + 
    labs(y = "Scaled current")
}

plotSig2 <- function(x, title = NULL) {
  ggplot() +
    geom_line(data = x, mapping = aes(x = Time, y = pA), size = 1) +
    theme_bw(base_size = 15) +
    labs(title = title) + 
    scale_x_continuous(n.breaks = 2, labels = NULL) + 
    labs(y = "Current (pA)")
}
```

```{r}
load("./analysis/03.MachineLearning/01.data/Version6/AAInfo_RawSig.RData")
```

```{r}
AAInfo <- AAInfo[!amino_acid %in% c("Cys", "Pro")]
AAInfo$AllTime <- mcmapply(AAInfo$ID, FUN = function(x) {
  RawSig[ID == x, diff(range(Time))] * 1000
}, mc.cores = 20)
```

```{r}
ids <- AAInfo[AllTime > 5 & DwellTime > 2 & AreaRatio_L2 > 0.2, ID]
```

```{r}
plotSig(RawSig[ID == ids[4230]])
```

```{r}
AAInfo[ID == ids[4230]]
```



```{r}
files <- list.files("./analysis/01.AASignalRecognition/Version9/03.BUBSignal", pattern = "21319002", recursive = TRUE, full.names = T)
BUBs <- readRDS(files)
names(BUBs) <- paste0("21319002", "_", sprintf("%05d", seq_along(BUBs)))
```

```{r}
mat2 <- BUBs[["21319002_01577"]]
Rle(mat2[, L == "B"])
mat2 <- mat2[1900:2900, ]
```

```{r fig.width=2.8, fig.height=2.5}
p1 <- plotSig2(mat2)
p1
```

```{r}
mat1 <- RawSig[ID == ids[4230]]
```

```{r fig.width=2.8, fig.height=2.5}
p2 <- plotSig(mat1)
p2
```

```{r fig.width=2.8, fig.height=2.5}
denL <- mat1[, density(pA, from = 0, to = 1, n = 200, adjust = 0.5)]
denL <- with(denL, data.table(x, y))

p3 <- ggplot(denL, aes(x, y)) + 
  geom_line(size = 1) +
  geom_point(size = 1.2) +
  theme_bw(base_size = 15) +
  labs(y = "Density", x = "Scaled current") + 
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank()) + 
  coord_flip() + 
  lims(y = c(0, 20)) + 
  annotate(geom = "text", x = c(0, 0.5, 1), y = 17.5, label = c("X001", "...", "X200"), color = "red")
p3
```


```{r fig.height=3, fig.width=7}
p1 + p2 + p3
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/FeatureExtraction.pdf", width = 8, height = 3.5)
```


```{r}
RF1 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Density_Line_Ony_Fit1.Rds")
RF2 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Density_Line_Ony_Fit2.Rds")
RF3 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Density_Line_Ony_Fit3.Rds")
RF4 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Density_Line_Ony_Fit4.Rds")
RF5 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Density_Line_Ony_Fit5.Rds")
RF6 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Density_Line_Ony_Fit6.Rds")

vImp <- varImp(RF1, scale = TRUE)
vImp1 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))
vImp <- varImp(RF2, scale = TRUE)
vImp2 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))
vImp <- varImp(RF3, scale = TRUE)
vImp3 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))
vImp <- varImp(RF4, scale = TRUE)
vImp4 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))
vImp <- varImp(RF5, scale = TRUE)
vImp5 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))
vImp <- varImp(RF6, scale = TRUE)
vImp6 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance), x = as.numeric(gsub("X", "", row.names(vImp$importance))))

vImp <- cbind(vImp1[, .(Importance)], vImp2[, .(Importance)], vImp3[, .(Importance)], vImp4[, .(Importance)], vImp5[, .(Importance)], vImp6[, .(Importance)])

denL$importance <- rowMeans(vImp)
```


```{r fig.width=3.5, fig.height=3.5}
ggplot() + 
  geom_line(data = denL, aes(x, y, colour = importance), size = 1) +
  geom_point(data = denL[order(importance)], aes(x, y, colour = importance), size = 1.2) +
  theme_bw(base_size = 15) +
  labs(y = "Density", x = "Scaled current") + 
  theme(axis.ticks.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "top") + 
  coord_flip() + 
  scale_colour_gradient(low = "#FFF5F0", high = "#67000D")
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/FeatureImportance.pdf", width = 3.5, height = 3.5)
```

```{r fig.width=3.5, fig.height=3.5}
ggplot() + 
  geom_line(data = denL, aes(x, y, colour = importance), size = 1) +
  geom_point(data = denL[order(importance)], aes(x, y, colour = importance), size = 1.2) +
  theme_bw(base_size = 15) +
  labs(y = "Density", x = "Scaled current") + 
  theme(axis.ticks.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "none") + 
  coord_flip() + 
  scale_colour_gradient(low = "#FFF5F0", high = "#67000D")
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/FeatureImportance2.pdf", width = 3.5, height = 3.5)
```


```{r fig.width=3.5, fig.height=3.5}
ggplot() + 
  geom_line(data = denL, aes(x, y, colour = importance), size = 1) +
  geom_point(data = denL[order(importance)], aes(x, y, colour = importance), size = 1.2) +
  theme_bw(base_size = 15) +
  labs(y = "Density", x = "Scaled current") + 
  theme(axis.ticks.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "right", legend.title = element_text(angle = 270)) + 
  coord_flip() + 
  scale_colour_gradient(low = "#FFF5F0", high = "#67000D")
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/FeatureImportance3.pdf", width = 3.5, height = 3.5)
```


```{r}
Preds <- readRDS(file = "analysis/03.MachineLearning/Version7/02.Modeling/01.RF/02.CompareModels/Preds.Rds")
```

```{r}
cM <- Preds[[4]][Dataset == "ValidationUp" & Prob > 0.7, confusionMatrix(pred, true)]
cM <- as.matrix(cM$table)
cM <- reshape2::dcast(as.data.frame(cM), Prediction ~ Reference)
cM <- data.frame(cM[, -1], row.names = cM[, 1])
cM <- apply(cM, 2, prop.table)*100
row.names(cM) <- plyr::mapvalues(row.names(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
colnames(cM) <- plyr::mapvalues(colnames(cM), AMINO_ACID_CODE, names(AMINO_ACID_CODE))

ggplot(data = reshape2::melt(as.matrix(cM)), aes(x = Var1, y = Var2, fill = value)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#FFF5F0", high = "#67000D") +
  theme_bw(base_size = 15) + 
  theme(legend.title = element_blank(), plot.margin = unit(c(0.25, 0, 0, 0), "lines")) + 
  labs(x = "Prediction", y = "Reference") -> p1

ggplot(data.table(A = factor(rownames(cM), levels = rownames(cM)), Percent = rowSums(cM)), aes(x = A, y = Percent)) +
  geom_col(fill = "#A50F15") +
  theme_bw(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "lines")) -> p2
```

```{r fig.width=5.5, fig.height=5.5}
p2 / p1 + plot_layout(heights = c(2, 8))
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix.pdf", width = 7, height = 7)
```


```{r}
cMList <- lapply(Preds, function(x) {
  do.call(rbind, lapply(c("Test", "TestUp", "Validation", "ValidationUp"), function(d) {
    data.table(Model = x[, unique(Model)], DataSet = d, as.data.table(x[Dataset == d, confusionMatrix(pred, true)]$byClass))
  }))
})
cMList <- do.call(rbind, cMList)
cMList[, Model := gsub("Fit", "RF", Model)]
```

```{r fig.width=5, fig.height=3}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Sensitivity, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15)
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_Sensitivity.pdf", width = 5, height = 3)

ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Specificity, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15)
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_Specificity.pdf", width = 5, height = 3)

ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = F1, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15)
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_F1.pdf", width = 5, height = 3)

ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Precision, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15)
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_Precision.pdf", width = 5, height = 3)

ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Recall, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15)
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_Recall.pdf", width = 5, height = 3)
```


```{r fig.width=10, fig.height=4}
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Sensitivity, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(legend.position = "top") -> p1
lg <- as_ggplot(get_legend(p1))
p1 <- p1 + theme(legend.position = "none")

ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = Specificity, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(legend.position = "none") -> p2
ggplot(cMList[DataSet %in% c("Test", "Validation")], aes(x = Model, y = F1, colour = DataSet)) + 
  geom_boxplot(outlier.shape = NA) +
  theme_bw(base_size = 15) + 
  theme(legend.position = "none") -> p3

lg / (p1 + p2 + p3) + plot_layout(heights = c(1, 9))
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_Boxplot.pdf", width = 10, height = 4)
```


```{r fig.width=7, fig.height=4}
lg / (p1 + p2) + plot_layout(heights = c(1, 9))
ggsave("./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/confusionMatrix_Boxplot2.pdf", width = 8, height = 3.5)
```


```{r}
library(caret)
library(data.table)
library(openxlsx)
RF1 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Fit1.Rds")
RF2 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Fit2.Rds")
RF3 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Fit3.Rds")
RF4 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Fit4.Rds")
RF5 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Fit5.Rds")
RF6 <- readRDS("./analysis/03.MachineLearning/Version7/02.Modeling/01.RF/01.Models/RF_Fit6.Rds")

vImp <- varImp(RF1, scale = TRUE)
vImp1 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))
vImp <- varImp(RF2, scale = TRUE)
vImp2 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))
vImp <- varImp(RF3, scale = TRUE)
vImp3 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))
vImp <- varImp(RF4, scale = TRUE)
vImp4 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))
vImp <- varImp(RF5, scale = TRUE)
vImp5 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))
vImp <- varImp(RF6, scale = TRUE)
vImp6 <- data.table(Importance = vImp$importance[, 1], Variable = row.names(vImp$importance))

vImp <- cbind(vImp1[, .(Variable, Importance)], vImp2[, .(Importance)], vImp3[, .(Importance)], vImp4[, .(Importance)], vImp5[, .(Importance)], vImp6[, .(Importance)])
colnames(vImp)[2:7] <- paste0("RF", 1:6)
write.xlsx(vImp, "./analysis/03.MachineLearning/Version7/02.Modeling/11.ModelingFigure/RF_importance.xlsx")
```

