---
title: "Figure 2"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
```

# Signal example

```{r}
files <- list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals", full.names = T)
sig0 <- mclapply(files, fread)
sig0 <- data.table(A = rep(gsub(".signal.txt", "", basename(files)), mapply(nrow, sig0)), do.call(rbind, sig0))
```

```{r}
T0 <- as.data.table(openxlsx::read.xlsx("./script/00.FigureTables/Rebuttal/NatureMethods/Fig2/d.xlsx", 2))
```

```{r}
set.seed(12345)
sigi <- rbind(sig0[State == "Sington" & DwellTime > 1 & SignalCurrentPercent > 80, .SD[which.min(CurrentSD)], .(A, State)], 
              sig0[State == "Mixtrue" & DwellTime > 1, .SD[which.min(StageSD)], .(A, State)])
```

```{r}
sigi <- lapply(T0$A, function(aat) {
  if(aat %in% c("Cys", "Tyr")) {
    sig0[DeltaMean < .2 & A == aat & State == "Sington" & SignalCurrentPercent > 98][which.min(CurrentSD)]
  } else {
      if(aat == "His1") {
    sig0[DeltaMean < .2 & A == aat & State == "Sington" & SignalCurrentPercent > 80 & DwellTime > 10 & DwellTime < 20][which.min(CurrentSD)]
  } else {
    sig0[DeltaMean < .2 & A == aat & State == "Sington" & SignalCurrentPercent > 80 & DwellTime > T0[A == aat, half.life - 1] & DwellTime < T0[A == aat, half.life + 1]][which.min(CurrentSD)]
  }
  }
})
sigi <- do.call(rbind, sigi)
```


```{r}
sigi_abf <- mclapply(seq_len(nrow(sigi)), function(i) {
  abf <- readRDS(sigi[i, paste0("./analysis/81.ABFProcessing/ABF/ABF_", File, ".Rds")])
  abf <- abf[Time > sigi[i, StartTime] - 0.001 & Time < sigi[i, EndTime] + 0.001]
  data.table(sigi[i, .(A, AA, State, ID)], abf)
}, mc.cores = 21)

sigi_abf <- lapply(seq_along(sigi_abf), function(x) {
  i <- sigi[x, ]
  j <- sigi_abf[[x]]
  j$Time <- j$Time - min(j$Time)
  j[, pA := pA / i$BaseMean]
  j
})
sigi_abf <- do.call(rbind, sigi_abf)
```

```{r}
data <- sigi_abf[, .(AminoAcid = A, Time, Current = pA)]
data[, AminoAcid := factor(AminoAcid, levels = c("His1", "His2", "Lys", "Arg", "Glu", "Asp", "Gly", "Ala", "Val", "Leu", "Met", "Ile", "Pro", "Phe", "Trp", "Cys", "Ser", "Tyr", "Asn", "Gln", "Thr"))]
AABlockade <- sigi[, .(AminoAcid = A, Blockade)]
AABlockade[, AminoAcid := factor(AminoAcid, levels = c("His1", "His2", "Lys", "Arg", "Glu", "Asp", "Gly", "Ala", "Val", "Leu", "Met", "Ile", "Pro", "Phe", "Trp", "Cys", "Ser", "Tyr", "Asn", "Gln", "Thr"))]
```

```{r}
Fig1F <- list(data, AABlockade)
openxlsx::write.xlsx(Fig1F, "analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig1F.xlsx")
```


