---
title: "Figure 6 f"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(parallel)
library(caret)
library(IRanges)
library(shiny)
library(plotly)
library(ggpubr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(Biostrings)
```

```{r}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

Peaks <- function(x, y) {
  stopifnot(length(x) == length(y))
  uR <- IRanges(diff(y) >= 0)
  dR <- IRanges(diff(y) <= 0)
  res <- do.call(c, lapply(seq_along(uR), function(i) {
    reduce(c(uR[i], dR[i]))
  }))
  
  Ps <- mapply(seq_along(res), FUN = function(i) {
    x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
  })
  Py <- mapply(seq_along(res), FUN = function(i) {
    max(y[start(res[i]):end(res[i])])
  })
  res <- data.table(x = Ps, xmin = x[start(res)], xmax = x[end(res)], y = Py)
  attr(res, "peaks") <- Ps
  return(res)
}

MainRidge <- function(x, bw = 0.001, bwstep = NULL, n = 1024, peaks = 2, mingap = 0.01, CI = 0.99, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  res <- ps[order(y, decreasing = T)][seq_len(peaks)]
  res <- na.omit(res)
  if(peaks > 1) {
    if(is.null(bwstep)) bwstep <- mingap/10
    while (nrow(res) > 1 & min(res[, diff(sort(x))]) < mingap) {
      bw <- bw + bwstep
      den <- density(x, bw = bw, n = n, ...)
      ps <- Peaks(den$x, den$y)
      res <- ps[order(y, decreasing = T)][seq_len(peaks)]
      res <- na.omit(res)
    }
  }
  if(CI < 1) {
    new_x <- lapply(seq_len(nrow(res)), function(i) {
      resy <- with(den, y[x > res[i, xmin] & x < res[i, xmax]])
      resy <- resy > max(resy) * (1 - CI) + min(resy)
      resx <- range(with(den, x[x > res[i, xmin] & x < res[i, xmax]])[resy])
      resx
    })
    new_x <- do.call(rbind, new_x)
    res$xmin <- new_x[, 1]
    res$xmax <- new_x[, 2]
  }
  res$ratio <- mapply(function(i) mean(x >= res$xmin[i] & x <= res$xmax[i]), seq_len(nrow(res)))
  
  if(plot) {
    plot(den)
    abline(v = res[, x], lty = 2, col = 2)
    abline(v = res[, xmin], lty = 2, col = 3)
    abline(v = res[, xmax], lty = 2, col = 3)
  } else {
    return(res)
  }
}
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
a_cols <- aa_cols
names(a_cols) <- plyr::mapvalues(names(a_cols), AMINO_ACID_CODE, names(AMINO_ACID_CODE))
```

```{r}
files <- list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals", "txt", full.names = T)
Sigs1 <- lapply(files, fread)
Sigs1 <- data.table(A = rep(gsub(".signal.txt", "", basename(files)), mapply(nrow,  Sigs1)), do.call(rbind, Sigs1))

SigSumm <- Sigs1[State == "Sington", .(BlockadeSD = sd(Blockade), 
                     BlockadeMean = mean(Blockade), 
                     BlockadeMedian = median(Blockade), 
                     BlockadeQ1 = quantile(Blockade, 1/4), 
                     BlockadeQ3 = quantile(Blockade, 3/4), 
                     DwellTimeSD = sd(DwellTime), 
                     DwellTimeMAD = mad(DwellTime), 
                     DwellTimeQ1 = quantile(DwellTime, 1/4), 
                     DwellTimeQ3 = quantile(DwellTime, 3/4), 
                     DwellTimeMean = mean(DwellTime), 
                     DwellTimeMedian = median(DwellTime)), A]
```

```{r}
abf_F <- readRDS("./analysis/81.ABFProcessing/ABF/ABF_Username_2022-03-14_005.Rds")
```

```{r}
abf_j <- abf_F[Time > 1282.65 & Time < 1283.125]
L0_2 <- MainRidge(x = abf_j[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm2 <- SigSumm[A %in% AMINO_ACID_CODE[unlist(strsplit("F", ""))]]
aasumm2[, y := L0_2 * (1 - BlockadeMean)]
aasumm2[, ymin := L0_2 * (1 - BlockadeMean - BlockadeSD)]
aasumm2[, ymax := L0_2 * (1 - BlockadeMean + BlockadeSD)]
```

```{r}
si <- as.data.table(IRanges(abf_j[, pA / L0_2 < 0.9]))
si <- si[order(width, decreasing = T)][1:6]
si <- data.table(StartTime = abf_j[si$start, Time], EndTime = abf_j[si$end, Time])
si$SignalCurrent <- mapply(seq_len(nrow(si)), FUN = function(x) {
  abf_j[between(Time, si[x, StartTime], si[x, EndTime]), median(pA)]
})
si <- si[order(StartTime)]
si$Pred2 <- c("F", "V", "", "F", "V", "L")
```

```{r}
abf_S <- readRDS("./analysis/81.ABFProcessing/ABF/ABF_Username_2022-03-11_003.Rds")
```

```{r fig.width=18, fig.height=3}
# abf_i <- abf_S[Time > 418 - .25 & Time < 418 + 0.25]
abf_i <- abf_S[Time > 248 - 0.52 & Time < 248 + 0]
L0 <- MainRidge(x = abf_i[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm1 <- SigSumm[A %in% AMINO_ACID_CODE[unlist(strsplit("S", ""))]]
aasumm1[, y := L0 * (1 - BlockadeMean)]
aasumm1[, ymin := L0 * (1 - BlockadeMean - BlockadeSD)]
aasumm1[, ymax := L0 * (1 - BlockadeMean + BlockadeSD)]
```

```{r}
LSGV <- fread("./analysis/89.Neoantigen/04.SignalsPrediction/LSGV_prediction.txt", sep = "\t")
```

```{r}
PreSig <- LSGV[StartTime > 248 - 0.52 & EndTime < 248]
PreSig[, Pred2 := plyr::mapvalues(Pred2, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
```

```{r}
openxlsx::write.xlsx(list(abf_j, aasumm2, si, abf_i, aasumm1, PreSig), "./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig6F.xlsx")
```
