---
title: "Figure 6 i"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(parallel)
library(caret)
library(IRanges)
library(shiny)
library(plotly)
library(ggpubr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(Biostrings)
```

```{r}
polyp <- as.data.table(openxlsx::read.xlsx("./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig6GH.xlsx"))
```

```{r}
CurrList <- mclapply(polyp[, unique(file_id)], function(fi) {
  # print(fi)
  Curr <- readRDS(paste0("./analysis/81.ABFProcessing/SignalCurrent/SignalCurrent_", gsub("\\.[0-9]$", "", fi), ".Rds"))
  stopifnot(all(polyp[file_id == fi, ID] %in% Curr[, ID]))
  Curr[ID %in% polyp[file_id == fi, ID]]
}, mc.cores = 20)
```


```{r}
CurrList_Den <- lapply(CurrList, function(x) {
  density(x[, Current], from = 0, to = 1, n = 1024, bw = 0.001)$y
})
CurrList_Den <- do.call(rbind, CurrList_Den)
row.names(CurrList_Den) <- polyp[, unique(file_id)]
```


```{r fig.width=8, fig.height=7}
loc <- cmdscale(stats::dist(CurrList_Den, method = "euclidean"))
colnames(loc) <- c("Dim.1", "Dim.2")
cmd_raw_result <- merge(unique(polyp[, .(PPT, file_id)]), as.data.table(loc, keep.rownames = "file_id"))
```

```{r}
openxlsx::write.xlsx(cmd_raw_result, "./analysis/00.FigureTables/Rebuttal/Nov12/Figures/Data/Fig6I.xlsx")
```

```{r fig.width=8, fig.height=7}
ggplot(cmd_raw_result, aes(x = Dim.1, Dim.2, colour = PPT)) + 
  ggforce::geom_mark_ellipse(expand = unit(0, "mm"), con.cap = 0, con.border = "none", con.type = "straight") + 
  ggforce::geom_mark_ellipse(aes(label = PPT, filter = !PPT %in% c("LVFFA", "LVFFAG", "LVFFAK")), expand = unit(0, "line"), 
                             label.colour = "grey", con.colour = "grey", con.cap = 0, con.border = "none", con.type = "straight") + 
  geom_point(size = 2) + 
  scale_colour_brewer(palette = "Paired", guide = guide_legend(nrow = 3)) + 
  # labs(title = "CMD") + 
  theme_base(base_size = 22) + 
  theme(plot.background = element_blank(), 
        legend.position = "top",
        legend.title = element_blank()) -> p1
p1
```






