---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(caret)
library(shiny)
library(plotly)
library(ggpubr)
library(IRanges)
```

```{r}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

KnnSelecting <- function(signals, dists, dist_method = "euclidean", k = 20, noise = 0) {
  stopifnot(noise < k)
  if(is(dists, "dist")) {
    knn1 <- dbscan::kNN(dists, k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists, "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  } else {
    knn1 <- dbscan::kNN(dists[[dist_method]], k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists[[dist_method]], "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  }
  
  tu <- row.names(knn1$id)[which(rowSums(knn2) <= noise)]
  # tu <- union(tu, knn2[which(rowSums(knn2) <= noise), 1])
  tu <- grep("^Noise", tu, invert = TRUE, value = TRUE)
  ggplot(signals, aes(x = Blockade, y = DwellTime, colour = !ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = c("#E41A1C", "#377EB8")) + 
    theme_classic() + 
    theme(legend.position = "none") -> p1
  ggplot(signals[ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#E41A1C") + 
    theme_classic() + 
    theme(legend.position = "none") + 
    labs(title = length(tu)) -> p2
  ggplot(signals[!ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#377EB8") + 
    theme_classic() + 
    theme(legend.position = "none") -> p3
  print(p1 + p2 + p3)
  return(tu)
}

RemoveOutlier1 <- function(tree, n = 10, o = NULL) {
  k <- ceiling(length(res.hc$labels)/100)
  res_ct <- stats::cutree(res.hc, k = k)
  while (sum(table(res_ct) >= n) == 1) {
    k <- k + 1
    res_ct <- stats::cutree(res.hc, k = k)
  }
  if(is.null(o)) o <- n
  names(res_ct[res_ct %in% names(which(table(res_ct) >= o))])
}
RemoveOutlier <- function(tree, n = 10, Keep = 0.95) {
  h <- length(tree$height)
  g <- cutree(tree, h = tree$height[h])
  g <- data.table(tip = names(g), cluster = g)
  
  while (g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] > Keep) {
    h <- h - 1
    g <- cutree(tree, h = tree$height[h])
    g <- data.table(tip = names(g), cluster = g)
  }
  cat(paste0("Keep: ", round(g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] * 100, 2), "%"))
  g[cluster %in% g[, .N, cluster][N >= n, cluster], tip]
}

get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

# Peaks <- function(x, y) {
#   stopifnot(length(x) == length(y))
#   uR <- IRanges(diff(y) >= 0)
#   dR <- IRanges(diff(y) <= 0)
#   res <- do.call(c, lapply(seq_along(uR), function(i) {
#     reduce(c(uR[i], dR[i]))
#   }))
#   
#   Ps <- mapply(seq_along(res), FUN = function(i) {
#     x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
#   })
#   res <- IRanges(start = x[start(res)], end = x[end(res)])
#   end(res[length(res)]) <- max(x)
#   attr(res, "peaks") <- Ps
#   return(res)
# }
Peaks <- function(x, y) {
  stopifnot(length(x) == length(y))
  uR <- IRanges(diff(y) >= 0)
  dR <- IRanges(diff(y) <= 0)
  res <- do.call(c, lapply(seq_along(uR), function(i) {
    reduce(c(uR[i], dR[i]))
  }))
  
  Ps <- mapply(seq_along(res), FUN = function(i) {
    x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
  })
  Py <- mapply(seq_along(res), FUN = function(i) {
    max(y[start(res[i]):end(res[i])])
  })
  res <- data.table(x = Ps, xmin = x[start(res)], xmax = x[end(res)], y = Py)
  attr(res, "peaks") <- Ps
  return(res)
}

densityPeak <- function(x, bw = 0.01, peaks = 2, n = 1024, from = 0, to = 1, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  dx <- attr(ps, "peaks")
  dy <- den$y[den$x %in% attr(ps, "peaks")]
  dy <- dy/max(dy)
  
  dx2 <- dx[dx <= dx[which.max(dy)]]
  dy2 <- dy[dx <= dx[which.max(dy)]]
  
  dx2 <- dx2[dy2 %in% head(sort(dy2, decreasing = T), peaks)]
  dy2 <- dy2[dy2 %in% head(sort(dy2, decreasing = T), peaks)]
  res <- sort(dx2, decreasing = T)
  df <- mean(abs(diff(den$y)))
  CI <- mapply(res, FUN = function(i) {
    from <- with(den, x[x < i])[max(start(IRanges(diff(with(den, y[x < i])) > mean(abs(diff(with(den, y[x < i])))))))]
    to <- with(den, x[x > i])[min(end(IRanges(diff(with(den, y[x > i])) < mean(abs(diff(with(den, y[x > i])))))))]
    min(c(i - from, to - i))
  })
  attr(res, "CI") <- CI
  if(plot) {
    plot(den)
    abline(v = res, lty = 2, col = 2)
    abline(v = res - attr(res,"CI"), lty = 2, col = 3)
    abline(v = res + attr(res,"CI"), lty = 2, col = 3)
  } else {
    return(res)
  }
}

BaseMeanFiltering <- function(SigFile, starttime = NULL, endtime = NULL, outdir = NULL, target = NULL, product = NULL) {
  if(is.null(starttime)) stop()
  if(is.null(endtime)) stop()
  if(is.null(outdir)) stop()
  if(is.null(target)) stop()
  outdir <- gsub("//", "/", paste0(outdir, "/", target))
  if(!dir.exists(outdir)) dir.create(outdir)
  dataset <- fread(SigFile)
  dataset <- dataset[StartTime > starttime*60 & EndTime < endtime*60]
  dataset[, A := target]
  dataset[, DwellTime := DwellTime * 1000]
  shinyApp(
    ui = fluidPage(
      fluidRow(style = "padding-bottom: 20px;",
               column(2, numericInput('size', 'Point size', value = .3, min = .1, max = 1, step = .1)),
               column(3, sliderInput('nbins', 'Number of bins', value = 500, min = 100, max = 1000, step = 50)),
               column(3, sliderInput('BaseMean', 'BaseMean region', value = c(90, 130), min = 80, max = max(dataset[, round(BaseMean)]))),
               column(3, radioButtons(inputId = "LogScale", label = "log scale:", choices = c("TRUE", "FALSE"), inline = T))
      ),
      fluidRow(column(6, plotlyOutput('BaseMeanBlockade')), column(6, plotlyOutput('BlockadeDwellTime'))),
      plotlyOutput('BaseMeanHistogram'),
      actionButton("goButton", 'Save', class = "btn-success"),
      verbatimTextOutput("sp")
    ), 
    server = function(input, output, session) {
      selectedData <- reactive({
        dataset[BaseMean > input$BaseMean[1] & BaseMean < input$BaseMean[2]]
      })
      
      output$BaseMeanBlockade = renderPlotly({
        ggplot(selectedData(), aes(x = BaseMean, y = Blockade)) + 
          geom_point(size = input$size) + 
          # geom_hline(yintercept = AABlockade[amino_acid %in% selectedData()[, unique(A)], Blockade], color = "red") + 
          theme_minimal() -> p
        ggplotly(p)
      })
      
      output$BaseMeanHistogram = renderPlotly({
        ggplot(selectedData(), aes(x = BaseMean)) + 
          geom_histogram(bins = input$nbins) + 
          theme_minimal() -> p2
        ggplotly(p2) %>% layout(dragmode = "select")
      })
      
      output$BlockadeDwellTime = renderPlotly({
        d <- (event_data("plotly_selected"))
        if(is.null(d)) {
          selectedData2 <- reactive({
            dataset
          })
        } else {
          selectedData2 <- reactive({
            dataset[BaseMean > min(d$x) & BaseMean < max(d$x)]
          })
        }
        ggplot(selectedData2(), aes(x = Blockade, y = DwellTime)) + 
          geom_point(size = input$size) + 
          # geom_vline(xintercept = product, color = "red") +
          theme_minimal() + 
          labs(title = selectedData2()[, unique(A)]) -> p3
        if(!is.null(product)) {
          p3 <- p3 + geom_vline(xintercept = product, color = "red")
        }
        
        if(input$LogScale == "TRUE") {
          p3 <- p3 + scale_y_log10()
        }
        ggplotly(p3)
      })
      
      output$sp <- renderPrint({
        d <- (event_data("plotly_selected"))
        if(is.null(d)) {
          cat("Number of selected points:", nrow(d))
        } else {
          selectedData2 <- reactive({
            dataset[BaseMean > min(d$x) & BaseMean < max(d$x)]
          })
          if(input$goButton != 0) {
            if(!is.null(d)) {
              fwrite(selectedData2(), paste0(outdir, "/", gsub(".txt", ".MainL0.txt", basename(SigFile))), sep = "\t", quote = F)
              cat("Saved", nrow(selectedData2()), "points.")
            } else {
              cat("Number of selected points:", nrow(selectedData2()))
            }
          } else {
            cat("Number of selected points:", nrow(selectedData2()))
          }
        }
      })
    }
  )
}

MainRidge <- function(x, bw = 0.001, bwstep = NULL, n = 1024, peaks = 2, mingap = 0.01, CI = 0.99, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  res <- ps[order(y, decreasing = T)][seq_len(peaks)]
  res <- na.omit(res)
  if(peaks > 1) {
    if(is.null(bwstep)) bwstep <- mingap/10
    while (nrow(res) > 1 & min(res[, diff(sort(x))]) < mingap) {
      bw <- bw + bwstep
      den <- density(x, bw = bw, n = n, ...)
      ps <- Peaks(den$x, den$y)
      res <- ps[order(y, decreasing = T)][seq_len(peaks)]
      res <- na.omit(res)
    }
  }
  if(CI < 1) {
    new_x <- lapply(seq_len(nrow(res)), function(i) {
      resy <- with(den, y[x > res[i, xmin] & x < res[i, xmax]])
      resy <- resy > max(resy) * (1 - CI) + min(resy)
      resx <- range(with(den, x[x > res[i, xmin] & x < res[i, xmax]])[resy])
      resx
    })
    new_x <- do.call(rbind, new_x)
    res$xmin <- new_x[, 1]
    res$xmax <- new_x[, 2]
  }
  res$ratio <- mapply(function(i) mean(x >= res$xmin[i] & x <= res$xmax[i]), seq_len(nrow(res)))
  
  if(plot) {
    plot(den)
    abline(v = res[, x], lty = 2, col = 2)
    abline(v = res[, xmin], lty = 2, col = 3)
    abline(v = res[, xmax], lty = 2, col = 3)
  } else {
    return(res)
  }
}
```


```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/Voltage/不同电压.xlsx"))
colnames(meta) <- c("file_name", "amino_acid", "voltage", "concentration", "start_time", "end_time")
meta <- meta[, .SD[, .(.SD, SubFile = seq_len(.N))], file_name]
colnames(meta) <- gsub(".SD.", "", colnames(meta))
meta[, SubFile := paste0(file_name, "_", SubFile)]
meta[is.na(concentration), concentration := 0]
meta[, amino_acid := gsub("Arg\\(R\\)", "Arg", amino_acid)]
meta[, amino_acid := gsub("Lys\\(K\\)", "Lys", amino_acid)]
setkey(meta, file_name)
meta[SubFile == "21201011_1", amino_acid := "Asp"]
meta[SubFile == "21205019_1", amino_acid := "Arg"]
meta[SubFile == "21203011_1", amino_acid := "Glu"]
meta[SubFile == "21207008_1", amino_acid := "Lys"]
meta[SubFile == "21307001_1", amino_acid := "Trp"]
meta[SubFile == "21319005_1", amino_acid := "Thr"]
meta[, start_time := as.numeric(start_time)]
meta[, end_time := as.numeric(end_time)]
meta <- rbind(meta, data.table(file_name = "21207004", amino_acid = "Lys", voltage = 50, concentration = 100, start_time = 7, end_time = 16, SubFile = "21207004_1"))
meta <- rbind(meta, data.table(file_name = "21320003", amino_acid = "Thr", voltage = 50, concentration = 100, start_time = 11, end_time = 18, SubFile = "21320003_1"))
meta <- rbind(meta, data.table(file_name = "21321013", amino_acid = "Leu", voltage = c(50, 75, 100, 100, 100), concentration = 100, 
                               start_time = c(0, 11.2, 14.3, 15.4, 18.4), end_time = c(6.5, 14.2, 14.9, 16.8, 19.2), 
                               SubFile = paste0("21320003_", 1:5)))
meta$abf_file <- mapply(function(x) list.files("./data/Voltage", x, full.names = T), meta$file_name)
meta[, voltage := factor(voltage, levels = c("50", "75", "100"))]
```

# Asp

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Asp/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```



# Glu

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Glu/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```












# Arg

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Arg/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```












# Lys

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Lys/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```












# Lys

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Lys/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```












# Trp

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Trp/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```












# Thr

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Thr/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[, .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```












# Leu

```{r}
select_sigs <- fread("./analysis/61.SignalSelecting/02.Voltage/Leu/Selected_sigs.txt", sep = "\t")
select_sigs[, voltage := paste(voltage, "(mV)")]
select_sigs[, voltage := factor(voltage, levels = c("50 (mV)", "75 (mV)", "100 (mV)"))]
```

```{r fig.width=10, fig.height=7}
ggplot(select_sigs, aes(x = Blockade, y = DwellTime, colour = voltage)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, .5)) + 
  facet_wrap(~ voltage, ncol = 1, scales = "free_y", strip.position = "right") + 
  scale_colour_brewer(palette = "Reds", guide = "none") + 
  labs(y = "Dwell time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  theme_light(base_size = 15) -> p1
p1
```

```{r}
sig <- split(select_sigs, select_sigs$SubFile)
SigInterTime <- lapply(sig, function(sigi) {
  setkey(sigi, StartTime)
  InterTime <- data.table(File = sigi[, unique(SubFile)], 
                          StartTime = sigi[, EndTime][-c(nrow(sigi))], 
                          EndTime = sigi[, StartTime][-c(1)], 
                          SigBefore = sigi[, ID][-c(nrow(sigi))], 
                          SigAfter = sigi[, ID][-c(1)], 
                          SigBeforeBaseMean = sigi[, BaseMean][-c(nrow(sigi))], 
                          SigAfterBaseMean = sigi[, BaseMean][-c(1)])
  
  filei <- sigi[, unique(SubFile)]
  abf <- readRDS(paste0("./analysis/21.ABFProcessing/04.Voltage/ABF/", filei, ".Rds"))
  L0 <- fread(list.files("./analysis/61.SignalSelecting/02.Voltage", paste0("RawSignal_", filei, ".MainL0.txt"), recursive = T, full.names = T))
  
  ssd <- abf[Sm >= L0[, min(BaseMean)] & Sm <= L0[, max(BaseMean)], sd(pA)]
  abf[, L0 := Sm >= L0[, min(BaseMean) - ssd] & Sm <= L0[, max(BaseMean) + ssd]]
  abf[, Closed := pA < sigi[, min(SignalCurrent)]]
  
  ValidRegion <- IRanges(Rle(abf[, Valid]))
  Valid <- data.table(satrt = abf[start(ValidRegion), Time], end = abf[end(ValidRegion), Time])
  InterTime <- InterTime[StartTime %inrange% Valid & EndTime %inrange% Valid]
  InterTime2 <- mclapply(seq_len(nrow(InterTime)), function(i) {
    abf[Time > InterTime[i, StartTime] & Time < InterTime[i, EndTime], .(Time1 = diff(range(Time)), Time2 = mean(L0) * diff(range(Time)))]
  }, mc.cores = 30)
  InterTime2 <- do.call(rbind, InterTime2)
  InterTime <- cbind(InterTime, InterTime2)
  return(InterTime)
})
SigInterTime <- do.call(rbind, SigInterTime)
SigInterTime <- merge(SigInterTime, meta[amino_acid == "Leu", .(SubFile, amino_acid, voltage, concentration)], by.x = "File", by.y = "SubFile")
```

```{r fig.width=4, fig.height=4}
ggplot(SigInterTime, aes(x = voltage, y = Time2 * 1000, fill = voltage)) + 
  ggbeeswarm::geom_quasirandom(size = 1, alpha = .3, width = .2) +
  # geom_jitter(size = 1, alpha = .3, height = 0, width = 0.15) + 
  geom_boxplot(alpha = .8, width = 0.3, outlier.shape = NA) + 
  scale_y_log10() + 
  labs(x = "Voltage (mV)", y = "Interval time (ms)", title = select_sigs[, unique(amino_acid)]) + 
  stat_compare_means(comparisons = list(c("50", "75"), c("75", "100"), c("50", "100")), label.y.npc = "bottom") + 
  scale_fill_brewer(palette = "Reds", guide = "none") + 
  theme_light(base_size = 15) -> p2
p2
```


```{r}
ggplot(select_sigs[, .(Time = round(StartTime)), voltage][, .N, .(voltage, Time)], aes(x = voltage, y = N)) + 
  geom_boxplot() + 
  stat_compare_means(comparisons = list(c("50 (mV)", "75 (mV)"), c("75 (mV)", "100 (mV)"), c("50 (mV)", "100 (mV)")), label.y.npc = "bottom")
```

