---
title: "Polypeptide sequencing"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
  code_folding: "hide"
toc: true
toc_depth: 4
toc_float: 
  collapsed: false
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = F, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r}
library(openxlsx)
library(ggplot2)
library(data.table)
library(Biostrings)
library(ggpubr)
```

```{r}
set.seed(19)
AA_Cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(AA_Cols) <- Biostrings::AA_STANDARD
```

```{r}
meta <- do.call(rbind, lapply(list.files("./analysis/01.AASignalRecognition/Version9/02.RangesL0L1/", ".txt", full.names = TRUE, recursive = T), fread))
# meta <- meta[, .(file_name, amino_acid, concentration, start_time, end_time, TimeRatio)]
meta[, file_name := as.character(file_name)]
meta <- meta[!file_name %in% c("21205012", "21205021", "21201008", "21303003")]

files <- list.files("./analysis/01.AASignalRecognition/Version9/04.FinalSignal", pattern = "_Sigs.txt", recursive = TRUE, full.names = T)
AAs <- lapply(files, fread)
names(AAs) <- gsub("_Sigs.txt", "", basename(files))
for(i in seq_along(AAs)) AAs[[i]] <- data.table(file_name = names(AAs)[i], AAs[[i]])
AA <- do.call(rbind, AAs)
AA <- AA[!file_name %in% c("21205012", "21205021", "21201008", "21303003")]

AA <- merge(meta, AA, by = "file_name")
AA <- AA[!is.na(Blockade) & Outer == 0 & AreaRatio_L1 > 0.1]
AA[, .N, amino_acid]
AA[, aa := plyr::mapvalues(amino_acid, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]

AA[aa %in% c("E", "D", "H", "R", "K"), Class := "charged"]
AA[aa %in% c("L", "I", "M", "V", "A", "F", "G", "W", "P"), Class := "polar"]
AA[aa %in% c("S", "N", "Q", "T", "Y", "C"), Class := "nonpolar"]
```

```{r}
load(file = "./analysis/03.MachineLearning/01.data/Version6/AAInfo_RawSig.RData")
# AAInfo <- AAInfo[!amino_acid %in% c("Cys", "Pro")]
AAInfo$AllTime <- mapply(AAInfo$ID, FUN = function(x) {
  RawSig[ID == x, diff(range(Time))] * 1000
})
AAInfo[, aa := plyr::mapvalues(amino_acid, AMINO_ACID_CODE, names(AMINO_ACID_CODE))]
AAInfo[aa %in% c("E", "D", "H", "R", "K"), Class := "charged"]
AAInfo[aa %in% c("L", "I", "M", "V", "A", "F", "G", "W", "P"), Class := "polar"]
AAInfo[aa %in% c("S", "N", "Q", "T", "Y", "C"), Class := "nonpolar"]
```


```{r}
od <- AAInfo[, mean(DwellTime), c("aa", "Class")][order(Class, V1), as.character(aa)]
AAInfo[, aa := factor(aa, levels = od)]
ggplot(AAInfo, aes(x = aa, y = DwellTime, colour = Class)) + 
  geom_violin() +
  stat_summary(fun.data = "mean_sd") + 
  theme_bw(base_size = 15) + 
  scale_y_log10() + 
  # scale_colour_manual(values = AA_Cols[AAInfo[, levels(factor(aa))]], guide = "none") + 
  scale_color_brewer(palette = "Dark2") +
  labs(x = "Amino acid", y = "Dwell time (ms)") + 
  theme(legend.position = "top")
ggsave("./analysis/01.AASignalRecognition/Version9/05.plot/AA_DwellTime.pdf", width = 5, height = 3.5)
```

```{r}
od <- AAInfo[, mean(AllTime), c("aa", "Class")][order(Class, V1), as.character(aa)]
AAInfo[, aa := factor(aa, levels = od)]
ggplot(AAInfo, aes(x = aa, y = AllTime, colour = Class)) + 
  geom_violin() +
  stat_summary(fun.data = "mean_sd") + 
  theme_bw(base_size = 15) + 
  scale_y_log10() + 
  # scale_colour_manual(values = AA_Cols[AAInfo[, levels(factor(aa))]], guide = "none") + 
  scale_color_brewer(palette = "Dark2") +
  labs(x = "Amino acid", y = "All time (ms)") + 
  theme(legend.position = "top")
ggsave("./analysis/01.AASignalRecognition/Version9/05.plot/AA_AllTime.pdf", width = 5, height = 3.5)
```

