---
title: "Ala"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = F, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
```

```{r}
library(readABF)
library(data.table)
library(S4Vectors)
library(IRanges)
library(changepoint)
library(ggplot2)
library(MASS)
library(strucchange)
library(ggpubr)
source("/mnt/raid61/Personal_data/tangchao/AANanopore/script/01.AASignalRecognition/Version3/SignalProcessing/AdditionalFunctions.R")
```

```{r eval=FALSE}
sort(unique(openxlsx::read.xlsx("/mnt/raid61/Personal_data/tangchao/AANanopore/data/meta_info_and_base_line_20210513.xlsx")[[3]]))
```

```{r}
AA <- "Ala"
```

```{r}
meta <- data.table(openxlsx::read.xlsx("/mnt/raid61/Personal_data/tangchao/AANanopore/data/meta_info_and_base_line_20210513.xlsx"))[, 1:9]

Ptabf <- file.path("/mnt/raid61/Personal_data/tangchao/AANanopore/data/ZhangMing_20210402")
OutDir <- file.path("/mnt/raid61/Personal_data/tangchao/AANanopore/analysis/01.AASignalRecognition/Version3", AA)

if(!dir.exists(OutDir)) dir.create(OutDir)
# file.remove(list.files(OutDir, full.names = T))

meta <- meta[amino_acid == AA, ]
meta <- na.omit(meta)
DT::datatable(meta)
```

```{r}
meta[, file_name := as.character(file_name)]
L1Min <- unique(meta[, L1min])
L1Max <- unique(meta[, L1max])
```

```{r}
BUBs <- mclapply(seq_len(nrow(meta)), function(i) {
  File <- meta[,file_name][i]
  StartTime <- meta[,start_time][i]
  EndTime <- meta[,end_time][i]
  
  phe <- readABF::readABF(list.files(path = Ptabf, pattern = as.character(File), full.names = T))
  phe <- as.data.table(as.data.frame(phe))
  colnames(phe) <- c("Time", "pA", "mV")
  phe <- phe[Time > StartTime * 60 & Time < EndTime * 60, ]
  
  phe <- phe[round(mV) == 50, ]
  phe <- phe[pA > 0, ]
  phe <- phe[pA < 130, ]
  phe$Sm <- KBins2(sig = phe$pA, pen.value = 1 - 1e-16, minseglen1 = 1, minseglen2 = 1)
  
  DenSm <- density(phe[, Sm], adjust = 1)
  
  L0 <- L0Coor(DenSm)
  L0Min <- min(L0) * 0.9
  
  pdf(paste0(file.path(OutDir, File), "_L0_Coordinate.pdf"))
  plot(DenSm, xlab = "Current (pA)", main = "density of smooth current", xlim = c(90, 130))
  abline(v = L0, lty = 2, col = 2)
  dev.off()
  
  # if(ConfusedL0(DenSm) < 0.2) {
  #   return(NULL)
  # }
  
  phe[, L := NULL]
  phe[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
  phe[Sm < L0Min, L := "U"] # U shape
  phe[is.na(L), L := "O"] # Other
  
  BUB <- BUB_Sig(Mat = phe)
  BUB <- BUB[mapply(function(x) max(x$Sm), BUB) <= max(L0)]
  return(BUB)
}, mc.cores = nrow(meta))
```

```{r}
names(BUBs) <- meta[, file_name]
saveRDS(BUBs, file = file.path(OutDir, "BUB.Rds"))
```

```{r eval=FALSE}
BUBs <- readRDS(file.path(OutDir, "BUB.Rds"))
```

```{r}
BUBs <- BUBs[mapply(length, BUBs) > 20]
```

```{r}
mapply(length, BUBs)
```

```{r}
for(i in seq_along(BUBs)) names(BUBs[[i]]) <- paste0(names(BUBs)[i], "_", seq_along(BUBs[[i]]))
names(BUBs) <- NULL
BUBs <- do.call(c, BUBs)
for(i in seq_along(BUBs)) BUBs[[i]]$File <- names(BUBs)[i]
```

```{r}
length(BUBs)
```

```{r}
BUBs <- BUBs[mapply(BUBs, FUN = function(x) x[L == "B", .N]) >= 2000]
```

```{r}
length(BUBs)
```

```{r}
variance <- mclapply(BUBs, function(x) {
  m <- x[L == "U", .N, Sm][which.max(N), Sm]
  x[L == "U" & Sm == m, .(MDA = mad(pA), SD = sd(pA))]
}, mc.cores = 10)
variance <- do.call(rbind, variance)
variance[, ID := 1:.N]
variance <- variance[MDA < quantile(MDA, 0.95) & SD < quantile(SD, 0.95) & MDA < 2.5, ]
BUBs <- BUBs[variance$ID]
```

```{r}
length(BUBs)
```

```{r}
purity <- function(x, w = 2, l = 20) { # here, w is the hight around the main stage, l is the length to include
  sn <- x[L == "U", .N, Sm][N >= l, ]
  mm <- sn[which.max(N), Sm]
  sn[abs(Sm - mm) <= w, Sm := mm]
  max(sn[, sum(N), Sm][, prop.table(V1)])
}
```

```{r}
puritys <- mcmapply(purity, BUBs, mc.cores = 10)
hist(puritys, breaks = 200)
mean(puritys == 1)
```

```{r}
BUBs <- BUBs[puritys == 1]
```

```{r}
length(BUBs)
```

```{r}
SigFile <- data.table(ID = names(BUBs), File = mapply(function(x) x[1], strsplit(names(BUBs), "_")))

L0tu <- mclapply(SigFile[, unique(File)], function(f) {
  id <- SigFile[File == f, ID]
  bubf <- BUBs[id]
  L0F <- data.table(Sid = names(bubf), 
                    pA = mapply(function(x) x[L == "B", mean(pA)], bubf), 
                    Sm = mapply(function(x) x[L == "B", mean(Sm)], bubf))
  rg <- CISelect(L0F$Sm)
  L0F[Sm > min(rg) & Sm < max(rg), Sid]
}, mc.cores = length(SigFile[, unique(File)]))
L0tu <- do.call(c, L0tu)
```

```{r}
length(L0tu)
```

```{r}
BUBs <- BUBs[L0tu]
```

```{r}
BUB_Tab <- do.call(rbind, BUBs)
```

```{r}
hist(BUB_Tab[, pA], breaks = 500, xlab = "Current of BUB", main = "Histogram of BUB current")
```

```{r}
BUB3 <- lapply(BUBs, function(x) x[L != "B", 1 - pA/(x[L == "B", mean2(pA)])])
BUB3 <- data.table(Bs = do.call(c, BUB3), File = rep(names(BUBs), mapply(length, BUB3)))
BUB3$File <- mapply(function(x) x[1], strsplit(BUB3$File, "_"))
```

```{r}
ggplot(BUB3, aes(Bs, color = File)) +
  geom_line(stat = "density") + 
  labs(x = "Blockade of BUB") + 
  theme_classic(base_size = 15)
```

```{r}
BRs <- BUB3$Bs
DenSm <- density(BRs, adjust = 1)
(L1 <- L1Coor(DenSm, MinBR = L1Min, MaxBR = L1Max))
```

```{r}
ggplot(BUB3, aes(Bs, color = File)) +
  geom_line(stat = "density") + 
  labs(x = "Blockade of BUB") + 
  theme_classic(base_size = 15) + 
  geom_vline(xintercept = L1)
```

```{r}
ggplot(BUB3[Bs > min(L1) & Bs < max(L1), ], aes(Bs, color = File)) +
  geom_line(stat = "density") + 
  labs(x = "Blockade of L1") + 
  theme_classic(base_size = 15) + 
  geom_vline(xintercept = L1) + 
  scale_color_brewer(palette = "Dark2")
```

```{r}
ggplot(BUB3[Bs > min(L1) & Bs < max(L1), ], aes(x = File, y = Bs, color = File)) +
  geom_boxplot() + 
  labs(x = "Blockade of L1") + 
  theme_classic(base_size = 15) + 
  scale_color_brewer(palette = "Dark2") + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r}
(CI <- CISelect(BUB3[Bs > min(L1) & Bs < max(L1), Bs]))
```

```{r}
ggplot(BUB3[Bs > min(CI) & Bs < max(CI), ], aes(Bs, color = File)) +
  geom_line(stat = "density", adjust = 2) + 
  labs(x = "Blockade of L1") + 
  theme_classic(base_size = 15) + 
  lims(x = L1)
```

```{r}
ggplot(BUB3[Bs > min(CI) & Bs < max(CI), ], aes(x = File, y = Bs, color = File)) +
  geom_boxplot() + 
  labs(x = "Blockade of L1") + 
  theme_classic(base_size = 15) + 
  scale_color_brewer(palette = "Dark2") + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r}
FileMean <- BUB3[Bs > min(CI) & Bs < max(CI), .(Mean = median(Bs)), File]
OutLiers <- c(FileMean[, median(Mean)] - 3 * FileMean[, mad(Mean)], FileMean[, median(Mean)] + 3 * FileMean[, mad(Mean)])
Tiletu <- FileMean[Mean > min(OutLiers) & Mean < max(OutLiers), File]
BUB3 <- BUB3[File %in% Tiletu, ]
BUB3 <- BUB3[Bs > min(CI) & Bs < max(CI), ]
```

```{r}
fit <- BUB3[, fitdistr(Bs, "normal")]
para <- fit$estimate
hist(BUB3$Bs, prob = TRUE, breaks = 10, xlab = "Blockade of L1", main = "Histogram of L1 blockade")
x <- BUB3$Bs
curve(dnorm(x, para[1], para[2]), col = 2, add = TRUE)
set.seed(123)
BUB3$BsGussian <- sort(rnorm(BUB3$Bs, para[1], para[2]))[rank(BUB3$Bs)]
```

```{r}
para
```

```{r}
hist(BUB3$BsGussian, prob = TRUE, 
     breaks = 1000, 
     xlim = c(0.1, 0.3), 
     xlab = "Gussian blockade of L1", 
     main = "Histogram of L1 gussian blockade")
abline(v = CI)
abline(v = BUB3[, quantile(BsGussian, c(0.05, 0.95))], col = 2)
```

```{r}
summary(lm(Bs ~ BsGussian, data = BUB3))
```

```{r}
(L1 <- BUB3[, quantile(BsGussian, c(0.05, 0.95))])
```

```{r}
mapply(function(x) {
  mean(x[L != "B", Sm] < min(x[L == "B", mean2(pA)] * (1 - L1)))
}, BUBs) -> PBRs2
```

```{r}
hist(PBRs2, breaks = 50)
```

```{r}
mean(PBRs2 == 0)
sum(PBRs2  == 0)
```

```{r}
BUBs <- BUBs[PBRs2 == 0]
```

```{r}
mcmapply(BUBs, FUN = function(x) {
  sn <- x[L == "U", .N, Sm][which.max(N), Sm]
  L1R <- x[L == "B", mean2(pA)] * (1 - L1)
  sn >= min(L1R) & sn <= max(L1R)
}, mc.cores = 10) -> InL1
mean(InL1)
```

```{r}
BUBs <- BUBs[InL1]
```

```{r}
length(BUBs)
```

```{r}
BUB_Tab <- do.call(rbind, BUBs)
```

```{r}
hist(BUB_Tab[, pA], breaks = 50, xlab = "Current of BUB", main = "Histogram of BUB current")
```

```{r}
BUB3 <- lapply(BUBs, function(x) x[L != "B", 1 - pA/(x[L == "B", mean(pA)])])
BUB3 <- data.table(Bs = do.call(c, BUB3), File = rep(names(BUBs), mapply(length, BUB3)))
BUB3$File <- mapply(function(x) x[1], strsplit(BUB3$File, "_"))
```

```{r}
ggplot(BUB3, aes(Bs, color = File)) +
  geom_line(stat = "density") + 
  labs(x = "Blockade of BUB") + 
  theme_classic(base_size = 15)
```

```{r}
BRs <- BUB3$Bs
adj = 1
DenSm <- density(BRs, adjust = adj)
L1 <- L1Coor(DenSm, MinBR = L1Min, MaxBR = L1Max)

while (anyNA(L1)) {
  adj = adj - 0.1
  DenSm <- density(BRs, adjust = adj)
  L1 <- L1Coor(DenSm, MinBR = L1Min, MaxBR = L1Max)
}
L1
```

```{r}
ggplot(BUB3, aes(Bs, color = File)) +
  geom_line(stat = "density") + 
  labs(x = "Blockade of BUB") + 
  theme_classic(base_size = 15) + 
  geom_vline(xintercept = L1)
```

```{r}
(CI <- CISelect(BUB3[Bs > min(L1) & Bs < max(L1), Bs]))
```

```{r}
BUB3 <- BUB3[Bs > min(CI) & Bs < max(CI), ]
fit <- BUB3[, fitdistr(Bs, "normal")]
para <- fit$estimate
hist(BUB3[, ]$Bs, prob = TRUE, breaks = 10, xlab = "Blockade of L1", main = "Histogram of L1 blockade")
x <- BUB3$Bs
curve(dnorm(x, para[1], para[2]), col = 2, add = TRUE)
set.seed(123)
BUB3$BsGussian <- sort(rnorm(BUB3$Bs, para[1], para[2]))[rank(BUB3$Bs)]
```

```{r}
para
```

```{r}
hist(BUB3$BsGussian, prob = TRUE, 
     breaks = 1000, 
     xlim = c(0.1, 0.3), 
     xlab = "Gussian blockade of L1", 
     main = "Histogram of L1 gussian blockade")
abline(v = CI)
abline(v = BUB3[, quantile(BsGussian, c(0.05, 0.95))], col = 2)
```
```{r}
(L1 <- BUB3[, quantile(BsGussian, c(0.05, 0.95))])
```

```{r}
summary(lm(Bs ~ BsGussian, data = BUB3))
```

```{r}
mapply(function(x) {
  mean(1 - x[L != "B", Sm]/x[L == "B", mean2(pA)] > min(L1) & 1 - x[L != "B", Sm]/x[L == "B", mean2(pA)] < max(L1))
}, BUBs) -> PBRs
```

```{r}
hist(PBRs[PBRs > 0], breaks = 400)
```


```{r}
sum(PBRs == 1)
mean(PBRs == 1)
```

```{r}
BUBs2 <- BUBs[PBRs == 1]
```

```{r}
saveRDS(BUBs2, file = file.path(OutDir, "BUB_filter.Rds"))
```

```{r}
mclapply(BUBs2, function(x) {
  sn <- x[L == "U", .N, Sm][which.max(N), Sm]
  Blockade <- 1 - x[L == "U" & Sm == sn, mean2(pA)]/x[L == "B", mean2(pA)]
  DwellTime <- x[L == "U" & Sm == sn, range(Time)]
  data.table(File = x[, unique(File)], Start = min(DwellTime), End = max(DwellTime), Blockade = Blockade, DwellTime = diff(DwellTime))
}, mc.cores = 10) -> Summ
Summ <- do.call(rbind, Summ)
Summ$Signal <- mapply(function(x) x[2], strsplit(Summ$File, "_"))
Summ$File <- mapply(function(x) x[1], strsplit(Summ$File, "_"))
Summ <- na.omit(Summ)
```

```{r}
ggplot(Summ, aes(x = Blockade, y = DwellTime, color = File)) + 
  geom_point() + 
  theme_classic2(base_size = 15) + 
  lims(x = c(0.1, 0.3))
```

```{r}
ggplot(Summ, aes(Blockade, color = File)) +
  geom_line(stat = "density") + 
  labs(x = "Blockade of L1") + 
  theme_classic(base_size = 15) + 
  facet_wrap( ~ File)
```

```{r}
fit <- Summ[, fitdistr(Blockade, "normal")]
para <- fit$estimate
hist(Summ[, Blockade], prob = TRUE, breaks = 20, xlab = "Blockade of L1", main = "Histogram of L1 blockade")
x <- BUB3$Blockade
curve(dnorm(x, para[1], para[2]), col = 2, add = TRUE)
set.seed(123)
Summ$BsGussian <- sort(rnorm(Summ$Blockade, para[1], para[2]))[rank(Summ$Blockade)]
```

```{r}
para
```

```{r}
hist(Summ$BsGussian, prob = TRUE, 
     breaks = 20, 
     xlim = c(0.1, 0.3), 
     xlab = "Gussian blockade of L1", 
     main = "Histogram of L1 gussian blockade")
```

```{r}
summary(lm(Blockade ~ BsGussian, data = Summ))
```

```{r}
Summ <- merge(Summ, meta, by.x = "File", by.y = "file_name")
```

```{r}
fwrite(Summ, file = file.path(OutDir, "Signal_summary.txt"), sep = "\t", row.names = F, quote = F)
```

