---
title: "Signal"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
params:
  File:
    label: "Select the ABF file: "
    input: file
    value: demo.ABF
  StartTime:
    label: "When the signal start (s): "
    input: numeric
    value: 0
  EndTime:
    label: "When the signal end (s): "
    input: numeric
    value: Inf
  MinL0:
    label: "The minimum current of baseline (pA): "
    input: numeric
    value: 25
  MaxL0:
    label: "The maximum current of baseline (pA): "
    input: numeric
    value: 40
  MinBR:
    label: "The minimum of blockade: "
    input: numeric
    value: 0.2
    min: 0
    max: 1
  MinTime:
    label: "The minimum of dwell time (ms): "
    input: numeric
    value: 0.3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval      = T, #在块中运行代码(default = TRUE)
                      highlight = T, #高亮显示
                      echo      = F, #是否在输出中包含源代码
                      tidy      = T, #是否整理代码
                      error     = T, #是否在输出中包含错误信息
                      warning   = F, #是否在输出中包含警告(default = TRUE)
                      message   = F, #是否在输出中包含参考的信息
                      cache.    = F)
```

```{r}
library(readABF)
library(data.table)
library(S4Vectors)
library(IRanges)
library(changepoint)
library(ggplot2)
library(MASS)
library(strucchange)
library(ggpubr)
KBins3 <- function(sig, minseglen1 = 100, pen.value = 1e-3, penalty = "MBIC") {
  ansmean1 <- suppressWarnings(changepoint::cpt.mean(sig, penalty = penalty, method = "PELT", minseglen = minseglen1, pen.value = pen.value))
  Tab1 <- data.table(P = sig, B1 = rep(seq_len(nseg(ansmean1)), seg.len(ansmean1)))
  Tab2 <- Tab1[, .(Sm = median(P)), by = "B1"]
  res <- merge(Tab1, Tab2, by = "B1")
  res$Sm  
}
CISelect <- function(x, adjust = 1, plot = TRUE) {
  densi <- density(x, adjust = adjust)
  denst <- data.table(x = densi$x, y = densi$y)
  fit_bp = breakpoints(y ~ 1, data = denst, breaks = 2)
  cpt <- denst[fit_bp$breakpoints, x]
  pek <- denst[, .SD[which.max(y), x]]
  
  while (all(pek < cpt) | all(pek > cpt)) {
    adjust <- adjust + 0.1
    densi <- density(x, adjust = adjust)
    denst <- data.table(x = densi$x, y = densi$y)
    fit_bp = breakpoints(y ~ 1, data = denst, breaks = 2)
    cpt <- denst[fit_bp$breakpoints, x]
    pek <- denst[, .SD[which.max(y), x]]
  }
  
  if(plot) {
    plot(densi, main = paste0("density(x = x, adjust = ", adjust, ")"))
    abline(v = cpt)
  }
  cpt
}

mean2 <- function(x, q1 = 0.25, q2 = 0.75) {
  q <- quantile(x, c(q1, q2))
  mean(x[x > min(q) & x < max(q)])
}
```

```{r}
File <- params$File

StartTime <- params$StartTime
EndTime <- params$EndTime

MinL0 <- params$MinL0
MaxL0 <- params$MaxL0

MinBR <- params$MinBR
MinTime <- params$MinTime
```

```{r}
File <- file.path("/mnt/raid61/Personal_data/tangchao/AANanopore/data/other/2021-01-10_002.ABF")
StartTime <- 20
EndTime <- 26

MinL0 <- 25
MaxL0 <- 40

MinBR <- 0.3
MinTime <- 0.3 # ms
```

```{r}
abf <- readABF::readABF(File)
abf <- as.data.table(as.data.frame(abf))
colnames(abf) <- c("Time", "pA")
abf <- abf[Time > StartTime * 60 & Time < EndTime * 60, ]
abf[, pA := - pA]
```

```{r}
abf$Sm <- KBins3(sig = abf$pA, minseglen1 = 5, pen.value = 1e-1, penalty = "MBIC")
```

```{r}
DenSm <- density(abf[, pA], adjust = 1)

L0 <- CISelect(abf[, pA], plot = F)
L0Min <- min(L0) * (1 - MinBR)

plot(DenSm, xlab = "Current (pA)", main = "density of smooth current")
abline(v = L0, lty = 2, col = 2)
abline(v = L0Min, lty = 2, col = 3)
```

```{r}
abf[, L := NULL]
abf[Sm <= max(L0) & Sm >= min(L0), L := "B"] # baseline
abf[Sm < L0Min, L := "U"] # U shape
abf[is.na(L), L := "O"] # Other
```

```{r}
plotS <- function(x) {
  ggplot() + 
    geom_step(data = x, aes(x = Time, y = pA)) + 
    geom_step(data = x, aes(x = Time, y = Sm), color = "red") + 
    theme_classic(base_size = 15)
}
```

```{r}
abs <- IRanges(abf[, pA < max(L0 * (1 - MinBR))])
abs <- abs[width(abs) >= 3]
gap <- gaps(abs)
nw <- which(width(gap) < 50)

abs <- abs[-c(nw - 1, nw + 1)]
gap <- gaps(abs)

FlankL <- mapply(seq_along(abs), FUN = function(i) {
  if(i == 1) {
    min((nrow(abf) - end(abs[i])), 200)
  } else {
    min(200, width(gap[i - 1]))
  }
})

FlankR <- mapply(seq_along(abs), FUN = function(i) {
  if(i == length(abs)) {
    min(start(abs)[1], 200)
  } else {
    min(200, width(gap[i]))
  }
})

start(abs) <- start(abs) - FlankL
end(abs) <- end(abs) + FlankR
```

```{r}
BUB <- lapply(seq_along(abs), function(x) {
  abf[start(abs[x]):end(abs[x]), ]
})
```

```{r}
lapply(BUB, function(x) {
  bc <- x[L == "B", median(Sm)]
  # sn <- x[pA < bc * (1 - MinBR), .N, Sm][which.max(N), Sm]
  sn <- x[pA < bc * (1 - MinBR), min(Sm)]
  Blockade <- tryCatch(1 - x[Sm == sn, mean(pA)]/x[L == "B", mean2(pA)], error = function(e) NA)
  DwellTime <- tryCatch(x[pA < bc * (1 - MinBR), range(Time)], error = function(e) NA)
  data.table(Start = min(DwellTime), End = max(DwellTime), Blockade = Blockade, DwellTime = diff(DwellTime))
}) -> Summ
Summ <- do.call(rbind, Summ)
BUB <- BUB[!Summ[, is.na(Blockade)]]
Summ <- na.omit(Summ)

BUB <- BUB[Summ[, DwellTime] >= MinTime * 1e-3]
Summ <- Summ[DwellTime >= MinTime * 1e-3, ]

BUB <- BUB[Summ[, Blockade] >= MinBR]
Summ <- Summ[Blockade >= MinBR, ]
DT::datatable(Summ)
```

```{r}
ggplot(Summ, aes(x = Blockade, y = DwellTime)) + 
  geom_point() + 
  theme_classic(base_size = 15)
```

```{r fig.width=16, fig.height=16}
ps <- lapply(BUB[1:16], plotS)
cowplot::plot_grid(plotlist = ps, nrow = 4)
```


