---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
knitr::opts_knit$set(base.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(cowplot)
library(parallel)
library(caret)
```

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10)

library(doParallel)
cl <- makePSOCKcluster(10)
registerDoParallel(cl)
```

# NB

```{r}
dir.create("./analysis/03.MachineLearning/Version8/02.Modeling/02.NB/01.Models", recursive = T)
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version8/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  NBC <- train(Class ~ ., data = Train, 
                preProc = c("center", "scale", "YeoJohnson", "nzv"),
                method = "naive_bayes", 
                trControl = fitControl,
                verbose = FALSE,
                ## to evaluate:
                # tuneLength = 50,
                metric = "Accuracy", 
                allowParallel = TRUE)
  saveRDS(NBC, file = paste0("./analysis/03.MachineLearning/Version8/02.Modeling/02.NB/01.Models/NB_Fit", i, ".Rds"))
})
```

# NNet

```{r}
dir.create("./analysis/03.MachineLearning/Version8/02.Modeling/03.NNet/01.Models", recursive = T)
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version8/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  NNet <- train(Class ~ ., data = Train, 
                preProc = c("center", "scale", "YeoJohnson", "nzv"),
                method = "pcaNNet", 
                trControl = fitControl,
                verbose = FALSE,
                ## to evaluate:
                tuneLength = 10,
                metric = "Accuracy", 
                allowParallel = TRUE)
  saveRDS(NNet, file = paste0("./analysis/03.MachineLearning/Version8/02.Modeling/03.NNet/01.Models/NNet_Fit", i, ".Rds"))
})
```

# KNN

```{r}
dir.create("./analysis/03.MachineLearning/Version8/02.Modeling/04.KNN/01.Models", recursive = T)
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version8/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  KNN <- train(Class ~ ., 
               data = Train, 
               method = "knn", 
               tuneLength = 10,
               trControl = fitControl)
  saveRDS(KNN, file = paste0("./analysis/03.MachineLearning/Version8/02.Modeling/04.KNN/01.Models/KNN_Fit", i, ".Rds"))
})
```

# CART

```{r}
dir.create("./analysis/03.MachineLearning/Version8/02.Modeling/05.CART/01.Models", recursive = T)
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version8/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  CART <- train(Class ~ ., data = Train, 
                preProc = c("center", "scale", "YeoJohnson", "nzv"),
                method = "treebag", 
                trControl = fitControl,
                verbose = FALSE,
                ## to evaluate:
                tuneLength = 10,
                metric = "Accuracy", 
                allowParallel = TRUE)
  saveRDS(CART, file = paste0("./analysis/03.MachineLearning/Version8/02.Modeling/05.CART/01.Models/CART_Fit", i, ".Rds"))
})
```

# AdaBoost

```{r}
dir.create("./analysis/03.MachineLearning/Version8/02.Modeling/06.AdaBoost/01.Models", recursive = T)
lapply(1:6, function(i) {
  load(paste0("./analysis/03.MachineLearning/Version8/01.DataPreparation/Train_Data_", i, ".RData"))
  set.seed(825)
  AdaBoost <- train(Class ~ ., data = Train, 
                # preProc = c("center", "scale", "YeoJohnson", "nzv"),
                method = "AdaBoost.M1", 
                trControl = fitControl,
                verbose = FALSE,
                ## to evaluate:
                # tuneLength = 10,
                metric = "Accuracy", 
                allowParallel = TRUE)
  saveRDS(AdaBoost, file = paste0("./analysis/03.MachineLearning/Version8/02.Modeling/06.AdaBoost/01.Models/AdaBoost_Fit", i, ".Rds"))
})
```


