---
title: "Figure 2"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(Biostrings)
library(data.table)
library(patchwork)
library(parallel)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
```

# Signal example

```{r}
files <- list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals", full.names = T)
sig0 <- mclapply(files, fread)
sig0 <- data.table(A = rep(gsub(".signal.txt", "", basename(files)), mapply(nrow, sig0)), do.call(rbind, sig0))
```

```{r}
set.seed(12345)
sigi <- rbind(sig0[State == "Sington" & DwellTime > 1 & SignalCurrentPercent > 80, .SD[sample(.N, 1)], .(A, State)], 
              sig0[State == "Mixtrue" & DwellTime > 1, .SD[sample(.N, 1)], .(A, State)])
```

```{r}
sigi_abf <- mclapply(seq_len(nrow(sigi)), function(i) {
  abf <- readRDS(sigi[i, paste0("./analysis/81.ABFProcessing/ABF/ABF_", File, ".Rds")])
  abf <- abf[Time > sigi[i, StartTime] - 0.001 & Time < sigi[i, EndTime] + 0.001]
  data.table(sigi[i, .(A, AA, State, ID)], abf)
}, mc.cores = 11)
sigi_abf <- do.call(rbind, sigi_abf)
sigi_abf[, State := plyr::mapvalues(State, c("Sington", "Mixtrue"), c("State 1", "State 2"))]
sigi_abf[, State := factor(State, levels = c("State 1", "State 2"))]
sigi_abf[, A := gsub("CbC", "CMC", A)]
sigi_abf[, AA := gsub("CbC", "CMC", AA)]
```

```{r fig.width=4, fig.height=3}
ggplot(sigi_abf[A %in% c("Pro")], aes(x = Time, y = pA, colour = State)) + 
  geom_step() + 
  facet_grid(. ~ State + A, scales = "free", space = "free") + 
  labs(title = "Pro") + 
  theme_light(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        legend.title = element_blank(), 
        strip.background = element_rect(size = 0), 
        strip.text = element_blank(), 
        axis.text.x = element_blank(), axis.ticks.x = element_blank()) -> p1
p23 <- ggpubr::as_ggplot(ggpubr::get_legend(p1))
```

```{r}
sigi_abf <- split(sigi_abf, sigi_abf$ID)
sigi_abf <- lapply(sigi_abf, function(x) {
  x$Time <- x$Time - min(x$Time)
  x$pA2 <- x$pA / sigi[ID %in% x$ID, BaseMean]
  x
})
sigi_abf <- do.call(rbind, sigi_abf)
```

```{r}
ggplot(sigi_abf[A %in% "Ala"], aes(x = Time * 1000, y = pA2, colour = State)) + 
  geom_step() + 
  facet_grid(. ~ State + A, scales = "free", space = "free") + 
  scale_y_continuous(n.breaks = 4) + 
  scale_x_continuous(breaks = c(0, 1)) + 
  labs(title = "Ala", x = "Time (ms)") + 
  theme_light(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        legend.position = "none",
        strip.background = element_rect(size = 0), 
        strip.text = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "line"))
```

```{r}
Ps <- mclapply(sigi_abf[A != "CMC", unique(A)], function(a) {
  ggplot(sigi_abf[A %in% a], aes(x = Time * 1000, y = pA2, colour = State)) + 
    geom_step() + 
    facet_grid(. ~ State + A, scales = "free", space = "free") + 
    scale_y_continuous(n.breaks = 3, limits = c(0, 1)) + 
    scale_x_continuous(breaks = c(0, 1), labels = c("", 1)) + 
    labs(title = a, x = "Time (ms)", y = "Scaled current") + 
    theme_light(base_size = 15) + 
    theme(panel.grid = element_blank(), 
        legend.position = "none",
        strip.background = element_rect(size = 0), 
        strip.text = element_blank(), 
        # axis.text = element_blank(), 
        # axis.ticks = element_blank(), 
        plot.margin = unit(c(0, 0, 0, 0), "line"))
}, mc.cores = 20)
Ps <- c(Ps, list(p23))
```

```{r fig.width=20, fig.height=4}
Ps2 <- lapply(seq_along(Ps), function(i) {
  if(i != 12) {
    Ps[[i]] + theme(axis.title = element_blank())
  } else {
    Ps[[i]]
  }
})
```

```{r fig.width=20, fig.height=4}
aligned_plots <- patchwork::align_patches(Ps2)
cowplot::plot_grid(plotlist = aligned_plots, nrow = 2)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/AA_Example.pdf", width = 20, height = 4)
```


# b

```{r}
Sigs1 <- sig0[State == "Sington"]
SigSumm <- Sigs1[, .(BlockadeSD = sd(Blockade), 
                     BlockadeMean = mean(Blockade), 
                     BlockadeMedian = median(Blockade), 
                     BlockadeQ1 = quantile(Blockade, 1/4), 
                     BlockadeQ3 = quantile(Blockade, 3/4), 
                     DwellTimeSD = sd(DwellTime), 
                     DwellTimeMAD = mad(DwellTime), 
                     DwellTimeQ1 = quantile(DwellTime, 1/4), 
                     DwellTimeQ3 = quantile(DwellTime, 3/4), 
                     DwellTimeMean = mean(DwellTime), 
                     DwellTimeMedian = median(DwellTime)), .(AA, A)]
SigSumm[, A := gsub("CbC", "CMC", A)]
SigSumm[, AA := gsub("CbC", "CMC", AA)]
SigSumm[AA %in% c(AMINO_ACID_CODE[c("E", "D", "H", "R", "K")], "CMC"), Class := "Charged"]
SigSumm[AA %in% AMINO_ACID_CODE[c("L", "I", "M", "V", "A", "F", "G", "W", "P")], Class := "Nonpolar"]
SigSumm[AA %in% AMINO_ACID_CODE[c("S", "N", "Q", "T", "Y", "C")], Class := "Polar"]
SigSumm <- SigSumm[A != "CMC"]
```

```{r}
library(MASS)
library(fitdistrplus)
FIT <- lapply(SigSumm$A, function(x) {
  fitdistr(Sigs1[A == x, Blockade], "normal")$estimate
})
FIT <- data.table(A = SigSumm$A, as.data.table(do.call(rbind, FIT)))
```

```{r}
setkey(SigSumm, A)
setkey(FIT, A)
identical(SigSumm$A, FIT$A)
SigSumm$BlockadeMean <- FIT$mean
SigSumm$BlockadeSD <- FIT$sd
```


```{r}
ggplot() +
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Charged", BlockadeMean][1], sd = SigSumm[Class == "Charged", BlockadeSD][1]), colour = aa_cols[SigSumm[Class == "Charged", A][1]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Charged", BlockadeMean][2], sd = SigSumm[Class == "Charged", BlockadeSD][2]), colour = aa_cols[SigSumm[Class == "Charged", A][2]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Charged", BlockadeMean][3], sd = SigSumm[Class == "Charged", BlockadeSD][3]), colour = aa_cols[SigSumm[Class == "Charged", A][3]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Charged", BlockadeMean][4], sd = SigSumm[Class == "Charged", BlockadeSD][4]), colour = aa_cols[SigSumm[Class == "Charged", A][4]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Charged", BlockadeMean][5], sd = SigSumm[Class == "Charged", BlockadeSD][5]), colour = aa_cols[SigSumm[Class == "Charged", A][5]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Charged", BlockadeMean][6], sd = SigSumm[Class == "Charged", BlockadeSD][6]), colour = aa_cols[SigSumm[Class == "Charged", A][6]]) + 
  scale_x_continuous(limits = c(0.11, 0.26)) + 
  geom_text_repel(data = SigSumm[Class == "Charged"][, .(A = A, x = BlockadeMean, y = dnorm(BlockadeMean, BlockadeMean, BlockadeSD))], aes(x, y, label = A, colour = A)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  scale_y_continuous(breaks = c(0, SigSumm[Class == "Charged", .SD[which.min(BlockadeSD)], ][, dnorm(BlockadeMean, BlockadeMean, BlockadeSD)]/2, SigSumm[Class == "Charged", .SD[which.min(BlockadeSD)], ][, dnorm(BlockadeMean, BlockadeMean, BlockadeSD)]), labels = c(0, 0.5, 1)) + 
  geom_hline(yintercept = 0, colour = "white", size = 1.05) + 
  labs(y = "Relative abundance", x = "Blockade") + 
  facet_wrap(~ "Charged", strip.position = "right") + 
  theme_light(base_size = 15) + 
  theme(panel.grid = element_blank(), strip.background = element_rect(fill = RColorBrewer::brewer.pal(n = 3, "Dark2")[1])) -> p1

ggplot() +
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][1], sd = SigSumm[Class == "Nonpolar", BlockadeSD][1]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][1]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][2], sd = SigSumm[Class == "Nonpolar", BlockadeSD][2]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][2]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][3], sd = SigSumm[Class == "Nonpolar", BlockadeSD][3]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][3]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][4], sd = SigSumm[Class == "Nonpolar", BlockadeSD][4]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][4]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][5], sd = SigSumm[Class == "Nonpolar", BlockadeSD][5]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][5]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][6], sd = SigSumm[Class == "Nonpolar", BlockadeSD][6]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][6]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][7], sd = SigSumm[Class == "Nonpolar", BlockadeSD][7]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][7]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][8], sd = SigSumm[Class == "Nonpolar", BlockadeSD][8]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][8]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Nonpolar", BlockadeMean][9], sd = SigSumm[Class == "Nonpolar", BlockadeSD][9]), colour = aa_cols[SigSumm[Class == "Nonpolar", A][9]]) + 
  scale_x_continuous(limits = c(0.11, 0.26)) + 
  geom_text_repel(data = SigSumm[Class == "Nonpolar"][, .(A = A, x = BlockadeMean, y = dnorm(BlockadeMean, BlockadeMean, BlockadeSD))], aes(x, y, label = A, colour = A)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  scale_y_continuous(breaks = c(0, SigSumm[Class == "Nonpolar", .SD[which.min(BlockadeSD)], ][, dnorm(BlockadeMean, BlockadeMean, BlockadeSD)]/2, SigSumm[Class == "Nonpolar", .SD[which.min(BlockadeSD)], ][, dnorm(BlockadeMean, BlockadeMean, BlockadeSD)]), labels = c(0, 0.5, 1)) + 
  geom_hline(yintercept = 0, colour = "white", size = 1.05) + 
  labs(y = "Relative abundance", x = "Blockade") + 
  facet_wrap(~ "Nonpolar", strip.position = "right") + 
  theme_light(base_size = 15) + 
  theme(panel.grid = element_blank(), strip.background = element_rect(fill = RColorBrewer::brewer.pal(n = 3, "Dark2")[3])) -> p2

ggplot() +
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Polar", BlockadeMean][1], sd = SigSumm[Class == "Polar", BlockadeSD][1]), colour = aa_cols[SigSumm[Class == "Polar", A][1]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Polar", BlockadeMean][2], sd = SigSumm[Class == "Polar", BlockadeSD][2]), colour = aa_cols[SigSumm[Class == "Polar", A][2]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Polar", BlockadeMean][3], sd = SigSumm[Class == "Polar", BlockadeSD][3]), colour = aa_cols[SigSumm[Class == "Polar", A][3]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Polar", BlockadeMean][4], sd = SigSumm[Class == "Polar", BlockadeSD][4]), colour = aa_cols[SigSumm[Class == "Polar", A][4]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Polar", BlockadeMean][5], sd = SigSumm[Class == "Polar", BlockadeSD][5]), colour = aa_cols[SigSumm[Class == "Polar", A][5]]) + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = SigSumm[Class == "Polar", BlockadeMean][6], sd = SigSumm[Class == "Polar", BlockadeSD][6]), colour = aa_cols[SigSumm[Class == "Polar", A][6]]) + 
  scale_x_continuous(limits = c(0.11, 0.26)) + 
  geom_text_repel(data = SigSumm[Class == "Polar"][, .(A = A, x = BlockadeMean, y = dnorm(BlockadeMean, BlockadeMean, BlockadeSD))], aes(x, y, label = A, colour = A)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  scale_y_continuous(breaks = c(0, SigSumm[Class == "Polar", .SD[which.min(BlockadeSD)], ][, dnorm(BlockadeMean, BlockadeMean, BlockadeSD)]/2, SigSumm[Class == "Polar", .SD[which.min(BlockadeSD)], ][, dnorm(BlockadeMean, BlockadeMean, BlockadeSD)]), labels = c(0, 0.5, 1)) + 
  geom_hline(yintercept = 0, colour = "white", size = 1.05) + 
  labs(y = "Relative abundance", x = "Blockade") + 
  facet_wrap(~ "Polar", strip.position = "right") + 
  theme_light(base_size = 15) + 
  theme(panel.grid = element_blank(), strip.background = element_rect(fill = RColorBrewer::brewer.pal(n = 3, "Dark2")[2])) -> p3
```

```{r fig.width=6, fig.height=8}
p1 <- p1 + theme(axis.title = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.tag = element_text(face = "bold", size = 20)) + labs(tag = "a")
p2 <- p2 + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())
p3 <- p3 + theme(axis.title.y = element_blank())
p1 + p2 + p3 + plot_layout(ncol = 1)
```

# c 

```{r}
A_V <- data.table(V = c(87.8, 188.2, 120.1, 115.4, 105.4, 140.9, 145.1, 59.9, 156.3, 166.1, 168, 172.7, 165.2, 189.7, 123.3, 91.7, 118.3, 227.9, 191.2, 138.8), 
                  aa = c("A", "R", "N", "D", "C", "E", "Q", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V"))
A_V[, AA := plyr::mapvalues(aa, names(AMINO_ACID_CODE), AMINO_ACID_CODE)]
aaBlockade <- merge(SigSumm, A_V, by = "AA")
aaBlockade[, Class := factor(Class, levels = c("Charged", "Polar", "Nonpolar"))]
```

```{r fig.height=4, fig.width=4}
ggplot(aaBlockade, aes(x = V, y = BlockadeMean)) + 
  geom_pointrange(mapping = aes(ymin = BlockadeMean - BlockadeSD, ymax = BlockadeMean + BlockadeSD, colour = Class)) + 
  geom_smooth(method = "lm", se = FALSE) + 
  geom_text_repel(aes(label = A)) + 
  stat_cor(label.y.npc = "bottom", label.x.npc = 0.4) + 
  theme_bw(base_size = 15) + 
  labs(y = "Blockade", x = expression("Volume of amino acid (" *10^"-3"*nm^3*")"), tag = "b") +
  theme(legend.position = "none", 
        plot.tag = element_text(face = "bold", size = 20), 
        panel.grid = element_blank(), 
        legend.box.spacing = unit(0, "line"), 
        legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Dark2") -> p4
p4
```


```{r fig.height=4, fig.width=4.5}
ggplot(aaBlockade[Class %in% c("Polar", "Nonpolar") & !A %in% c("Cys", "Pro")], aes(x = V, y = BlockadeMean)) + 
  geom_pointrange(mapping = aes(ymin = BlockadeMean - BlockadeSD, ymax = BlockadeMean + BlockadeSD, colour = Class)) + 
  geom_smooth(method = "lm", se = FALSE) + 
  geom_text_repel(aes(label = A)) + 
  stat_cor(label.y.npc = "bottom", label.x.npc = 0.4) + 
  theme_bw(base_size = 15) + 
  labs(y = "Blockade", x = expression("Volume of amino acid (" *10^"-3"*nm^3*")")) +
  theme(legend.position = "none", 
        plot.tag = element_text(face = "bold", size = 20), 
        panel.grid = element_blank(), 
        legend.box.spacing = unit(0, "line"), 
        legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Dark2")
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig2/FigS1.pdf", width = 4.5, height = 4)
```


```{r}
A_F <- as.data.table(openxlsx::read.xlsx("./data/MetaInfomation/AA_feature.xlsx"))
aaBlockade <- merge(aaBlockade, A_F[, .(AA = Abbreviations, MM = `Molecular.mass.(Da)`, Volume = `Volume.(A3)`)], by = "AA")
```

```{r fig.height=4, fig.width=4}
ggplot(aaBlockade, aes(x = MM, y = BlockadeMean)) + 
  geom_pointrange(mapping = aes(ymin = BlockadeMean - BlockadeSD, ymax = BlockadeMean + BlockadeSD, colour = Class)) + 
  geom_smooth(method = "lm", se = FALSE) + 
  geom_text_repel(aes(label = A)) + 
  stat_cor(label.y.npc = "bottom", label.x.npc = 0.4) + 
  theme_bw(base_size = 15) + 
  labs(y = "Blockade", x = expression("Molecular mass (Da)")) +
  theme(legend.position = "none", 
        panel.grid = element_blank(), 
        legend.box.spacing = unit(0, "line"), 
        legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Dark2")
```

# d 

```{r}
DwellTime <- lapply(Sigs1[, unique(A)], function(aat) {
  ls <- levels(cut_interval(Sigs1[A == aat, DwellTime], 10))
  ls <- mapply(function(x) {
    mean(as.numeric(unlist(strsplit(gsub("\\]", "", gsub("\\[", "", gsub("\\(", "", x))), ","))))
  }, ls)
  ls <- as.numeric(ls)
  bin_N <- ls[as.numeric(cut_interval(Sigs1[A == aat, DwellTime], 10))]
  mydata <- data.table(x = bin_N)[, .(y = .N), x][order(x)]
  exponential.model <- lm(log(y + 1) ~ x, data = mydata)
  timevalues <- mydata[, x]
  # Counts.exponential2 <- exp(predict(exponential.model, list(x = timevalues)))
  # plot(mydata, xlab = "Dwell time (ms)", main = "Histogram of dwell time")
  # lines(timevalues, Counts.exponential2, lwd = 2, col = "red", xlab = "Time (s)", ylab = "Count")
  coefs <- coef(exponential.model)
  # summary(exponential.model)
  # coef(exponential.model)
  A1 <- exp(coefs[1])
  t <- - 1 / coefs[2]
  half_life <- log(0.5) / coefs[2] # half-life
  model_summ <- summary(exponential.model)
  A1_Std.Error <- exp(coefs[1] + coefficients(model_summ)[1, 2]) - A1
  t_Std.Error <- - 1 / (coefs[2] + coefficients(model_summ)[2, 2]) - t
  half_life_Std.Error <- log(0.5) / (coefs[2] + coefficients(model_summ)[2, 2]) - half_life
  model_summ$r.squared
  model_summ$adj.r.squared
  data.table(A = aat, A1, A1.SE = A1_Std.Error, t, t.SE = t_Std.Error, half.life = half_life, half.life_Std.Error = half_life_Std.Error, R2 = model_summ$r.squared, Adj.R2 = model_summ$adj.r.squared)
})
DwellTime <- do.call(rbind, DwellTime)
DwellTime[, AA := substr(A, 1, 3)]
DwellTime[, A := gsub("CbC", "CMC", A)]
DwellTime[, AA := gsub("CbC", "CMC", AA)]
DwellTime[AA %in% c(AMINO_ACID_CODE[c("E", "D", "H", "R", "K")], "CMC"), Class := "Charged"]
DwellTime[AA %in% AMINO_ACID_CODE[c("L", "I", "M", "V", "A", "F", "G", "W", "P")], Class := "Nonpolar"]
DwellTime[AA %in% AMINO_ACID_CODE[c("S", "N", "Q", "T", "Y", "C")], Class := "Polar"]
DwellTime <- DwellTime[A != "CMC"]
DwellTime[, Class := factor(Class, levels = c("Charged", "Nonpolar", "Polar"))]
od <- DwellTime[order(Class, half.life), A]
DwellTime[, A := factor(A, levels = od)]
```

```{r}
Sigs1[, A := factor(A, levels = od)]
Sigs1[, AA := gsub("CbC", "CMC", AA)]
Sigs1[AA %in% c(AMINO_ACID_CODE[c("E", "D", "H", "R", "K")], "CMC"), Class := "Charged"]
Sigs1[AA %in% AMINO_ACID_CODE[c("L", "I", "M", "V", "A", "F", "G", "W", "P")], Class := "Nonpolar"]
Sigs1[AA %in% AMINO_ACID_CODE[c("S", "N", "Q", "T", "Y", "C")], Class := "Polar"]
Sigs1[, Class := factor(Class, levels = c("Charged", "Nonpolar", "Polar"))]
```

```{r}
ggplot() + 
  geom_violin(data = Sigs1[A != "CMC"], aes(x = A, y = DwellTime, colour = Class)) +
  geom_pointrange(data = DwellTime, aes(x = A, y = half.life, ymin = half.life - half.life_Std.Error, ymax = half.life + half.life_Std.Error), size = 0.5) + 
  scale_y_log10() +
  theme_bw(base_size = 15) + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 3, name = "Dark2")[c(1, 3, 2)]) + 
  labs(x = "Amino acid", y = "Dwell time (ms)", tag = "d") + 
  theme(legend.position = "none", 
        plot.tag = element_text(face = "bold", size = 20), 
        panel.grid = element_blank(), 
        legend.title = element_blank()) -> p6
p6
```

```{r eval=FALSE}
openxlsx::write.xlsx(list(Sigs1[A != "CMC"], DwellTime), "./script/00.FigureTables/Rebuttal/NatureMethods/Fig2/d.xlsx")
```

# e

```{r}
IntervalTime <- do.call(rbind, lapply(list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/04.IntervalTime", full.names = T), fread))
```

```{r}
time0 <- merge(merge(IntervalTime, sig0[, .(ID, A, file_id, File, State)], by.x = "SigAfter", by.y = "ID"), sig0[, .(ID, A, file_id, File, State)], by.x = "SigBefore", by.y = "ID")
setnames(time0, "A.x", "A")
setnames(time0, "file_id.x", "file_id")
setnames(time0, "File.x", "File")
```

```{r}
IntervalTime <- merge(time0[, .(GapTime1 = sum(Time1), GapTime2 = sum(Time2)), .(File, file_id)], sig0[, .(SigTime = sum(DwellTime), N = .N, Sington = sum(State == "Sington"), Mixtrue = sum(State == "Mixtrue")), .(File, file_id)], by = c("File", "file_id"))
IntervalTime <- merge(IntervalTime, fread("./data/MetaInfomation/StandardAA_Meta.txt"), by.x = c("File", "file_id"), by.y = c("file_name", "file_id"))
IntervalTime[, ValidTime := GapTime2 * 1000 + SigTime]
IntervalTime[, ValidTime := ValidTime / 1000 / 60]
```

```{r}
IntervalTime[, Freq := N / concentration / ValidTime]
IntervalTime[, AA := gsub("CbC", "CMC", amino_acid)]
IntervalTime[AA %in% c(AMINO_ACID_CODE[c("E", "D", "H", "R", "K")], "CMC"), Class := "Charged"]
IntervalTime[AA %in% AMINO_ACID_CODE[c("L", "I", "M", "V", "A", "F", "G", "W", "P")], Class := "Nonpolar"]
IntervalTime[AA %in% AMINO_ACID_CODE[c("S", "N", "Q", "T", "Y", "C")], Class := "Polar"]
IntervalTime[, Class := factor(Class, levels = c("Charged", "Nonpolar", "Polar"))]
od <- IntervalTime[, median(Freq), .(Class, AA)][order(Class, V1), AA]
IntervalTime[, AA := factor(AA, levels = od)]
```

```{r}
ggplot(IntervalTime[AA != "CMC"], aes(x = AA, y = Freq, colour = Class)) + 
  geom_boxplot() + 
  geom_point() + 
  scale_y_log10(breaks = c(0.1, 0.2, 0.4, 1, 2, 4, 10, 20, 40, 100)) + 
  theme_bw(base_size = 15) + 
  labs(x = "Amino acid", y = expression(Signal~frequency~"("*μM^"-1"*" min"^-1*")"), tag = "c") + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 3, name = "Dark2")[c(1, 3, 2)]) + 
  theme(legend.position = "none", 
        plot.tag = element_text(face = "bold", size = 20), 
        # axis.title.x = element_blank(), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) -> p5
p5
```

```{r eval=FALSE}
openxlsx::write.xlsx(IntervalTime[AA != "CMC"], "./script/00.FigureTables/Rebuttal/NatureMethods/Fig2/e.xlsx")
```

```{r}
IntervalTime[AA %in% AMINO_ACID_CODE[c("D", "E")], Property2 := "Charged(-)"]
IntervalTime[AA %in% AMINO_ACID_CODE[c("K", "R", "H")], Property2 := "Charged(+)"]
IntervalTime[Class != "Charged", Property2 := "Uncharged"]

IntervalTime[AA %in% AMINO_ACID_CODE[c("D", "E")], Property2 := "Charged(-)"]
IntervalTime[AA %in% AMINO_ACID_CODE[c("K", "R", "H")], Property2 := "Charged(+)"]
IntervalTime[Class != "Charged", Property2 := Class]
IntervalTime[, Property2 := factor(Property2, levels = c("Charged(-)", "Charged(+)", "Nonpolar", "Polar"))]
```

```{r fig.height=4, fig.width=4}
my_comp <- list(c("Charged(-)", "Charged(+)"), c("Polar", "Nonpolar"))

ggplot(IntervalTime[AA != "CMC"], aes(x = Property2, y = Freq, colour = Property2)) + 
  geom_boxplot() + 
  geom_point() + 
  scale_y_sqrt() + 
  stat_compare_means(aes(label = ..p.signif..), label.y.npc = 0.8, comparisons = my_comp) + 
  labs(x = "Amino acid", y = expression(Signal~frequency~"("*μM^"-1"*" min"^-1*")"), tag = "e") + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 3, name = "Dark2")[c(1, 1, 3, 2)]) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none", 
        plot.tag = element_text(face = "bold", size = 20), 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 30, hjust = 1), 
        legend.title = element_blank(), 
        panel.grid = element_blank()) -> p7
p7
```



```{r}
State_N <- sig0[, .N, .(A, State)]
State_N <- State_N[, .(State, N, P = N / sum(N) * 100), .(A)]
State_N[, A := factor(A, levels = State_N[State != "Sington", mean(P), A][order(V1), A])]
State_N <- State_N[A != "CbC"]
```

```{r fig.width=4, fig.height=6}
ggplot(State_N, aes(x = A, y = P, fill = State)) + 
  geom_col() + 
  geom_text(aes(label = N), position = position_stack(vjust = 0.5), angle = 0) + 
  scale_fill_brewer(palette = "Paired", guide = guide_legend(reverse = T)) + 
  coord_flip() + 
  theme_bw(base_size = 15) + 
  labs(y = "Percentage (%)", x = expression("Amino acid")) + 
  theme(legend.position = "top", 
        panel.grid = element_blank(), 
        legend.box.spacing = unit(0, "line"), 
        legend.title = element_blank())
```



```{r}
sig00 <- merge(sig0, fread("./data/MetaInfomation/StandardAA_Meta.txt")[, .(AA = amino_acid, concentration, file_id = as.character(file_id))], by = c("AA", "file_id"))
State_N <- sig00[, .N, .(A, State, concentration)]
State_N <- State_N[, .(State, N, P = N / sum(N) * 100), .(A, concentration)]
State_N[, concentration := factor(concentration, levels = c("1", "2", "4", "5", "10", "20", "100", "200"))]
State_N[, A := factor(A, levels = State_N[State != "Sington", mean(P), A][order(V1), A])]
State_N <- State_N[A != "CbC"]
```

```{r fig.width=9, fig.height=5}
ggplot() + 
  geom_point(data = State_N[State == "Sington"], aes(x = A, y = P, colour = concentration)) + 
  geom_col(data = State_N[State == "Sington", mean_sd(P), A], aes(x = A, y = y), fill = NA, colour = "black") + 
  geom_errorbar(data = State_N[State == "Sington", mean_sd(P), A], aes(x = A, y = y, ymin = ymin, ymax = ymax), width = 0.4) + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 9, name = "Reds")[-1], guide = guide_legend(nrow = 2, title = "Concentration (μM)")) + 
  labs(y = "Percentage of \nState 1 signal (%)") + 
  theme_light(base_size = 22) + 
  theme(plot.background = element_blank(), 
        axis.text.x = element_text(angle = 40), 
        legend.position = "top", 
        axis.title.x = element_blank())
```

```{r fig.width=9, fig.height=5}
cairo_pdf("./analysis/00.FigureTables/Rebuttal/NatureMethods/State1_Percentage.pdf", width = 9, height = 5)
ggplot() + 
  geom_point(data = State_N[State == "Sington"], aes(x = A, y = P, colour = concentration)) + 
  geom_col(data = State_N[State == "Sington", mean_sd(P), A], aes(x = A, y = y), fill = NA, colour = "black") + 
  geom_errorbar(data = State_N[State == "Sington", mean_sd(P), A], aes(x = A, y = y, ymin = ymin, ymax = ymax), width = 0.4) + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 9, name = "Reds")[-1], guide = guide_legend(nrow = 2, title = "Concentration (μM)")) + 
  labs(y = "Percentage of \nState 1 signal (%)") + 
  theme_light(base_size = 22) + 
  theme(plot.background = element_blank(), 
        axis.text.x = element_text(angle = 40), 
        legend.position = "top", 
        axis.title.x = element_blank())
dev.off()
```

```{r}
file <- list.files("analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/04.IntervalTime", full.names = T)
IntervalTime <- lapply(file, fread)
names(IntervalTime) <- gsub("_IntervalTime.txt", "", basename(file))
IntervalTime <- data.table(A = rep(names(IntervalTime), mapply(nrow, IntervalTime)), do.call(rbind, IntervalTime))
```

```{r}
meta <- fread("./data/MetaInfomation/StandardAA_Meta.txt")
InteTime <- merge(IntervalTime, meta[concentration > 0, .(file_name, concentration)], by.x = "File", by.y = "file_name")
InteTime[, concentration := factor(concentration, levels = c("1", "2", "4", "5", "10", "20", "100", "200"))]
od <- InteTime[, mean(Time2), A][order(V1), as.character(A)]
InteTime[, AA := factor(A, levels = od)]
```


```{r fig.width=12, fig.height=3}
InteTime[, AA := gsub("CbC", "CMC", AA)]
ggplot(InteTime, aes(x = AA, y = Time2 * 1000, colour = concentration)) + 
  geom_boxplot() + 
  scale_y_log10() + 
  scale_colour_brewer(palette = "Reds", guide = guide_legend(nrow = 1, title = "Concentration (μM)")) + 
  labs(y = "Interval time (ms)") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank())
```

```{r fig.width=12, fig.height=4}
ggplot(InteTime[AA != "CMC"], aes(x = AA, y = Time2 * 1000, colour = concentration)) + 
  geom_violin() + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.9)) + 
  scale_y_log10() + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 9, name = "Reds")[-1], guide = guide_legend(nrow = 1, title = "Concentration (μM)")) + 
  labs(y = "Interval time (ms)") + 
  theme_light(base_size = 22) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank())
```


```{r fig.width=12, fig.height=4}
cairo_pdf("./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig2/IntervalTime_Vs_Concentration.pdf", width = 12, height = 4)
ggplot(InteTime[AA != "CMC"], aes(x = AA, y = Time2 * 1000, colour = concentration)) + 
  geom_violin() + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.9)) + 
  scale_y_log10() + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 9, name = "Reds")[-1], guide = guide_legend(nrow = 1, title = "Concentration (μM)")) + 
  labs(y = "Interval time (ms)") + 
  theme_light(base_size = 22) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank())
dev.off()
```


```{r}
InteTime_I <- InteTime[, .(Mean = mean(Time2), Median = median(Time2)), .(AA, concentration)]
```


```{r}
InteTime_10 <- InteTime[concentration == 10]
InteTime_10[, AA := factor(AA, levels = InteTime_10[concentration == 10, median(Time2), AA][order(V1), as.character(AA)])]

ggplot(InteTime_10, aes(x = AA, y = Time2 * 1000, colour = AA)) + 
  geom_violin() + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.9)) + 
  scale_y_log10() + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(y = "Interval time (ms)", title = "10 uM") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank())

InteTime_100 <- InteTime[concentration == 100]
InteTime_100[, AA := factor(AA, levels = InteTime_100[concentration == 100, median(Time2), AA][order(V1), as.character(AA)])]

ggplot(InteTime_100, aes(x = AA, y = Time2 * 1000, colour = AA)) + 
  geom_violin() + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.9)) + 
  scale_y_log10() + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(y = "Interval time (ms)", title = "100 uM") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "top", 
        axis.title.x = element_blank()) 
```

```{r}
InteTime[AA == "Pro", wilcox.test(Time2 ~ concentration)]
InteTime[AA == "Pro", kruskal.test(Time2 ~ concentration)]
```

```{r}
InteTime_Sub <- InteTime[AA %in% AMINO_ACID_CODE[c("D", "E", "K", "R")] & concentration == 100]
InteTime_Sub <- InteTime[concentration == 100]
InteTime_Sub[AA %in% AMINO_ACID_CODE[c("D", "E")], Property := "Negatively charged"]
InteTime_Sub[AA %in% AMINO_ACID_CODE[c("K", "R", "H")], Property := "Positively charged"]
InteTime_Sub[AA %in% AMINO_ACID_CODE[c("S", "C", "T", "N", "Q", "Y")], Property := "Polar"]
InteTime_Sub[AA %in% AMINO_ACID_CODE[c("G", "A", "V", "L", "M", "I", "P", "F", "W")], Property := "Nonpolar"]
InteTime_Sub[, Property2 := Property]
InteTime_Sub[Property %in% c("Nonpolar", "Polar"), Property2 := "Uncharged"]
InteTime_Sub[, Property2 := factor(Property2, levels = c("Negatively charged", "Uncharged", "Positively charged"))]
```

```{r fig.width=3, fig.height=4}
ggplot(InteTime_Sub, aes(x = Property2, y = Time2 * 1000, colour = Property2)) + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.3)) + 
  scale_y_log10() + 
  labs(y = "Interval time (ms)") + 
  scale_colour_brewer(palette = "Set1", guide = guide_legend(ncol = 1)) + 
  # stat_compare_means(method = "anova") +
  stat_compare_means(aes(label = ..p.signif..), label.y.npc = 0.95) +
  theme_light(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        legend.position = "none",
        axis.text.x = element_text(angle = 60, hjust = 1), 
        legend.title = element_blank())
```


```{r fig.width=3, fig.height=4}
ggplot(InteTime_Sub[Property2 == "Uncharged"], aes(x = Property, y = Time2 * 1000, colour = Property)) + 
  geom_boxplot(outlier.shape = NA, width = .5, position = position_dodge(width = 0.3)) + 
  scale_y_log10() + 
  labs(y = "Interval time (ms)") + 
  scale_colour_brewer(palette = "Set2", guide = guide_legend(ncol = 1)) + 
  # stat_compare_means(method = "anova") +
  stat_compare_means(aes(label = ..p.signif..), label.y.npc = 0.95) +
  theme_light(base_size = 15) + 
  theme(axis.title.x = element_blank(), 
        legend.position = "none",
        axis.text.x = element_text(angle = 60, hjust = 1), 
        legend.title = element_blank())
```


```{r fig.height=10, fig.width=18, echo=FALSE}
design <- "
  1111144455555
  1111144455555
  2222244455555
  2222266666777
  3333366666777
  3333366666777
"
p1 + p2 + p3 + p4 + p5 + p6 + p7 + 
  plot_layout(design = design)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig2/Fig2.pdf", width = 18, height = 10)
```

```{r}
cairo_pdf("./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig2/Fig2.pdf", width = 18, height = 10)
p1 + p2 + p3 + p4 + p5 + p6 + p7 + 
  plot_layout(design = design)
dev.off()
```

```{r}
openxlsx::write.xlsx(sig0[, .N, .(A, State)], "./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig2/AA_State_N.xlsx")
```


```{r}
DwellTime[, DwellTime := paste(round(t, 3), "±", round(t.SE, 3))]
SigSumm[, Blockade := paste(round(BlockadeMean, 3), "±", round(BlockadeSD, 4))]
```

```{r}
SigFreq <- as.data.table(openxlsx::read.xlsx("./script/00.FigureTables/Rebuttal/NatureMethods/Fig2/e.xlsx"))
SigFreq <- SigFreq[, .(Frequency = paste(round(mean(Freq), 3), "±", round(sd(Freq), 3))), AA]
```

```{r}
Tab_Summ <- merge(merge(SigSumm[, .(A, AA, Blockade)], DwellTime[, .(A, AA, DwellTime)], by = c("AA", "A")), SigFreq, by = "AA")
openxlsx::write.xlsx(Tab_Summ, "./analysis/00.FigureTables/Rebuttal/NatureMethods/Fig2/AA_summary.xlsx")
```




```{r}
ggplot() +
  geom_histogram(data = Sigs1[A == "Ala", ], aes(Blockade, after_stat(density)), binwidth = 0.001, fill = "grey") + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = FIT[A == "Ala", mean], sd = FIT[A == "Ala", sd]), colour = "red", size = 1.2) + 
  labs(title = "Ala", subtitle = FIT[A == "Ala", paste("Mean =", round(mean, 3), "; SD =", round(sd, 4))]) + 
  ggthemes::theme_base(base_size = 10) + 
  theme(plot.background = element_blank())
```

```{r}
psl <- lapply(FIT[, A], function(aat) {
  ggplot() +
  geom_histogram(data = Sigs1[A == aat, ], aes(Blockade, after_stat(density)), binwidth = 0.001, fill = "grey") + 
  stat_function(fun = dnorm, n = 1024, args = list(mean = FIT[A == aat, mean], sd = FIT[A == aat, sd]), colour = "red", size = 1.2) + 
  labs(title = aat, subtitle = FIT[A == aat, paste("Mean =", round(mean, 3), "; SD =", round(sd, 4))]) + 
  ggthemes::theme_base(base_size = 10) + 
  theme(plot.background = element_blank())
})
```

```{r fig.width=9, fig.height=14}
cowplot::plot_grid(plotlist = psl, nrow = 7)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/AA_Blockade.pdf", width = 9, height = 14)
```




