---
title: "Supplementary File: Extracting and describing standard aminio acid signals from noise"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output:
  pdf_document:
    toc: yes
    toc_depth: '4'
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r echo=FALSE}
library(factoextra)
library(data.table)
library(Biostrings)
library(patchwork)
library(gridExtra)
library(ggpmisc)
library(ggplot2)
library(ggrepel)
library(IRanges)
library(ggExtra)
library(dplyr)
```

```{r echo=FALSE}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}
```

## His

```{r echo=FALSE, fig.width=24, fig.height=6}
aat <- "His"
bgsignal <- fread(paste0("./analysis/81.ABFProcessing/SelectedSignals/", aat, "_background.txt"))
bgsignal[, file_id := as.character(file_id)]
bgsignal[, File := gsub("\\.[0-9]", "", file_id)]
bgsignal[, ID := paste0("Noise_", ID)]

dataset <- fread(paste0("./analysis/81.ABFProcessing/SelectedSignals/", aat, "_signal.txt"))
dataset[, file_id := as.character(file_id)]
dataset[, File := gsub("\\.[0-9]", "", file_id)]
dataset[, ID := paste0(aat, "_", ID)]

FeatureMatrix <- paste0("./analysis/81.ABFProcessing/FeatureMatrix/FeatureMatrix_", unique(dataset$File), ".txt")
FeatureMatrix <- do.call(rbind, lapply(FeatureMatrix, fread))
FeatureMatrix[, ID := paste0(aat, "_", ID)]
FeatureMatrix <- FeatureMatrix[ID %in% dataset[, ID]]
FeatureMatrix[, AA := aat]
setkey(FeatureMatrix, ID)
FeatureMatrix <- FeatureMatrix[dataset$ID, ]
FeatureMatrix <- data.frame(FeatureMatrix[, grepl("^X", colnames(FeatureMatrix)) | grepl("DwellTime", colnames(FeatureMatrix)), with = F], row.names = FeatureMatrix[[1]])

LineMat <- melt.data.table(as.data.table(FeatureMatrix, keep.rownames = "ID"), id.vars = "ID")[variable != "DwellTime"]
LineMat[, x := as.numeric(gsub("^X", "", variable))]
LineMat[, Blockade := 1 - x/1000]
LineMat <- LineMat[, .SD[, .(alpha = value/sum(value), Blockade)], ID]
```

```{r echo=FALSE}
sig1 <- lapply(list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat, full.names = T), fread)
sig1 <- data.table(A = rep(gsub(".signal.txt", "", list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals/", aat)), mapply(nrow, sig1)), do.call(rbind, sig1))
```

```{r echo=FALSE}
bgsignal$D <- bgsignal[, get_density(x = Blockade, y = log10(DwellTime))]
dataset$D <- dataset[, get_density(x = Blockade, y = log10(DwellTime))]
data1 <- dataset[DwellTime < max(DwellTime)]

ggplot(data = bgsignal[order(D)], mapping = aes(x = Blockade, y = DwellTime)) + 
  geom_density_2d_filled(aes(fill = ..level..), contour_var = "ndensity", breaks = seq(0, 1, length.out = 100)) + 
  geom_point(aes(alpha = pmin(D + .02, 1), colour = File), size = .1) + 
  scale_y_log10(limits = data1[, range(DwellTime)]) + 
  scale_x_continuous(limits = data1[, range(Blockade)]) + 
  scale_colour_brewer(palette = "Set2") + 
  scale_fill_manual(values = c(scales::alpha("grey20", 0:99/99), RColorBrewer::brewer.pal(n = dataset[, length(unique(File))], name = "Dark2")), aesthetics = c("fill")) + 
    labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        # plot.margin = unit(c(0, 1, 0, 1), "line"), 
        legend.position = "none") -> p1

ggplot(data = dataset[order(D)], mapping = aes(x = Blockade, y = DwellTime)) + 
  geom_density_2d_filled(aes(fill = ..level..), contour_var = "ndensity", breaks = seq(0, 1, length.out = 100)) + 
  geom_point(aes(alpha = pmin(D + .02, 1), colour = File), size = .1) + 
  scale_y_log10(limits = data1[, range(DwellTime)]) + 
  scale_x_continuous(limits = data1[, range(Blockade)]) + 
  scale_colour_brewer(palette = "Set2") + 
  scale_fill_manual(values = c(scales::alpha("grey20", 0:99/99), RColorBrewer::brewer.pal(n = dataset[, length(unique(File))], name = "Dark2")), aesthetics = c("fill")) + 
    labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        # plot.margin = unit(c(0, 1, 0, 1), "line"), 
        legend.position = "none") -> p2

ggplot(data = dataset[order(D)], mapping = aes(x = Blockade, y = DwellTime)) + 
  geom_point(aes(alpha = pmin(D + .02, 1), colour = ifelse(ID %in% sig1$ID, "signal", "noise")), size = .5) + 
  scale_y_log10(limits = data1[, range(DwellTime)]) + 
  scale_x_continuous(limits = data1[, range(Blockade)]) + 
  scale_colour_brewer(palette = "Set1", direction = -1) + 
  scale_fill_manual(values = c(scales::alpha("#67000D", 0:99/99), RColorBrewer::brewer.pal(n = 4, name = "Dark2")), aesthetics = c("fill")) + 
  guides(alpha = "none", colour = guide_legend(reverse = T)) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = c(0.8, 0.9), 
        legend.background = element_blank(), 
        # plot.margin = unit(c(0, 1, 0, 1), "line"),  
        panel.grid = element_blank()) -> p3

ggplot(data = dataset[ID %in% sig1$ID][order(D)], mapping = aes(x = Blockade, y = DwellTime)) + 
  geom_point(aes(colour = File), size = 1) + 
  scale_y_log10() + 
  scale_colour_brewer(palette = "Set2", direction = -1) + 
  scale_fill_manual(values = c(scales::alpha("#67000D", 0:99/99), RColorBrewer::brewer.pal(n = 4, name = "Dark2")), aesthetics = c("fill")) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = "none", 
        # plot.margin = unit(c(0, 1, 0, 1), "line"), 
        panel.grid = element_blank()) -> p4
```

```{r echo=FALSE}
ggplot(sig1, aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(aes(shape = as.character(File)), alpha = 0.5) + 
  scale_y_log10() + 
  scale_colour_brewer(palette = "Set2") + 
  guides(shape = "none") + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        legend.box.background = element_blank(), 
        plot.margin = unit(c(0, 1, 1, 1), "line"),
        legend.position = c(0.5, 0.9)) -> p11
```

```{r echo=FALSE}
ggplot(sig1, aes(x = Blockade, y = DwellTime, colour = ifelse(State == "Sington", "State 1", "State 2"))) + 
  geom_point(aes(shape = as.character(File)), alpha = 0.5) + 
  scale_y_log10() + 
  guides(colour = guide_legend(nrow = 1, reverse = T), shape = "none") + 
  labs(y = "Dwell time (ms)") + 
  facet_wrap(~ A) + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_blank(), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        legend.box.background = element_blank(), 
        plot.margin = unit(c(0, 1, 1, 1), "line"),
        legend.position = "none") -> p4
```

```{r echo=FALSE}
ggplot(sig1, aes(x = Blockade, fill = ifelse(State == "Sington", "State 1", "State 2"))) + 
  geom_histogram(position = position_dodge(), binwidth = 0.001) + 
  guides(fill = guide_legend(nrow = 1, reverse = F)) + 
  facet_wrap(~ A) + 
  theme_minimal(base_size = 15) + 
  theme(panel.grid = element_blank(), 
        axis.title = element_blank(), 
        plot.margin = unit(c(1, 1, 0, 1), "line"),
        axis.text = element_blank(), 
        axis.ticks = element_blank(), 
        strip.background = element_rect(size = 0), 
        strip.text = element_blank(),
        legend.position = c(0.7, 0.5), 
        legend.key.width = unit(0.4, "line"), 
        legend.box.spacing = unit(0, "line"), 
        plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank()) -> p5
# p5
```

```{r fig.height=6, fig.width=10, eval=FALSE, echo=FALSE}
p5 / p4 + plot_layout(heights = c(1, 3))
```

```{r echo=FALSE}
tab1 <- merge(LineMat, sig1[, .(A, AA, ID, State)])
tab2 <- sig1[, .(.N, ID = list(ID)), .(A, State)]
tab2[, State := plyr::mapvalues(State, c("Sington", "Mixtrue"), c("State 1", "State 2"))]
tab2[, L := paste0(State, "\n", N)]
tab2 <- data.table(tab2[rep(seq_len(nrow(tab2)), mapply(length, tab2$ID))], ID0 = unlist(tab2$ID))
tab1 <- merge(tab1, tab2[, .(ID0, L)], by.x = "ID", by.y = "ID0")
tab1[, L := factor(L, levels = c("State 1\n193", "State 2\n653", "State 1\n306", "State 2\n1032"))]
```

```{r echo=FALSE}
ggplot(tab1, aes(x = Blockade, y = ID, alpha = alpha, colour = L)) + 
  geom_line() + 
  scale_colour_brewer(palette = "Dark2") + 
  facet_grid(L + A ~ ., scales = "free_y", space = "free") + 
  theme_classic(base_size = 15) + 
  theme(axis.text.y = element_blank(), 
        # axis.title.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.line.y = element_blank(),
        strip.placement = "inside", 
        strip.text.y = element_text(angle = 0), 
        strip.background = element_blank(), 
        panel.background = element_blank(), 
        plot.background = element_blank(), 
        plot.tag = element_text(size = 20, face = "bold"), 
        legend.position = "none") + 
  labs(x = "Blockade", y = "Signal") -> p6
p6
```

```{r echo=FALSE}
ls <- levels(cut_interval(sig1[A == "His1" & State == "Sington", DwellTime], 10))
ls <- mapply(function(x) {
  mean(as.numeric(unlist(strsplit(gsub("\\]", "", gsub("\\[", "", gsub("\\(", "", x))), ","))))
}, ls)
ls <- as.numeric(ls)
bin_N <- ls[as.numeric(cut_interval(sig1[A == "His1" & State == "Sington", DwellTime], 10))]
mydata <- data.table(x = bin_N)[, .(y = .N), x][order(x)]
exponential.model <- lm(log(y + 1) ~ x, data = mydata)
f <- function(x) exp(predict(exponential.model, list(x = x)))

model_summ <- summary(exponential.model)
coefs <- coef(exponential.model)
A1 <- exp(coefs[1])
t <- - 1 / coefs[2]
half_life <- log(0.5) / coefs[2] # half-life
half_life_Std.Error <- log(0.5) / (coefs[2] + coefficients(model_summ)[2, 2]) - half_life
A1_Std.Error <- exp(coefs[1] + coefficients(model_summ)[1, 2]) - A1
t_Std.Error <- - 1 / (coefs[2] + coefficients(model_summ)[2, 2]) - t
tab <- data.table(x = c("equation", "A1", "t1", "R-squared", "Adjusted R-squared", "half-life"), 
                  y = c("y = A1*exp(-x/t1)", paste(round(A1, 2), "±", round(A1_Std.Error, 2)), paste(round(t, 2), "±", round(t_Std.Error, 2)), round(model_summ$r.squared, 3), round(model_summ$adj.r.squared, 3), paste(round(half_life, 2), "±", round(half_life_Std.Error, 2))))
```

```{r echo=FALSE}
ggplot(mydata, aes(x = x, y = y)) + 
  geom_col(width = 1.9, alpha = 0.5, fill = "#1B9E77") + 
  stat_function(fun = f, colour = "#1B9E77") + 
  annotation_custom(tableGrob(tab, rows = NULL, cols = NULL, theme = ttheme_gtbw()), xmin = mydata[, max(x) * 0.5], xmax = mydata[, max(x)], ymin = mydata[, max(y) * 0.5], ymax = mydata[, max(y)]) + 
  labs(x = "Dwell time (ms)", y = "Count") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = "none", 
        panel.grid = element_blank()) -> p7_1
```

```{r echo=FALSE}
ls <- levels(cut_interval(sig1[A == "His1" & State != "Sington", DwellTime], 10))
ls <- mapply(function(x) {
  mean(as.numeric(unlist(strsplit(gsub("\\]", "", gsub("\\[", "", gsub("\\(", "", x))), ","))))
}, ls)
ls <- as.numeric(ls)
bin_N <- ls[as.numeric(cut_interval(sig1[A == "His1" & State != "Sington", DwellTime], 10))]
mydata2 <- data.table(x = bin_N)[, .(y = .N), x][order(x)]
exponential.model2 <- lm(log(y + 1) ~ x, data = mydata2)
f2 <- function(x) exp(predict(exponential.model2, list(x = x)))

model_summ <- summary(exponential.model2)
coefs <- coef(exponential.model2)
A1 <- exp(coefs[1])
t <- - 1 / coefs[2]
half_life <- log(0.5) / coefs[2] # half-life
half_life_Std.Error <- log(0.5) / (coefs[2] + coefficients(model_summ)[2, 2]) - half_life
A1_Std.Error <- exp(coefs[1] + coefficients(model_summ)[1, 2]) - A1
t_Std.Error <- - 1 / (coefs[2] + coefficients(model_summ)[2, 2]) - t
tab2 <- data.table(x = c("equation", "A1", "t1", "R-squared", "Adjusted R-squared", "half-life"), 
                  y = c("y = A1*exp(-x/t1)", paste(round(A1, 2), "±", round(A1_Std.Error, 2)), paste(round(t, 2), "±", round(t_Std.Error, 2)), round(model_summ$r.squared, 3), round(model_summ$adj.r.squared, 3), paste(round(half_life, 2), "±", round(half_life_Std.Error, 2))))
```

```{r echo=FALSE}
ggplot(mydata2, aes(x = x, y = y)) + 
  geom_col(alpha = 0.5, fill = "#D95F02") + 
  stat_function(fun = f2, colour = "#D95F02") + 
  annotation_custom(tableGrob(tab2, rows = NULL, cols = NULL, theme = ttheme_gtbw()), xmin = mydata2[, max(x) * 0.5], xmax = mydata2[, max(x)], ymin = mydata2[, max(y) * 0.8], ymax = mydata2[, max(y)]) + 
  labs(x = "Dwell time (ms)", y = "Count") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = "none", 
        panel.grid = element_blank()) -> p7_2
```


```{r echo=FALSE}
ls <- levels(cut_interval(sig1[A == "His2" & State == "Sington", DwellTime], 10))
ls <- mapply(function(x) {
  mean(as.numeric(unlist(strsplit(gsub("\\]", "", gsub("\\[", "", gsub("\\(", "", x))), ","))))
}, ls)
ls <- as.numeric(ls)
bin_N <- ls[as.numeric(cut_interval(sig1[A == "His2" & State == "Sington", DwellTime], 10))]
mydata3 <- data.table(x = bin_N)[, .(y = .N), x][order(x)]
exponential.model3 <- lm(log(y + 1) ~ x, data = mydata3)
f3 <- function(x) exp(predict(exponential.model3, list(x = x)))

model_summ <- summary(exponential.model3)
coefs <- coef(exponential.model3)
A1 <- exp(coefs[1])
t <- - 1 / coefs[2]
half_life <- log(0.5) / coefs[2] # half-life
half_life_Std.Error <- log(0.5) / (coefs[2] + coefficients(model_summ)[2, 2]) - half_life
A1_Std.Error <- exp(coefs[1] + coefficients(model_summ)[1, 2]) - A1
t_Std.Error <- - 1 / (coefs[2] + coefficients(model_summ)[2, 2]) - t
tab3 <- data.table(x = c("equation", "A1", "t1", "R-squared", "Adjusted R-squared", "half-life"), 
                  y = c("y = A1*exp(-x/t1)", paste(round(A1, 2), "±", round(A1_Std.Error, 2)), paste(round(t, 2), "±", round(t_Std.Error, 2)), round(model_summ$r.squared, 3), round(model_summ$adj.r.squared, 3), paste(round(half_life, 2), "±", round(half_life_Std.Error, 2))))
```

```{r echo=FALSE}
ggplot(mydata3, aes(x = x, y = y)) + 
  geom_col(alpha = 0.5, fill = "#7570B3") + 
  stat_function(fun = f3, colour = "#7570B3") + 
  annotation_custom(tableGrob(tab3, rows = NULL, cols = NULL, theme = ttheme_gtbw()), xmin = mydata3[, max(x) * 0.5], xmax = mydata3[, max(x)], ymin = mydata3[, max(y) * 0.5], ymax = mydata3[, max(y)]) + 
  labs(x = "Dwell time (ms)", y = "Count") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = "none", 
        panel.grid = element_blank()) -> p7_3
```


```{r echo=FALSE}
ls <- levels(cut_interval(sig1[A == "His2" & State != "Sington", DwellTime], 10))
ls <- mapply(function(x) {
  mean(as.numeric(unlist(strsplit(gsub("\\]", "", gsub("\\[", "", gsub("\\(", "", x))), ","))))
}, ls)
ls <- as.numeric(ls)
bin_N <- ls[as.numeric(cut_interval(sig1[A == "His2" & State != "Sington", DwellTime], 10))]
mydata4 <- data.table(x = bin_N)[, .(y = .N), x][order(x)]
exponential.model4 <- lm(log(y + 1) ~ x, data = mydata4)
f4 <- function(x) exp(predict(exponential.model4, list(x = x)))

model_summ <- summary(exponential.model4)
coefs <- coef(exponential.model4)
A1 <- exp(coefs[1])
t <- - 1 / coefs[2]
half_life <- log(0.5) / coefs[2] # half-life
half_life_Std.Error <- log(0.5) / (coefs[2] + coefficients(model_summ)[2, 2]) - half_life
A1_Std.Error <- exp(coefs[1] + coefficients(model_summ)[1, 2]) - A1
t_Std.Error <- - 1 / (coefs[2] + coefficients(model_summ)[2, 2]) - t
tab4 <- data.table(x = c("equation", "A1", "t1", "R-squared", "Adjusted R-squared", "half-life"), 
                  y = c("y = A1*exp(-x/t1)", paste(round(A1, 2), "±", round(A1_Std.Error, 2)), paste(round(t, 2), "±", round(t_Std.Error, 2)), round(model_summ$r.squared, 3), round(model_summ$adj.r.squared, 3), paste(round(half_life, 2), "±", round(half_life_Std.Error, 2))))
```

```{r echo=FALSE}
ggplot(mydata4, aes(x = x, y = y)) + 
  geom_col(alpha = 0.5, fill = "#E7298A") + 
  stat_function(fun = f4, colour = "#E7298A") + 
  annotation_custom(tableGrob(tab4, rows = NULL, cols = NULL, theme = ttheme_gtbw()), xmin = mydata4[, max(x) * 0.5], xmax = mydata4[, max(x)], ymin = mydata4[, max(y) * 0.5], ymax = mydata4[, max(y)]) + 
  labs(x = "Dwell time (ms)", y = "Count") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.position = "none", 
        panel.grid = element_blank()) -> p7_4
```


```{r echo=FALSE}
sig1[, File := as.character(File)]
HighFreqFile <- gsub("\\.[0-9]", "", sig1[, max(table(round(StartTime))), File][order(V1, decreasing = T), File])
```

```{r fig.height=2, fig.width=12, echo=FALSE}
abf1 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", HighFreqFile[1], ".Rds"))
time1 <- as.numeric(names(sig1[File == HighFreqFile[1]][, which.max(table(round(StartTime)))]))

ggplot() + 
  geom_step(data = abf1[round(Time) == time1], mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 4) + 
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  labs(x = "Time (s)", y = "Current (pA)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank()) -> p12

if(sig1[A == "His1"][, any(File == HighFreqFile[1] & State == "Sington" & round(StartTime) == time1)]) {
  p12 <- p12 + geom_rect(data = sig1[A == "His1"][File == HighFreqFile[1] & State == "Sington" & round(StartTime) == time1], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf1[round(Time) == time1, min(pA)], ymax = abf1[round(Time) == time1, max(pA)]), fill = "#1B9E77", alpha = 0.2)
}

if(sig1[A == "His1"][, any(File == HighFreqFile[1] & State == "Mixtrue" & round(StartTime) == time1)]) {
  p12 <- p12 + geom_rect(data = sig1[A == "His1"][File == HighFreqFile[1] & State == "Mixtrue" & round(StartTime) == time1], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf1[round(Time) == time1, min(pA)], ymax = abf1[round(Time) == time1, max(pA)]), fill = "#D95F02", alpha = 0.2)
}

if(sig1[A == "His2"][, any(File == HighFreqFile[1] & State == "Sington" & round(StartTime) == time1)]) {
  p12 <- p12 + geom_rect(data = sig1[A == "His2"][File == HighFreqFile[1] & State == "Sington" & round(StartTime) == time1], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf1[round(Time) == time1, min(pA)], ymax = abf1[round(Time) == time1, max(pA)]), fill = "#7570B3", alpha = 0.2)
}

if(sig1[A == "His2"][, any(File == HighFreqFile[1] & State == "Mixtrue" & round(StartTime) == time1)]) {
  p12 <- p12 + geom_rect(data = sig1[A == "His2"][File == HighFreqFile[1] & State == "Mixtrue" & round(StartTime) == time1], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf1[round(Time) == time1, min(pA)], ymax = abf1[round(Time) == time1, max(pA)]), fill = "#E7298A", alpha = 0.2)
}

p12 <- p12 + theme(axis.title.x = element_blank(), plot.margin = unit(c(1, 1, 0.25, 1), "line"), )
```

```{r fig.height=2, fig.width=12, echo=FALSE}
abf2 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", HighFreqFile[2], ".Rds"))
time2 <- as.numeric(names(sig1[File == HighFreqFile[2]][, which.max(table(round(StartTime)))]))

ggplot() + 
  geom_step(data = abf2[round(Time) == time2], mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 4) + 
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  labs(x = "Time (s)", y = "Current (pA)") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank()) -> p13

if(sig1[A == "His1"][, any(File == HighFreqFile[2] & State == "Sington" & round(StartTime) == time2)]) {
  p13 <- p13 + geom_rect(data = sig1[A == "His1"][File == HighFreqFile[2] & State == "Sington" & round(StartTime) == time2], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf2[round(Time) == time2, min(pA)], ymax = abf2[round(Time) == time2, max(pA)]), fill = "#1B9E77", alpha = 0.2)
}

if(sig1[A == "His1"][, any(File == HighFreqFile[2] & State == "Mixtrue" & round(StartTime) == time2)]) {
  p13 <- p13 + geom_rect(data = sig1[A == "His1"][File == HighFreqFile[2] & State == "Mixtrue" & round(StartTime) == time2], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf2[round(Time) == time2, min(pA)], ymax = abf2[round(Time) == time2, max(pA)]), fill = "#D95F02", alpha = 0.2)
}

if(sig1[A == "His2"][, any(File == HighFreqFile[2] & State == "Sington" & round(StartTime) == time2)]) {
  p13 <- p13 + geom_rect(data = sig1[A == "His2"][File == HighFreqFile[2] & State == "Sington" & round(StartTime) == time2], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf2[round(Time) == time2, min(pA)], ymax = abf2[round(Time) == time2, max(pA)]), fill = "#7570B3", alpha = 0.2)
}

if(sig1[A == "His2"][, any(File == HighFreqFile[2] & State == "Mixtrue" & round(StartTime) == time2)]) {
  p13 <- p13 + geom_rect(data = sig1[A == "His2"][File == HighFreqFile[2] & State == "Mixtrue" & round(StartTime) == time2], 
                         mapping = aes(xmin = StartTime, xmax = EndTime, ymin = abf2[round(Time) == time2, min(pA)], ymax = abf2[round(Time) == time2, max(pA)]), fill = "#E7298A", alpha = 0.2)
}

p13 <- p13 + theme(plot.tag = element_blank(), plot.margin = unit(c(0.25, 1, 1, 1), "line"))
```

```{r fig.height=14, fig.width=12, echo=FALSE}
design <- "
  11112222
  11112222
  11112222
  11112222
  33334444
  33334444
  33334444
  33334444
  55555666
  55555666
  55555666
  77777666
  77777666
  77777666
  77777666
"
p1 + p2 + p3 + p11 + p5 + p6 + p4 + 
  plot_layout(design = design) + 
  plot_annotation(tag_levels = 'a')
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/His12_1.pdf", width = 12, height = 14)
```

```{r fig.width=12, fig.height=6, echo=FALSE}
ps1 <- cowplot::plot_grid(p7_1, p7_2, p7_3, p7_4, labels = c("a", "b", "c", "d"), label_size = 20, label_y = 1.02)
```

```{r fig.width=12, fig.height=10, echo=FALSE}
cowplot::plot_grid(ps1, p12, p13, ncol = 1, labels = c("", "e", ""), label_size = 20, rel_heights = c(6, 2, 2), label_y = 1.02)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/His12_2.pdf", width = 12, height = 10)
```

```{r}
load("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/His/Modeling_Data.RData")
model1 <- readRDS("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/His/RF_model.Rds")
```

```{r}
test_res <- data.table(ID = Sigs_Test_FM$ID, Obse = Sigs_Test$A, Pred = predict(model1, Sigs_Test_FM), Prob = apply(predict(model1, Sigs_Test_FM, type = "prob"), 1, max))
test_res[, Obse := factor(Obse, levels = test_res[, levels(Pred)])]
test_res[, mean(Obse == Pred)]
```

```{r}
cM <- test_res[, confusionMatrix(Pred, Obse)]
```

```{r fig.width=4, fig.height=4}
pdf("./analysis/00.FigureTables/Rebuttal/NatureMethods/His12_3.pdf", width = 4, height = 4)
pheatmap::pheatmap(cM$table, display_numbers = T, legend = F, cluster_rows = F, cluster_cols = F, fontsize = 15, fontsize_number = 15, number_format = "%.0f", 
                   color = colorRampPalette(RColorBrewer::brewer.pal(n = 7, name = "Reds"))(100))
dev.off()
```



