---
title: "AANanopore"
author: "Chao Tang"
date: "2022/7/26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval      = T, # 在块中运行代码(default = TRUE)
                      highlight = T, # 高亮显示
                      echo      = F, # 是否在输出中包含源代码
                      tidy      = T, # 是否整理代码
                      error     = T, # 是否在输出中包含错误信息
                      warning   = F, # 是否在输出中包含警告(default = TRUE)
                      message   = F, # 是否在输出中包含参考的信息
                      cache.    = F)
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r warning=FALSE}
library(data.table)
library(patchwork)
library(IRanges)
library(caret)
library(shiny)
library(plotly)
library(ggpubr)
```

```{r}
aa_cols <- c(RColorBrewer::brewer.pal(n = 8, "Accent")[-c(1, 4, 5, 8)], 
             RColorBrewer::brewer.pal(n = 11, "PiYG")[c(4, 9, 11)], 
             ggsci::pal_aaas()(10), 
             ggsci::pal_locuszoom()(7)[-c(3, 6, 7)], 
             RColorBrewer::brewer.pal(n = 3, name = "Set2")[1:2])
aa_cols <- plyr::mapvalues(aa_cols, "#D43F3AFF", RColorBrewer::brewer.pal(n = 8, name = "BrBG")[1])
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CbC", "His1", "His2")
names(aa_cols) <- c(AMINO_ACID_CODE[1:20], "CMC", "His1", "His2")
```

```{r}
get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

KnnSelecting <- function(signals, dists, dist_method = "euclidean", k = 20, noise = 0) {
  stopifnot(noise < k)
  if(is(dists, "dist")) {
    knn1 <- dbscan::kNN(dists, k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists, "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  } else {
    knn1 <- dbscan::kNN(dists[[dist_method]], k = k)
    knn2 <- apply(knn1$id, 2, function(x) x %in% which(attr(dists[[dist_method]], "Labels") %in% grep("^Noise", rownames(knn1$id), value = TRUE)))
  }
  
  tu <- row.names(knn1$id)[which(rowSums(knn2) <= noise)]
  # tu <- union(tu, knn2[which(rowSums(knn2) <= noise), 1])
  tu <- grep("^Noise", tu, invert = TRUE, value = TRUE)
  ggplot(signals, aes(x = Blockade, y = DwellTime, colour = !ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = c("#E41A1C", "#377EB8")) + 
    theme_classic() + 
    theme(legend.position = "none") -> p1
  ggplot(signals[ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#E41A1C") + 
    theme_classic() + 
    theme(legend.position = "none") + 
    labs(title = length(tu)) -> p2
  ggplot(signals[!ID %in% tu], aes(x = Blockade, y = DwellTime, colour = ID %in% tu)) + 
    geom_point(size = .5) + 
    scale_y_log10() + 
    scale_colour_manual(values = "#377EB8") + 
    theme_classic() + 
    theme(legend.position = "none") -> p3
  print(p1 + p2 + p3)
  return(tu)
}

RemoveOutlier1 <- function(tree, n = 10, o = NULL) {
  k <- ceiling(length(res.hc$labels)/100)
  res_ct <- stats::cutree(res.hc, k = k)
  while (sum(table(res_ct) >= n) == 1) {
    k <- k + 1
    res_ct <- stats::cutree(res.hc, k = k)
  }
  if(is.null(o)) o <- n
  names(res_ct[res_ct %in% names(which(table(res_ct) >= o))])
}
RemoveOutlier <- function(tree, n = 10, Keep = 0.95) {
  h <- length(tree$height)
  g <- cutree(tree, h = tree$height[h])
  g <- data.table(tip = names(g), cluster = g)
  
  while (g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] > Keep) {
    h <- h - 1
    g <- cutree(tree, h = tree$height[h])
    g <- data.table(tip = names(g), cluster = g)
  }
  cat(paste0("Keep: ", round(g[, .N, cluster][N >= n, sum(N)/length(tree$labels)] * 100, 2), "%"))
  g[cluster %in% g[, .N, cluster][N >= n, cluster], tip]
}

get_density <- function(x, y, n = 1000, ...) {
  dens <- MASS::kde2d(x, y, n = n, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii] / max(dens$z[ii]))
}

# Peaks <- function(x, y) {
#   stopifnot(length(x) == length(y))
#   uR <- IRanges(diff(y) >= 0)
#   dR <- IRanges(diff(y) <= 0)
#   res <- do.call(c, lapply(seq_along(uR), function(i) {
#     reduce(c(uR[i], dR[i]))
#   }))
#   
#   Ps <- mapply(seq_along(res), FUN = function(i) {
#     x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
#   })
#   res <- IRanges(start = x[start(res)], end = x[end(res)])
#   end(res[length(res)]) <- max(x)
#   attr(res, "peaks") <- Ps
#   return(res)
# }
Peaks <- function(x, y) {
  stopifnot(length(x) == length(y))
  uR <- IRanges(diff(y) >= 0)
  dR <- IRanges(diff(y) <= 0)
  res <- do.call(c, lapply(seq_along(uR), function(i) {
    reduce(c(uR[i], dR[i]))
  }))
  
  Ps <- mapply(seq_along(res), FUN = function(i) {
    x[start(res[i]):end(res[i])][which.max(y[start(res[i]):end(res[i])])]
  })
  Py <- mapply(seq_along(res), FUN = function(i) {
    max(y[start(res[i]):end(res[i])])
  })
  res <- data.table(x = Ps, xmin = x[start(res)], xmax = x[end(res)], y = Py)
  attr(res, "peaks") <- Ps
  return(res)
}

densityPeak <- function(x, bw = 0.01, peaks = 2, n = 1024, from = 0, to = 1, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  dx <- attr(ps, "peaks")
  dy <- den$y[den$x %in% attr(ps, "peaks")]
  dy <- dy/max(dy)
  
  dx2 <- dx[dx <= dx[which.max(dy)]]
  dy2 <- dy[dx <= dx[which.max(dy)]]
  
  dx2 <- dx2[dy2 %in% head(sort(dy2, decreasing = T), peaks)]
  dy2 <- dy2[dy2 %in% head(sort(dy2, decreasing = T), peaks)]
  res <- sort(dx2, decreasing = T)
  df <- mean(abs(diff(den$y)))
  CI <- mapply(res, FUN = function(i) {
    from <- with(den, x[x < i])[max(start(IRanges(diff(with(den, y[x < i])) > mean(abs(diff(with(den, y[x < i])))))))]
    to <- with(den, x[x > i])[min(end(IRanges(diff(with(den, y[x > i])) < mean(abs(diff(with(den, y[x > i])))))))]
    min(c(i - from, to - i))
  })
  attr(res, "CI") <- CI
  if(plot) {
    plot(den)
    abline(v = res, lty = 2, col = 2)
    abline(v = res - attr(res,"CI"), lty = 2, col = 3)
    abline(v = res + attr(res,"CI"), lty = 2, col = 3)
  } else {
    return(res)
  }
}

BaseMeanFiltering <- function(SigFile, starttime = NULL, endtime = NULL, outdir = NULL, target = NULL, product = NULL) {
  if(is.null(starttime)) stop()
  if(is.null(endtime)) stop()
  if(is.null(outdir)) stop()
  if(is.null(target)) stop()
  outdir <- gsub("//", "/", paste0(outdir, "/", target))
  dataset <- fread(SigFile)
  dataset <- dataset[StartTime > starttime*60 & EndTime < endtime*60]
  dataset[, A := target]
  dataset[, DwellTime := DwellTime * 1000]
  shinyApp(
    ui = fluidPage(
      fluidRow(style = "padding-bottom: 20px;",
               column(2, numericInput('size', 'Point size', value = .3, min = .1, max = 1, step = .1)),
               column(3, sliderInput('nbins', 'Number of bins', value = 500, min = 100, max = 1000, step = 50)),
               column(3, sliderInput('BaseMean', 'BaseMean region', value = c(90, 130), min = 80, max = max(dataset[, round(BaseMean)]))),
               column(3, radioButtons(inputId = "LogScale", label = "log scale:", choices = c("TRUE", "FALSE"), inline = T))
      ),
      fluidRow(column(6, plotlyOutput('BaseMeanBlockade')), column(6, plotlyOutput('BlockadeDwellTime'))),
      plotlyOutput('BaseMeanHistogram'),
      actionButton("goButton", 'Save', class = "btn-success"),
      verbatimTextOutput("sp")
    ), 
    server = function(input, output, session) {
      selectedData <- reactive({
        dataset[BaseMean > input$BaseMean[1] & BaseMean < input$BaseMean[2]]
      })
      
      output$BaseMeanBlockade = renderPlotly({
        ggplot(selectedData(), aes(x = BaseMean, y = Blockade)) + 
          geom_point(size = input$size) + 
          # geom_hline(yintercept = AABlockade[amino_acid %in% selectedData()[, unique(A)], Blockade], color = "red") + 
          theme_minimal() -> p
        ggplotly(p)
      })
      
      output$BaseMeanHistogram = renderPlotly({
        ggplot(selectedData(), aes(x = BaseMean)) + 
          geom_histogram(bins = input$nbins) + 
          theme_minimal() -> p2
        ggplotly(p2) %>% layout(dragmode = "select")
      })
      
      output$BlockadeDwellTime = renderPlotly({
        d <- (event_data("plotly_selected"))
        if(is.null(d)) {
          selectedData2 <- reactive({
            dataset
          })
        } else {
          selectedData2 <- reactive({
            dataset[BaseMean > min(d$x) & BaseMean < max(d$x)]
          })
        }
        ggplot(selectedData2(), aes(x = Blockade, y = DwellTime)) + 
          geom_point(size = input$size) + 
          # geom_vline(xintercept = product, color = "red") +
          theme_minimal() + 
          labs(title = selectedData2()[, unique(A)]) -> p3
        if(!is.null(product)) {
          p3 <- p3 + geom_vline(xintercept = product, color = "red")
        }
        
        if(input$LogScale == "TRUE") {
          p3 <- p3 + scale_y_log10()
        }
        ggplotly(p3)
      })
      
      output$sp <- renderPrint({
        d <- (event_data("plotly_selected"))
        if(is.null(d)) {
          cat("Number of selected points:", nrow(d))
        } else {
          selectedData2 <- reactive({
            dataset[BaseMean > min(d$x) & BaseMean < max(d$x)]
          })
          if(input$goButton != 0) {
            if(!is.null(d)) {
              if(!dir.exists(outdir)) dir.create(outdir, recursive = T)
              fwrite(selectedData2(), paste0(outdir, "/", gsub(".txt", ".MainL0.txt", basename(SigFile))), sep = "\t", quote = F)
              cat("Saved", nrow(selectedData2()), "points.")
            } else {
              cat("Number of selected points:", nrow(selectedData2()))
            }
          } else {
            cat("Number of selected points:", nrow(selectedData2()))
          }
        }
      })
    }
  )
}

MainRidge <- function(x, bw = 0.001, bwstep = NULL, n = 1024, peaks = 2, mingap = 0.01, CI = 0.99, plot = T, ...) {
  den <- density(x, bw = bw, n = n, ...)
  ps <- Peaks(den$x, den$y)
  res <- ps[order(y, decreasing = T)][seq_len(peaks)]
  res <- na.omit(res)
  if(peaks > 1) {
    if(is.null(bwstep)) bwstep <- mingap/10
    while (nrow(res) > 1 & min(res[, diff(sort(x))]) < mingap) {
      bw <- bw + bwstep
      den <- density(x, bw = bw, n = n, ...)
      ps <- Peaks(den$x, den$y)
      res <- ps[order(y, decreasing = T)][seq_len(peaks)]
      res <- na.omit(res)
    }
  }
  if(CI < 1) {
    new_x <- lapply(seq_len(nrow(res)), function(i) {
      resy <- with(den, y[x > res[i, xmin] & x < res[i, xmax]])
      resy <- resy > max(resy) * (1 - CI) + min(resy)
      resx <- range(with(den, x[x > res[i, xmin] & x < res[i, xmax]])[resy])
      resx
    })
    new_x <- do.call(rbind, new_x)
    res$xmin <- new_x[, 1]
    res$xmax <- new_x[, 2]
  }
  res$ratio <- mapply(function(i) mean(x >= res$xmin[i] & x <= res$xmax[i]), seq_len(nrow(res)))
  
  if(plot) {
    plot(den)
    abline(v = res[, x], lty = 2, col = 2)
    abline(v = res[, xmin], lty = 2, col = 3)
    abline(v = res[, xmax], lty = 2, col = 3)
  } else {
    return(res)
  }
}
```

# Select main base line

```{r}
meta0 <- as.data.table(openxlsx::read.xlsx("data/MetaInfomation/整理数据(20230831).xlsx", sheet = 6))
colnames(meta0) <- c("file_name", "start_time", "end_time", "amino_acid", "file", "purpose", "sample", "base_line", "note")
meta <- meta0[file_name %in% gsub(".abf", "", list.files("./data/ChenShanchuan/20230830", "abf"))]
meta
```

```{r}
files <- list.files("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/03.GroupedSignals", "txt", full.names = T)
Sigs1 <- lapply(files, fread)
Sigs1 <- data.table(A = rep(gsub(".signal.txt", "", basename(files)), mapply(nrow,  Sigs1)), do.call(rbind, Sigs1))

AABlockade <- Sigs1[State == "Sington", .(BlockadeSD = sd(Blockade), 
                     BlockadeMean = mean(Blockade), 
                     BlockadeMedian = median(Blockade), 
                     BlockadeQ1 = quantile(Blockade, 1/4), 
                     BlockadeQ3 = quantile(Blockade, 3/4), 
                     DwellTimeSD = sd(DwellTime), 
                     DwellTimeMAD = mad(DwellTime), 
                     DwellTimeQ1 = quantile(DwellTime, 1/4), 
                     DwellTimeQ3 = quantile(DwellTime, 3/4), 
                     DwellTimeMean = mean(DwellTime), 
                     DwellTimeMedian = median(DwellTime)), A]
```

```{r}
AA_Run1 <- c("Gln", "CbC", "Thr")
AA_Run2 <- c("Gln", "CbC", "Thr", "Ser", "Ile", "Gly")
AA_Run3 <- c("Gln", "CbC", "Thr", "Ser", "Ile", "Gly", "Ala", "Trp", "Met")
AA_Run4 <- c("Gln", "CbC", "Thr", "Ser", "Ile", "Gly", "Ala", "Trp", "Met", "Glu")
AA_Run5 <- c("Gln", "CbC", "Thr", "Ser", "Ile", "Gly", "Ala", "Trp", "Met", "Glu", "Arg")
```

```{r}
files <- list.files("./analysis/81.ABFProcessing/RawSignal", full.names = TRUE)
files <- files[gsub("RawSignal_", "", gsub(".txt", "", basename(files))) %in% meta$file_name]

bg_files <- grep(pattern = "20230830_0000", files, value = T)
sg_files <- files[!grepl(pattern = "20230830_0000", files)]

outdir <- file.path("./analysis/62.MachineLearning/02.MixtureAA/20230830/Rep2")

BaseMeanFiltering(SigFile = bg_files, starttime = 0, endtime = 5.5, outdir = outdir, target = "Background")

BaseMeanFiltering(SigFile = sg_files[1], starttime = 0, endtime = 10.70, target = "Run1", 
                  outdir = outdir, 
                  product = as.numeric(AABlockade[AA %in% AA_Run1, Blockade]))

BaseMeanFiltering(SigFile = sg_files[2], starttime = 0, endtime = 10.60, target = "Run2", 
                  outdir = outdir, 
                  product = as.numeric(AABlockade[AA %in% AA_Run2, Blockade]))

BaseMeanFiltering(SigFile = sg_files[3], starttime = 0, endtime = 11.20, target = "Run3", 
                  outdir = outdir, 
                  product = as.numeric(AABlockade[AA %in% AA_Run3, Blockade])) # 可以重选一次试试

BaseMeanFiltering(SigFile = sg_files[4], starttime = 0, endtime = 12.30, target = "Run4", 
                  outdir = outdir, 
                  product = as.numeric(AABlockade[AA %in% AA_Run4, Blockade])) # 可以重选一次试试

BaseMeanFiltering(SigFile = sg_files[5], starttime = 0, endtime = 13.90, target = "Run5",
                  outdir = outdir,
                  product = as.numeric(AABlockade[AA %in% AA_Run5, Blockade])) # 可以重选一次试试
```


# Remain sigle main peak signals

```{r}
files <- list.files(outdir, "MainL0.txt", full.names = T, recursive = T)
sigs <- lapply(files, fread)
sigs <- do.call(rbind, sigs)
sigs$File <- stringr::str_remove_all(sigs$ID, "_([[:digit:]]+)$")
```

```{r}
sgsignals <- sigs[A != "Background", ]
B_file <- sgsignals[, unique(File)]
B_file <- paste0("./analysis/81.ABFProcessing/SignalCurrent/SignalCurrent_", B_file, ".Rds")
Sig_Current <- lapply(B_file, function(x) {
  readRDS(x)
})
Sig_Current <- do.call(rbind, Sig_Current)
Sig_Current <- Sig_Current[ID %in% sgsignals[, ID]]
stopifnot(all(is.element(sgsignals[, ID], Sig_Current[, ID])))
```

# Distance of signal

## Background data

```{r}
StandardAA_bg_FeatureMatrixs <- readRDS("./analysis/61.SignalSelecting/01.StandardAA/01.SignalDistance/StandardAA_Big_FeatureMatrixs.Rds")
StandardAA_bg_FeatureMatrixs[, AA := NULL]
```

```{r}
bgsignals <- sigs[A == "Background", ]
bgsignals[, ID := paste0("Noise_", ID)]

B_file <- bgsignals[, unique(File)]
Big_FeatureMatrix <- list.files(path = "./analysis/81.ABFProcessing/FeatureMatrix", B_file, full.names = TRUE)
Big_FeatureMatrix <- fread(Big_FeatureMatrix)
Big_FeatureMatrix[, ID := paste0("Noise_", ID)]
Big_FeatureMatrix <- Big_FeatureMatrix[ID %in% bgsignals$ID]
```

## Signal data

```{r}
sgsignals <- sigs[A != "Background" & SignalCurrentPercent > 75, ]
sgsignals <- sigs[A != "Background", ]
B_file <- sgsignals[, unique(File)]
B_file <- paste0("./analysis/81.ABFProcessing//FeatureMatrix/FeatureMatrix_", B_file, ".txt")
Sig_FeatureMatrix <- lapply(B_file, function(x) fread(x)[ID %in% sgsignals$ID])
Sig_FeatureMatrix <- do.call(rbind, Sig_FeatureMatrix)
```

```{r eval=FALSE}
mclapply(paste0("Run", 1:5), function(x) {
  SFMi <- Sig_FeatureMatrix[ID %in% sgsignals[A == x, ID]]
  if(nrow(SFMi) > nrow(Big_FeatureMatrix)) {
    FeatureMatrix <- rbind(Big_FeatureMatrix, 
                           StandardAA_bg_FeatureMatrixs[sample(.N, nrow(SFMi) - nrow(Big_FeatureMatrix))], 
                           SFMi, fill = TRUE)
  } else {
    FeatureMatrix <- rbind(Big_FeatureMatrix, SFMi)
  }
  setkey(FeatureMatrix, ID)
  FeatureMatrix <- data.frame(FeatureMatrix[, grepl("^X", colnames(FeatureMatrix)) | grepl("DwellTime", colnames(FeatureMatrix)), with = F], row.names = FeatureMatrix[[1]])
  euclidean = stats::dist(FeatureMatrix, method = "euclidean")
  saveRDS(euclidean, file = paste0(outdir, "/", x, "_Signals_euclidean_distance.Rds"))
}, mc.cores = 5)
```


```{r fig.width=20, fig.height=3}
ggplot(sigs, aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(alpha = 0.3, size = 0.3) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  facet_wrap(~ A, nrow = 1, scales = "free_y")
```

# Distance filtering

## Run1

```{r fig.width=24, fig.height=6}
Run1_dist <- readRDS("./analysis/62.MachineLearning/02.MixtureAA/20230830/Rep2/Run1_Signals_euclidean_distance.Rds")
select_sigs_Run1 <- KnnSelecting(signals = sgsignals[A == "Run1"], dists = Run1_dist, k = 10, noise = 0)
```

## Run2

```{r fig.width=24, fig.height=6}
Run2_dist <- readRDS("./analysis/62.MachineLearning/02.MixtureAA/20230830/Rep2/Run2_Signals_euclidean_distance.Rds")
select_sigs_Run2 <- KnnSelecting(signals = sgsignals[A == "Run2"], dists = Run2_dist, k = 10, noise = 0)
```

## Run3

```{r fig.width=24, fig.height=6}
Run3_dist <- readRDS("./analysis/62.MachineLearning/02.MixtureAA/20230830/Rep2/Run3_Signals_euclidean_distance.Rds")
select_sigs_Run3 <- KnnSelecting(signals = sgsignals[A == "Run3"], dists = Run3_dist, k = 10, noise = 0)
```

## Run4

```{r fig.width=24, fig.height=6}
Run4_dist <- readRDS("./analysis/62.MachineLearning/02.MixtureAA/20230830/Rep2/Run4_Signals_euclidean_distance.Rds")
select_sigs_Run4 <- KnnSelecting(signals = sgsignals[A == "Run4"], dists = Run4_dist, k = 10, noise = 0)
```

## Run5

```{r fig.width=24, fig.height=6}
Run5_dist <- readRDS("./analysis/62.MachineLearning/02.MixtureAA/20230830/Rep2/Run5_Signals_euclidean_distance.Rds")
select_sigs_Run5 <- KnnSelecting(signals = sgsignals[A == "Run5"], dists = Run5_dist, k = 10, noise = 0)
```

# Remove Outlier 

## Run1
```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run1]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run1 <- RemoveOutlier(tree = res.hc, n = 20, Keep = 0.95)
ggplot(sgsignals[ID %in% select_sigs_RemoveOutlier_Run1], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run1, BlockadeMean]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  labs(title = length(select_sigs_RemoveOutlier_Run1)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```

## Run2
```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run2]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run2 <- RemoveOutlier(tree = res.hc, n = 20, Keep = 0.95)
ggplot(sgsignals[ID %in% select_sigs_RemoveOutlier_Run2], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run2, BlockadeMean]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  labs(title = length(select_sigs_RemoveOutlier_Run2)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```

## Run3
```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run3]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run3 <- RemoveOutlier(tree = res.hc, n = 20, Keep = 0.95)
ggplot(sgsignals[ID %in% select_sigs_RemoveOutlier_Run3], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run3, BlockadeMean]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  labs(title = length(select_sigs_RemoveOutlier_Run3)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```

## Run4

```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run4]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run4 <- RemoveOutlier(tree = res.hc, n = 20, Keep = 0.95)
ggplot(sgsignals[A %in% "Run4" & ID %in% select_sigs_RemoveOutlier_Run4], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run4, BlockadeMean]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  labs(title = length(select_sigs_RemoveOutlier_Run4)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```

## Run5

```{r}
subtab <- Sig_FeatureMatrix[ID %in% select_sigs_Run5]
subtab <- data.frame(subtab[, grepl("^X", colnames(subtab)) | grepl("DwellTime", colnames(subtab)), with = F], row.names = subtab[[1]])
res.ds <- stats::dist(subtab)
res.hc <- stats::hclust(res.ds, method = "single")
```

```{r fig.width=10, fig.height=4}
select_sigs_RemoveOutlier_Run5 <- RemoveOutlier(tree = res.hc, n = 20, Keep = 0.95)
ggplot(sgsignals[A %in% "Run5" & ID %in% select_sigs_RemoveOutlier_Run5], aes(x = Blockade, y = DwellTime, colour = A)) + 
  geom_point(size = .5) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run5, BlockadeMean]) + 
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  labs(title = length(select_sigs_RemoveOutlier_Run5)) + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none")
```

# Model prediction

```{r}
paste0(sort(names(AMINO_ACID_CODE[AMINO_ACID_CODE %in% AA_Run5])), collapse = "")
```

```{r}
select_sigs <- c(select_sigs_RemoveOutlier_Run1, select_sigs_RemoveOutlier_Run2, select_sigs_RemoveOutlier_Run3, select_sigs_RemoveOutlier_Run4, select_sigs_RemoveOutlier_Run5)
subtab <- Sig_FeatureMatrix[ID %in% select_sigs]
Fit1 <- readRDS("./analysis/81.ABFProcessing/SelectedSignals/01.StandardAA/06.Modeling/Version2/L1/SubAAs/ModelABEGIMQRSTW/RFmodel.Rds")
pred0 <- predict(Fit1, subtab)
pred1 <- predict(Fit1, subtab, type = "prob")
pred <- data.table(ID = subtab[, ID], as.data.table(pred1), Prob = apply(pred1, 1, max), DiffProb = apply(pred1, 1, function(x) diff(tail(sort(x), 2))), Pred = pred0)
```

```{r}
sgsignals_pred <- merge(sgsignals, pred[, .(ID, Prob, DiffProb, Pred)], by = "ID")
sgsignals_pred
```

```{r}
fwrite(sgsignals_pred, "./analysis/00.FigureTables/Rebuttal/NatureMethods/Mixture_AminoAcid_Prediction.txt", sep = "\t", quote = FALSE)
```

```{r fig.width=18, fig.height=10}
ggplot(sgsignals_pred[SignalCurrentPercent > 75 & Prob > 0.5]) + 
  geom_text(aes(x = Blockade, y = DwellTime, colour = Pred, label = Pred)) + 
  # geom_rect(data = SigSumm[A %in% AA_Run3, ], aes(xmin = BlockadeMean - BlockadeSD, xmax = BlockadeMean + BlockadeSD, ymin = 0, ymax = 110, fill = A), alpha = 0.3) +
  scale_y_log10() + 
  scale_x_continuous(limits = c(0.1, 0.3)) + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = guide_legend(title = element_blank())) + 
  labs(y = "Dwell time (ms)") + 
  theme_light(base_size = 15) + 
  theme(legend.position = "right", 
        panel.grid = element_blank()) + 
  facet_wrap(~ A)
```

```{r fig.width=24, fig.height=5}
ggplot(sgsignals_pred[A == "Run1" & SignalCurrentPercent > 75 & Prob > 0.5], aes(x = Blockade, y = DwellTime, colour = Pred)) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run1, BlockadeMean]) + 
  geom_text(aes(label = Pred), size = 2) + 
  scale_y_log10() + 
  scale_x_continuous(breaks = AABlockade[A %in% AA_Run1, BlockadeMean], 
                     labels = AABlockade[A %in% AA_Run1, gsub("CbC", "CMC", A)], limits = c(0.1, 0.3)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols) + 
  labs(title = "Run1", y = "Dwell time (ms)", tag = "a") + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none", plot.tag = element_text(face = "bold", size = 20), axis.text.x = element_text(angle = 60, hjust = 1)) -> p1

ggplot(sgsignals_pred[A == "Run2" & SignalCurrentPercent > 75 & Prob > 0.5], aes(x = Blockade, y = DwellTime, colour = Pred)) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run2, BlockadeMean]) + 
  geom_text(aes(label = Pred), size = 2) + 
  scale_y_log10() + 
  scale_x_continuous(breaks = AABlockade[A %in% AA_Run2, BlockadeMean], 
                     labels = AABlockade[A %in% AA_Run2, gsub("CbC", "CMC", A)], limits = c(0.1, 0.3)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols) + 
  labs(title = "Run2", y = "Dwell time (ms)") + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 60, hjust = 1)) -> p2

ggplot(sgsignals_pred[A == "Run3" & SignalCurrentPercent > 75 & Prob > 0.5], aes(x = Blockade, y = DwellTime, colour = Pred)) + 
  geom_vline(xintercept = AABlockade[A %in% AA_Run3, BlockadeMean]) + 
  geom_text(aes(label = Pred), size = 2) + 
  scale_y_log10() + 
  scale_x_continuous(breaks = AABlockade[A %in% AA_Run3, BlockadeMean], 
                     labels = AABlockade[A %in% AA_Run3, gsub("CbC", "CMC", A)], limits = c(0.1, 0.3)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols) + 
  labs(title = "Run3", y = "Dwell time (ms)") + 
  theme_classic(base_size = 15) + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 60, hjust = 1)) -> p3

ggplot(sgsignals_pred[A == "Run4" & SignalCurrentPercent > 75 & Prob > 0.5], aes(x = Blockade, y = DwellTime, colour = Pred)) +
  geom_vline(xintercept = AABlockade[A %in% AA_Run4, BlockadeMean]) +
  geom_text(aes(label = Pred), size = 2) +
  scale_y_log10() +
  scale_x_continuous(breaks = AABlockade[A %in% AA_Run4, BlockadeMean],
                     labels = AABlockade[A %in% AA_Run4, gsub("CbC", "CMC", A)], limits = c(0.1, 0.3)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols) + 
  labs(title = "Run4", y = "Dwell time (ms)") +
  theme_classic(base_size = 15) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 60, hjust = 1)) -> p4

ggplot(sgsignals_pred[A == "Run5" & SignalCurrentPercent > 75 & Prob > 0.5], aes(x = Blockade, y = DwellTime, colour = Pred)) +
  geom_vline(xintercept = AABlockade[A %in% AA_Run5, BlockadeMean]) +
  geom_text(aes(label = Pred), size = 2) +
  scale_y_log10() +
  scale_x_continuous(breaks = AABlockade[A %in% AA_Run5, BlockadeMean],
                     labels = AABlockade[A %in% AA_Run5, gsub("CbC", "CMC", A)], limits = c(0.1, 0.3)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols) + 
  labs(title = "Run5", y = "Dwell time (ms)") +
  theme_classic(base_size = 15) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 60, hjust = 1)) -> p5

p1 + p2 + p3 + p4 + p5 + plot_layout(ncol = 5)
```


# AA assign

```{r fig.height=5, fig.width=24}
abf1 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", "20230830_0001", ".Rds"))
time1 <- sgsignals_pred[A == "Run1", .N, round(StartTime)][which.max(N), round]
abf_run1_i <- abf1[Time >= time1 - 0.5 & Time <= time1 + 0.5, ]
L0 <- MainRidge(x = abf_run1_i[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm1 <- AABlockade[A %in% AA_Run1]
aasumm1[, y := L0 * (1 - BlockadeMean)]
aasumm1[, ymin := L0 * (1 - BlockadeMean - BlockadeSD)]
aasumm1[, ymax := L0 * (1 - BlockadeMean + BlockadeSD)]

ggplot() + 
  geom_rect(data = aasumm1, aes(xmin = abf_run1_i[, min(Time)], xmax = abf_run1_i[, max(Time)], ymin = ymin, ymax = ymax, fill = A), alpha = 0.3) + 
  geom_step(data = abf_run1_i, mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 4, limits = c(aasumm1[, min(ymin)] - 5, abf_run1_i[, max(pA)]), 
                     sec.axis = dup_axis(breaks = aasumm1[, y], labels = aasumm1[, A])) +
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(x = "Time (s)", y = "Current (pA)", title = "Run1") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        axis.title.y.right = element_blank())
```





```{r fig.height=10, fig.width=24}
abf2 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", "20230830_0002", ".Rds"))
time2 <- sgsignals_pred[A == "Run2", .N, round(StartTime)][order(N, decreasing = T)][2, round]
abf_run2_i <- abf2[Time >= time2 - 1 & Time <= time2 + 0, ]
L0 <- MainRidge(x = abf_run2_i[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm2 <- AABlockade[A %in% AA_Run2]
aasumm2[, y := L0 * (1 - BlockadeMean)]
aasumm2[, ymin := L0 * (1 - BlockadeMean - BlockadeSD)]
aasumm2[, ymax := L0 * (1 - BlockadeMean + BlockadeSD)]

ggplot() + 
  geom_rect(data = aasumm2, aes(xmin = abf_run2_i[, min(Time)], xmax = abf_run2_i[, max(Time)], ymin = ymin, ymax = ymax, fill = A), alpha = 0.3) + 
  geom_step(data = abf_run2_i, mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 4, limits = c(aasumm2[, min(ymin)] - 5, abf_run2_i[, max(pA)]), 
                     sec.axis = dup_axis(breaks = aasumm2[, y], labels = aasumm2[, A])) +
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(x = "Time (s)", y = "Current (pA)", title = "Run2") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        axis.title.y.right = element_blank())
```


```{r fig.height=10, fig.width=24}
abf3 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", "20230830_0003", ".Rds"))
time3 <- sgsignals_pred[A == "Run3", .N, round(StartTime)][order(N, decreasing = T)][1, round]
abf_run3_i <- abf3[Time >= time3 - 0.5 & Time <= time3 + 0.5, ]
L0 <- MainRidge(x = abf_run3_i[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm3 <- AABlockade[A %in% AA_Run3]
aasumm3[, y := L0 * (1 - BlockadeMean)]
aasumm3[, ymin := L0 * (1 - BlockadeMean - BlockadeSD)]
aasumm3[, ymax := L0 * (1 - BlockadeMean + BlockadeSD)]

ggplot() + 
  geom_rect(data = aasumm3, aes(xmin = abf_run3_i[, min(Time)], xmax = abf_run3_i[, max(Time)], ymin = ymin, ymax = ymax, fill = A), alpha = 0.3) + 
  geom_step(data = abf_run3_i, mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 4, limits = c(aasumm3[, min(ymin)] - 5, abf_run3_i[, max(pA)]), 
                     sec.axis = dup_axis(breaks = aasumm3[, y], labels = aasumm3[, A])) +
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(x = "Time (s)", y = "Current (pA)", title = "Run3") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        axis.title.y.right = element_blank())
```

```{r fig.height=8, fig.width=24}
abf4 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", "20230830_0004", ".Rds"))
time4 <- sgsignals_pred[A == "Run4", .N, round(StartTime)][order(N, decreasing = T)][1, round]
abf_run4_i <- abf4[Time >= time4 - 0.5 & Time <= time4 + 0.5, ]
L0 <- MainRidge(x = abf_run4_i[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm4 <- AABlockade[A %in% AA_Run4]
aasumm4[, y := L0 * (1 - BlockadeMean)]
aasumm4[, ymin := L0 * (1 - BlockadeMean - BlockadeSD)]
aasumm4[, ymax := L0 * (1 - BlockadeMean + BlockadeSD)]

ggplot() + 
  geom_rect(data = aasumm4, aes(xmin = abf_run4_i[, min(Time)], xmax = abf_run4_i[, max(Time)], ymin = ymin, ymax = ymax, fill = A), alpha = 0.3) + 
  geom_step(data = abf_run4_i, mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 4, limits = c(aasumm4[, min(ymin)] - 5, abf_run4_i[, max(pA)]), 
                     sec.axis = dup_axis(breaks = aasumm4[, y], labels = aasumm4[, A])) +
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(x = "Time (s)", y = "Current (pA)", title = "Run4") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        axis.title.y.right = element_blank())
```


```{r fig.height=8, fig.width=24}
abf5 <- readRDS(paste0("./analysis/81.ABFProcessing/ABF/ABF_", "20230830_0005", ".Rds"))
time5 <- sgsignals_pred[A == "Run5", .N, round(StartTime)][order(N, decreasing = T)][1, round]
abf_run5_i <- abf5[Time >= time5 - 0.5 & Time <= time5 + 0.5, ]
L0 <- MainRidge(x = abf_run5_i[, pA], bw = 0.5, peaks = 1, CI = 0.95, plot = F)[[1]]
aasumm5 <- AABlockade[A %in% AA_Run5]
aasumm5[, y := L0 * (1 - BlockadeMean)]
aasumm5[, ymin := L0 * (1 - BlockadeMean - BlockadeSD)]
aasumm5[, ymax := L0 * (1 - BlockadeMean + BlockadeSD)]

ggplot() + 
  geom_rect(data = aasumm5, aes(xmin = abf_run5_i[, min(Time)], xmax = abf_run5_i[, max(Time)], ymin = ymin, ymax = ymax, fill = A), alpha = 0.3) + 
  geom_step(data = abf_run5_i, mapping = aes(x = Time, y = pA), size = 0.1) + 
  scale_y_continuous(n.breaks = 5, limits = c(aasumm5[, min(ymin)] - 5, abf_run5_i[, max(pA)]), 
                     sec.axis = dup_axis(breaks = aasumm5[, y], labels = aasumm5[, A])) +
  scale_x_continuous(expand = c(0.0001, 0.0001), n.breaks = 5, labels = c(0, 0.25, 0.5, 0.75, 1)) + 
  scale_fill_manual(breaks = names(aa_cols), values = aa_cols, guide = "none") + 
  labs(x = "Time (s)", y = "Current (pA)", title = "Run5", tag = "c") + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        panel.grid = element_blank(), 
        axis.title.y.right = element_blank()) -> p7
p7
```


```{r}
meta
```

```{r}
sgsignals_pred[, .N, .(A, File)]
```

```{r}
sgsignals_pred_hc <- sgsignals_pred[SignalCurrentPercent > 75 & Prob > 0.5]

retime1 <- sgsignals_pred_hc[File == "20230830_0001" & EndTime > 0 * 60][order(StartTime)]
g01 <- retime1[, min(StartTime)]
retime1[, StartTime := StartTime - g01]
retime1[, EndTime := EndTime - g01]

retime2 <- sgsignals_pred_hc[File == "20230830_0002"][order(StartTime)]
g12 <- 10 + retime1[, max(EndTime)] - retime2[, min(StartTime)]
retime2[, StartTime := StartTime + g12]
retime2[, EndTime := EndTime + g12]

retime3 <- sgsignals_pred_hc[File == "20230830_0003"][order(StartTime)]
g23 <- 10 + retime2[, max(EndTime)] - retime3[, min(StartTime)]
retime3[, StartTime := StartTime + g23]
retime3[, EndTime := EndTime + g23]

retime4 <- sgsignals_pred_hc[File == "20230830_0004"][order(StartTime)]
g34 <- 10 + retime3[, max(EndTime)] - retime4[, min(StartTime)]
retime4[, StartTime := StartTime + g34]
retime4[, EndTime := EndTime + g34]

retime5 <- sgsignals_pred_hc[File == "20230830_0005"][order(StartTime)]
g45 <- 10 + retime4[, max(EndTime)] - retime5[, min(StartTime)]
retime5[, StartTime := StartTime + g45]
retime5[, EndTime := EndTime + g45]

retime <- rbind(retime1, retime2, retime3, retime4, retime5)
retime[, Bin := (StartTime + EndTime) / 2]
retime$Bini <- seq_len(nrow(retime))
retime[, Pred := as.character(Pred)]
```

```{r fig.width=8, fig.height=6}
ran_gr <- retime[, .(start = min(Bini), end = max(Bini)), A]
setnames(ran_gr, "A", "Run")
ggplot(retime[Pred %in% gsub("CbC", "CMC", AA_Run5)]) +
  stat_ecdf(aes(Bini, colour = Pred)) + 
  scale_colour_manual(breaks = names(aa_cols), values = aa_cols, guide = guide_legend(ncol = 2)) + 
  # geom_rect(data = ran_gr, aes(xmin = start, xmax = end, ymin = 0, ymax = 1, fill = Run), alpha = 0.3) + 
  labs(x = "Relative time", y = "Cumulative distribution probablity", tag = "b") + 
  scale_x_continuous(breaks = ran_gr[, start], labels = c(paste(AA_Run1, collapse = "\n"), 
                                                          paste(setdiff(AA_Run2, AA_Run1), collapse = "\n"), 
                                                          paste(setdiff(AA_Run3, AA_Run2), collapse = "\n"), 
                                                          paste(setdiff(AA_Run4, AA_Run3), collapse = "\n"),
                                                          paste(setdiff(AA_Run5, AA_Run4), collapse = "\n"))) + 
  theme_light(base_size = 15) + 
  theme(plot.tag = element_text(size = 20, face = "bold"), 
        legend.title = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        axis.ticks.x = element_line(arrow = arrow(length = unit(0.3, "line"))), 
        axis.ticks.length.x = unit(1, 'line'), 
        axis.text.x = element_text(vjust = 1), 
        legend.position = c(0.2, .7), 
        axis.title.y.right = element_blank()) -> p6
p6
```

```{r fig.height=16, fig.width=16, echo=FALSE}
design <- "
  112233
  445566
  777777
  777777
"
p1 + p2 + p3 + p4 + p5 + p6 + p7 + 
  plot_layout(design = design)
ggsave("./analysis/00.FigureTables/Rebuttal/NatureMethods/Mixture.pdf", width = 16, height = 16)
```

