---
title: "Performance of all classifier"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center')
knitr::opts_knit$set(root.dir = "/mnt/raid61/Personal_data/tangchao/AANanopore")
```

```{r required packages}
library(data.table)
library(ggplot2)
library(patchwork)
library(Biostrings)
library(parallel)
library(caret)
library(openxlsx)
library(cowplot)
library(ggseqlogo)
library(ggrepel)
```

```{r}
set.seed(19)
AA_Cols <- sample(c(RColorBrewer::brewer.pal(n = 12, "Paired"), RColorBrewer::brewer.pal(n = 8, "Dark2")), 20)
names(AA_Cols) <- Biostrings::AA_STANDARD
```

```{r}
AADensityPlot <- function(x, top = 4) {
  ggplot(x, aes(Blockade, after_stat(count / max(count)), fill = AA, colour = AA)) +
    geom_density(adjust = 3, alpha = 0.5) + 
    scale_fill_manual(breaks = names(AA_Cols), values = AA_Cols, guide = guide_legend(ncol = 2)) + 
    scale_colour_manual(breaks = names(AA_Cols), values = AA_Cols) + 
    theme_bw(base_size = 15) + 
    labs(y = "density", x = "blockade") -> p
  pd <- ggplot_build(p)
  tab <- head(as.data.table(pd$data[[1]])[, .SD[which.max(count), ], colour][order(count, decreasing = T), ], top)
  tab <- merge(tab, data.table(AA = names(AA_Cols), colour = AA_Cols), by = "colour")
  p + geom_text_repel(data = tab, aes(x = x, y = y, label = AA), size = 5) + theme(panel.grid = element_blank())
}
```

# 20211025

```{r}
files <- list.files("./analysis/02.PolypeptideSequencing/20211025/Version2/02.SignalPrediction", full.names = TRUE)
```

```{r}
meta <- as.data.table(openxlsx::read.xlsx("./data/ZhangMing_20211025/实验信息表1025.xlsx"))
meta <- meta[!grepl("lank", amino_acid)]

meta <- unique(meta[, .(file_name, amino_acid)])
meta <- meta[file_name %in% gsub("AA_Signals_", "", gsub(".RData", "", basename(files)))]
meta$amino_acid <- mapply(function(x) tail(x, 1), strsplit(mapply(function(x) tail(x, 1), strsplit(meta$amino_acid, ", ")), ") "))
setkey(meta, file_name)
```

```{r}
Polypeptide1_iden <- lapply(files, function(x) {
  load(x)
  Polypeptide1_iden$MaxPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, max)
  Polypeptide1_iden$MinPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, min)
  Polypeptide1_iden$MeanPP <- apply(Polypeptide1_iden[, .(RF, KNN, CART)], 1, mean)
  Polypeptide1_iden
})

Polypeptide1_iden <- data.table(meta[rep(gsub("AA_Signals_", "", gsub(".RData", "", basename(files))), mapply(nrow, Polypeptide1_iden))], do.call(rbind, Polypeptide1_iden))
```


```{r}
p1 <- AADensityPlot(Polypeptide1_iden[amino_acid == "APRLRFYSL" & Cutoff == "C4" & MinPP > 0.6])
p1
```

```{r}
M1 <- Polypeptide1_iden[amino_acid == "APRLRFYSL" & Cutoff == "C4" & MinPP > 0.6, .N, AA]
```


```{r}
ggplot(Polypeptide1_iden[amino_acid == "DRVYIHPFHL" & Cutoff == "C3" & MinPP > 0.5], 
       aes(Blockade, after_stat(count / 40000), fill = AA, colour = AA)) +
  geom_density(adjust = 3, alpha = 0.5) + 
  scale_fill_manual(breaks = names(AA_Cols), values = AA_Cols, guide = guide_legend(ncol = 2)) + 
  scale_colour_manual(breaks = names(AA_Cols), values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  labs(y = "density") -> p2
pd <- ggplot_build(p2)
tab <- head(as.data.table(pd$data[[1]])[, .SD[which.max(count), ], colour][order(count, decreasing = T), ], 3)
tab <- merge(tab, data.table(AA = names(AA_Cols), colour = AA_Cols), by = "colour")
p2 <- p2 + geom_text_repel(data = tab, aes(x = x, y = y, label = AA), size = 5) + theme(panel.grid = element_blank())
p2
```

```{r}
M2 <- Polypeptide1_iden[amino_acid == "DRVYIHPFHL" & Cutoff == "C3" & MinPP > 0.5, .N, AA]
```

```{r}
ggplot(Polypeptide1_iden[amino_acid == "RPVKVYPNGAEDESAEAFPLEF" & Cutoff == "C3" & MinPP > 0.5], 
       aes(Blockade, after_stat(count / 3000), fill = AA, colour = AA)) +
  geom_density(adjust = 3, alpha = 0.5) + 
  scale_fill_manual(breaks = names(AA_Cols), values = AA_Cols, guide = guide_legend(ncol = 2)) + 
  scale_colour_manual(breaks = names(AA_Cols), values = AA_Cols) + 
  theme_bw(base_size = 15) + 
  labs(y = "density", x = "blockade") -> p3
pd <- ggplot_build(p3)
tab <- head(as.data.table(pd$data[[1]])[, .SD[which.max(count), ], colour][order(count, decreasing = T), ], 3)
tab <- merge(tab, data.table(AA = names(AA_Cols), colour = AA_Cols), by = "colour")
p3 <- p3 + geom_text_repel(data = tab, aes(x = x, y = y, label = AA), size = 5) + theme(panel.grid = element_blank())
p3
```

```{r}
M3 <- Polypeptide1_iden[amino_acid == "RPVKVYPNGAEDESAEAFPLEF" & Cutoff == "C3" & MinPP > 0.6, .N, AA]
```


```{r}
M1$P <- M1$N / sum(M1$N) * 100
M2$P <- M2$N / sum(M2$N) * 100
M3$P <- M3$N / sum(M3$N) * 100

M1[AA %in% c("L", "S", "Y", "F"), Lab := paste0(AA, " (", N, ")")]
M2[AA %in% c("L", "H", "F"), Lab := paste0(AA, " (", N, ")")]
M3[AA %in% c("L", "E", "F"), Lab := paste0(AA, " (", N, ")")]

Mat <- rbind(data.table(Exp = "S1", M1), data.table(Exp = "S2", M2), data.table(Exp = "S3", M3))
Mat[is.na(Lab), Lab := ""]
```

```{r}
Mat[, Col := paste0(Exp, "_", AA)]
Mat$Col <- factor(Mat$Col, levels = Mat[order(N, decreasing = F), Col])
Mat[, Cols := plyr::mapvalues(AA, names(AA_Cols), AA_Cols)]
Mat[, Exp := gsub("^S", "P", Exp)]
```

```{r fig.width=3, fig.height=4}
ggplot(Mat, aes(x = Exp, y = P, fill = Col)) + 
  geom_col(alpha = 0.8) + 
  scale_fill_manual(breaks = as.character(Mat$Col), values = Mat$Cols) + 
  theme_bw(base_size = 15) + 
  theme(legend.position = "none", panel.grid = element_blank()) + 
  geom_text(aes(label = Lab), position = position_stack(vjust = 0.5)) + 
  labs(x = "Peptides", y = "Percentage (%)") -> p4
p4
```

```{r}
p1 <- p1 + scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1), labels = c(0, 0.25, 0.5, 0.75, 1)) + lims(x = c(0.1, 0.25))
p2 <- p2 + scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1)*1.07, labels = c(0, 0.25, 0.5, 0.75, 1)) + lims(x = c(0.1, 0.25))
p3 <- p3 + scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1)*1.38, labels = c(0, 0.25, 0.5, 0.75, 1)) + lims(x = c(0.1, 0.25))
p1 + p2 + p3
```


```{r fig.width=12, fig.height=3}
p1 <- p1 + theme(legend.position = "none") + labs(y = "Relative abundance\nof identified AAs", x = "")
p2 <- p2 + theme(legend.position = "none") + labs(y = "")
p3 <- p3 + theme(legend.position = "none") + labs(y = "", x = "")

p1 + p2 + p3 + p4 + plot_layout(nrow = 1)
```

```{r fig.width=12, fig.height=3}
ps <- cowplot::plot_grid(p1, p2, p3, p4, nrow = 1, rel_widths = c(1.08, 1, 1, 1))
ps
ggsave(ps, filename = "./analysis/00.FigureTables/Sep24/Figure4/AA_Predict.eps", width = 12, height = 3)
ggsave(ps, filename = "./analysis/00.FigureTables/Sep24/Figure4/AA_Predict.pdf", width = 12, height = 3)
```














